### ISSUE TITLE
Sharing broken when LDAP and Mail App is enabled

### ISSUE THREAD

**Issue by Niols** [nextcloud/server#106]
I tryed the drop-in replacement of ownCloud by Nextcloud yesterday.
Almost everything is working like a charm. Except sharing:

### Steps to reproduce
Hard to tell.
I've taken a working ownCloud 9.0.2.2 version and did a manual upgrade to Nextcloud 9.0.50 (backup everything, download the .tar.bz2, check it, replace everything, copy config, run `php occ upgrade`, …) and got no error.
My new Nextcloud instance is working fine, except for this:

### Expected behaviour
Since I didn't change anything in the configuration, I was expecting my shares to work in the same way:
- shares listed in "shared to me" and "shared by me" in the files app
- sharing and resharing available when clicking on a file/directory and going to "Sharing"

### Actual behaviour

- Both the "shared to me" and "shared by me" lists are empty, even if I have shares working correctly.

- The "share" tab simply say "Resharing isn't authorized", while it was working on the previous ownCloud instance, and the configuration says it's enabled.

It doesn't look like it's broken, just… disabled. Here is my administration sharing tab:
- [x] Allow apps to use sharing API
- [x] Allow users to share by link
  - [ ] Force password protection
  - [x] Allow publish upload
  - [ ] Allow users to send share notifications by e-mail
  - [x] Specify a default expiration date
    - Expiration after 7 days
    - [ ] Force expiration date
- [x] Allow resharing
- [x] Allow sharing with groups
- [x] Allow sharing only between members of the same group
- [ ] Allow users to send sharing notifications by e-mail
- [ ] Prevent some groups from sharing
- [x] Enable usernames' autocompletion

(Sorry, I translated it myself from french, so that might not be the same thing as in english. I hope it's understandable thought…)

### Server configuration
- **Operating system**: Debian Jessie, packages up-to-date
- **Web server:** Nginx 1.6.2
- **Database:** MySQL 14.14
- **PHP version:** 5.6.22
- **Nextcloud version:** 9.0.50
- **Updated from an older Nextcloud/ownCloud or fresh install:** Manually updated from ownCloud 9.0.2.2
- **Where did you install Nextcloud from:** From [here](https://nextcloud.com/install/#instructions-server). tar bz2 archive, checked against sha256 and PGP.

**Signing status (Nextcloud 9.0 and above):** https://cloud.niols.fr/index.php/settings/integrity/failed 

    No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - bookmarks: 0.7
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.5.1
  - music: 0.3.11
  - news: 8.8.0
  - notes: 2.0.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.9.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0

Disabled:
  - encryption
  - user_external

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "oc8h49hqsg07",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.niols.fr",
            "cloud.b-six.rocks"
        ],
        "datadirectory": "\/home\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.niols.fr",
        "dbtype": "mysql",
        "version": "9.0.50.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "mail_from_address": "noreply",
        "mail_smtpmode": "php",
        "mail_domain": "cloud.niols.fr",
        "default_language": "fr",
        "loglevel": 0,
        "maintenance": false,
        "htaccess.RewriteBase": "\/"
    }
}
```

**Are you using external storage, if yes which one:** local (two external storages)
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration

```
+-------------------------------+----------------------------------------------------------------+
| Configuration                 |                                                                |
+-------------------------------+----------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                              |
| hasPagedResultSupport         |                                                                |
| homeFolderNamingRule          |                                                                |
| lastJpegPhotoLookup           | 0                                                              |
| ldapAgentName                 | cn=owncloud,ou=services,dc=niols,dc=fr                         |
| ldapAgentPassword             | ***                                                            |
| ldapAttributesForGroupSearch  |                                                                |
| ldapAttributesForUserSearch   |                                                                |
| ldapBackupHost                |                                                                |
| ldapBackupPort                |                                                                |
| ldapBase                      | dc=niols,dc=fr                                                 |
| ldapBaseGroups                | ou=groups,dc=niols,dc=fr                                       |
| ldapBaseUsers                 | ou=people,dc=niols,dc=fr                                       |
| ldapCacheTTL                  | 600                                                            |
| ldapConfigurationActive       | 1                                                              |
| ldapDynamicGroupMemberURL     |                                                                |
| ldapEmailAttribute            | mail                                                           |
| ldapExperiencedAdmin          | 1                                                              |
| ldapExpertUUIDGroupAttr       | cn                                                             |
| ldapExpertUUIDUserAttr        | uid                                                            |
| ldapExpertUsernameAttr        | uid                                                            |
| ldapGroupDisplayName          | displayname                                                    |
| ldapGroupFilter               | (&(objectclass=groupOfNames)(objectclass=owncloud))            |
| ldapGroupFilterGroups         |                                                                |
| ldapGroupFilterMode           | 0                                                              |
| ldapGroupFilterObjectclass    |                                                                |
| ldapGroupMemberAssocAttr      | member                                                         |
| ldapHost                      | localhost                                                      |
| ldapIgnoreNamingRules         |                                                                |
| ldapLoginFilter               | (&(objectclass=inetOrgPerson)(objectclass=owncloud)(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                |
| ldapLoginFilterEmail          | 0                                                              |
| ldapLoginFilterMode           | 0                                                              |
| ldapLoginFilterUsername       | 1                                                              |
| ldapNestedGroups              | 0                                                              |
| ldapOverrideMainServer        |                                                                |
| ldapPagingSize                | 500                                                            |
| ldapPort                      | 389                                                            |
| ldapQuotaAttribute            | owncloudQuota                                                  |
| ldapQuotaDefault              | 0                                                              |
| ldapTLS                       | 0                                                              |
| ldapUserDisplayName           | displayName                                                    |
| ldapUserDisplayName2          |                                                                |
| ldapUserFilter                | (&(objectclass=inetOrgPerson)(objectclass=owncloud))           |
| ldapUserFilterGroups          |                                                                |
| ldapUserFilterMode            | 0                                                              |
| ldapUserFilterObjectclass     |                                                                |
| ldapUuidGroupAttribute        | auto                                                           |
| ldapUuidUserAttribute         | auto                                                           |
| turnOffCertCheck              | 0                                                              |
| useMemberOfToDetectMembership | 1                                                              |
+-------------------------------+----------------------------------------------------------------+
```

### Client configuration
**Browser:** Mozilla Firefox 47.0 (also tested in Chromium 51.0.2704.84)
**Operating system:** Arch linux, up-to-date

#### Web server error log

empty

#### Nextcloud log (data/owncloud.log)

With comments
```
## I loaded the page https://cloud.niols.fr/index.php/apps/files/
{"reqId":"cbBEQui8CfC\/7TMGrtS+","remoteAddr":"81.194.27.158","app":"files","message":" Backends provided no user object for niols","level":3,"time":"2016-06-15T08:34:09+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"niols"}
{"reqId":"cbBEQui8CfC\/7TMGrtS+","remoteAddr":"81.194.27.158","app":"PHP","message":"OC\\User\\NoUserException: Backends provided no user object for niols at \/home\/owncloud\/public_html\/lib\/private\/files\/filesystem.php#391","level":3,"time":"2016-06-15T08:34:09+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"niols"}
{"reqId":"rzrUiEZcxl0QWYSphrft","remoteAddr":"81.194.27.158","app":"files","message":" Backends provided no user object for niols","level":3,"time":"2016-06-15T08:34:10+00:00","method":"GET","url":"\/ocs\/v1.php\/apps\/files_external\/api\/v1\/mounts?format=json","user":"niols"}
{"reqId":"rzrUiEZcxl0QWYSphrft","remoteAddr":"81.194.27.158","app":"PHP","message":"OC\\User\\NoUserException: Backends provided no user object for niols at \/home\/owncloud\/public_html\/lib\/private\/files\/filesystem.php#391","level":3,"time":"2016-06-15T08:34:10+00:00","method":"GET","url":"\/ocs\/v1.php\/apps\/files_external\/api\/v1\/mounts?format=json","user":"niols"}

## I clicked on a directory

## I reached the tab "Sharing"
{"reqId":"tC7h79UQlhI2AAZxjsFj","remoteAddr":"81.194.27.158","app":"files","message":" Backends provided no user object for niols","level":3,"time":"2016-06-15T08:34:20+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json&path=%2FJeux&reshares=true","user":"niols"}
{"reqId":"tC7h79UQlhI2AAZxjsFj","remoteAddr":"81.194.27.158","app":"PHP","message":"OC\\User\\NoUserException: Backends provided no user object for niols at \/home\/owncloud\/public_html\/lib\/private\/files\/filesystem.php#391","level":3,"time":"2016-06-15T08:34:20+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json&path=%2FJeux&reshares=true","user":"niols"}
{"reqId":"c4\/RNZD42Ucp0qHd+FUL","remoteAddr":"81.194.27.158","app":"files","message":" Backends provided no user object for niols","level":3,"time":"2016-06-15T08:34:20+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json&path=%2FJeux&shared_with_me=true","user":"niols"}
{"reqId":"c4\/RNZD42Ucp0qHd+FUL","remoteAddr":"81.194.27.158","app":"PHP","message":"OC\\User\\NoUserException: Backends provided no user object for niols at \/home\/owncloud\/public_html\/lib\/private\/files\/filesystem.php#391","level":3,"time":"2016-06-15T08:34:20+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json&path=%2FJeux&shared_with_me=true","user":"niols"}
```

#### Browser log

Javascript logs in Mozilla Firefox, with comments
```
## I opened the page https://cloud.niols.fr/index.php/apps/files/
Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead. (unknown)
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead      jquery.min.js:1:0
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://cloud.niols.fr 'unsafe-eval'"). files
window.controllers is deprecated. Do not use it for UA detection.      ace.js:1716:0
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.      jquery.min.js:5:17117
TypeError: data.ocs is undefined      app.js:330:1
TypeError: response.ocs is undefined      statusmanager.js:142:6

## I clicked on a directory
no element found      filter:1:1

## I reached the tab "Sharing"
TypeError: data1[0].ocs is undefined      shareitemmodel.js:622:5
```

I'll stay around and provide as much help as I can.
cc @LukasReschke that I saw on IRC

**Comment by LukasReschke** [comment]
Interesting. `Backends provided no user object for niols` hints to be the bug https://github.com/owncloud/mail/issues/1422 which also should be existent in the ownCloud server.

Can you confirm that sharing works again if you disable the mail app?

cc @ChristophWurst Maybe we debug this for real today 😉

**Comment by Niols** [comment]
Ho ho, I wasn't expecting that.
Indeed, mail disabled from Web interface, and sharing seems to be working (I'll try all cases and provide more information if I can)

**Comment by LukasReschke** [comment]
Thanks for the feedback. Somehow having the mail app and LDAP enabled seems to break some stuff. I'll see if I find some time today to debug this.

Thanks a lot for the bug report! Helps a lot to have all the required information :-)

**Comment by Niols** [comment]
You're welcome, that's the least I can do :)
If you need more testing, don't hesitate to ask me.
The issue having nothing to do with the upgrade from ownCloud to Nextcloud, should I rename it?

**Comment by LukasReschke** [comment]
> The issue having nothing to do with the upgrade from ownCloud to Nextcloud, should I rename it?

Let's go with something like "Sharing broken when LDAP and Mail App is enabled" :)

**Comment by LukasReschke** [comment]
@Niols Could you test https://github.com/nextcloud/server/pull/174/commits/43065e736996b898a20d502e24dabf7ed79d0b32? Thanks a lot 🚀

**Comment by MorrisJobke** [comment]
Fixed via #174

**Comment by Niols** [comment]
@LukasReschke 
I have no problem with testing. How am I supposed to do so? Create a whole new Nextcloud instance, plug it on my LDAP, activate the mail app and see if I still have the bug?
I would like to keep my main instance on the stable release channel

**Comment by MorrisJobke** [comment]
> I would like to keep my main instance on the stable release channel

There was just a unscheduled release yesterday (9.0.51) that contains your fix. Give it a try.

**Comment by MorrisJobke** [comment]
:)

**Comment by Niols** [comment]
Oh. Alright, I'll be back!

**Comment by Niols** [comment]
OK.
Upgrade went well.
I activated all the apps listed in my bug report, and I can't reproduce anymore.
Logs are clean too.
Nice job! :)
