### ISSUE TITLE
Pb accessing overview and application pages in Nextcloud 14 - Call to undefined method GuzzleHttp\Client::request()

### ISSUE THREAD

**Issue by Larsene** [nextcloud/server#11159]
Hi, since last NC14 update, i can’t access anymore to the overview page, neither on the applications page

### Steps to reproduce
1. updgrading nextcloud 14 to 14.0.0.17
2.
3.

**Nextcloud version:** 

NextCloudPi version  v0.59.0
NextCloudPi image    NextCloudPi_11-23-17
distribution         Raspbian GNU/Linux 9 \n \l
automount            yes
USB devices          sda sdb
datadir              /var/www/nextcloud/data
data in SD           yes
data filesystem      ext2/ext3
data disk usage      631G/918G
rootfs usage         631G/918G
swapfile             /var/swap
dbdir                /var/lib/mysql
Nextcloud check      ok
Nextcloud version    14.0.0.17
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       closed
IP                   172.20.90.41
gateway              172.20.90.254
interface            eth0
certificates         none
NAT loopback         no

**logs** 

{“reqId”:“W5Nj038AAQEAAHOH9M0AAEAB”,“level”:3,“time”:“2018-09-08T05:53:24+00:00”,“remoteAddr”:“37.168.105.33”,“user”:“admin”,“app”:“index”,“method”:“GET”,“url”:"/index.php/settings/admin/overview",“message”:{“Exception”:“Error”,“Message”:“Call to undefined method GuzzleHttp\Client::request()”,“Code”:0,“Trace”:[{“file”:"/var/www/nextcloud/lib/private/Updater/ChangesCheck.php",“line”:127,“function”:“get”,“class”:“OC\Http\Client\Client”,“type”:"->",“args”:[“https://updates.nextcloud.com/changelog_server/?version=14.0.0",{“headers”:{“If-None-Match”:[“72f8f8b283a522bbeb40866fae7db85d”]}}]},{“file”:"/var/www/nextcloud/lib/private/Updater/ChangesCheck.php",“line”:73,“function”:“queryChangesServer”,“class”:“OC\Updater\ChangesCheck”,“type”:"->”,“args”:[“https://updates.nextcloud.com/changelog_server/?version=14.0.0",{“id”:1,"class”:“OC\Updater\ChangesResult”}]},{“file”:"/var/www/nextcloud/apps/updatenotification/lib/UpdateChecker.php",“line”:65,“function”:“check”,“class”:“OC\Updater\ChangesCheck”,“type”:"->",“args”:[“https://updates.nextcloud.com/changelog_server/?version=14.0.0",“14.0.0”]},{“file”:"/var/www/nextcloud/apps/updatenotification/lib/Settings/Admin.php",“line”:87,“function”:“getUpdateState”,“class”:“OCA\UpdateNotification\UpdateChecker”,“type”:"->”,“args”:[]},{“file”:"/var/www/nextcloud/settings/Controller/CommonSettingsTrait.php",“line”:115,“function”:“getForm”,“class”:“OCA\UpdateNotification\Settings\Admin”,“type”:"->",“args”:[]},{“file”:"/var/www/nextcloud/settings/Controller/AdminSettingsController.php",“line”:74,“function”:“formatSettings”,“class”:“OC\Settings\Controller\AdminSettingsController”,“type”:"->",“args”:[{“10”:[{“class”:“OC\Settings\Admin\Overview”}],“11”:[{“class”:“OCA\UpdateNotification\Settings\Admin”}]}]},{“file”:"/var/www/nextcloud/settings/Controller/CommonSettingsTrait.php",“line”:126,“function”:“getSettings”,“class”:“OC\Settings\Controller\AdminSettingsController”,“type”:"->",“args”:[“overview”]},{“file”:"/var/www/nextcloud/settings/Controller/AdminSettingsController.php",“line”:65,“function”:“getIndexResponse”,“class”:“OC\Settings\Controller\AdminSettingsController”,“type”:"->",“args”:[“admin”,“overview”]},{“file”:"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",“line”:166,“function”:“index”,“class”:“OC\Settings\Controller\AdminSettingsController”,“type”:"->",“args”:[“overview”]},{“file”:"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",“line”:99,“function”:“executeController”,“class”:“OC\AppFramework\Http\Dispatcher”,“type”:"->",“args”:[{“class”:“OC\Settings\Controller\AdminSettingsController”},“index”]},{“file”:"/var/www/nextcloud/lib/private/AppFramework/App.php",“line”:118,“function”:“dispatch”,“class”:“OC\AppFramework\Http\Dispatcher”,“type”:"->",“args”:[{“class”:“OC\Settings\Controller\AdminSettingsController”},“index”]},{“file”:"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php",“line”:47,“function”:“main”,“class”:“OC\AppFramework\App”,“type”:"::",“args”:[“OC\Settings\Controller\AdminSettingsController”,“index”,{“class”:“OC\AppFramework\DependencyInjection\DIContainer”},{“section”:“overview”,"_route":“settings.AdminSettings.index”}]},{“function”:"__invoke",“class”:“OC\AppFramework\Routing\RouteActionHandler”,“type”:"->",“args”:[{“section”:“overview”,"_route":“settings.AdminSettings.index”}]},{“file”:"/var/www/nextcloud/lib/private/Route/Router.php",“line”:297,“function”:“call_user_func”,“args”:[{“class”:“OC\AppFramework\Routing\RouteActionHandler”},{“section”:“overview”,"_route":“settings.AdminSettings.index”}]},{“file”:"/var/www/nextcloud/lib/base.php",“line”:989,“function”:“match”,“class”:“OC\Route\Router”,“type”:"->",“args”:["/settings/admin/overview"]},{“file”:"/var/www/nextcloud/index.php",“line”:42,“function”:“handleRequest”,“class”:“OC”,“type”:"::",“args”:[]}],“File”:"/var/www/nextcloud/lib/private/Http/Client/Client.php",“Line”:161,“CustomMessage”:"–"},“userAgent”:“Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.64”,“version”:“14.0.0.17”}
{“reqId”:“W5Nj038AAQEAAHOH9M0AAEAB”,“level”:0,“time”:“2018-09-08T05:53:24+00:00”,“remoteAddr”:“37.168.105.33”,“user”:“admin”,“app”:“core”,“method”:“GET”,“url”:"/index.php/settings/admin/overview",“message”:“Scss is disabled for /var/www/nextcloud/core/css/jquery-ui-fixes.scss, ignoring”,“userAgent”:“Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.64”,“version”:“14.0.0.17”}
{“reqId”:“W5Nj038AAQEAAHOH9M0AAEAB”,“level”:0,“time”:“2018-09-08T05:53:24+00:00”,“remoteAddr”:“37.168.105.33”,“user”:“admin”,“app”:“core”,“method”:“GET”,“url”:"/index.php/settings/admin/overview",“message”:“Scss is disabled for /var/www/nextcloud/core/css/server.scss, ignoring”,“userAgent”:“Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.64”,“version”:“14.0.0.17”}
{“reqId”:“W5Nj038AAQEAAHOH9M0AAEAB”,“level”:0,“time”:“2018-09-08T05:53:24+00:00”,“remoteAddr”:“37.168.105.33”,“user”:“admin”,“app”:“core”,“method”:“GET”,“url”:"/index.php/settings/admin/overview",“message”:“Scss is disabled for /var/www/nextcloud/core/css/css-variables.scss, ignoring”,“userAgent”:“Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.64”,“version”:“14.0.0.17”}
{“reqId”:“W5Nj038AAQEAAHOH9M0AAEAB”,“level”:0,“time”:“2018-09-08T05:53:24+00:00”,“remoteAddr”:“37.168.105.33”,“user”:“admin”,“app”:“core”,“method”:“GET”,“url”:"/index.php/settings/admin/overview",“message”:“Scss is disabled for /var/www/nextcloud/apps/firstrunwizard/css/firstrunwizard.scss, ignoring”,“userAgent”:“Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.64”,“version”:“14.0.0.17”}
{“reqId”:“W5Nj038AAQEAAHOH9M0AAEAB”,“level”:0,“time”:“2018-09-08T05:53:24+00:00”,“remoteAddr”:“37.168.105.33”,“user”:“admin”,“app”:“core”,“method”:“GET”,“url”:"/index.php/settings/admin/overview",“message”:“Scss is disabled for /var/www/nextcloud/apps/notifications/css/styles.scss, ignoring”,“userAgent”:“Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.64”,“version”:“14.0.0.17”}
{“reqId”:“W5Nj038AAQEAAHOH9M0AAEAB”,“level”:0,“time”:“2018-09-08T05:53:24+00:00”,“remoteAddr”:“37.168.105.33”,“user”:“admin”,“app”:“core”,“method”:“GET”,“url”:"/index.php/settings/admin/overview",“message”:“Scss is disabled for /var/www/nextcloud/core/css/jquery.ocdialog.scss, ignoring”,“userAgent”:“Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.64”,“version”:“14.0.0.17”}
{“reqId”:“W5Nj038AAQEAAHOH9M0AAEAB”,“level”:0,“time”:“2018-09-08T05:53:24+00:00”,“remoteAddr”:“37.168.105.33”,“user”:“admin”,“app”:“core”,“method”:“GET”,“url”:"/index.php/settings/admin/overview",“message”:“Scss is disabled for /var/www/nextcloud/core/search/css/results.scss, ignoring”,“userAgent”:“Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.64”,“version”:“14.0.0.17”}
{“reqId”:“W5Nj038AAQEAAHOH9M0AAEAB”,“level”:0,“time”:“2018-09-08T05:53:24+00:00”,“remoteAddr”:“37.168.105.33”,“user”:“admin”,“app”:“core”,“method”:“GET”,“url”:"/index.php/settings/admin/overview",“message”:“Scss is disabled for /var/www/nextcloud/core/css/styles.scss, ignoring”,“userAgent”:“Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.64”,“version”:“14.0.0.17”}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

Enabled:
  - accessibility: 1.0.1
  - admin_audit: 1.4.0
  - admin_notifications: 1.0.2
  - audioplayer: 2.3.2
  - bookmarks: 0.12.1
  - calendar: 1.6.1
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notes: 2.4.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_u2f: 1.6.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - activity
  - apporder
  - camerarawpreviews
  - checksum
  - cms_pico
  - encryption
  - external
  - files_external
  - files_reader
  - flowupload
  - impersonate
  - metadata
  - mindmaps
  - passman
  - polls
  - previewgenerator
  - quota_warning
  - rainloop
  - tasks
  - unsplash
  - user_external
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "5": "nextcloudpi.local",
            "1": "172.20.90.41",
            "2": ***REMOVED SENSITIVE VALUE***,
            "3": "192.168.137.119"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/172.20.90.41",
        "dbtype": "mysql",
        "version": "14.0.0.17",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "updater.release.channel": "beta",
        "theme": "",
        "maintenance": false,
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpsecure": "ssl"
    }
}

```
</details>

**Are you using external storage : no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav

**Comment by Larsene** [comment]
do you know how to fix that or i have to reinstall a fresh version on my server ? (as i cant't manage apps, neither i can update Nextcloud for now.

**Comment by Larsene** [comment]
okay, this issue was resolved after updating to 14.0.1. 👍

**Comment by patrice-geo** [comment]
I have the same issue coming from NC 13 to 14. Then I upgraded to 14.0.3 via the command line and I still get the same issue.

**Comment by susobaco** [comment]
I also have this error, both in the app "cron" and in "index". Nextcloud 14.0.3 on Debian stretch
