### ISSUE TITLE
TypeError Exception With v14

### ISSUE THREAD

**Issue by benyanke** [nextcloud/server#11231]
In both my upgraded instance as well as a clean install (using THIS), I am now seeing this in the browser logs, thrown by a code integrity error.

To replicate:

1) Get docker-compose.yml file [here](https://raw.githubusercontent.com/benyanke/docker-compose-library/master/nextcloud/docker-compose.yml)
2) Change 'latest' tag to '14'
3) `docker-compose up -d`
4) `docker-compose ps` to find the port it's bound to
5) login with admin/admin
6) note the error logs in `/settings/admin/logging`

```
TypeError: Argument 1 passed to OC\Settings\Controller\CheckSetupController::getAppDirsWithDifferentOwnerForAppRoot() must be of the type array, boolean given, called in /nextcloud/settings/Controller/CheckSetupController.php on line 551
/nextcloud/settings/Controller/CheckSetupController.php - line 551:

OC\Settings\Controller\CheckSetupController->getAppDirsWithDifferentOwnerForAppRoot(false, { path: "/ap ... e})

/nextcloud/settings/Controller/CheckSetupController.php - line 624:

OC\Settings\Controller\CheckSetupController->getAppDirsWithDifferentOwner()

/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166:

OC\Settings\Controller\CheckSetupController->check()

/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\ ... {}, "check")

/nextcloud/lib/private/AppFramework/App.php - line 118:

OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\ ... {}, "check")

/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

OC\AppFramework\App::main("OC\\Setting ... r", "check", OC\AppFramew ... {}, { _route: "s ... "})


OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "s ... "})

/nextcloud/lib/private/Route/Router.php - line 297:

call_user_func(OC\AppFramew ... {}, { _route: "s ... "})

/nextcloud/lib/base.php - line 989:

OC\Route\Router->match("/settings/ajax/checksetup")

/nextcloud/index.php - line 42:

OC::handleRequest()
```

**Comment by danielkesselberg** [comment]
Thanks for reporting this issue :+1: Issue is fixed with 14.0.1 (#11088).

**Comment by rw71** [comment]
I think this problem is still existing. I installed 14.0.3.

In the Administration Overview there is the following:
```
Security & setup warnings

It's important for the security and performance of your instance that everything is configured correctly. To help you with that we are doing some automatic checks. Please see the linked documentation for more information.

There are some errors regarding your setup.
Error occurred while checking server setup
Please double check the installation guides ↗, and check for any errors or warnings in the log.
```

Hier is the log:
```
Error: Call to undefined function OC\Settings\Controller\posix_getuid()
/volume1/web/cloud/settings/Controller/CheckSetupController.php - line 624:
OC\Settings\Controller\CheckSetupController->getAppDirsWithDifferentOwner()
/volume1/web/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 166:
OC\Settings\Controller\CheckSetupController->check()
/volume1/web/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:
OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\ ... {}, "check")
/volume1/web/cloud/lib/private/AppFramework/App.php - line 118:
OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\ ... {}, "check")
/volume1/web/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:
OC\AppFramework\App::main("OC\\Setting ... r", "check", OC\AppFramew ... {}, { _route: "s ... "})
OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "s ... "})
/volume1/web/cloud/lib/private/Route/Router.php - line 297:
call_user_func(OC\AppFramew ... {}, { _route: "s ... "})
/volume1/web/cloud/lib/base.php - line 987:
OC\Route\Router->match("/settings/ajax/checksetup")
/volume1/web/cloud/index.php - line 42:
OC::handleRequest()
```
