### ISSUE TITLE
root directory unvailable, if external storage is offline on 14.0.1

### ISSUE THREAD

**Issue by ManOki** [nextcloud/server#11545]
### Steps to reproduce
1. Update to NC 14.0.1
2. Setup External Storage, e.g. SMB share on NAS
3. Shutdown NAS
4. Login into nextcloud

### Expected behaviour
See all my files. In NC13, I got a hint, if external storage was offline, but still able to see regular nextcloud files.

### Actual behaviour
I'm getting the error "This directory is unavailable, please check the logs or contact the administrator"

### Server configuration

**Operating system**: Debian Stretch

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** PHP 7.0.30-0+deb9u1

**Nextcloud version:** 14.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 13.0.6

**Where did you install Nextcloud from:** Via php updater.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - apporder: 0.5.0
  - audioplayer: 2.4.1
  - bookmarks_fulltextsearch: 1.0.0
  - calendar: 1.6.2
  - camerarawpreviews: 0.5.6
  - caniupdate: 0.2.0
  - checksum: 0.4.1
  - circles: 0.15.1
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_fulltextsearch: 1.0.0
  - files_fulltextsearch_tesseract: 1.0.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.3.2
  - files_retention: 1.3.0
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - fulltextsearch: 1.0.0
  - fulltextsearch_elasticsearch: 1.0.0
  - gallery: 18.1.0
  - groupfolders: 1.3.3
  - impersonate: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.10.0
  - metadata: 0.7.0
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - previewgenerator: 1.1.0
  - provisioning_api: 1.4.0
  - quota_warning: 1.3.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - spreed: 4.0.0
  - support: 1.0.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_external: 0.4
  - workflowengine: 1.4.0
Disabled:
  - bruteforcesettings
  - encryption
  - external
  - firstrunwizard
  - keeweb
  - nextcloud_announcements
  - notifications
  - richdocuments
  - survey_client
  - systemtags
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.1.1",
        "updatechecker": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "trusted_domains": [
            "domain1",
            "domain2",
            "domain3"
        ],
        "loglevel": 3,
        "logtimezone": "UTC",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost\/nextcloud",
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "enable_previews": true,
        "preview_max_filesize_image": -1,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir
",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "maintenance": false,
        "theme": "",
        "defaultapp": "apporder",
        "htaccess.RewriteBase": "\/nextcloud",
        "overwritewebroot": "\/nextcloud",
        "updater.release.channel": "stable",
        "auth.bruteforce.protection.enabled": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** SMB

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 62.0.2

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"JHr9HGzYLKjqZAYy5chP","level":4,"time":"2018-09-29T16:37:13+00:00","remoteAddr":"192.168.178.50","user":"user","app":"webdav","method":"PROPFIND","url":"\/nextcloud\/remote.php\/dav\/files\/user\/","message":{"Exception":"Icewind\\SMB\\Exception\\InvalidArgumentException","Message":"Invalid request for \/Share\Folder (InvalidArgumentException)","Code":22,"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Native\/NativeState.php","line":61,"function":"fromMap","class":"Icewind\\SMB\\Exception\\Exception","type":"::","args":[{"1":"Icewind\\SMB\\Exception\\ForbiddenException","2":"Icewind\\SMB\\Exception\\NotFoundException","13":"Icewind\\SMB\\Exception\\ForbiddenException","16":"Icewind\\SMB\\Exception\\FileInUseException","17":"Icewind\\SMB\\Exception\\AlreadyExistsException","20":"Icewind\\SMB\\Exception\\InvalidTypeException","21":"Icewind\\SMB\\Exception\\InvalidTypeException","22":"Icewind\\SMB\\Exception\\InvalidArgumentException","28":"Icewind\\SMB\\Exception\\OutOfSpaceException","39":"Icewind\\SMB\\Exception\\NotEmptyException","110":"Icewind\\SMB\\Exception\\TimedOutException","111":"Icewind\\SMB\\Exception\\ConnectionRefusedException","112":"Icewind\\SMB\\Exception\\HostDownException","113":"Icewind\\SMB\\Exception\\NoRouteToHostException"},22,"\/Share\Folder"]},{"file":"\/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Native\/NativeState.php","line":73,"function":"handleError","class":"Icewind\\SMB\\Native\\NativeState","type":"->","args":["\/Share\Folder"]},{"file":"\/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Native\/NativeState.php","line":181,"function":"testResult","class":"Icewind\\SMB\\Native\\NativeState","type":"->","args":[false,"smb:\/\/nas\/other\/Share\Folder"]},{"file":"\/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Native\/NativeShare.php","line":113,"function":"stat","class":"Icewind\\SMB\\Native\\NativeState","type":"->","args":["smb:\/\/nas\/other\/Share\Folder"]},{"file":"\/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Native\/NativeShare.php","line":109,"function":"getStat","class":"Icewind\\SMB\\Native\\NativeShare","type":"->","args":["\/Share\Folder"]},{"file":"\/var\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/SMB.php","line":164,"function":"stat","class":"Icewind\\SMB\\Native\\NativeShare","type":"->","args":["\/Share\Folder"]},{"file":"\/var\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/SMB.php","line":492,"function":"getFileInfo","class":"OCA\\Files_External\\Lib\\Storage\\SMB","type":"->","args":["\/Share\Folder"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Common.php","line":109,"function":"filetype","class":"OCA\\Files_External\\Lib\\Storage\\SMB","type":"->","args":["Folder"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Common.php","line":143,"function":"is_dir","class":"OC\\Files\\Storage\\Common","type":"->","args":["Folder"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Common.php","line":163,"function":"isCreatable","class":"OC\\Files\\Storage\\Common","type":"->","args":["Folder"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":214,"function":"getPermissions","class":"OC\\Files\\Storage\\Common","type":"->","args":["Folder"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Availability.php","line":230,"function":"getPermissions","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["Folder"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":214,"function":"getPermissions","class":"OC\\Files\\Storage\\Wrapper\\Availability","type":"->","args":["Folder"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/PermissionsMask.php","line":79,"function":"getPermissions","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["Folder"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Jail.php","line":218,"function":"getPermissions","class":"OC\\Files\\Storage\\Wrapper\\PermissionsMask","type":"->","args":["Folder"]},{"file":"\/var\/www\/nextcloud\/apps\/files_sharing\/lib\/SharedStorage.php","line":198,"function":"getPermissions","class":"OC\\Files\\Storage\\Wrapper\\Jail","type":"->","args":[""]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":214,"function":"getPermissions","class":"OCA\\Files_Sharing\\SharedStorage","type":"->","args":[""]},{"file":"\/var\/www\/nextcloud\/apps\/files_sharing\/lib\/Cache.php","line":145,"function":"getPermissions","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":[""]},{"file":"\/var\/www\/nextcloud\/apps\/files_sharing\/lib\/Cache.php","line":113,"function":"formatCacheEntry","class":"OCA\\Files_Sharing\\Cache","type":"->","args":[{"__class__":"OC\\Files\\Cache\\CacheEntry"},""]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/FileInfo.php","line":359,"function":"get","class":"OCA\\Files_Sharing\\Cache","type":"->","args":[""]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/FileInfo.php","line":206,"function":"updateEntryfromSubMounts","class":"OC\\Files\\FileInfo","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Node\/Node.php","line":189,"function":"getMTime","class":"OC\\Files\\FileInfo","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Node.php","line":156,"function":"getMTime","class":"OC\\Files\\Node\\Node","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":794,"function":"getLastModified","class":"OCA\\DAV\\Connector\\Sabre\\Node","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/PropFind.php","line":98,"function":"Sabre\\DAV\\{closure}","class":"Sabre\\DAV\\CorePlugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":798,"function":"handle","class":"Sabre\\DAV\\PropFind","type":"->","args":["{DAV:}getlastmodified",{"__class__":"Closure"}]},{"function":"propFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Files\\FilesHome"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"propFind"],[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Files\\FilesHome"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1059,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["propFind",[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Files\\FilesHome"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":981,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Files\\FilesHome"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1666,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["files\/user",["{DAV:}getlastmodified"],0]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":359,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/myhost.com\/nextcloud\/remote.php\/dav\/files\/user\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPropFind"],[{"absoluteUrl":"https:\/\/myhost.com\/nextcloud\/remote.php\/dav\/files\/user\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PROPFIND",[{"absoluteUrl":"https:\/\/myhost.com\/nextcloud\/remote.php\/dav\/files\/user\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/myhost.com\/nextcloud\/remote.php\/dav\/files\/user\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Server.php","line":293,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/remote.php","line":163,"args":["\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Exception\/Exception.php","Line":30,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.3 (build 1) (Nextcloud)","version":"14.0.1.1"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
undefined pageModifier.js:585:9
Mutations-Ereignisse sollten nicht mehr verwendet werden. Verwenden Sie MutationObserver stattdessen. pageModifier.js:81:20
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
Missing plural form in language file merged-template-prepend.js:3841:4
unreachable code after return statement[Weitere Informationen] merged.js:1502:4
window.controllers/Controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung. merged.js:2176
New search handler registered search.js:66:4
Source-Map-Fehler: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://myhost.com/nextcloud/apps/files_markdown/build/editor.js?v=4e9842ef-1
Source-Map-Adresse: editor.js.map[Weitere Informationen]
querying Whats New data was successful: nocontent merged-template-prepend.js:4478:4
undefined merged-template-prepend.js:4479:4
</details>

**Comment by ManOki** [comment]
From my point of view, this is closely connected to #11442.

My guess: there is no problem with my normal nextcloud data. If my external storage is offline, i get the following error. in latest NC13, there was just a hint, that external storage is atm not available, but i was able to see all other files. now, exception handling seems to be changed and this exception is threated as an error, not a warning/info anymore.

**Comment by ManOki** [comment]
All my nextcloud clients are not able to connect to server files, if my NAS is offline, i.e. webpage, desktop client, android app..

Other web apps like calendar are still working.

**Comment by jospoortvliet** [comment]
Should be fixed in 14.0.2, test the release candidate - now out. https://help.nextcloud.com/t/help-testing-rc1-version-of-14-0-2-13-0-7-and-12-0-12/38359

**Comment by ManOki** [comment]
@jospoortvliet no, the release candidate did not fix my issue. Still getting the same error. Can you reopen the issue?
