### ISSUE TITLE
Can't copy and overwrite from external storage

### ISSUE THREAD

**Issue by joekerna** [nextcloud/server#12445]
### Steps to reproduce
1. Mount local directory as external storage
2. Try to copy file from external storage to local storage that already exists

### Expected behaviour
Nextcloud should ask if I want to replace the existing file like it does for local-local copy

### Actual behaviour
Copying files that don't already exists works fine. When trying to overwrite a file I get the following error message:

> Could not copy “filename.zip”, target exists

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Nginx (latest mainline)

**Database:** MySQL 

**PHP version:** 7.2.63

**Nextcloud version:** (see Nextcloud admin page) 14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Update

**Where did you install Nextcloud from:** Nextcloud website

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 63

**Operating system:** osX, Windows 10

**Comment by joekerna** [comment]
It doesn't seem to be a rights issue on the local storage. I've created a file with rights 777 and the issue is still there.

**Comment by Brianetta** [comment]
Confirming this issue; I've been having to delete the file from the target folder as a work-around since at least version 13.

**Comment by skjnldsv** [comment]
This comes from https://github.com/nextcloud/server/pull/5596
And is fixed by https://github.com/nextcloud/server/pull/14691

It's because you cannot change or move a mount point. Aka external storage or shared root.

**Comment by Brianetta** [comment]
![image](https://user-images.githubusercontent.com/719817/60687201-027c3e00-9ea5-11e9-88c9-36e68c1ed571.png)
Not fixed in 16.0.2

**Comment by joekerna** [comment]
I can confirm. It is not fixed in 16.0.3. Please reopen
