### ISSUE TITLE
Drag and drop of a folder in firefox gives no feedback

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#1336]
With firefox uploading of folders is not possible. However instead of showing an error like in previous versions, currently you just get the "light blue" drag-n-drop color everywhere and nothing further happens.

Ref https://help.nextcloud.com/t/uploading-folders-not-possible/3106

**Comment by MorrisJobke** [comment]
let me debug this quickly.

**Comment by MorrisJobke** [comment]
> let me debug this quickly.

#1406 solves the UI glitch and now behaves like stable9

**Comment by MorrisJobke** [comment]
Ref https://github.com/nextcloud/server/pull/83

**Comment by MorrisJobke** [comment]
Fixed in master - backport request pending

**Comment by hregnier** [comment]
Hi there,
Sorry to raise this issue from the dead, but I still have the problem on my 10.0.1.
Drag and drop works on chrome and opera, but not in firefox or IE.
By the way, folder with accent (like "création") pops out an error : "Erreur lors de l'envoi du fichier "InvalidStateError" : Aucun fichier n'a été envoyé. Erreur inconnue" something like "Errors chen sending files "InvalidStateError" : no file were sent. Unknown error"

**Comment by MorrisJobke** [comment]
> By the way, folder with accent (like "création") pops out an error : "Erreur lors de l'envoi du fichier "InvalidStateError" : Aucun fichier n'a été envoyé. Erreur inconnue" something like "Errors chen sending files "InvalidStateError" : no file were sent. Unknown error"

Then please open a new issue ;)

**Comment by MorrisJobke** [comment]
But please first give the latest release a try https://nextcloud.com/changelog/#latest10 (in your case 10.0.2 ;))

**Comment by ncist2011** [comment]
hi there,
drag and drop folder with chinese characters name, using firefox on windows7, throw exception like InvalidStateError.
![qq20170221-0](https://cloud.githubusercontent.com/assets/4124982/23194729/c5851f60-f8ea-11e6-80e3-6b17d4a1eb53.png)
