### ISSUE TITLE
Update nextcloud 15.0.4 to 15.0.5 error "ocm-provider" apache2

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#14445]
I just did nextcloud update to release 15.0.5 and in the test entries came out written that I have to solve with rules on apache that I have ocm-provider error how can I do it?

should I edit .htaccess files and if so?

error I have is this:

Your server is not configured correctly to resolve "/ ocm-provider /". This is probably related to a server configuration that has not been updated to provide this folder directly. Compare your configuration with the rewrite rules provided in ".htaccess" for Apache or the one provided in the Nginx documentation on its page. On Nginx, it is usually the lines that start with "location ~" those to be updated.

**Comment by AnotherSpecialist** [comment]
see also https://help.nextcloud.com/t/your-web-server-is-not-properly-set-up-to-resolve-ocm-provider/48530

**Comment by tigernero79** [comment]
thank you,
it was I who had written the post above you solving with 301 redirect put in .htaccess file having shared hosting

I had not written here

they are always the same tiger.

Good work for me.

Tested on Also

Redirect 301 / ocm-provider / / nx / ocm-provider /
Redirect 301 / ocs-provider / / nx / ocs-provider /

The writers on .htaccess root
And work for me,

/ nx / is folder on My nextcloud

**Comment by MorrisJobke** [comment]
Hi everyone in here - it turns out that the setup check here is wrong. Both `ocm-provider` and `ocs-provider` don’t need to be routed from the root of the domain. We will fix the setup check and documentation accordingly.

**Comment by tigernero79** [comment]
let us know if it is better to delete the entries in the htaccess file and what to do if you want to add more or not

**Comment by MorrisJobke** [comment]
> let us know if it is better to delete the entries in the htaccess file and what to do if you want to add more or not

They can go. The setup check will still fail in 15.0.5 and will be fixed in 15.0.6

**Comment by ludenticus** [comment]
Why is this issue closed. I'm still stocked on 15.0.5 on a shared webserver with no SSH access.

**Comment by kesselb** [comment]
> Why was this issue closed?

The reporter has closed this issue. I would assume he found a way to fix it.

> They can go. The setup check will still fail in 15.0.5 and will be fixed in 15.0.6

The broken check is fixed with 15.0.6. It's safe to ignore the warning.

**Comment by ludenticus** [comment]
I see. Thanks a lot

**Comment by wagnbeu0** [comment]
I still get this error message. Nextcloud is installed on the root folder of y apache webserver in /var/www/html --> what need to be done to get away this error message?
