### ISSUE TITLE
Support of Swift V3 Auth aka Identity v3 API for Swift Object Storage

### ISSUE THREAD

**Issue by stenstad** [nextcloud/server#1504]
https://github.com/php-opencloud/openstack is needed to support Openstack Swift using Identity v3 for authentication. This includes (amongst others) IBM Bluemix and Zetta.IO.

Identity v2 has been marked as deprecated since.. Late 2013?

The main problem is that php-opencloud require a newer version of Guzzle wich also requires PHP 5.6. This is mentioned in an existing Owncloud issue:

https://github.com/owncloud/core/issues/20787

It seems Owncloud might have solved this now:

https://github.com/owncloud/core/pull/25513

**Comment by nickvergessen** [comment]
For nextcloud 11 and later we require php 5.6, so we can update guzzle, so that should work in the end?

**Comment by stenstad** [comment]
Yes, that solves the dependency problems at least.

There still must be a migration from rackspace/php-opencloud to php-opencloud/openstack to be able to support Swift V3.

**Comment by jgallucci32** [comment]
While I welcome support for new authentication methods, please do not be so quick to deprecate older authentication methods with Swift. This type of thinking plagued the OwnCloud development which is why our company ultimately went with a competitor, and from what I can tell it was these issues that led to NextCloud's existence. For other reasons not disclosed, we are back in the market for a new EFSS system with support for our large-scale Swift backend object storage using V1 authentication. Really hoping NextCloud can become more flexible in its support for private backend object storage.

**Comment by stenstad** [comment]
@jgallucci32 Adding current authentication doesn't mean that SwiftV1 auth is removed as far as I know. It is Keystone/Identity v2 that is depreacted, but I would assume the library still supports it. SwiftV1 auth is separate from Keystone.

**Comment by Starfish22** [comment]
@stenstad I second this option. I have been struggling with DLO on Swift. And as php-opencloud [https://github.com/rackspace/php-opencloud](url) is being end-of-life'd anyway, I would second any move to the SDK. Many more features, out of the box it seems.

**Comment by MorrisJobke** [comment]
Looks like this is fixed by #4410 (was also backported to 12.0.4 afaik)

**Comment by stenstad** [comment]
This is not fixed. https://github.com/rackspace/php-opencloud is not developed, and does not support v3 auth. The readme.md previously even said:

> OpenStack users are recommended to use https://github.com/php-opencloud/openstack, which is the latest supported version of the SDK. This codebase which you are now looking at will enter end-of-life soon. For Rackspace Cloud users, a v2 is actively being worked on.

Ref: https://github.com/rackspace/php-opencloud/issues/699

Openstack Identity v2 was marked as deprecated in 2013.

Please switch to https://github.com/php-opencloud/openstack instead.

**Comment by MorrisJobke** [comment]
You are right - this is about Swift and not about S3. Sorry for that.

**Comment by MorrisJobke** [comment]
Fixed in 14 with #8359
