### ISSUE TITLE
quick file sharing by inputfield ignores expiration settings, breaks expiration enforcement

### ISSUE THREAD

**Issue by yasuoiwakura** [nextcloud/server#15116]
When sharing a file by just entering a mail adress into the searchfield (shareWith-view34), the expiration setting is being ignored. Even when expiration enforcement was set by an admin.

### Steps to reproduce
0. as an admin, set default expiration to 30days (maybe activate enforcement)
1. as a user, choose a file, click the share button, share menu slides in
2. enter a mail adress, press enter
3. 

### Expected behaviour
the default expiration setting shall apply

### Actual behaviour
file is being shared without expiration
even enforcement is being ignored

### Server configuration

Ubuntu 18.04

**Web server:**
ii  apache2                       2.4.29-1ubuntu4.6                          amd64        Apache HTTP Server
**Database:**
mysql
**PHP version:**
7.2
**Nextcloud version:**
15.0.7

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - announcementcenter: 3.4.1
  - apporder: 0.6.0
  - audioplayer: 2.6.1
  - bookmarks: 0.17.0
  - browser_warning: 0.1.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dashboard: 6.0.0
  - data_request: 1.2.0
  - dav: 1.8.1
  - deck: 0.5.2
  - drop_account: 0.1.0
  - dropit: 0.2.1
  - external: 3.2.0
  - extract: 1.0.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_antivirus: 2.0.1
  - files_automatedtagging: 1.5.0
  - files_downloadactivity: 1.4.0
  - files_external: 1.6.0
  - files_sharing: 1.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - flowupload: 0.0.9
  - gallery: 18.2.0
  - impersonate: 1.2.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - oauth2: 1.3.0
  - provisioning_api: 1.5.0
  - sharebymail: 1.5.0
  - sharerenamer: 2.6.0
  - socialsharing_email: 1.0.5
  - spreed: 5.0.2
  - systemtags: 1.5.0
  - terms_of_service: 1.1.1
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - workflow_script: 1.0.1
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - files_frommail
  - files_markdown
  - files_mindmap
  - files_pdfviewer
  - files_texteditor
  - files_videoplayer
  - firstrunwizard
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Tobsche** [comment]
Maybe I'm wrong, but share via mail does not have an option to enforce the expiration date...sadly.
The "set expiration date" option is AFAIK for public links only, as you can see in the follwing screens:
![grafik](https://user-images.githubusercontent.com/44866756/59099604-d7ddaa80-8923-11e9-900c-94c7d1805605.png)
![grafik](https://user-images.githubusercontent.com/44866756/59099484-80d7d580-8923-11e9-9050-377ce73ccdd5.png)
However, I would love to see this feature in the future!

**Comment by kesselb** [comment]
cc @skjnldsv is that fixed with the new sidebar?

**Comment by yasuoiwakura** [comment]
short feedback:
in 17.0.2 still the same behavior. (trouble upgrading to NC18)

The email share is a regular link-share plus email-notification, so the the default settings should apply, in particular since the sharing person - since not displayed - could easily forget to set an expiration

**Comment by skjnldsv** [comment]
> cc @skjnldsv is that fixed with the new sidebar?

yes, mail now behave the same as links (well, they are the same after all, so)
We will not backport it to older versions as the logic is fairly different in the code :(
