### ISSUE TITLE
Bulk delete of shares

### ISSUE THREAD

**Issue by frlan** [nextcloud/server#15142]
It would be cool to allow bulk deleting of shares via e.g. apps/files/?dir=/&view=shareoverview 

Scenario:
When not setting an expiration date for a share e.g. via link it happens with time, that there are a huge number of shares. So given this long list, it would be nice to just select the shared items and remove the shares with a few clicks instead of deleting each link on each item.

**Comment by skjnldsv** [comment]
Done with nc 28!

**Comment by Leinad4Mind** [comment]
Hi there, I have version 31 and still can't see how I can bulk delete shares

**Comment by Denyerec** [comment]
Came here with the same issue, I have been testing creating shares with the API and now have scores of them everywhere. It'd be nice to be able to just highlight the folders and hit an "Unshare" button, but I'm unable to find a way in the UI without manually going through each one.
