### ISSUE TITLE
File name is omitted if it is a smartphone with NC17

### ISSUE THREAD

**Issue by Bables55** [nextcloud/server#17364]
After updating to Nextcloud 17.0.0, I accessed the NC with an iPhone web browser.
When I hold the iPhone vertically and look at the file list, the file name is omitted and the icon, file size, menu, and update date and time are displayed. The share icon is covered by the file size. Some browsers display some characters of the file extension by the Web browser. Of course I usually see it if I hold it horizontally.
If I use the iOS app of NC, it will display normally even if I have it vertically.

I think the display when the user holds the smartphone vertically can omit the file size and update date.

**Comment by kesselb** [comment]
Is it possible to add a screenshot to your report?

**Comment by Bables55** [comment]
> Is it possible to add a screenshot to your report?
![smartphonesize](https://user-images.githubusercontent.com/30524004/66102025-df6c4200-e5eb-11e9-9832-a67202f2d97a.png)
*I'm Japanese and the NC language is set to English, but the time display is Japanese.

**Comment by Octopus2** [comment]
![Screenshot_2019-10-03_16-30-28](https://user-images.githubusercontent.com/4060419/66136383-aa67eb80-e5fb-11e9-9f0b-3c2d8485c3d8.png)

Some with Nextcloud 17, Android 8 on an Samsung Galaxy S7, Chrome

**Comment by AndyFx12** [comment]
same here - Nextcloud 17 with Android 7.1.1 on an MotoG4-Play. Chrome and Firefox.

**Comment by DmDS** [comment]
same thing....

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by elpraga** [comment]
Also present on Android devices.  

It makes it impossible to browse folders and files when the phone is in vertical position.

**Comment by justasomeone** [comment]
it shows in landscape mode, and on my pcs, and in grid mode, but both my phones (IphoneSE and Samsung S8) have this issue in portrait mode, which is the mode I use often. :( 

![5WM7kgf](https://user-images.githubusercontent.com/56227254/66270942-c3081980-e826-11e9-9a63-6c5598d7936e.jpg)

**Comment by GretaD** [comment]
this was suppose to be fixed with this PR: #17162 
It looks good on the 18th version, but it still exist on the 17th one

**Comment by GretaD** [comment]
After consulting this with @jancborchardt looks like the problem is that the **Size** and **Modified** column is not suppose to be there at the first place on mobile view. This might be a regression of some other change. I am working to fix this.

**Comment by Gatak** [comment]
Should this not be tested before a release?

**Comment by kesselb** [comment]
Pinned this issue a few days ago because I had in mind that a lot of people are going to report this. I don't know why someone unpinned it but given that we already had 4 more reports since then I'm pinning it again.

**Comment by skjnldsv** [comment]
> I don't know why someone unpinned it

I just tried, and it show a message when someone unpin a ticket :thinking: 
And I cannot find the previous unpin message! (that time it was not me @kesselb :grin: )

**Comment by jancborchardt** [comment]
> @weeman1337 unpinned this issue 19 days ago

;)

**Comment by kesselb** [comment]
Hmm. I'm sorry for using a bad phrase. What I wanted to say is: "I'm pinning it again because people are reporting this."  :see_no_evil:

**Comment by Gatak** [comment]
This is now fixed on 17 RC1! :smile:

**Comment by rollanders** [comment]
It is still present in NC17.0.1 RC1 on Chrome in Android mobile. Firefox for Android scales OK. 
Another issue related to mobile screen is that in the contacts list I can only swipe sideways on the top of the screen, above the contacts names.

**Comment by Gatak** [comment]
Sorry. I only checked with Opera Mobile (which is based on Chrome). No scaling issue there either.

**Comment by rollanders** [comment]
Maybe a problem with caching. Now it works OK!

**Comment by jancborchardt** [comment]
Thanks a lot for testing and confirming the fix everyone! :)
