### ISSUE TITLE
SVG logo fill color is changed in Firefox

### ISSUE THREAD

**Issue by virhonestum** [nextcloud/server#17814]
### Steps to reproduce
1. Upload the following file as the logo to your nextcloud instance

<details>
<summary>logo-file.svg</summary>

```svg
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 463 463" style="enable-background:new 0 0 463 463;" xml:space="preserve">
    <style type="text/css">
		.st0{fill:#FFFFFF;}
	</style>
    <path class="st0" d="M375.2,200c-5.8,0-11.7,0.6-17.4,1.7c-4.3-21.5-18.3-39.9-37.9-49.9c-19.6-9.9-42.7-10.4-62.6-1.1
	c-18-49.7-73-75.4-122.7-57.3s-75.4,73-57.3,122.7c-43.5,1.4-77.9,37.4-77.3,81c0.7,43.6,36.1,78.5,79.7,78.6h295.5
	c48.5,0,87.8-39.3,87.8-87.8S423.7,200,375.2,200z"></path>
</svg>
```
</details>

### Expected behaviour
A white cloud will be the logo

### Actual behaviour
In Firefox (all addons disabled, nextcloud dark mode disabled) the cloud is actually black. In Vivaldi and Chromium the cloud is white, like its supposed to be.
Before the update to NC17 it also worked fine.

### Server configuration

**Operating system**: I unfortunately don't know

**Web server:** Not showing in the server info settings tab either

**Database:** mysql

**PHP version:** 7.3.11

**Nextcloud version:** 17.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Update

**Where did you install Nextcloud from:** My hosting provider did it

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - apporder: 0.8.0
  - calendar: 1.7.1
  - carnet: 0.18.7
  - circles: 0.17.8
  - cloud_federation_api: 1.0.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - deck: 0.7.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - impersonate: 1.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - metadata: 0.10.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - occweb: 0.0.4
  - password_policy: 1.7.0
  - polls: 0.10.4
  - provisioning_api: 1.7.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - spreed: 7.0.1
  - tasks: 0.11.3
  - text: 1.1.0
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_totp: 4.0.0
  - updatenotification: 1.7.0
  - viewer: 1.1.0
  - workflowengine: 1.7.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.0.9",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379",
            "timeout": "1.5",
            "dbindex": "0"
        },
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "log_type": "syslog",
        "syslog_tag": "nextcloud-nx3851",
        "simpleSignUpLink.shown": false,
        "upgrade.disable-web": true,
        "updatechecker": true,
        "mail_sendmailmode": "smtp",
        "maintenance": false,
        "has_rebuilt_cache": true,
        "loglevel": 2,
        "app_install_overwrite": [
            "occweb"
        ],
        "skeletondirectory": "\/var\/www\/html\/themes\/hetzner\/skeleton"
    }
}
```
</details>

**Are you using external storage, if yes which one:** nope

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 70.0.1

**Operating system:** Both on Windows 10 and Manjaro with KDE Plasma

### Logs
Unfortunately I don't have access to any of the logs

**Comment by kesselb** [comment]
cc @juliushaertl

**Comment by metroid2010** [comment]
I have the same problem. The logo is a SVG, too.
Screenshots:
![chromium](https://user-images.githubusercontent.com/17139470/68477507-f70f9980-022d-11ea-8b50-f89fa674460b.png)
![firefox](https://user-images.githubusercontent.com/17139470/68477516-f8d95d00-022d-11ea-90b2-f5df57b38522.png)

**Comment by aladen** [comment]
Hi, same issue here.
The default svg logo can be replaced in /core/img/logo awaiting a fix.
![screenshot-01](https://user-images.githubusercontent.com/15218159/68547537-e94f4500-03e2-11ea-8229-14c4f829dc29.jpg)
![screenshot-02](https://user-images.githubusercontent.com/15218159/68547538-f409da00-03e2-11ea-9652-ed8807f5ae51.jpg)

**Comment by aladen** [comment]
It seems to be related to this:
https://github.com/ImageMagick/ImageMagick/issues/1510

**Comment by aladen** [comment]
I tried :
# apt-get install libmagickcore-6.q16-6-extra
# systemctl restart php7.3-fpm.service apache2.service
# sudo -u www-data php /var/www/cloud/occ maintenance:repair

It fixed the svg color but messed up the BO...

**Comment by pieter-groeneweg** [comment]
![image](https://user-images.githubusercontent.com/10771283/69091928-99f4be80-0a4b-11ea-9871-bc06ac00b2b6.png)

Same here... 
debian 9, PHP 7.2, apache 2.4, MySQL 10.1.41-MariaDB

clicking the image in the debugger may open this in a single tab in FF allright in correct colors..

**Comment by michaelschefczyk** [comment]
Im my case, this does happen right after updating to 17 (17.0.1) and just with Firefox - not Chromium and not Internet Explorer. I may have to do with mime types, but how to change it is not obvious for me. My server side mime.types file seems to be OK and the mimetypemapping.dist.json seeps to be OK as well - it does contain: "svg": ["image/svg+xml", "text/plain"],

Is there any known workaround for Firefox?

**Comment by pieter-groeneweg** [comment]
Targeting the login page.
When i check debugger - network - in FF i see a bunch of files blocked "CSP".. whereas Chrome allows them. 

FF has initiator "unknown"
Chrome has initiator "login?clear=1"

Screenshot is FF debugger... the blocked files are loaded fine further down the list (ie. as in green main.js?v=bceeb4db-6 and on are loaded)
This is not happening in Chrome.

![afbeelding](https://user-images.githubusercontent.com/10771283/69738590-a907fa80-1136-11ea-931b-6c39f336daff.png)

**Comment by kesselb** [comment]
> Cannot say it is related but it is an observation....

https://github.com/nextcloud/server/issues/12724#issuecomment-548361148

**Comment by juliushaertl** [comment]
Possible fix at https://github.com/nextcloud/server/pull/18140 

Testing is very welcome.

**Comment by pieter-groeneweg** [comment]
see my comment in https://github.com/nextcloud/server/pull/18140
for the svg it works the red lines in FF debugger remain... no extensions enabled...

**Comment by juliushaertl** [comment]
The red lines are actually a firefox bug, see https://github.com/nextcloud/server/issues/12724#issuecomment-548361148 for details.

**Comment by pieter-groeneweg** [comment]
I will leave the red lines to Mozilla to solve.. ;)

**Comment by juliushaertl** [comment]
Fix merged

**Comment by michaelschefczyk** [comment]
I did install 17.0.2 hoping that the issue would go away. However, the issue remains unchanged. Can a knowledgeable person please point out when merges will hit generally available releases?

**Comment by kesselb** [comment]
> Can a knowledgeable person please point out when merges will hit generally available releases?

Nextcloud 18. Critical patches are backported to earlier releases.

**Comment by pieter-groeneweg** [comment]
That is lame... we can be going for 17.0.15 before we upgrade to 18 and all updates in 17 will have this bug?

**Comment by kesselb** [comment]
>  all updates in 17 will have this bug?

Yes. Is this something that should be backported? Is there any real impact (e.g. something is not working) beside the cosmetic issues?

**Comment by pieter-groeneweg** [comment]
yes, since users think it is broken.... any visual defect is damaging trust..
to have an app widely accepted it needs trust.

Apart from a bug that can be solved by adding three lines!

**Comment by kesselb** [comment]
Fix is coming to 17.0.3 and 16.0.8

**Comment by aladen** [comment]
Thanks for the backports #18140

**Comment by pieter-groeneweg** [comment]
Awesome! Thanks jou guys.

**Comment by pieter-groeneweg** [comment]
It apparently did not make it into 17.0.3

**Comment by michaelschefczyk** [comment]
To get rid of this issue, I did upgrade to 18.

Von: pieter-groeneweg <notifications@github.com>
Gesendet: Freitag, 7. Februar 2020 10:05
An: nextcloud/server <server@noreply.github.com>
Cc: Prof. Dr. Michael Schefczyk <michael@schefczyk.net>; Comment <comment@noreply.github.com>
Betreff: Re: [nextcloud/server] SVG logo fill color is changed in Firefox (#17814)


It apparently did not make it into 17.0.3

**Comment by aladen** [comment]
Actually, still not backported in 17.0.3
apps/theming/lib/Controller/ThemingController.php
#18140

Applying manually the 3 lines fix can do the trick but it will break the security scan.

**Comment by Moini** [comment]
As a workaround, one can also edit the SVG file. Convert the fill in the style attribute to a standalone fill attribute, i.e. if there's 

`style="fill:#ffffff; ..."`

take the fill (and stroke, if used) out and make it:

`fill=#ffffff`

This can only be done quickly for very simple files.

Inkscape can do this automatically, when saving as optimized SVG.

![screenshot_2020-03-06_18-57-05](https://user-images.githubusercontent.com/3240233/76109219-4eefbe80-5fdc-11ea-825b-8ef19c40109f.png)

**Comment by Moini** [comment]
17.0.4 seems to have the update.
