### ISSUE TITLE
Delete from external storage will cause an error in log and no particular files in trash bin

### ISSUE THREAD

**Issue by GAS85** [nextcloud/server#18132]
### Steps to reproduce
1. Added local Folder as External storage
2. Have Quote usage above 50%
3. Delete big file from the External Storage via Android Client
4. See error in log
```
{"reqId":"MyoScupZtkTYEI1sGQ7L","level":3,"time":"2019-11-26T17:14:29+00:00","remoteAddr":"111.111.111.111","user":"UserX","app":"PHP","method":"DELETE","url":"\/remote.php\/webdav\/Externals\/Local\/SomeFile.mkv","message":"rename(\/\/home\/UserX\/samba\/share\/usb\/Video\/SomeFile.mkv,\/\/var\/nextcloud\/data\/UserX\/files_trashbin\/files\/SomeFile.mkv.d1574788025): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#289","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.9.0","version":"16.0.6.1"}
{"reqId":"if7qeqresmfkYWY0EHCV","level":3,"time":"2019-11-26T17:15:11+00:00","remoteAddr":"111.111.111.111","user":"UserX","app":"PHP","method":"DELETE","url":"\/remote.php\/webdav\/Externals\/Local\/SomeFile2.mkv","message":"rename(\/\/home\/UserX\/samba\/share\/usb\/Video\/SomeFile2.mkv,\/\/var\/nextcloud\/data\/UserX\/files_trashbin\/files\/SomeFile2.mkv.d1574788058): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#289","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.9.0","version":"16.0.6.1"}
```
5. Check trash bin - no files were found.
6. Check External storage folder - files are deleted.

### Expected behaviour
Deleting of files from external storage should cause moving of them to the Nextcloud Trashbin.

### Actual behaviour
Files were deleted without moving them into trash-bin and error was logged.

```
{"reqId":"MyoScupZtkTYEI1sGQ7L","level":3,"time":"2019-11-26T17:14:29+00:00","remoteAddr":"111.111.111.111","user":"UserX","app":"PHP","method":"DELETE","url":"\/remote.php\/webdav\/Externals\/Local\/SomeFile.mkv","message":"rename(\/\/home\/UserX\/samba\/share\/usb\/Video\/SomeFile.mkv,\/\/var\/nextcloud\/data\/UserX\/files_trashbin\/files\/SomeFile.mkv.d1574788025): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#289","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.9.0","version":"16.0.6.1"}
{"reqId":"if7qeqresmfkYWY0EHCV","level":3,"time":"2019-11-26T17:15:11+00:00","remoteAddr":"111.111.111.111","user":"UserX","app":"PHP","method":"DELETE","url":"\/remote.php\/webdav\/Externals\/Local\/SomeFile2.mkv","message":"rename(\/\/home\/UserX\/samba\/share\/usb\/Video\/SomeFile2.mkv,\/\/var\/nextcloud\/data\/UserX\/files_trashbin\/files\/SomeFile2.mkv.d1574788058): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#289","userAgent":"Mozilla\/5.0 (Android) Nextcloud-android\/3.9.0","version":"16.0.6.1"}
```

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache/2.4.41 (Ubuntu)

**Database:** mysql  Ver 15.1 Distrib 10.1.43-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2

**PHP version:** PHP 7.3.11

**Nextcloud version:** 16.06

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated 

**Where did you install Nextcloud from:** Official

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - audioplayer: 2.8.4
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - checksum: 0.4.3
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - data_request: 1.3.0
  - dav: 1.9.2
  - deck: 0.6.6
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_automatedtagging: 1.6.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_retention: 1.5.1
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - flowupload: 0.1.5
  - gallery: 18.3.0
  - gpxpod: 4.1.0
  - keeweb: 0.5.1
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.17.0
  - maps: 0.1.2
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.3
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - phonetrack: 0.5.2
  - polls: 0.10.4
  - previewgenerator: 2.1.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - radio: 0.6.5
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 3.0.1
  - unsplash: 1.1.4
  - updatenotification: 1.6.0
  - viewer: 1.2.0
  - weather: 1.6.4
  - workflowengine: 1.6.0
Disabled:
  - encryption
  - files_external_dropbox
  - impersonate
  - sharerenamer
  - support
  - user_ldap
  - workflow_script
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "DOMAIN1",
            "2": "DOMAIN2"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/DOMAIN1\/nextcloud",
        "dbtype": "mysql",
        "version": "16.0.6.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filesystem_check_changes": 0,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 1.5
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "logfile": "\/var\/nextcloud\/data\/nextcloud.log",
        "loglevel": 1,
        "trashbin_retention_obligation": "14, auto",
        "versions_retention_obligation": "14, 180",
        "data-fingerprint": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "preview_max_x": 1080,
        "preview_max_y": 1920,
        "auth.bruteforce.protection.enabled": true,
        "simpleSignUpLink.shown": false,
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "has_rebuilt_cache": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** local + WebDAV

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**  No

**Comment by kesselb** [comment]
Another report about this issue https://github.com/nextcloud/server/issues/19171

**Comment by Xaklse** [comment]
I recently discovered the same problem on Nextcloud 18.0.4; months ago I moved from NC16 to NC17 and then to NC18. No errors in log related to this (I think so). Files moved to trash bin from "internal" storage aren't missing.
It would be great to know if it can be easily reproduced.

**Comment by acsfer** [comment]
Fixed by https://github.com/nextcloud/server/pull/21628

**Comment by Xaklse** [comment]
Not fixed; problem reproduced on server that upgraded to Nextcloud 18.0.8
#21982 #21628
