### ISSUE TITLE
The registry button is not in the middle (Version 18.0.0)

### ISSUE THREAD

**Issue by hensephil** [nextcloud/server#19049]
The registry button on my nextcloud is not in the middle Its slightly to thr left. but its only on the web version of it.
It first started to apear in version 18.0.0.
<img width="691" alt="2020-01-21 14_38_14-Juze" src="https://user-images.githubusercontent.com/51832284/72809504-082c4c00-3c5c-11ea-96ea-07b027a7b5f2.png">

**Comment by Ecphrasis** [comment]
Same thing with the user_cas app (https://apps.nextcloud.com/apps/user_cas) installed !

![Sans titre](https://user-images.githubusercontent.com/11899009/72849284-a6450400-3ca6-11ea-8275-300f2ffb68f4.png)

**Comment by AaronADev** [comment]
Same issue here as well

**Comment by felixrupp** [comment]
As the developer of user_cas, I don’t have any control over the styling of the additional login button on the startpage. Sorry for that!

**Comment by PaulterTV** [comment]
same issue on my site

**Comment by kesselb** [comment]
Could you try #19238?

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/server/pull/19238

**Comment by Ecphrasis** [comment]
I'm sorry to re-open this issue, but since upgrade to 18.0.1, the button is at the middle, but the CSS still doesn't apply to him, and the button is very ugly. it's not a dramatic bug, but I love my beautiful theme :)
![Sans titre](https://user-images.githubusercontent.com/11899009/74443146-0167b200-4e73-11ea-8ba8-7c3bb5331696.png)
