### ISSUE TITLE
Force applications update check button

### ISSUE THREAD

**Issue by waazdakka** [nextcloud/server#19172]
**Is your feature request related to a problem? Please describe.**
Could you add a force update check in the Applications pages, allowing the admin to push an update when he wants to ?

**Describe the solution you'd like**
Add a "Check applications updates" on the "Your applications" tab
Maybe add the possibilty to modify the frequency of the automatic check in the settings panel ?

**Describe alternatives you've considered**

**Additional context**

**Comment by kesselb** [comment]
Are you talking about Nextcloud or apps for Nextcloud?

**Comment by waazdakka** [comment]
Apps for Nextcloud! :)

**Comment by kesselb** [comment]
Nextcloud caches the response from apps.nextcloud.com for 5 minutes. So every time you visit the apps management page you see the available updates. I don't see the need to change anything here. It's planned to update the cache with a background job and probably keep it longer than 5 minutes. Then probably a force applications update make sense.

**Comment by waazdakka** [comment]
Oh, if it's every 5 minutes, indeed I guess there is no reason for such a button! 👍  :)

**Comment by szaimen** [comment]
Seems like this is resolved.

**Comment by PanCakeConnaisseur** [comment]
5 minutes doesn't seem to be right. I have been waiting for 50 minutes for my instance (Nextcloud Hub 7 (28.0.5)) to pick up  a new app version and it's still not registering it.

Is there a CLI way to force this?
