### ISSUE TITLE
Error opening a PDF shared by link

### ISSUE THREAD

**Issue by cksr9** [nextcloud/server#19572]
### Steps to reproduce
1. Create approval with a PDF
2. Click "Hide download"
3. Share link

### Expected behaviour
Open PDF in PDF viewer

### Actual behaviour
"Missing PDF file" appears when opened

### Server configuration

**Operating system:** Ubuntu 18.04 LTS

**Web server:** nginx

**Database:** mysql 10.4.12

**PHP version:** 7.3.15

**Nextcloud version:** 18.01

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
 accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - carnet: 0.20.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.8
  - dav: 1.14.0
  - documentserver_community: 0.1.5
  - encryption: 2.6.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_antivirus: 2.2.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - passwords: 2020.2.1
  - photos: 1.0.0
  - polls: 1.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.2
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0


</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/server/pull/19349 is causing this, the issue is that the pdf viewer still needs to download the file of course to show it. This is one on the main reasons why this was mainly a "hide download" feature instead of a "disable download" in the first place.

Not sure how we should solve this, as we either allow download of the file to the browser somehow or we cannot show filetypes that are rendered in the frontend. 

cc @rullzer @nickvergessen

**Comment by nickvergessen** [comment]
Should be fixed by #19699

**Comment by cksr9** [comment]
The error remains despite the changes.
![image](https://user-images.githubusercontent.com/61312752/76503304-f0946700-6445-11ea-946a-548d79de5e6f.png)

**Comment by cheneraie** [comment]
Same issue with Nextcloud 17.0.4.

**Comment by cheneraie** [comment]
> 
> 
> Same issue with Nextcloud 17.0.4.

And the error remains after 18.0.2 upgrade.

**Comment by juliushaertl** [comment]
I can reproduce, let me have another look at that.

**Comment by juliushaertl** [comment]
Seems @nickvergessen was faster with https://github.com/nextcloud/server/pull/20032 :wink:

**Comment by nickvergessen** [comment]
Fixed by #20032

**Comment by cheneraie** [comment]
Not quite fixed.
OK for the PDF files directly shared. But for PDF files contains by public shared folder, we still have the message about missing PDF.

**Comment by nickvergessen** [comment]
Yeah it has been foxed afterwards with #20032

**Comment by cheneraie** [comment]
OK. Thanks. I'll wait :-).

**Comment by fuco809** [comment]
i have with a new 20.0.7 version this issue again, anyone else?
running on apache2.4 + fpm php7.3 + nextcloud 20.0.7 (upgraded from 18)

**Comment by nickvergessen** [comment]
it was fixed for 20.0.8
