### ISSUE TITLE
OC\User\NoUserException: Backends provided no user object

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#19647]
I use two nextcloud updated to version 18.0.1 and I have problem in deleting files from a shared federated folder.  while nextcloud user who shared my folder with me you can safely operate the files I who received the federated folder I can upload the images but not delete them although on another instance I have permissions on the folder for editing.  I get this error "OC \ User \ NoUserException: Backends provided no user object" how can I solve?

```
Attach complete error:

[webdav] Fatal: OC\User\NoUserException: Backends provided no user object at <<closure>>

 0. <<closure>>
    OC\Files\Node\Root->getUserFolder("Studio@scavalentenx.duckdns.org/")
 1. /var/www/Pensierando/nx/lib/private/Files/Node/LazyRoot.php line 65
    call_user_func_array([OC\Files\Node\Root {},"getUserFolder"], ["Studio@scavalentenx.duckdns.org/"])
 2. /var/www/Pensierando/nx/lib/private/Files/Node/LazyRoot.php line 282
    OC\Files\Node\LazyRoot->__call("getUserFolder", ["Studio@scavalentenx.duckdns.org/"])
 3. /var/www/Pensierando/nx/apps/files_trashbin/lib/Storage.php line 142
    OC\Files\Node\LazyRoot->getUserFolder("Studio@scavalentenx.duckdns.org/")
 4. /var/www/Pensierando/nx/apps/files_trashbin/lib/Storage.php line 182
    OCA\Files_Trashbin\Storage->shouldMoveToTrash("2020-02-23_161848.jpg")
 5. /var/www/Pensierando/nx/apps/files_trashbin/lib/Storage.php line 100
    OCA\Files_Trashbin\Storage->doDelete("2020-02-23_161848.jpg", "unlink")
 6. /var/www/Pensierando/nx/apps/files_accesscontrol/lib/StorageWrapper.php line 287
    OCA\Files_Trashbin\Storage->unlink("2020-02-23_161848.jpg")
 7. /var/www/Pensierando/nx/lib/private/Files/View.php line 1162
    OCA\FilesAccessControl\StorageWrapper->unlink("2020-02-23_161848.jpg")
 8. /var/www/Pensierando/nx/lib/private/Files/View.php line 716
    OC\Files\View->basicOperation("unlink", "/Cartella Con T ... g", ["delete"])
 9. /var/www/Pensierando/nx/apps/dav/lib/Connector/Sabre/File.php line 448
    OC\Files\View->unlink("/Cartella Con T ... g")
10. /var/www/Pensierando/nx/3rdparty/sabre/dav/lib/DAV/Tree.php line 179
    OCA\DAV\Connector\Sabre\File->delete()
11. /var/www/Pensierando/nx/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 287
    Sabre\DAV\Tree->delete("files/Tiger/Car ... g")
12. <<closure>>
    Sabre\DAV\CorePlugin->httpDelete(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
13. /var/www/Pensierando/nx/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpDelete"], [Sabre\HTTP\Requ ... }])
14. /var/www/Pensierando/nx/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:DELETE", [Sabre\HTTP\Requ ... }])
15. /var/www/Pensierando/nx/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
16. /var/www/Pensierando/nx/apps/dav/lib/Server.php line 319
    Sabre\DAV\Server->exec()
17. /var/www/Pensierando/nx/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
18. /var/www/Pensierando/nx/remote.php line 165
    require_once("/var/www/Pensie ... p")

DELETE /remote.php/dav/files/Tiger/Cartella%20Con%20Tiger/2020-02-23_161848.jpg
from 37.160.88.102 by Tiger at 2020-02-25T21:10:45+00:00
```

**Comment by tigernero79** [comment]
in practice, those who receive the federated folder from another nextcloud despite having the permissions to delete, cannot delete files that only the one who shared the federated folder puts in that folder, while I, who received the shared folder in my nextcloud, can only files but don't delete them as well if other has given me the permissions.

**Comment by tigernero79** [comment]
@nickvergessen I read that you committed to the problem that I have on nextcloud 12, 

https://github.com/nextcloud/files_downloadactivity/pull/8

but now I run on instance nextcloud 18.0.1 and I still have that error on the federated shared folders where those who shared can delete the files and those who receive the federated folder it cannot delete the files inside despite having received the permissions. how to solve?

**Comment by pilsetnieks** [comment]
Same happens on 18.0.3

**Comment by arjan-s** [comment]
Same on 18.0.4 :(

**Comment by aimotrens** [comment]
Same problem on 18.0.7

**Comment by arjan-s** [comment]
Did the upgrade to 19.0.1, no difference. Still this error when trying to delete files.

**Comment by uPvtkBlpiucvDUf** [comment]
I jus had a look at the stacktrace from https://github.com/nextcloud/server/issues/19647#issue-570839647 and the code. The problem seems to be this in the trashbin app (`OCA\Files_Trashbin\Storage::shouldMoveToTrash`):

```php
// check if there is a app which want to disable the trash bin for this file
$fileId = $this->storage->getCache()->getId($path);
$owner = $this->storage->getOwner($path);
if ($owner === false) {
	$nodes = $this->rootFolder->getById($fileId);
} else {
	$nodes = $this->rootFolder->getUserFolder($owner)->getById($fileId);
}
```

This assumes `$owner` is either `false` or a user. However, for federated shares, `$owner` is something like `Studio@scavalentenx.duckdns.org/`, which is neither `false` nor a user. As a result, `$this->rootFolder->getUserFolder($owner)` raises an exception and the delete operation fails.

The problems seems to have been introduced in this commit: https://github.com/nextcloud/server/commit/8e7c287e2ac4bd60d69a77fb7295e8ea2b8b9617. I think the trashbin behavior needs to be adjusted to work with federated shares. Unfortunately, I don't know enough about nextcloud internals to know how the trashbin should be correctly handled in this case.

@rullzer Can you help?

Fwiw: I can reproduce this issue on 19.0.1 and when it occurs I can also reproduce this other issue: https://github.com/nextcloud/desktop/issues/853 regarding high CPU usage of the desktop client. This high CPU usage occurs precisely after I receive a federated share and then try to delete a file in this share (which fails as described above). If I remove the federated share, also the desktop client syncing issue is gone. The reason seems to be that the server always sends a new `Etag` to the client for the federated share so that the client is constantly syncing (according to logs recorded with `nextcloud --logdebug`). I will write a more detailed comment about this when I find the time.

**Comment by fettfoen** [comment]
I have the same problem. Similar/identical log entries. Im running nextcloud 17.0.3, will upgrade to latest nextcloud 18 soon as possible.

Is this a known bug? Is there any workaround or wait until fixed?

**Comment by khlschrnk** [comment]
I also got this problem since a a long time. Now, with 19.0.3 it's still appearing in my log at every run of cron.

**Comment by kiplingw** [comment]
I am experiencing the same problem on 19.0.3. Remote user shared a folder with me. They have given me full permissions to create, edit, and delete. I am able to do all of but the latter. The logs show the following stack trace:

```
{"reqId":"X2Z8DISIBkpZi3KVwiBabgAAAA0",
"level":3,
"time":"2020-09-19T21:45:53+00:00",
"remoteAddr":"<redacted>",
"user":"kip",
"app":"files",
"method":"DELETE",
"url":"/remote.php/dav/files/<redacted>/test.md",
"message":"Backends provided no user object for <redacted>@nextcloud.<redacted>.com/",
"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0",
"version":"19.0.3.1"}
{
    "reqId":"X2Z8DISIBkpZi3KVwiBabgAAAA0",

    "level":4,

    "time":"2020-09-19T21:45:53+00:00",

    "remoteAddr":"<redacted>",

    "user":"kip",

    "app":"webdav",

    "method":"DELETE",

    "url":"/remote.php/dav/files/<redacted>/test.md",

    "message":
    {
        "Exception":"OC\\User\\NoUserException",

        "Message":"Backends provided no user object",

        "Code":0,

        "Trace":
        [
            {
                "function":"getUserFolder",

                "class":"OC\\Files\\Node\\Root",

                "type":"->",

                "args":
                [
                    "<redacted>@nextcloud.<redacted>.com/"
                ]
            },

            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/lib/private/Files/Node/LazyRoot.php",

                "line":66,

                "function":"call_user_func_array",

                "args":
                [
                    [
                        {
                            "__class__":"OC\\Files\\Node\\Root"
                        },

                        "getUserFolder"
                    ],

                    [
                        "<redacted>@nextcloud.<redacted>.com/"
                    ]
                ]
            },

            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/lib/private/Files/Node/LazyRoot.php",

                "line":283,

                "function":"__call",

                "class":"OC\\Files\\Node\\LazyRoot",

                "type":"->",

                "args":
                [
                    "getUserFolder",

                    [
                        "<redacted>@nextcloud.<redacted>.com/"
                    ]
                ]
            },

            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/apps/files_trashbin/lib/Storage.php",

                "line":141,

                "function":"getUserFolder",

                "class":"OC\\Files\\Node\\LazyRoot",

                "type":"->",

                "args":
                [
                    "<redacted>@nextcloud.<redacted>.com/"
                ]
            },

            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/apps/files_trashbin/lib/Storage.php",

                "line":181,

                "function":"shouldMoveToTrash",

                "class":"OCA\\Files_Trashbin\\Storage",

                "type":"->",

                "args":
                [
                    "test.md"
                ]
            },

            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/apps/files_trashbin/lib/Storage.php",

                "line":99,

                "function":"doDelete",

                "class":"OCA\\Files_Trashbin\\Storage",

                "type":"->",

                "args":
                [
                    "test.md",

                    "unlink"
                ]
            },

            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/lib/private/Files/View.php",

                "line":1161,

                "function":"unlink",

                "class":"OCA\\Files_Trashbin\\Storage",

                "type":"->",

                "args":
                [
                    "test.md"
                ]
            },

            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/lib/private/Files/View.php",

                "line":718,

                "function":"basicOperation",

                "class":"OC\\Files\\View",

                "type":"->",

                "args":
                [
                    "unlink",

                    "/<redacted>/test.md",

                    [
                        "delete"
                    ]
                ]
            },

            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/apps/dav/lib/Connector/Sabre/File.php",

                "line":458,
                "function":"unlink",
                "class":"OC\\Files\\View",
                "type":"->",
                "args":
                [
                    "/<redacted>/test.md"
                ]
            },
            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/3rdparty/sabre/dav/lib/DAV/Tree.php",
                "line":183,
                "function":"delete",
                "class":"OCA\\DAV\\Connector\\Sabre\\File",
                "type":"->",
                "args":[]
            },
            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
                "line":295,
                "function":"delete",
                "class":"Sabre\\DAV\\Tree",
                "type":"->",
                "args":
                [
                    "files/kip/<redacted>/test.md"
                ]
            },
            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
                "line":89,
                "function":"httpDelete",
                "class":"Sabre\\DAV\\CorePlugin",
                "type":"->",
                "args":
                [
                    {
                        "__class__":"Sabre\\HTTP\\Request"
                    },
                    {
                        "__class__":"Sabre\\HTTP\\Response"
                    }
                ]
            },
            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/3rdparty/sabre/dav/lib/DAV/Server.php",
                "line":474,
                "function":"emit",
                "class":"Sabre\\DAV\\Server",
                "type":"->",
                "args":
                [
                    "method:DELETE",
                    [
                        {
                            "__class__":"Sabre\\HTTP\\Request"
                        },
                        {
                            "__class__":"Sabre\\HTTP\\Response"
                        }
                    ]
                ]
            },
            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/3rdparty/sabre/dav/lib/DAV/Server.php",
                "line":251,
                "function":"invokeMethod",
                "class":"Sabre\\DAV\\Server",
                "type":"->",
                "args":
                [
                    {
                        "__class__":"Sabre\\HTTP\\Request"
                    },
                    {
                        "__class__":"Sabre\\HTTP\\Response"
                    }
                ]
            },
            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/3rdparty/sabre/dav/lib/DAV/Server.php",
                "line":319,
                "function":"start",
                "class":"Sabre\\DAV\\Server",
                "type":"->",
                "args":
                [
                ]
            },
            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/apps/dav/lib/Server.php",
                "line":320,
                "function":"exec",
                "class":"Sabre\\DAV\\Server",
                "type":"->",
                "args":
                [
                ]
            },
            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/apps/dav/appinfo/v2/remote.php",
                "line":35,
                "function":"exec",
                "class":"OCA\\DAV\\Server",
                "type":"->",
                "args":
                [
                ]
            },
            {
                "file":"/home/ct_nextcloud/nextcloud.<redacted>.com/remote.php",
                "line":167,
                "args":
                [
                    "/home/ct_nextcloud/nextcloud.<redacted>.com/apps/dav/appinfo/v2/remote.php"
                ],
                "function":"require_once"
            }
        ],
        "File":"/home/ct_nextcloud/nextcloud.<redacted>.com/lib/private/Files/Node/Root.php",
        "Line":373,
        "CustomMessage":"--"
    },
    "userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0",
    "version":"19.0.3.1"
}

```

**Comment by andyboeh** [comment]
I have the same problem. Since in https://github.com/nextcloud/server/issues/19647#issuecomment-665742937 it was mentioned that `files_trashbin` could be the problem, I disabled the "Deleted Files" app on the receiving cloud (it's still enabled on the sharing server). I could then delete the shared folder without a problem.

**Comment by arjan-s** [comment]
I didn't want to disable the trashbin app, so I wrote a small patch for it that is a bit of an ugly workaround for this issue. But hey, it works for me. :)
```
---  apps/files_trashbin/lib/Storage-original-19.0.3.php	2020-10-05 13:50:52.910970135 +0200
+++  apps/files_trashbin/lib/Storage.php	2020-10-05 13:52:05.097636210 +0200
@@ -137,6 +137,8 @@
 		$owner = $this->storage->getOwner($path);
 		if ($owner === false) {
 			$nodes = $this->rootFolder->getById($fileId);
+		} elseif (is_string($owner) && strpos($owner, '@') !== false) {
+			return false;
 		} else {
 			$nodes = $this->rootFolder->getUserFolder($owner)->getById($fileId);
 		}

```

**Comment by andyboeh** [comment]
Yeah, this won't work for me: I use E-Mail addresses as usernames...

**Comment by arjan-s** [comment]
You could also remove the strpos() call and only do the is_string() call, that would work too.

**Comment by fettfoen** [comment]
I guess this should be fixed as soon as possible. Or give an easy way to disable trash for remote shares (federated shares). In my opinion this is not a small problem. I hope the enterprise version is not affected.

**Comment by NDMann** [comment]
Issue still present on Nextcloud 20.0.1 (dafault install/update)

**Issued resolved with this Fix:** 
https://github.com/nextcloud/server/issues/19647#issuecomment-703583321

Worked perfectly when installed on the Nextcloud guest
The host that share the "Federated Share" doesn't need fixes

**Comment by paulkernstock** [comment]
From what I read here, it seems I'm seeing the same error. I can read from and write to a shared folder that comes from a federated NC v20 instance on my NC v20 instance, but deletion fails with `OC\User\NoUserException: Backends provided no user object`.

**Comment by loelkes** [comment]
I get this error wenn I generate previews with the "Preview Generator" app (in connection to OnlyOffice). It seems that the preview generator triggers only office to download the file for preview generation, then the download request fails because of `getUserFolder`. 

Is this an issue related to the preview app or to the server?

**Comment by aquananu** [comment]
i have the same issue, nextcloud 24.0.3 with openldap

can someone help

**Comment by thekk1** [comment]
I have the same problem.
Removing a user in Nextcloud is a main problem that will never be fixed because the developers are much more focused on releasing new main versions instead of making main functions working properly.

As always, the only solution is to do it by your self. I managed it by remove any information from this user from the database and moved the shared files to other users.
Thanks for the addition work @Developers. <3

**Comment by enoch85** [comment]
@nickvergessen Maybe you should have another look at this?

**Comment by nickvergessen** [comment]
> I have the same problem in NC 20 and 21.

Both versions are unsupported since more than 1 year. Please update to Nextcloud 24 which is the oldest still supported version.

> nickvergessen Maybe you should have another look at this?

Doesn't look like a bug with Talk, so no, I can not have a look at this due to limited time I have.

**Comment by thekk1** [comment]
This is what a good developer does!
Jump to a new main version and ignoring bugs that he does in the older with the excuse it is not supported anymore. Even if the bug is still there or its not possible to jump to a new version because the dependencies or dependencies of dependencies in his product does not allow it.

Thx again (23th time I guess) to the fabulous Nextcloud development team.

**Comment by jancborchardt** [comment]
Hi @thekk1, please keep in mind everyone contributing to Nextcloud is human. Passive aggressive comments and implying people are not "good developer[s]" when they describe standard version deprecation practice in software projects is not very kind nor motivating.

Note we have a [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/), and that being friendly is especially important in digital communication. Everyone helps keeping the Nextcloud community a nice place. :)

**Comment by adriangalbincea** [comment]
This is still an issue on 27.1.2. I applied @arjan-s patch and will keep an eye on it. I remember that I patched it in the past again but with the updates it overrides. Please fix this issue and stop saying to users to update the product because is unsupported if you did not address the issue on the newer versions. I understand that we are all humans but this problem has been addressed first time a few years ago and has not been fixed yet.

**Comment by punkyard** [comment]
same on AiO 27.1.0 - I get a log every minute or more

```
[core] Error: OC\User\NoUserException: Backends provided no user object at <<closure>>

 0. <<closure>>
    OC\Files\Node\Root->getUserFolder("")
 1. /var/www/html/lib/private/Files/Node/LazyFolder.php line 74
    call_user_func_array([["OC\\Files\\No ... "], [""])
 2. /var/www/html/lib/private/Files/Node/LazyRoot.php line 40
    OC\Files\Node\LazyFolder->__call("getUserFolder", [""])
 3. /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php line 73
    OC\Files\Node\LazyRoot->getUserFolder("")
 4. /var/www/html/custom_apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 72
    OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFile(["OC\\User\\User"], ["OC\\Files\\FileInfo"])
 5. /var/www/html/custom_apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 59
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder([3,"ENGLISH ... "])
 6. /var/www/html/custom_apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 43
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
 7. /var/www/html/lib/public/BackgroundJob/Job.php line 81
    OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run(null)
 8. /var/www/html/lib/public/BackgroundJob/TimedJob.php line 103
    OCP\BackgroundJob\Job->start(["OC\\BackgroundJob\\JobList"])
 9. /var/www/html/lib/public/BackgroundJob/TimedJob.php line 93
    OCP\BackgroundJob\TimedJob->start(["OC\\BackgroundJob\\JobList"])
10. /var/www/html/cron.php line 152
    OCP\BackgroundJob\TimedJob->execute(["OC\\BackgroundJob\\JobList"], ["OC\\Log"])

at 2023-10-07T20:57:54+00:00
```

**Comment by RailsViceRoads** [comment]
I can confirm that. I receive this log entry with every cron run (every 5 minutes) on my NC instance.
The NC version is 27.1.2.1.

**Comment by ostasevych** [comment]
Getting this error on 27.1.3

**Comment by faxotherapy** [comment]
Me too on 27.1.3, got this in the log:
```
[core] Error: OC\User\NoUserException: Backends provided no user object at <<closure>>

 0. <<closure>>
    OC\Files\Node\Root->getUserFolder()
 1. /snap/nextcloud/38457/htdocs/lib/private/Files/Node/LazyFolder.php line 74
    call_user_func_array()
 2. /snap/nextcloud/38457/htdocs/lib/private/Files/Node/LazyRoot.php line 40
    OC\Files\Node\LazyFolder->__call()
 3. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/Versions/VersionsBackend.php line 73
    OC\Files\Node\LazyRoot->getUserFolder()
 4. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 72
    OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFile()
 5. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 59
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()
 6. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 43
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
 7. /snap/nextcloud/38457/htdocs/lib/public/BackgroundJob/Job.php line 81
    OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run()
 8. /snap/nextcloud/38457/htdocs/lib/public/BackgroundJob/TimedJob.php line 103
    OCP\BackgroundJob\Job->start()
 9. /snap/nextcloud/38457/htdocs/lib/public/BackgroundJob/TimedJob.php line 93
    OCP\BackgroundJob\TimedJob->start()
10. /snap/nextcloud/38457/htdocs/cron.php line 152
    OCP\BackgroundJob\TimedJob->execute()
```

It seems that I got this since I use “group folder” app

**Comment by enoch85** [comment]
@nickvergessen Latest version used so I'm reopening.

Please close if you disagree.

**Comment by ostasevych** [comment]
I am getting this error each an hour in average:

```
{
	"reqId":"6QiC7lkbmLuSCMGF3rq3",
	"level":3,
	"time":"2023-11-19T11:16:03+02:00",
	"remoteAddr":"",
	"user":"--",
	"app":"core",
	"method":"","url":"--",
	"message":"Error while running background job (class: OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions, arguments: )",
	"userAgent":"--",
	"version":"27.1.3.2",
	"exception":{
		"Exception":"OC\\User\\NoUserException",
		"Message":"Backends provided no user object","Code":0,
		"Trace":[{
			"function":"getUserFolder",
			"class":"OC\\Files\\Node\\Root",
			"type":"->"},
			{
			"file":"/var/www/html/nextcloud/lib/private/Files/Node/LazyFolder.php",
			"line":74,
			"function":"call_user_func_array"},{
				"file":"/var/www/html/nextcloud/lib/private/Files/Node/LazyRoot.php",
				"line":40,"function":"__call","class":"OC\\Files\\Node\\LazyFolder",
				"type":"->" },
			{
				"file":"/var/www/html/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php",
				"line":73,
				"function":"getUserFolder",
				"class":"OC\\Files\\Node\\LazyRoot",
				"type":"->"},
			{
				"file":"/var/www/html/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php",
				"line":72,
				"function":"getVersionsForFile",
				"class":"OCA\\GroupFolders\\Versions\\VersionsBackend",
				"type":"->"},
			{
				"file":"/var/www/html/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php",
				"line":59,
				"function":"expireFolder",
				"class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager",
				"type":"->"},
			{
				"file":"/var/www/html/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php",
				"line":43,
				"function":"expireAll",
				"class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager",
				"type":"->"},
			{
				"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/Job.php",
				"line":81,
				"function":"run",
				"class":"OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions",
				"type":"->"},
			{
				"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php",
				"line":103,
				"function":"start",
				"class":"OCP\\BackgroundJob\\Job",
				"type":"->"},
			{
				"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php",
				"line":93,
				"function":"start",
				"class":"OCP\\BackgroundJob\\TimedJob",
				"type":"->"},
			{
				"file":"/var/www/html/nextcloud/cron.php",
				"line":152,
				"function":"execute",
				"class":"OCP\\BackgroundJob\\TimedJob",
				"type":"->"}],
		"File":"/var/www/html/nextcloud/lib/private/Files/Node/Root.php",
		"Line":364,
		"message":"Error while running background job (class: OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions, arguments: )",
		"exception":[],
		"CustomMessage":"Error while running background job (class: OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions, arguments: )"},
	"id":"6559d55f7df4b"}
```

In the logreader:
```
Error | core | OC\User\NoUserException: Backends provided no user object |   | 23 minutes ago
Error | files | OC\User\NoUserException: Backends provided no user object |   | 23 minutes ago
Error | core | OC\User\NoUserException: Backends provided no user object |   | hour ago
Error | files | OC\User\NoUserException: Backends provided no user object |   | hour ago
Error | core | OC\User\NoUserException: Backends provided no user object |   | 2 hours ago
Error | files | OC\User\NoUserException: Backends provided no user object |   | 2 hours ago
Error | core | OC\User\NoUserException: Backends provided no user object |   | 3 hours ago
Error | files | OC\User\NoUserException: Backends provided no user object |   | 3 hours ago
Error | core | OC\User\NoUserException: Backends provided no user object |   | 4 hours ago
Error | files | OC\User\NoUserException: Backends provided no user object |   | 4 hours ago
```

The error both in files and core apps are the same - just dublicating.

**Comment by Gerri1** [comment]
I also have these error messages during my installation.

core - OC\User\NoUserException: Backends provided no user object
file - OC\User\NoUserException: Backends provided no user object

`<html><body>

Fehler | core | OC\User\NoUserException: Backends provided no user object<<closure>>OC\Files\Node\Root->getUserFolder()/var/www/html/nextcloud/lib/private/Files/Node/LazyFolder.php - line 74: call_user_func_array()/var/www/html/nextcloud/lib/private/Files/Node/LazyRoot.php - line 40: OC\Files\Node\LazyFolder->__call()/var/www/html/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php - line 73: OC\Files\Node\LazyRoot->getUserFolder()/var/www/html/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php - line 72: OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFile()/var/www/html/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php - line 59: OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()/var/www/html/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php - line 43: OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()/var/www/html/nextcloud/lib/public/BackgroundJob/Job.php - line 81: OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run()/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php - line 103: OCP\BackgroundJob\Job->start()/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php - line 93: OCP\BackgroundJob\TimedJob->start()/var/www/html/nextcloud/cron.php - line 152: OCP\BackgroundJob\TimedJob->execute()
-- | -- | --



</body>
</html>

`<html><body>

Fehler | files | OC\User\NoUserException: Backends provided no user object<<closure>>OC\Files\Node\Root->getUserFolder()/var/www/html/nextcloud/lib/private/Files/Node/LazyFolder.php - line 74: call_user_func_array()/var/www/html/nextcloud/lib/private/Files/Node/LazyRoot.php - line 40: OC\Files\Node\LazyFolder->__call()/var/www/html/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php - line 73: OC\Files\Node\LazyRoot->getUserFolder()/var/www/html/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php - line 72: OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFile()/var/www/html/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php - line 59: OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()/var/www/html/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php - line 43: OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()/var/www/html/nextcloud/lib/public/BackgroundJob/Job.php - line 81: OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run()/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php - line 103: OCP\BackgroundJob\Job->start()/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php - line 93: OCP\BackgroundJob\TimedJob->start()/var/www/html/nextcloud/cron.php - line 152: OCP\BackgroundJob\TimedJob->execute()
-- | -- | --



</body>
</html>`

**Comment by solracsf** [comment]
Feel free to try https://github.com/nextcloud/groupfolders/pull/2669 and provide feedback.

**Comment by solracsf** [comment]
Reports are a duplicate of https://github.com/nextcloud/groupfolders/issues/2559 so closing gere.

**Comment by k00ni** [comment]
I am confused, why this is a duplicate of https://github.com/nextcloud/groupfolders/issues/2559, if this one is over 2 years older than the linked issue. This issue also contains more information around the problem and tested configurations. It was closed in the meantime but reopened. It seems there is some confusion around here.

**Comment by solracsf** [comment]
No there isn't. Problem is that people see "Backends provided no user object" in the error log and thinks "this is the same issue" while it is **not** the same issue. All recents reports _(this year reports)_ on this issue are related to GroupFolders app, **not** Server.

So, it is a duplicate since the issue must be tracked on GroupFolders repo, **not** here.

**Comment by dgsiegel** [comment]
> So, it is a duplicate since the issue must be tracked on GroupFolders repo, **not** here.

I don't think this is the case, as we don't have the GroupFolders app installed. It only happens with public shares in our instance, see my comment (https://github.com/nextcloud/server/issues/19647#issuecomment-1782875071) above.

**Comment by adriangalbincea** [comment]
> > So, it is a duplicate since the issue must be tracked on GroupFolders repo, **not** here.
> 
> I don't think this is the case, as we don't have the GroupFolders app installed. It only happens with public shares in our instance, see my comment ([#19647 (comment)](https://github.com/nextcloud/server/issues/19647#issuecomment-1782875071)) above.

I agree. I don't have that app either and I get the same error.

**Comment by solracsf** [comment]
Where are your logs backtrace?
"Me too I have the same problem/error/wathever..." means nothing.

**Comment by dgsiegel** [comment]
> Where are your logs backtrace?

There are plenty of log backtraces already in this issue, but here you go:

```
[files] Error: OC\User\NoUserException: Backends provided no user object at <<closure>>

 0. <<closure>>
    OC\Files\Node\Root->getUserFolder()
 1. /var/www/<redacted>/lib/private/Files/Node/LazyFolder.php line 74
    call_user_func_array()
 2. /var/www/<redacted>/lib/private/Files/Node/LazyRoot.php line 40
    OC\Files\Node\LazyFolder->__call()
 3. /var/www/<redacted>/apps/files_versions/lib/Listener/FileEventsListener.php line 359
    OC\Files\Node\LazyRoot->getUserFolder()
 4. /var/www/<redacted>/apps/files_versions/lib/Listener/FileEventsListener.php line 295
    OCA\Files_Versions\Listener\FileEventsListener->getPathForNode()
 5. /var/www/<redacted>/apps/files_versions/lib/Listener/FileEventsListener.php line 116
    OCA\Files_Versions\Listener\FileEventsListener->pre_remove_hook()
 6. /var/www/<redacted>/lib/private/EventDispatcher/ServiceEventListener.php line 86
    OCA\Files_Versions\Listener\FileEventsListener->handle()
 7. /var/www/<redacted>/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 251
    OC\EventDispatcher\ServiceEventListener->__invoke()
 8. /var/www/<redacted>/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 73
    Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
 9. /var/www/<redacted>/lib/private/EventDispatcher/EventDispatcher.php line 94
    Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
10. /var/www/<redacted>/lib/private/EventDispatcher/EventDispatcher.php line 106
    OC\EventDispatcher\EventDispatcher->dispatch()
11. /var/www/<redacted>/lib/private/Files/Node/HookConnector.php line 149
    OC\EventDispatcher\EventDispatcher->dispatchTyped()
12. /var/www/<redacted>/lib/private/legacy/OC_Hook.php line 105
    OC\Files\Node\HookConnector->delete()
13. /var/www/<redacted>/lib/private/Files/View.php line 1270
    OC_Hook::emit()
14. /var/www/<redacted>/lib/private/Files/View.php line 1144
    OC\Files\View->runHooks()
15. /var/www/<redacted>/lib/private/Files/View.php line 702
    OC\Files\View->basicOperation()
16. /var/www/<redacted>/apps/dav/lib/Connector/Sabre/File.php line 536
    OC\Files\View->unlink()
17. /var/www/<redacted>/3rdparty/sabre/dav/lib/DAV/Tree.php line 179
    OCA\DAV\Connector\Sabre\File->delete()
18. /var/www/<redacted>/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 281
    Sabre\DAV\Tree->delete()
19. /var/www/<redacted>/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpDelete()
20. /var/www/<redacted>/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit()
21. /var/www/<redacted>/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
22. /var/www/<redacted>/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
23. /var/www/<redacted>/apps/dav/appinfo/v1/publicwebdav.php line 123
    Sabre\DAV\Server->exec()
24. /var/www/<redacted>/public.php line 81
    require_once("/var/www/<redacted>. ... p")

DELETE /public.php/webdav/<redacted>.pdf
from <redacted> at 2023-12-13T23:10:38+00:00
```

```
[files] Error: OC\User\NoUserException: Backends provided no user object at <<closure>>

 0. <<closure>>
    OC\Files\Node\Root->getUserFolder()
 1. /var/www/<redacted>/lib/private/Files/Node/LazyFolder.php line 74
    call_user_func_array()
 2. /var/www/<redacted>/lib/private/Files/Node/LazyRoot.php line 40
    OC\Files\Node\LazyFolder->__call()
 3. /var/www/<redacted>/apps/files_versions/lib/Listener/FileEventsListener.php line 359
    OC\Files\Node\LazyRoot->getUserFolder()
 4. /var/www/<redacted>/apps/files_versions/lib/Listener/FileEventsListener.php line 281
    OCA\Files_Versions\Listener\FileEventsListener->getPathForNode()
 5. /var/www/<redacted>/apps/files_versions/lib/Listener/FileEventsListener.php line 120
    OCA\Files_Versions\Listener\FileEventsListener->remove_hook()
 6. /var/www/<redacted>/lib/private/EventDispatcher/ServiceEventListener.php line 86
    OCA\Files_Versions\Listener\FileEventsListener->handle()
 7. /var/www/<redacted>/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 251
    OC\EventDispatcher\ServiceEventListener->__invoke()
 8. /var/www/<redacted>/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 73
    Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
 9. /var/www/<redacted>/lib/private/EventDispatcher/EventDispatcher.php line 94
    Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
10. /var/www/<redacted>/lib/private/EventDispatcher/EventDispatcher.php line 106
    OC\EventDispatcher\EventDispatcher->dispatch()
11. /var/www/<redacted>/lib/private/Files/Node/HookConnector.php line 159
    OC\EventDispatcher\EventDispatcher->dispatchTyped()
12. /var/www/<redacted>/lib/private/legacy/OC_Hook.php line 105
    OC\Files\Node\HookConnector->postDelete()
13. /var/www/<redacted>/lib/private/Files/View.php line 1270
    OC_Hook::emit()
14. /var/www/<redacted>/lib/private/Files/View.php line 1202
    OC\Files\View->runHooks()
15. /var/www/<redacted>/lib/private/Files/View.php line 702
    OC\Files\View->basicOperation()
16. /var/www/<redacted>/apps/dav/lib/Connector/Sabre/File.php line 536
    OC\Files\View->unlink()
17. /var/www/<redacted>/3rdparty/sabre/dav/lib/DAV/Tree.php line 179
    OCA\DAV\Connector\Sabre\File->delete()
18. /var/www/<redacted>/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 281
    Sabre\DAV\Tree->delete()
19. /var/www/<redacted>/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpDelete()
20. /var/www/<redacted>/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit()
21. /var/www/<redacted>/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
22. /var/www/<redacted>/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
23. /var/www/<redacted>/apps/dav/appinfo/v1/publicwebdav.php line 123
    Sabre\DAV\Server->exec()
24. /var/www/<redacted>/public.php line 81
    require_once("/var/www/<redacted>. ... p")

DELETE /public.php/webdav/<redacted>.pdf
from <redacted> at 2023-12-13T23:10:38+00:00
```

I get this error accessing a public share with read&write permissions enabled. I'm accessing that folder via curl and rclone and using the share's id as well as a password to upload and edit files in that folder.

**Comment by solracsf** [comment]
Good.

https://github.com/nextcloud/server/pull/41786 has been shipped with 27.1.5, it can help in this case.
Can you test and report back?

**Comment by dgsiegel** [comment]
> #41786 has been shipped with **v27.1.5** (or v28), released today, it can help in this case.
> 
> Can you test and report back? If this does not help, please provide a JSON backtrace.

Can't find the error anymore in our logs. Thanks!

**Comment by Marcus1Pierce** [comment]
After update to Nextcloud v27.1.5 i still have this error in my logs

`[core] Error: OC\User\NoUserException: Backends provided no user object at <<closure>>

 0. <<closure>>
    OC\Files\Node\Root->getUserFolder("")
 1. /var/www/html/lib/private/Files/Node/LazyFolder.php line 74
    call_user_func_array([["OC\\Files\\No ... "], [""])
 2. /var/www/html/lib/private/Files/Node/LazyRoot.php line 40
    OC\Files\Node\LazyFolder->__call("getUserFolder", [""])
 3. /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php line 73
    OC\Files\Node\LazyRoot->getUserFolder("")
 4. /var/www/html/custom_apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 72
    OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFile(["OC\\User\\User"], ["OC\\Files\\FileInfo"])
 5. /var/www/html/custom_apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 59
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder([52,"Pusat/Accou ... "])
 6. /var/www/html/custom_apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 43
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
 7. /var/www/html/lib/public/BackgroundJob/Job.php line 81
    OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run(null)
 8. /var/www/html/lib/public/BackgroundJob/TimedJob.php line 103
    OCP\BackgroundJob\Job->start(["OC\\BackgroundJob\\JobList"])
 9. /var/www/html/lib/public/BackgroundJob/TimedJob.php line 93
    OCP\BackgroundJob\TimedJob->start(["OC\\BackgroundJob\\JobList"])
10. /var/www/html/cron.php line 152
    OCP\BackgroundJob\TimedJob->execute(["OC\\BackgroundJob\\JobList"], ["OC\\Log"])

at 2023-12-17T00:30:01+00:00`

`[files] Error: OC\User\NoUserException: Backends provided no user object at <<closure>>

 0. <<closure>>
    OC\Files\Node\Root->getUserFolder("")
 1. /var/www/html/lib/private/Files/Node/LazyFolder.php line 74
    call_user_func_array([["OC\\Files\\No ... "], [""])
 2. /var/www/html/lib/private/Files/Node/LazyRoot.php line 40
    OC\Files\Node\LazyFolder->__call("getUserFolder", [""])
 3. /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php line 73
    OC\Files\Node\LazyRoot->getUserFolder("")
 4. /var/www/html/custom_apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 72
    OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFile(["OC\\User\\User"], ["OC\\Files\\FileInfo"])
 5. /var/www/html/custom_apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 59
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder([52,"Pusat/Accou ... "])
 6. /var/www/html/custom_apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 43
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
 7. /var/www/html/lib/public/BackgroundJob/Job.php line 81
    OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run(null)
 8. /var/www/html/lib/public/BackgroundJob/TimedJob.php line 103
    OCP\BackgroundJob\Job->start(["OC\\BackgroundJob\\JobList"])
 9. /var/www/html/lib/public/BackgroundJob/TimedJob.php line 93
    OCP\BackgroundJob\TimedJob->start(["OC\\BackgroundJob\\JobList"])
10. /var/www/html/cron.php line 152
    OCP\BackgroundJob\TimedJob->execute(["OC\\BackgroundJob\\JobList"], ["OC\\Log"])

at 2023-12-17T00:30:01+00:00`

Using Nextcloud 27-fpm Docker with latest pull
All Nextcloud Apps up to date

**Comment by solracsf** [comment]
@Marcus1Pierce your error is a duplicate of https://github.com/nextcloud/groupfolders/issues/2559

Keep it simple:

1. if the line `/groupfolders/lib/Versions/VersionsBackend.php` is present in the backtrace, it is a duplicate of https://github.com/nextcloud/groupfolders/issues/2559
2. if not, and you are using 28 or 27.1.5, report a new issue.

**Comment by Marcus1Pierce** [comment]
> @Marcus1Pierce your error is a duplicate of [nextcloud/groupfolders#2559](https://github.com/nextcloud/groupfolders/issues/2559)

@solracsf Sorry i though it the same think. I didn't read your comment before.

> 1. if the line `/groupfolders/lib/Versions/VersionsBackend.php` is present in the backtrace, it is a duplicate of [Logs filled with cron errors "Backends provided no user object" groupfolders#2559](https://github.com/nextcloud/groupfolders/issues/2559) in this case please also **make sure** you're using Group Folders app **version v16.0.1**. If these 2 conditions are met (line is present and app **is** v16.0.1) report on groupfolders repo.
> 2. if the line is not in the logs, and **you are using 28 or 27.1.5**, report a new issue here. If line is not present and you're using v26 or v27.1.4 or less, upgrade to v27.1.5.

If i check groupfolders v16.0.1 is available in Nextcloud v28. I think i can't upgarde to Nextcloud 28 for now. And for Nextcloud v27.1.5, latest version of groupfolders is 15.3.1.

**Comment by thompol** [comment]
> if the line is not in the logs, and you are using 28 or 27.1.5, report a new issue here. If line is not present and you're using v26 or v27.1.4 or less, upgrade to v27.1.5.

I'm seeing this issue on Nextcloud Hub 8 - version 29.0.2. The error is shown for a user that is deleted.

Backtrace:
```
{"reqId":"VDrCRUWF8Ocic19ty6gl","level":3,"time":"2024-09-15T09:37:00+00:00","remoteAddr":"","user":"--","app":"files","method":"","url":"--","message":"Backends provided no user object for auth.examle.com-663","userAgent":"--","version":"29.0.2.2","exception":{"Exception":"OC\\User\\NoUserException","Message":"Backends provided no user object","Code":0,"Trace":[{"function":"getUserFolder","class":"OC\\Files\\Node\\Root","type":"->","args":["auth.examle.com-663"]},{"file":"/var/www/html/lib/private/Files/Node/LazyFolder.php","line":84,"function":"call_user_func_array","args":[[["OC\\Files\\Node\\Root"],"getUserFolder"],["auth.examle.com-663"]]},{"file":"/var/www/html/lib/private/Files/Node/LazyRoot.php","line":53,"function":"__call","class":"OC\\Files\\Node\\LazyFolder","type":"->","args":["getUserFolder",["auth.examle.com-663"]]},{"file":"/var/www/html/custom_apps/files_fulltextsearch/lib/Service/FilesService.php","line":558,"function":"getUserFolder","class":"OC\\Files\\Node\\LazyRoot","type":"->","args":["auth.examle.com-663"]},{"file":"/var/www/html/custom_apps/files_fulltextsearch/lib/Service/FilesService.php","line":577,"function":"getFileFromId","class":"OCA\\Files_FullTextSearch\\Service\\FilesService","type":"->","args":["auth.examle.com-663",577]},{"file":"/var/www/html/custom_apps/files_fulltextsearch/lib/Service/FilesService.php","line":1288,"function":"getFileFromIndex","class":"OCA\\Files_FullTextSearch\\Service\\FilesService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/files_fulltextsearch/lib/Service/FilesService.php","line":707,"function":"updateDirectoryContentIndex","class":"OCA\\Files_FullTextSearch\\Service\\FilesService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/files_fulltextsearch/lib/Provider/FilesProvider.php","line":314,"function":"updateDocument","class":"OCA\\Files_FullTextSearch\\Service\\FilesService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/fulltextsearch/lib/Service/IndexService.php","line":409,"function":"updateDocument","class":"OCA\\Files_FullTextSearch\\Provider\\FilesProvider","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/fulltextsearch/lib/Cron/Index.php","line":109,"function":"updateDocument","class":"OCA\\FullTextSearch\\Service\\IndexService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/fulltextsearch/lib/Cron/Index.php","line":77,"function":"liveCycle","class":"OCA\\FullTextSearch\\Cron\\Index","type":"->","args":[]},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":80,"function":"run","class":"OCA\\FullTextSearch\\Cron\\Index","type":"->","args":[null]},{"file":"/var/www/html/lib/public/BackgroundJob/TimedJob.php","line":102,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->","args":[["OC\\BackgroundJob\\JobList"]]},{"file":"/var/www/html/lib/public/BackgroundJob/TimedJob.php","line":92,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[["OC\\BackgroundJob\\JobList"]]},{"file":"/var/www/html/cron.php","line":176,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[["OC\\BackgroundJob\\JobList"]]}],"File":"/var/www/html/lib/private/Files/Node/Root.php","Line":370,"message":"Backends provided no user object for auth.examle.com-663","exception":[],"CustomMessage":"Backends provided no user object for auth.examle.com-663"},"id":"66e6aabe0a7d7"}
```

**Comment by thompol** [comment]
Seems to be fixed after upgrading my AIO containers.
