### ISSUE TITLE
Some oldCloud term still in there!

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#2073]
As mentioned in [this twitter post](https://twitter.com/jds81/status/796077674569437184) and seen on the screenshot of 10.0.1 I just took:
![spectacle zb2837](https://cloud.githubusercontent.com/assets/551757/20175768/beb296e2-a744-11e6-9bbd-cd71dc783496.png)

We still accidentally mention oldCloud there! To be removed. Of course it isn't wrong, we're compatible with those... But still, meh.

**Comment by ChristophWurst** [comment]
This is only wrong in l10n files, the source file was fixed already it seems https://github.com/nextcloud/server/blob/39573e602d5e38e4b71b3d197d08798dd9558659/core/js/sharedialogview.js#L403

**Comment by nickvergessen** [comment]
Stable10 is still wrong: https://github.com/nextcloud/server/blob/stable10/core/js/sharedialogview.js#L393

**Comment by jospoortvliet** [comment]
would that be OK? https://github.com/nextcloud/server/pull/2078

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/server/pull/2078
