### ISSUE TITLE
Video playback cause a high load average (51.75), website gets stuck

### ISSUE THREAD

**Issue by pupboss** [nextcloud/server#22276]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Play a video (2-3 GB) on website, or
2. play a video on iOS app
3. Website will down and stuck, CPU&Memory use is quite low but load average is high

### Expected behaviour
Tell us what should happen

Should start to play the video, or show "error loading xxx.mp4" if encoding not support

### Actual behaviour
Tell us what happens instead

Website stuck, very high load average. 

If the video size less than 50MB, all work fine. 

For videos with size 700MB and 52mins length, 1601 kbps bitrate, firstly the player works as normal, but "Load average" increases until 40+, then website stuck, but in the period of Load average from 0.3 to 40+, the website operates as normal. 

![WX20200818-170736@2x](https://user-images.githubusercontent.com/8395112/90496228-274e7600-e178-11ea-96e4-206614970d22.png)

### Server configuration

**Operating system:**
Debian 10
**Web server:**
Nginx (Also tested on Apache2, same issue)

The only difference is, in Nginx there are many php-fpm processes, in Apache2 it is apache2.

**Database:**
Mysql 8
**PHP version:**
7.4-fpm
**Nextcloud version:** (see Nextcloud admin page)
19.0.1, all configurations are following official document, no warnings in admin page.
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
Official zip
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - bruteforcesettings: 1.6.0
  - checksum: 0.4.5
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - duplicatefinder: 0.0.2
  - extract: 1.2.4
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - maps: 0.1.6
  - metadata: 0.12.0
  - music: 0.16.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - camerarawpreviews
  - encryption
  - ocdownloader
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.pupboss.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.1.1",
        "overwrite.cli.url": "https:\/\/nas.pupboss.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "preview_max_x": 512,
        "preview_max_y": 512,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "465",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Safari & Chrome
**Operating system:**
OSX
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by pupboss** [comment]
Issue was addressed, it is because IO performance bottleneck. Solutions: use a separate disk to host data repository, or upgrade to a high performance SSD.

**Comment by yevon** [comment]
This is still a problem, nextcloud is unable to cancel downloads properly, big delays for download start, and continues reading files after downloading them.

**Comment by SebastienCaunes** [comment]
Why Nextcloud always close these issues ? They are not solved. I got same problem with SSD

**Comment by yevon** [comment]
That's incredible, nextcloud is super bugged for docker as I already mentioned and showed in other issues. In the helm chart there is s specific data volume that causes tons of issues that just breaks your system when you use a separated disk for your data. Please fix this, this is taking years...
