### ISSUE TITLE
NC 19 Dark Theme Issues words not seeable 

### ISSUE THREAD

**Issue by axheli** [nextcloud/server#23010]
![image](https://user-images.githubusercontent.com/59488153/93932958-8dce3300-fce6-11ea-9a9b-64a8fc754e59.png)
![image](https://user-images.githubusercontent.com/59488153/93933009-a0e10300-fce6-11ea-914f-a0e8e722f221.png)

![image](https://user-images.githubusercontent.com/59488153/93933298-0e8d2f00-fce7-11ea-9bea-12bd7d0c4dac.png)

This is also happening on demo.nextcloud.com

I've already tired different browsers, different computers, delete cache and browsing history. No luck.

**Comment by axheli** [comment]
Fixed on Nextcloud 20

**Comment by eidermar** [comment]
This is not fixed. We are still seeing this problem with v20.0.4. For example with external sharing links:

<img width="283" alt="Screen Shot 2021-02-03 at 18 48 14" src="https://user-images.githubusercontent.com/16689717/106787791-6c943080-6650-11eb-85eb-f8d4ca608673.png">

I don't understand why this dark mode is forced anyways. Could we not have an option to decide if we want our sharing links to make use of it or not?
