### ISSUE TITLE
NC20: New dashboard show nearly white screen after update from 19.0.3 to 20.0.0

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/server#23163]
### Steps to reproduce
1. Updated my v19.0.3 instance to v20.0.0

### Expected behaviour
Dashboard should be loading fine like at the conference instance

### Actual behaviour
New version is loading pretty well. The dashboard is nearly white. The menu bar is white but the item like "Files" is clickable. Account icon (avatar) at top right is visible and menu works.

<img width="1169" alt="Bildschirmfoto 2020-10-03 um 21 43 45" src="https://user-images.githubusercontent.com/2069590/95000485-8ac62300-05c1-11eb-864d-4af430724530.png">

Tried to disable/enable the dashboard. 
Tried Safari as well.
Tried to clear browser cache.

### Server configuration

**Operating system:**
Ubuntu 18.04

**Web server:**
Apache

**Database:**
PostgreSQL 10.14

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
20.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 19.0.3

**Where did you install Nextcloud from:**
Official updater

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
ff v81

**Operating system:**
Mac OS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No entries
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No entries
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
No entries
</details>

**Comment by thangisme** [comment]
![](https://iili.io/2W1AQI.png)
I just installed Nextcloud by web installer. There's no login form. And some script can't be loaded

**Comment by rakekniven** [comment]
> I just installed Nextcloud by web installer. There's no login form. And some script can't be loaded
That is not related to the issue.

**Comment by moblesmarti** [comment]
After the update v19.0.3 instance to v20.0.0 only users who are administrators can see the dashboard, other users without administrator permissions have a blank page.

**Comment by rakekniven** [comment]
<img width="1141" alt="Bildschirmfoto 2020-10-04 um 12 15 53" src="https://user-images.githubusercontent.com/2069590/95012777-91917c00-063b-11eb-8548-a62f27b4e66a.png">

**Comment by rakekniven** [comment]
> After the update v19.0.3 instance to v20.0.0 only users who are administrators can see the dashboard, other users without administrator permissions have a blank page.
> If you deactivate dashboard everything works correctly.

Not sure if this hits my issue. Tried to open dashboard as admin and regular user. Same behaviour for both users.
Disabling/enabling does not help.

**Comment by simon3p** [comment]
Stuck with this issue to. 

Same configuration except for the DB, I'm using MariaDB.

**Comment by dinkonin** [comment]
Same issue with: Web server:Nginx, Database:PostgreSQL 12.4, PHP version:7.4
I ran `occ maintenance:repair`, with no effect.
Nothing in nextcloud.log but I'm getting a lot of these errors in the browser console:

> vue.runtime.esm.js:1888 TypeError: Cannot read property 'match' of undefined
    at a.backgroundStyle (App.vue:152)
    at pn.get (vue.runtime.esm.js:4479)
    at pn.evaluate (vue.runtime.esm.js:4584)
    at a.backgroundStyle (vue.runtime.esm.js:4836)
    at a.<anonymous> (App.vue?6cbf:1)
    at a.e._render (vue.runtime.esm.js:3548)
    at a.r (vue.runtime.esm.js:4066)
    at pn.get (vue.runtime.esm.js:4479)
    at new pn (vue.runtime.esm.js:4468)
    at e (vue.runtime.esm.js:4073)

**Comment by rakekniven** [comment]
Hello @juliushaertl , the conference was great and your presentation on widget programming was great too. I wanted to try the dashboard right away and opened this issue. Do you have an idea?

**Comment by juliushaertl** [comment]
![image](https://user-images.githubusercontent.com/3404133/95050041-33bc6d00-06eb-11eb-8b62-64f25ecc70af.png)

I can reproduce this with the accessibility app being disabled. Is that the case for everyone having this issue? I'll see to add a check so we can make this work even without.

**Comment by rakekniven** [comment]
Just enabled accessibility app and the dashboard is there.

Well done 👏

**Comment by joekerna** [comment]
I have the accessibility app enabed but the issue is stil there. My dashboard is blank except my avatar

**Comment by joekerna** [comment]
@simon3p thanks... enabling and disabling again did the trick for me as well.

**Comment by lars-becker** [comment]
On my system it solved the problem, too.

**Comment by ryester27** [comment]
Is the accessibility app a dependency for the dashboard, or is this a bug? Might want to mention it somewhere if it's the former.

**Comment by rakekniven** [comment]
@ryester27 No, it is not a dependency and has already been fixed. See comments above. Should be delivered with release v20.0.1

**Comment by ryester27** [comment]
> @ryester27 No, it is not a dependency and has already been fixed. See comments above. Should be delivered with release v20.0.1

Figures I missed the PR link. Sorry about that

**Comment by ryester27** [comment]
With 20.0.1, I am still unable to see the Dashboard while the Accessibility app is disabled

![chrome_SP4JAW9EJn](https://user-images.githubusercontent.com/17807258/97204800-efbe0480-178c-11eb-88f5-aa343c431f11.png)

**Comment by rakekniven** [comment]
Anybody else having this issue with NC v.20.0.1?

For the records:
https://github.com/nextcloud/server/pull/23192

**Comment by dadall** [comment]
@rakekniven I do. Just did the upgrade from 19 to 20 and almost got a blank page.

I disable/enable the app without success. Keeping it disabled solved the issue :(

**Comment by billgross** [comment]
I do.  This is new to me since the upgrade to version 20.0.1snap1 occurred two days ago.
I have admin privileges, but I still get the white-screen-of-non-usefulness :'(
Anything you can do to heal the problem will be greatly appreciated!

**Comment by billgross** [comment]
I was able to regain visibility by enabling the accessibility app.
Then I was able to see the dashboard.  Evidently this is a new "feature".
I disabled the dashboard -- could still see things again -- and then disabled the accessibility app.  Visibility remained.
Evidently the inability to see things on login is related to the dashboard app.

**Comment by MaitreCake** [comment]
Same issue as @billgross

**Comment by Virusmater** [comment]
The same issue with 20.0.2
```No OC found index.js:46:12
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 globals.js:60:15
Notifications permissions denied App.vue:302
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
OCA.Files.Sidebar initialized Sidebar.js:37:10
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:60:15
Uncaught TypeError: OCA.Files.DetailTabView is undefined
    <anonymous> versionstabview.js:18
    Webpack 3
        n
        <anonymous>
        <anonymous>
versionstabview.js:18:7
    <anonymous> versionstabview.js:18
    Webpack 3
        n
        <anonymous>
        <anonymous>
OCA.Sharing.ShareSearch initialized ShareSearch.js:33:10
OCA.Sharing.ExternalLinkActions initialized ExternalLinkActions.js:33:10
OCA.Viewer initialized Viewer.js:46:10
No OCA.Files app found, viewer is now in standalone mode Viewer.vue:298
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 2 globals.js:60:15
TypeError: window.OCA.Accessibility is undefined
    h getBackgroundUrl.js:27
    backgroundImage App.vue:149
    VueJS 3
    backgroundStyle App.vue:156
    VueJS 3
    M App.vue:1
    VueJS 6
    <anonymous> main.js:21
    Webpack 3
vue.runtime.esm.js:1888:12
    VueJS 9
    <anonymous> main.js:21
    Webpack 3
Failed to register panel in the frontend as no backend data was provided for weather App.vue:211
    callbacksStatus App.vue:211
    VueJS 10
    registerStatus App.vue:249
    VueJS 5
    registerStatus App.vue:248
    registerStatus main.js:25
    <anonymous> weather-status.js:20
    (Async: EventListener.handleEvent)
    <anonymous> weather-status.js:15
    Webpack 3
Failed to register panel in the frontend as no backend data was provided for calendar App.vue:268
    rerenderPanels App.vue:268
    callbacks App.vue:199
    VueJS 10
    register App.vue:240
    register main.js:24
    <anonymous> dashboard.js:42
    (Async: EventListener.handleEvent)
    <anonymous> dashboard.js:41
    Webpack 3
Failed to register panel in the frontend as no backend data was provided for calendar App.vue:268
    rerenderPanels App.vue:268
    callbacks App.vue:199
    VueJS 4
Failed to register panel in the frontend as no backend data was provided for calendar App.vue:268
    rerenderPanels App.vue:268
    callbacks App.vue:199
    VueJS 10
    register App.vue:240
    register main.js:24
    <anonymous> dashboard.js:41
    (Async: EventListener.handleEvent)
    <anonymous> dashboard.js:40
    Webpack 3
Failed to register panel in the frontend as no backend data was provided for weather App.vue:211
    callbacksStatus App.vue:211
    VueJS 10
    registerStatus App.vue:249
    VueJS 5
    registerStatus App.vue:248
    registerStatus main.js:25
    <anonymous> main-user-status-menu.js:54
    (Async: EventListener.handleEvent)
    <anonymous> main-user-status-menu.js:49
    Webpack 3
Failed to register panel in the frontend as no backend data was provided for status App.vue:211
    callbacksStatus App.vue:211
    VueJS 10
    registerStatus App.vue:249
    VueJS 5
    registerStatus App.vue:248
    registerStatus main.js:25
    <anonymous> main-user-status-menu.js:54
    (Async: EventListener.handleEvent)
    <anonymous> main-user-status-menu.js:49
    Webpack 3
session heartbeat polling started session-heartbeat.js:97:9
Files_PDFViewer initialized for public page 
Object { isPublicPage: null, canDownload: true, isSecureViewerAvailable: false }
public.js:30:9
Please do NOT wait for the DOMContentLoaded before registering your viewer handler Viewer.vue:217
    handlers Viewer.vue:217
    VueJS 10
    value Viewer.js:78
    <anonymous> main.js:26
    (Async: EventListener.handleEvent)
    <anonymous> main.js:25
    Webpack 3
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, app: "unified-search", uid: "kompot" }
ConsoleLogger.js:42:18
```

**Comment by maxdrash** [comment]
Upgrade from 19.0.5 to 20.0.2 on stable channel here.
Same issue: blank page on dashboard app.
I had to activate Accessibility app and the dashboard app works.

You have to re-open this issue ticket and make changes for a mention of that fact:
- Accessibility app is mandatory or a dependancy.
- Force Accessibility to be activated.
or
- Request a code modification to make a dashboard a standalone app.

**Comment by rafitamolin** [comment]
Same issue here. Disabling and re-enabling accesibility doesn't work. No workaround... pityful.

**Comment by anthraxn8b** [comment]
Fixed it by activating accessibility app as follows:

    docker exec --user www-data cloud php occ app:enable accessibility

**Comment by TonyGravagno** [comment]
New installation of NC 20.0.3, dashboard works.
Disable Accessibility = white screen.
Enable fixes it.
Update to NC 20.0.4 available today.
Same test, same results.

This issue is not fixed. Please re-open.

**Comment by ChristophWurst** [comment]
@TonyGravagno mind inspecting the browser console for the js error(s)?

**Comment by dR3b** [comment]
Same error after update NC **20.0.5**! With version 20.0.4 everything still worked.

```bash
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 3 globals.js:60:15
Uncaught TypeError: OCA.Files.DetailTabView is undefined
    <anonymous> https://cloud.opensync.info/index.php/js/activity/activity-sidebar.js?v=727cd9cf-13:603
    <anonymous> https://cloud.opensync.info/index.php/js/activity/activity-sidebar.js?v=727cd9cf-13:803
activity-sidebar.js:603:24
    <anonym> https://cloud.opensync.info/index.php/js/activity/activity-sidebar.js?v=727cd9cf-13:603
    <anonym> https://cloud.opensync.info/index.php/js/activity/activity-sidebar.js?v=727cd9cf-13:803
Uncaught TypeError: n.Files.DetailTabView is undefined
    <anonymous> commentstabview.js:21
    <anonymous> commentstabview.js:756
    Webpack 3
commentstabview.js:21:23
Uncaught TypeError: OCA.Files.DetailTabView is undefined
    <anonymous> versionstabview.js:18
    Webpack 3
versionstabview.js:18:7
OCA.Sharing.ShareSearch initialized ShareSearch.js:33:10
```
