### ISSUE TITLE
OC.Notification.send* JS APIs appear to be broken in settings pages

### ISSUE THREAD

**Issue by strugee** [nextcloud/server#23852]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

1. Open Nextcloud settings (tested on `/settings/admin/overview` and `/settings/admin/logging`)
2. Open the developer console
3. Run `OC.Notification.sendTemporary('foobar');`

### Expected behaviour

The toast notification should be displayed in the upper-right.

### Actual behaviour

The main page view shifts down for a few seconds, then back. Note that I CANNOT reproduce this bug in the Files view - only Settings.

### Server configuration

**Operating system:** Debian 10

**Web server:** Apache 2

**Database:** SQLite

**PHP version:** 7.3.19

**Nextcloud version:** Nextcloud 21 alpha checked out from git at 65375320fb94fe3b7d0aaaecc9e66b7458ed6c1a

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 20(?) (I can't really remember since I was just setting up a dev environment and the whole thing was a bit of a mess)

**Where did you install Nextcloud from:** git

**Signing status:**
<details>
<summary>Signing status</summary>

```
Integrity checker has been disabled. Integrity cannot be verified.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - admin_audit: 1.11.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.0
  - facerecognition: 0.7.0
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.9.0
  - oauth2: 1.9.0
  - photos: 1.3.0
  - provisioning_api: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - systemtags: 1.11.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.0
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - bruteforcesettings
  - encryption
  - files_external
  - files_sharing
  - testing
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "21.0.0.1",
        "overwrite.cli.url": "http:\/\/nextcloud.localhost",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "app_install_overwrite": [
            "facerecognition"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration

**Browser:** confirmed in Firefox Nightly 84.0a1 built 2020-11-02 and Chromium 83.0.4103.116

**Operating system:** Debian 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Mon Nov 02 16:00:03.127566 2020] [mpm_prefork:notice] [pid 15705] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Mon Nov 02 16:00:03.131128 2020] [core:notice] [pid 15705] AH00094: Command line: '/usr/sbin/apache2'
[Mon Nov 02 16:13:39.276951 2020] [core:notice] [pid 15705] AH00052: child pid 15966 exit signal Segmentation fault (11)
[Mon Nov 02 16:13:39.556198 2020] [mpm_prefork:notice] [pid 15705] AH00169: caught SIGTERM, shutting down
[Mon Nov 02 16:13:39.701361 2020] [mpm_prefork:notice] [pid 21170] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Mon Nov 02 16:13:39.701424 2020] [core:notice] [pid 21170] AH00094: Command line: '/usr/sbin/apache2'
[Mon Nov 02 17:04:22.118961 2020] [access_compat:error] [pid 24127] [client 127.0.0.1:38226] AH01797: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Nov 02 17:04:25.923803 2020] [access_compat:error] [pid 21431] [client 127.0.0.1:38260] AH01797: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Nov 02 17:06:00.290979 2020] [access_compat:error] [pid 29278] [client 127.0.0.1:38440] AH01797: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Nov 02 17:08:28.299353 2020] [access_compat:error] [pid 21179] [client 127.0.0.1:38496] AH01797: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Nov 02 17:10:24.780542 2020] [access_compat:error] [pid 21179] [client 127.0.0.1:38560] AH01797: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Nov 02 17:27:10.840973 2020] [access_compat:error] [pid 30409] [client 127.0.0.1:46158] AH01797: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Nov 02 17:30:20.561163 2020] [access_compat:error] [pid 30405] [client 127.0.0.1:47740] AH01797: client denied by server configuration: /var/www/nextcloud/data/.ocdata
```
</details>

#### Nextcloud log (data/nextcloud.log)

(Omitted since there didn't seem to be anything interesting and this is a browser bug and my log is filled with deprecation spam - if anyone turns out to want it I can post it.)

#### Browser log
<details>
<summary>Browser log</summary>

The two lines I ran manually at the console are marked with `>` at the beginning.

```
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 globals.js:60:15
GEThttp://nextcloud.localhost/index.php/settings/admin/overview
[HTTP/1.1 200 OK 55ms]

Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
GEThttp://nextcloud.localhost/index.php/css/core/238c-2845-server.css?v=b92d206521717ac032f8aa58d3c7ff2f-a29e7648-0
[HTTP/1.1 200 OK 28ms]

GEThttp://nextcloud.localhost/index.php/css/core/238c-2845-css-variables.css?v=b92d206521717ac032f8aa58d3c7ff2f-a29e7648-0
[HTTP/1.1 200 OK 85ms]

GEThttp://nextcloud.localhost/index.php/css/user_status/7d23-2845-user-status-menu.css?v=b92d206521717ac032f8aa58d3c7ff2f-a29e7648-0
[HTTP/1.1 200 OK 48ms]

GEThttp://nextcloud.localhost/index.php/css/settings/1980-2845-settings.css?v=b92d206521717ac032f8aa58d3c7ff2f-a29e7648-0
[HTTP/1.1 200 OK 99ms]

GEThttp://nextcloud.localhost/index.php/css/icons/icons-vars.css?v=1604355747
[HTTP/1.1 200 OK 66ms]

GEThttp://nextcloud.localhost/index.php/apps/theming/styles?v=0
[HTTP/1.1 200 OK 74ms]

GEThttp://nextcloud.localhost/core/js/dist/main.js?v=a29e7648-0
[HTTP/1.1 200 OK 57ms]

GEThttp://nextcloud.localhost/core/js/dist/files_client.js?v=a29e7648-0
[HTTP/1.1 200 OK 6ms]

GEThttp://nextcloud.localhost/core/js/dist/files_fileinfo.js?v=a29e7648-0
[HTTP/1.1 200 OK 2ms]

GEThttp://nextcloud.localhost/index.php/js/core/merged-template-prepend.js?v=a29e7648-0
[HTTP/1.1 200 OK 61ms]

GEThttp://nextcloud.localhost/core/js/backgroundjobs.js?v=a29e7648-0
[HTTP/1.1 200 OK 12ms]

GEThttp://nextcloud.localhost/apps/accessibility/js/accessibilityoca.js?v=a29e7648-0
[HTTP/1.1 200 OK 13ms]

GEThttp://nextcloud.localhost/apps/updatenotification/js/updatenotification.js?v=a29e7648-0
[HTTP/1.1 200 OK 65ms]

GEThttp://nextcloud.localhost/apps/theming/js/theming.js?v=a29e7648-0
[HTTP/1.1 200 OK 1ms]

GEThttp://nextcloud.localhost/apps/user_status/js/user-status-menu.js?v=a29e7648-0
[HTTP/1.1 200 OK 27ms]

GEThttp://nextcloud.localhost/apps/settings/js/settings.js?v=a29e7648-0
[HTTP/1.1 200 OK 1ms]

GEThttp://nextcloud.localhost/apps/settings/js/admin.js?v=a29e7648-0
[HTTP/1.1 200 OK 1ms]

GEThttp://nextcloud.localhost/apps/settings/js/log.js?v=a29e7648-0
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/core/js/setupchecks.js?v=a29e7648-0
[HTTP/1.1 200 OK 1ms]

GEThttp://nextcloud.localhost/apps/files/js/jquery.fileupload.js?v=a29e7648-0
[HTTP/1.1 200 OK 3ms]

GEThttp://nextcloud.localhost/core/js/dist/unified-search.js?v=a29e7648-0
[HTTP/1.1 200 OK 21ms]

No OC found index.js:46:12
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
GEThttp://nextcloud.localhost/apps/dashboard/img/dashboard.svg?v=a29e7648
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/apps/files/img/app.svg?v=a29e7648
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/apps/photos/img/app.svg?v=a29e7648
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/apps/user_status/img/app.svg?v=a29e7648
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/apps/settings/img/admin.svg?v=a29e7648
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/apps/settings/img/apps.svg?v=a29e7648
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/apps/settings/img/users.svg?v=a29e7648
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/apps/settings/img/help.svg?v=a29e7648
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/core/img/actions/logout.svg?v=a29e7648
[HTTP/1.1 200 OK 1ms]

GEThttp://nextcloud.localhost/core/img/actions/user.svg
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/apps/settings/img/password.svg
[HTTP/1.1 200 OK 1ms]

GEThttp://nextcloud.localhost/apps/facerecognition/img/app-dark.svg
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/apps/accessibility/img/app-dark.svg
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/core/img/actions/share.svg
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/apps/workflowengine/img/app-dark.svg
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/apps/settings/img/admin.svg
[HTTP/1.1 200 OK 1ms]

GEThttp://nextcloud.localhost/core/img/actions/settings-dark.svg
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/core/img/actions/password.svg
[HTTP/1.1 200 OK 1ms]

jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
GEThttp://nextcloud.localhost/apps/theming/img/app-dark.svg
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/core/img/places/contacts.svg
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/apps/logreader/img/app-dark.svg
[HTTP/1.1 200 OK 0ms]

GEThttp://nextcloud.localhost/index.php/avatar/alex/32?v=0
[HTTP/1.1 200 OK 26ms]

GEThttp://nextcloud.localhost/index.php/svg/core/logo/logo?color=fff&v=1
[HTTP/1.1 200 OK 38ms]

$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
XHRGEThttp://nextcloud.localhost/ocs/v2.php/cloud//groups
[HTTP/1.1 200 OK 47ms]

XHRPUThttp://nextcloud.localhost/index.php/apps/user_status/heartbeat
[HTTP/1.1 204 No Content 42ms]

XHRGEThttp://nextcloud.localhost/ocs/v2.php/search/providers?from=%2Fsettings%2Fadmin%2Foverview
[HTTP/1.1 200 OK 24ms]

jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
session heartbeat polling started session-heartbeat.js:97:9
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 56 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, app: "unified-search", uid: "alex" }
ConsoleLogger.js:42:18
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
GEThttp://nextcloud.localhost/index.php/apps/theming/icon/settings?v=0
[HTTP/1.1 200 OK 46ms]

GEThttp://nextcloud.localhost/index.php/apps/theming/favicon/settings?v=0
[HTTP/1.1 200 OK 20ms]

XHRGEThttp://nextcloud.localhost/cron.php
[HTTP/1.1 200 OK 98ms]

XHRPROPFINDhttp://nextcloud.localhost/remote.php/webdav
[HTTP/1.1 207 Multi-Status 32ms]

XHRPROPFINDhttp://nextcloud.localhost/.well-known/caldav
[HTTP/1.1 301 Moved Permanently 0ms]

XHRPROPFINDhttp://nextcloud.localhost/.well-known/carddav
[HTTP/1.1 301 Moved Permanently 0ms]

XHRGEThttp://nextcloud.localhost/ocm-provider/
[HTTP/1.1 200 OK 4ms]

XHRGEThttp://nextcloud.localhost/ocs-provider/
[HTTP/1.1 200 OK 23ms]

XHRGEThttp://nextcloud.localhost/index.php/settings/ajax/checksetup
[HTTP/1.1 200 OK 163ms]

XHRGEThttp://nextcloud.localhost/index.php/heartbeat
[HTTP/1.1 200 OK 16ms]

XHRGEThttp://nextcloud.localhost/core/fonts/NotoSans-Regular-latin.woff2
[HTTP/1.1 200 OK 9ms]

XHRGEThttp://nextcloud.localhost/data/.ocdata?t=1604356535661
[HTTP/1.1 403 Forbidden 5ms]

XHRGEThttp://nextcloud.localhost/ocs/v2.php/apps/user_status/api/v1/user_status
[HTTP/1.1 200 OK 23ms]

jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 8 globals.js:60:15
XHRPROPFINDhttp://nextcloud.localhost/remote.php/dav/
[HTTP/1.1 207 Multi-Status 26ms]

jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
XHRPROPFINDhttp://nextcloud.localhost/remote.php/dav/
[HTTP/1.1 207 Multi-Status 26ms]

jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 92 globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 8 globals.js:60:15
Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:48:9
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:667:10
Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:1044:9
Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:1051:9
Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:1055:9
Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:1307:10
Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:175:9
Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:182:9
Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:186:9
Expected ‘none’, URL, or filter function but found ‘Alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:438:10
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:132:11
Unknown property ‘-moz-border-radius’.  Declaration dropped. overview:136:22
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:146:11
Unknown property ‘-moz-border-radius’.  Declaration dropped. overview:150:22
Unknown property ‘zoom’.  Declaration dropped. overview:9:10
Expected declaration but found ‘*’.  Skipped to next declaration. overview:10:5
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:55:13
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:71:13
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:137:13
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:204:13
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:309:13
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:321:13
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:585:13
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. overview:15:10
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. overview:1:34858
Error in parsing value for ‘left’.  Declaration dropped. overview:1:490
Error in parsing value for ‘left’.  Declaration dropped. overview:1:811
Error in parsing value for ‘top’.  Declaration dropped. overview:1:1117
Error in parsing value for ‘top’.  Declaration dropped. overview:1:1434
Error in parsing value for ‘height’.  Declaration dropped. overview:1:34601
Unknown property ‘backdrop-filter’.  Declaration dropped. overview:1:638
Error in parsing value for ‘left’.  Declaration dropped. overview:1:490
Error in parsing value for ‘left’.  Declaration dropped. overview:1:811
Error in parsing value for ‘top’.  Declaration dropped. overview:1:1117
Error in parsing value for ‘top’.  Declaration dropped. overview:1:1434
Unrecognized at-rule or error parsing at-rule ‘@-ms-viewport’. 238c-2845-server.css:1:23313
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. 238c-2845-server.css:1:54320
Unknown pseudo-class or pseudo-element ‘-o-prefocus’.  Ruleset ignored due to bad selector. 1980-2845-settings.css:1:18742
Unknown pseudo-class or pseudo-element ‘-o-prefocus’.  Ruleset ignored due to bad selector. 1980-2845-settings.css:1:20915
> console.log('begin test')
begin test debugger eval code:1:9
undefined
> OC.Notification.showTemporary('test');
Object { 0: div.toastify.on.dialogs.toastify-right.toastify-top, context: div.toastify.on.dialogs.toastify-right.toastify-top
, length: 1, selector: "" }

jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 144 globals.js:60:15
```
</details>

**Comment by skjnldsv** [comment]
It's `OC.Notification.showTemporary('foobar')`

And it works for me :thinking: 
I guess this was fixed in between?
Missing css after the dialog library migration I guess :thinking:

**Comment by skjnldsv** [comment]
![Capture d’écran_2020-11-08_11-52-46](https://user-images.githubusercontent.com/14975046/98463060-eedb9880-21b8-11eb-817c-f67db0f8b7c5.png)

**Comment by strugee** [comment]
@skjnldsv heh, sorry - I didn't copy and paste the code snipppet when writing this issue, I _did_ run the correct one in the console.

In any case, I can still reproduce this on `/settings/admin/overview`, commit c8822508de0aec9e1e6dbdfb793d2a1db8cb92c4. Maybe it's an app interfering? What do you have enabled in your dev setup?

**Comment by skjnldsv** [comment]
> Maybe it's an app interfering? What do you have enabled in your dev setup?

``` js
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.1
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.4.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.0
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.0
  - files_pdfviewer: 2.1.0
  - files_sharing: 1.13.0
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - forms: 2.0.4
  - guests: 1.5.0
  - integration_github: 0.0.10
  - integration_twitter: 0.0.5
  - lookup_server_connector: 1.9.0
  - mail: 1.5.0
  - oauth2: 1.9.0
  - photos: 1.3.0
  - provisioning_api: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.0.0-dev.6
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.0
  - viewer: 1.5.0
  - vueexample: 4.0.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0

```

**Comment by skjnldsv** [comment]
I can reproduce on  `/settings/admin/overview`

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
