### ISSUE TITLE
AmazonS3: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by dargmuesli** [nextcloud/server#24034]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Synchronize an external s3 directory.

### Expected behaviour
All files which exists on the remote should be downloaded.

### Actual behaviour
Multiple files are downloaded and seemingly randomly deleted again. It feels like Nextcloud only receives parts of the complete file list to synchronize.
The server log says: `Trying to access array offset on value of type null at /var/www/html/apps/files_external/lib/Lib/Storage/AmazonS3.php#168`, the client displays: `xxxxx.mp3: File was deleted from server`

### Server configuration

**Container used:** nextcloud:20.0.1-fpm-alpine

**Web server:** nginx:1.19.4-alpine

**Database:** PostgreSQL 13

**Nextcloud version:** 20.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** upgraded

**Where did you install Nextcloud from:** DockerHub

**Signing status:**
<details>
<summary>Signing status</summary>
I applied a fix from another issue to the mentioned file.

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- lib/private/legacy/OC_Helper.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/private/legacy/OC_Helper.php] => Array
                        (
                            [expected] => 23e9b91b61e6a7f3e5004d8bfdee0a50553cb6651313fe2531564c2a6682a5b092689afc72cacdd934f37a149c8ffbac8e93b20f896a33196bd61fb1f66dc8ab
                            [current] => 14f4243ed01b0f89789e405cf2197ee4e657061dee3326849f653d3ff1ef39a94edff5fce38d53155c6f91d177a0a134aa49cf233f074af9300d60d046a36ca1
                        )

                )

        )

)

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.6.0
  - activity: 2.13.2
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.1
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - encryption: 2.8.1
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - quota_warning: 1.9.1
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - systemtags: 1.10.0
  - tasks: 0.13.5
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - files_external_dropbox
  - survey_client
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            ***REMOVED SENSITIVE VALUE***
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "20.0.1.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false,
        "theme": "",
        "app_install_overwrite": [
            "files_external_dropbox",
            "contacts"
        ],
        "encryption.legacy_format_support": true,
        "encryption.key_storage_migrated": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** s3

**Are you using encryption:** yes, but not for the external storage

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** nextcloud (client)

**Operating system:** Arch Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
...
10.0.X.X - xxxxx 10/Nov/2020:16:59:54 +0000 "GET /remote.php" 200
10.0.X.X - xxxxx 10/Nov/2020:16:59:55 +0000 "GET /remote.php" 200
10.0.X.X - xxxxx 10/Nov/2020:17:00:09 +0000 "GET /ocs/v1.php" 200
10.0.X.X - xxxxx 10/Nov/2020:17:00:10 +0000 "GET /remote.php" 200
10.0.X.X - xxxxx 10/Nov/2020:17:00:15 +0000 "GET /remote.php" 404
10.0.X.X - xxxxx 10/Nov/2020:17:00:15 +0000 "GET /remote.php" 200
10.0.X.X - xxxxx 10/Nov/2020:17:00:34 +0000 "GET /remote.php" 404
10.0.X.X - xxxxx 10/Nov/2020:17:00:34 +0000 "GET /remote.php" 200
...
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{
   "reqId":"AqarUT6V5XhnQMncYzTE",
   "level":3,
   "time":"2020-11-10T16:43:43+00:00",
   "remoteAddr":"X.X.X.X",
   "user":"xxxxx",
   "app":"PHP",
   "method":"GET",
   "url":"/remote.php/dav/files/xxxxx/xxxxx/player/xxxxx.mp3",
   "message":{
      "Exception":"Error",
      "Message":"Trying to access array offset on value of type null at /var/www/html/apps/files_external/lib/Lib/Storage/AmazonS3.php#168",
      "Code":0,
      "Trace":[
         {
            "file":"/var/www/html/apps/files_external/lib/Lib/Storage/AmazonS3.php",
            "line":168,
            "function":"onError",
            "class":"OC\\Log\\ErrorHandler",
            "type":"::",
            "args":[
               8,
               "Trying to access array offset on value of type null",
               "/var/www/html/apps/files_external/lib/Lib/Storage/AmazonS3.php",
               168,
               {
                  "path":"player",
                  "result":{
                     "__class__":"Aws\\Result"
                  }
               }
            ]
         },
         {
            "file":"/var/www/html/apps/files_external/lib/Lib/Storage/AmazonS3.php",
            "line":468,
            "function":"doesDirectoryExist",
            "class":"OCA\\Files_External\\Lib\\Storage\\AmazonS3",
            "type":"->",
            "args":[
               "player"
            ]
         },
         {
            "file":"/var/www/html/apps/files_external/lib/Lib/Storage/AmazonS3.php",
            "line":255,
            "function":"filetype",
            "class":"OCA\\Files_External\\Lib\\Storage\\AmazonS3",
            "type":"->",
            "args":[
               "player"
            ]
         },
         {
            "file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php",
            "line":226,
            "function":"file_exists",
            "class":"OCA\\Files_External\\Lib\\Storage\\AmazonS3",
            "type":"->",
            "args":[
               "player"
            ]
         },
         {
            "file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php",
            "line":226,
            "function":"file_exists",
            "class":"OC\\Files\\Storage\\Wrapper\\Wrapper",
            "type":"->",
            "args":[
               "player"
            ]
         },
         {
            "file":"/var/www/html/lib/private/Files/Storage/Wrapper/Availability.php",
            "line":245,
            "function":"file_exists",
            "class":"OC\\Files\\Storage\\Wrapper\\Wrapper",
            "type":"->",
            "args":[
               "player"
            ]
         },
         {
            "file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php",
            "line":226,
            "function":"file_exists",
            "class":"OC\\Files\\Storage\\Wrapper\\Availability",
            "type":"->",
            "args":[
               "player"
            ]
         },
         {
            "file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php",
            "line":226,
            "function":"file_exists",
            "class":"OC\\Files\\Storage\\Wrapper\\Wrapper",
            "type":"->",
            "args":[
               "player"
            ]
         },
         {
            "file":"/var/www/html/lib/private/Files/View.php",
            "line":1334,
            "function":"file_exists",
            "class":"OC\\Files\\Storage\\Wrapper\\Wrapper",
            "type":"->",
            "args":[
               "player"
            ]
         },
         {
            "file":"/var/www/html/lib/private/Files/View.php",
            "line":1383,
            "function":"getCacheEntry",
            "class":"OC\\Files\\View",
            "type":"->",
            "args":[
               {
                  "cache":{
                     "__class__":"OC\\Files\\Cache\\Cache"
                  },
                  "scanner":{
                     "__class__":"OC\\Files\\Cache\\Scanner"
                  },
                  "watcher":null,
                  "propagator":null,
                  "updater":null,
                  "__class__":"OCA\\Files_Trashbin\\Storage"
               },
               "player",
               "/cReal Audio/player"
            ]
         },
         {
            "file":"/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php",
            "line":222,
            "function":"getFileInfo",
            "class":"OC\\Files\\View",
            "type":"->",
            "args":[
               "/jonas/files/cReal Audio/player"
            ]
         },
         {
            "file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php",
            "line":80,
            "function":"getChild",
            "class":"OCA\\DAV\\Connector\\Sabre\\Directory",
            "type":"->",
            "args":[
               "player"
            ]
         },
         {
            "file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php",
            "line":75,
            "function":"getNodeForPath",
            "class":"Sabre\\DAV\\Tree",
            "type":"->",
            "args":[
               "files/jonas/cReal Audio/player"
            ]
         },
         {
            "file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php",
            "line":75,
            "function":"getNodeForPath",
            "class":"Sabre\\DAV\\Tree",
            "type":"->",
            "args":[
               "files/jonas/cReal Audio/player/Trap Nation Mix"
            ]
         },
         {
            "file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
            "line":81,
            "function":"getNodeForPath",
            "class":"Sabre\\DAV\\Tree",
            "type":"->",
            "args":[
               "files/jonas/cReal Audio/player/Trap Nation Mix/cReal - Trap Nation Mix (2020-03).mp3"
            ]
         },
         {
            "file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
            "line":89,
            "function":"httpGet",
            "class":"Sabre\\DAV\\CorePlugin",
            "type":"->",
            "args":[
               {
                  "__class__":"Sabre\\HTTP\\Request"
               },
               {
                  "__class__":"Sabre\\HTTP\\Response"
               }
            ]
         },
         {
            "file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":474,
            "function":"emit",
            "class":"Sabre\\DAV\\Server",
            "type":"->",
            "args":[
               "method:GET",
               [
                  {
                     "__class__":"Sabre\\HTTP\\Request"
                  },
                  {
                     "__class__":"Sabre\\HTTP\\Response"
                  }
               ]
            ]
         },
         {
            "file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":251,
            "function":"invokeMethod",
            "class":"Sabre\\DAV\\Server",
            "type":"->",
            "args":[
               {
                  "__class__":"Sabre\\HTTP\\Request"
               },
               {
                  "__class__":"Sabre\\HTTP\\Response"
               }
            ]
         },
         {
            "file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":319,
            "function":"start",
            "class":"Sabre\\DAV\\Server",
            "type":"->",
            "args":[
               
            ]
         },
         {
            "file":"/var/www/html/apps/dav/lib/Server.php",
            "line":325,
            "function":"exec",
            "class":"Sabre\\DAV\\Server",
            "type":"->",
            "args":[
               
            ]
         },
         {
            "file":"/var/www/html/apps/dav/appinfo/v2/remote.php",
            "line":35,
            "function":"exec",
            "class":"OCA\\DAV\\Server",
            "type":"->",
            "args":[
               
            ]
         },
         {
            "file":"/var/www/html/remote.php",
            "line":167,
            "args":[
               "/var/www/html/apps/dav/appinfo/v2/remote.php"
            ],
            "function":"require_once"
         }
      ],
      "File":"/var/www/html/lib/private/Log/ErrorHandler.php",
      "Line":91,
      "CustomMessage":"--"
   },
   "userAgent":"Mozilla/5.0 (Linux) mirall/3.0.3git (Nextcloud)",
   "version":"20.0.1.1"
}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
xxxxx.mp3: File was deleted from server
```
</details>

**Comment by kesselb** [comment]
Fixed by https://github.com/nextcloud/server/pull/23645. Will be shipped with 20.0.2, 19.0.5, 18.0.11.

**Comment by dargmuesli** [comment]
Are you sure about that? I've manually inserted that code into my running nextcloud's files and the error seems to persist :thinking:

**Comment by dargmuesli** [comment]
I've now restarted server and client, just to be sure, and yep, the issue still persists. If there are no other changes coming in 20.0.2 which contribute to a fix, I plead to reopen this issue 🙏

**Comment by kesselb** [comment]
cc @rullzer @MorrisJobke

**Comment by MorrisJobke** [comment]
The `isset` only checks for the last index and not for everyone. So we need to add `isset($result['Contents'])  && isset($result['Contents'][0])  && ...`.

@dargmuesli Mind to try this then?

**Comment by MorrisJobke** [comment]
Line 169 would be then:

```php
if ((isset($result['Contents']) && isset($result['Contents'][0]) && isset($result['Contents'][0]['Key']) && $result['Contents'][0]['Key'] === rtrim($path, '/') . '/')
```

**Comment by dargmuesli** [comment]
Thanks for reopening!
I just tried that line, but my issue still persists...

Is it normal that Nextcloud downloads not all unsynced files in one iteration, but around 5-10 files in many iterations? To me it feels like that. The client scans, then downloads a few files, then rescans and downloads more. It looks like if it tries to download files which are already downloaded, it says "File was deleted from server"? Weird.

**Comment by MorrisJobke** [comment]
> Is it normal that Nextcloud downloads not all unsynced files in one iteration, but around 5-10 files in many iterations? To me it feels like that. The client scans, then downloads a few files, then rescans and downloads more. It looks like if it tries to download files which are already downloaded, it says "File was deleted from server"? Weird.

Typically not, but maybe @er-vin can jump in here and knows maybe a potential issue that might cause this behavior.

**Comment by kesselb** [comment]
> The `isset` only checks for the last index and not for everyone. So we need to add `isset($result['Contents']) && isset($result['Contents'][0]) && ...`.

https://3v4l.org/lZLv0 :thinking:

**Comment by MorrisJobke** [comment]
Then I mix something up here 🙈

**Comment by dargmuesli** [comment]
Please tell me if I can provide more valuable information :)

**Comment by er-vin** [comment]
> > Is it normal that Nextcloud downloads not all unsynced files in one iteration, but around 5-10 files in many iterations? To me it feels like that. The client scans, then downloads a few files, then rescans and downloads more. It looks like if it tries to download files which are already downloaded, it says "File was deleted from server"? Weird.
> 
> Typically not, but maybe @er-vin can jump in here and knows maybe a potential issue that might cause this behavior.

On that particular point, yes this can happen if some files are changing during sync. The client figures out something changed during the sync and then schedule a new one to do the discovery again. Obviously I'm guessing there.

**Comment by magikmw** [comment]
I'm encountering a similar message in the logs when unsuccessfully trying to access an S3 external storage folder. It's a different line, but my Nextcloud version is also different (`19.0.4`).
`Error: Trying  to access array offset on value of type null at  /var/www/html/nextcloud/apps/files_external/lib/Lib/Storage/AmazonS3.php#167`

I'm just trying to upload/list files via webdav (curl -T) and open the folder via web gui.
Upload by itself works - files are copied over.

**Comment by dargmuesli** [comment]
Line 167 sounds more like the one, mentioning which this issue was initially closed (#23645).

**Comment by dargmuesli** [comment]
If one gave me the data they are currently missing out on, I would be happy to provide it! 🤷

**Comment by dargmuesli** [comment]
Further debugging shows the following logs when trying to upload files directly via the Nextcloud web interface:

```
Error: Trying to access array offset on value of type bool at /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php#443

Sabre\DAV\Exception\BadRequest: Expected filesize of 2272719 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 519348 bytes. Could either be a network problem on the sending side or a problem writing to the storage on the server side.

Error: Cannot modify header information - headers already sent by (output started at /var/www/html/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/html/apps/dav/lib/Connector/Sabre/File.php#691

Error: fopen(https://creal-audio-test-nextcloud.s3.nl-ams.scw.cloud/player/Trap%20Nation%20Mix/cReal%20-%20Trap%20Nation%20Mix%20%282018-11%29.mp3): failed to open stream: HTTP request failed! at /var/www/html/lib/private/Files/ObjectStore/S3ObjectTrait.php#74

Error: fopen(httpseek://): failed to open stream: &quot;OC\Files\Stream\SeekableHttpStream::stream_open&quot; call failed at /var/www/html/lib/private/Files/Stream/SeekableHttpStream.php#67

Error: fread() expects parameter 1 to be resource, bool given at /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php#862

Error: fclose() expects parameter 1 to be resource, bool given at /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php#863
```

<details>
<summary>full stack traces</summary>

```
[PHP] Error: Error: Trying to access array offset on value of type bool at /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php#443 at <<closure>>

 0. /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php line 443
    OC\Log\ErrorHandler::onError(8, "Trying to acces ... l", "/var/www/html/l ... p", 443, {path: "player/T ... e})
 1. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 300
    OC\Files\Storage\Wrapper\Encryption->fopen("player/Trap Nat ... 3", "r")
 2. /var/www/html/lib/private/Files/View.php line 1165
    OC\Files\Storage\Wrapper\Wrapper->fopen("player/Trap Nat ... 3", "r")
 3. /var/www/html/lib/private/Files/View.php line 1001
    OC\Files\View->basicOperation("fopen", "/creal-audio-te ... 3", ["read"], "r")
 4. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 434
    OC\Files\View->fopen("creal-audio-tes ... 3", "r")
 5. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 90
    OCA\DAV\Connector\Sabre\File->get()
 6. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
 7. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 474
    Sabre\DAV\Server->emit("method:GET", [Sabre\HTTP\Requ ... }])
 8. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 251
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
 9. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    Sabre\DAV\Server->start()
10. /var/www/html/apps/dav/lib/Server.php line 332
    Sabre\DAV\Server->exec()
11. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
12. /var/www/html/remote.php line 167
    require_once("/var/www/html/a ... p")

GET /remote.php/dav/files/jonas/creal-audio-test-nextcloud/player/Trap%20Nation%20Mix/cReal%20-%20Trap%20Nation%20Mix%20(2018-01).mp3
from 141.101.76.202 by jonas at 2021-01-12T18:11:25+00:00

[no app in context] Error: Sabre\DAV\Exception\BadRequest: Expected filesize of 2272719 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 519348 bytes. Could either be a network problem on the sending side or a problem writing to the storage on the server side. at <<closure>>

0. /var/www/html/apps/dav/lib/Connector/Sabre/Directory.php line 155
   OCA\DAV\Connector\Sabre\File->put(null)
1. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1104
   OCA\DAV\Connector\Sabre\Directory->createFile("Trap Nation Mix.jpg", null)
2. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 527
   Sabre\DAV\Server->createFile("creal-audio-tes ... g", null, null)
3. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
   Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
4. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 474
   Sabre\DAV\Server->emit("method:PUT", [Sabre\HTTP\Requ ... }])
5. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 251
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
6. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 319
   Sabre\DAV\Server->start()
7. /var/www/html/apps/dav/appinfo/v1/webdav.php line 84
   Sabre\DAV\Server->exec()
8. /var/www/html/remote.php line 167
   require_once("/var/www/html/a ... p")

PUT /remote.php/webdav/creal-audio-test-nextcloud-2/player/Trap%20Nation%20Mix.jpg
from 141.101.77.12 by jonas at 2021-01-12T18:15:04+00:00

[PHP] Error: Error: Cannot modify header information - headers already sent by (output started at /var/www/html/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/html/apps/dav/lib/Connector/Sabre/File.php#691 at <<closure>>

0. <<closure>>
   OC\Log\ErrorHandler::onError(2, "Cannot modify h ... )", "/var/www/html/a ... p", 691, {string: "X-Hash ... "})
1. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 691
   header("X-Hash-SHA256:  ... 1")
2. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 195
   OCA\DAV\Connector\Sabre\File->header("X-Hash-SHA256:  ... 1")
3. <<closure>>
   OCA\DAV\Connector\Sabre\File->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
4. /var/www/html/lib/private/Files/Stream/HashWrapper.php line 71
   call_user_func(Closure {}, "*** sensitive parameter replaced ***")
5. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 319
   OC\Files\Stream\HashWrapper->stream_close()
6. /var/www/html/apps/dav/appinfo/v1/webdav.php line 84
   Sabre\DAV\Server->exec()
7. /var/www/html/remote.php line 167
   require_once("/var/www/html/a ... p")

PUT /remote.php/webdav/creal-audio-test-nextcloud-2/player/Trap%20Nation%20Mix.jpg
from 141.101.77.12 by jonas at 2021-01-12T18:15:04+00:00

[PHP] Error: Error: fopen(https://creal-audio-test-nextcloud.s3.nl-ams.scw.cloud/player/Trap%20Nation%20Mix/cReal%20-%20Trap%20Nation%20Mix%20%282018-11%29.mp3): failed to open stream: HTTP request failed! at /var/www/html/lib/private/Files/ObjectStore/S3ObjectTrait.php#74 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "fopen(https://c ... !", "/var/www/html/l ... p", 74, {range: "*** sen ... ]})
 1. /var/www/html/lib/private/Files/ObjectStore/S3ObjectTrait.php line 74
    fopen("https://creal-a ... 3", "r", false, null)
 2. /var/www/html/lib/private/Files/Stream/SeekableHttpStream.php line 87
    OCA\Files_External\Lib\Storage\AmazonS3->OC\Files\ObjectStore\{closure}("*** sensitive parameters replaced ***")
 3. /var/www/html/lib/private/Files/Stream/SeekableHttpStream.php line 119
    OC\Files\Stream\SeekableHttpStream->reconnect(0)
 4. <<closure>>
    OC\Files\Stream\SeekableHttpStream->stream_open("httpseek://", "r", {callback: Closure {}}, null)
 5. /var/www/html/lib/private/Files/Stream/SeekableHttpStream.php line 67
    fopen("httpseek://", "r", false, null)
 6. /var/www/html/lib/private/Files/ObjectStore/S3ObjectTrait.php line 75
    OC\Files\Stream\SeekableHttpStream::open(Closure {})
 7. /var/www/html/apps/files_external/lib/Lib/Storage/AmazonS3.php line 524
    OCA\Files_External\Lib\Storage\AmazonS3->readObject("player/Trap Nat ... 3")
 8. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 300
    OCA\Files_External\Lib\Storage\AmazonS3->fopen("player/Trap Nat ... 3", "r")
 9. /var/www/html/lib/private/Files/Storage/Wrapper/PermissionsMask.php line 118
    OC\Files\Storage\Wrapper\Wrapper->fopen("player/Trap Nat ... 3", "r")
10. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 300
    OC\Files\Storage\Wrapper\PermissionsMask->fopen("player/Trap Nat ... 3", "r")
11. /var/www/html/lib/private/Files/Storage/Wrapper/Availability.php line 315
    OC\Files\Storage\Wrapper\Wrapper->fopen("player/Trap Nat ... 3", "r")
12. /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php line 861
    OC\Files\Storage\Wrapper\Availability->fopen("player/Trap Nat ... 3", "r")
13. /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php line 930
    OC\Files\Storage\Wrapper\Encryption->readFirstBlock("player/Trap Nat ... 3")
14. /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php line 388
    OC\Files\Storage\Wrapper\Encryption->getHeader("player/Trap Nat ... 3")
15. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 300
    OC\Files\Storage\Wrapper\Encryption->fopen("player/Trap Nat ... 3", "r")
16. /var/www/html/lib/private/Files/View.php line 1165
    OC\Files\Storage\Wrapper\Wrapper->fopen("player/Trap Nat ... 3", "r")
17. /var/www/html/lib/private/Files/View.php line 1001
    OC\Files\View->basicOperation("fopen", "/creal-audio-te ... 3", ["read"], "r")
18. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 434
    OC\Files\View->fopen("creal-audio-tes ... 3", "r")
19. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 90
    OCA\DAV\Connector\Sabre\File->get()
20. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
21. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 474
    Sabre\DAV\Server->emit("method:GET", [Sabre\HTTP\Requ ... }])
22. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 251
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
23. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    Sabre\DAV\Server->start()
24. /var/www/html/apps/dav/lib/Server.php line 332
    Sabre\DAV\Server->exec()
25. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
26. /var/www/html/remote.php line 167
    require_once("/var/www/html/a ... p")

GET /remote.php/dav/files/jonas/creal-audio-test-nextcloud/player/Trap%20Nation%20Mix/cReal%20-%20Trap%20Nation%20Mix%20(2018-11).mp3
from 141.101.104.35 by jonas at 2021-01-12T18:18:59+00:00

[PHP] Error: Error: fopen(httpseek://): failed to open stream: &quot;OC\Files\Stream\SeekableHttpStream::stream_open&quot; call failed at /var/www/html/lib/private/Files/Stream/SeekableHttpStream.php#67 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "fopen(httpseek: ... d", "/var/www/html/l ... p", 67, {callback: Closure {},context: null})
 1. /var/www/html/lib/private/Files/Stream/SeekableHttpStream.php line 67
    fopen("httpseek://", "r", false, null)
 2. /var/www/html/lib/private/Files/ObjectStore/S3ObjectTrait.php line 75
    OC\Files\Stream\SeekableHttpStream::open(Closure {})
 3. /var/www/html/apps/files_external/lib/Lib/Storage/AmazonS3.php line 524
    OCA\Files_External\Lib\Storage\AmazonS3->readObject("player/Trap Nat ... 3")
 4. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 300
    OCA\Files_External\Lib\Storage\AmazonS3->fopen("player/Trap Nat ... 3", "r")
 5. /var/www/html/lib/private/Files/Storage/Wrapper/PermissionsMask.php line 118
    OC\Files\Storage\Wrapper\Wrapper->fopen("player/Trap Nat ... 3", "r")
 6. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 300
    OC\Files\Storage\Wrapper\PermissionsMask->fopen("player/Trap Nat ... 3", "r")
 7. /var/www/html/lib/private/Files/Storage/Wrapper/Availability.php line 315
    OC\Files\Storage\Wrapper\Wrapper->fopen("player/Trap Nat ... 3", "r")
 8. /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php line 861
    OC\Files\Storage\Wrapper\Availability->fopen("player/Trap Nat ... 3", "r")
 9. /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php line 930
    OC\Files\Storage\Wrapper\Encryption->readFirstBlock("player/Trap Nat ... 3")
10. /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php line 388
    OC\Files\Storage\Wrapper\Encryption->getHeader("player/Trap Nat ... 3")
11. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 300
    OC\Files\Storage\Wrapper\Encryption->fopen("player/Trap Nat ... 3", "r")
12. /var/www/html/lib/private/Files/View.php line 1165
    OC\Files\Storage\Wrapper\Wrapper->fopen("player/Trap Nat ... 3", "r")
13. /var/www/html/lib/private/Files/View.php line 1001
    OC\Files\View->basicOperation("fopen", "/creal-audio-te ... 3", ["read"], "r")
14. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 434
    OC\Files\View->fopen("creal-audio-tes ... 3", "r")
15. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 90
    OCA\DAV\Connector\Sabre\File->get()
16. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
17. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 474
    Sabre\DAV\Server->emit("method:GET", [Sabre\HTTP\Requ ... }])
18. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 251
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
19. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    Sabre\DAV\Server->start()
20. /var/www/html/apps/dav/lib/Server.php line 332
    Sabre\DAV\Server->exec()
21. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
22. /var/www/html/remote.php line 167
    require_once("/var/www/html/a ... p")

GET /remote.php/dav/files/jonas/creal-audio-test-nextcloud/player/Trap%20Nation%20Mix/cReal%20-%20Trap%20Nation%20Mix%20(2018-11).mp3
from 141.101.104.35 by jonas at 2021-01-12T18:18:59+00:00

[PHP] Error: Error: fread() expects parameter 1 to be resource, bool given at /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php#862 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "fread() expects ... n", "/var/www/html/l ... p", 862, {path: "player/T ... e})
 1. /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php line 862
    fread(false, 8192)
 2. /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php line 930
    OC\Files\Storage\Wrapper\Encryption->readFirstBlock("player/Trap Nat ... 3")
 3. /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php line 388
    OC\Files\Storage\Wrapper\Encryption->getHeader("player/Trap Nat ... 3")
 4. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 300
    OC\Files\Storage\Wrapper\Encryption->fopen("player/Trap Nat ... 3", "r")
 5. /var/www/html/lib/private/Files/View.php line 1165
    OC\Files\Storage\Wrapper\Wrapper->fopen("player/Trap Nat ... 3", "r")
 6. /var/www/html/lib/private/Files/View.php line 1001
    OC\Files\View->basicOperation("fopen", "/creal-audio-te ... 3", ["read"], "r")
 7. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 434
    OC\Files\View->fopen("creal-audio-tes ... 3", "r")
 8. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 90
    OCA\DAV\Connector\Sabre\File->get()
 9. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
10. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 474
    Sabre\DAV\Server->emit("method:GET", [Sabre\HTTP\Requ ... }])
11. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 251
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
12. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    Sabre\DAV\Server->start()
13. /var/www/html/apps/dav/lib/Server.php line 332
    Sabre\DAV\Server->exec()
14. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
15. /var/www/html/remote.php line 167
    require_once("/var/www/html/a ... p")

GET /remote.php/dav/files/jonas/creal-audio-test-nextcloud/player/Trap%20Nation%20Mix/cReal%20-%20Trap%20Nation%20Mix%20(2018-11).mp3
from 141.101.104.35 by jonas at 2021-01-12T18:18:59+00:00

[PHP] Error: Error: fclose() expects parameter 1 to be resource, bool given at /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php#863 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "fclose() expect ... n", "/var/www/html/l ... p", 863, {path: "player/T ... e})
 1. /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php line 863
    fclose(false)
 2. /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php line 930
    OC\Files\Storage\Wrapper\Encryption->readFirstBlock("player/Trap Nat ... 3")
 3. /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php line 388
    OC\Files\Storage\Wrapper\Encryption->getHeader("player/Trap Nat ... 3")
 4. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 300
    OC\Files\Storage\Wrapper\Encryption->fopen("player/Trap Nat ... 3", "r")
 5. /var/www/html/lib/private/Files/View.php line 1165
    OC\Files\Storage\Wrapper\Wrapper->fopen("player/Trap Nat ... 3", "r")
 6. /var/www/html/lib/private/Files/View.php line 1001
    OC\Files\View->basicOperation("fopen", "/creal-audio-te ... 3", ["read"], "r")
 7. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 434
    OC\Files\View->fopen("creal-audio-tes ... 3", "r")
 8. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 90
    OCA\DAV\Connector\Sabre\File->get()
 9. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
10. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 474
    Sabre\DAV\Server->emit("method:GET", [Sabre\HTTP\Requ ... }])
11. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 251
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
12. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    Sabre\DAV\Server->start()
13. /var/www/html/apps/dav/lib/Server.php line 332
    Sabre\DAV\Server->exec()
14. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
15. /var/www/html/remote.php line 167
    require_once("/var/www/html/a ... p")

GET /remote.php/dav/files/jonas/creal-audio-test-nextcloud/player/Trap%20Nation%20Mix/cReal%20-%20Trap%20Nation%20Mix%20(2018-11).mp3
from 141.101.104.35 by jonas at 2021-01-12T18:18:59+00:00
```
</details>

I've created new buckts and uploaded files via the s3 aws cli, Nextcloud client and Nextcloud website. I've rescanned the files via `occ` and performed the file cleanup. It somehow seems that it could be connected to an encryption issue, but maybe that's unrelated.

**Comment by szaimen** [comment]
I suppose this is still valid on NC21.0.2?

**Comment by dargmuesli** [comment]
Yes, indeed.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by dargmuesli** [comment]
Looks like it's working for me now!
