### ISSUE TITLE
An exception occurred while executing 'ALTER TABLE oc_activity_mq ADD COLUMN amq_subjectparams CLOB NOT NULL'

### ISSUE THREAD

**Issue by teras** [nextcloud/server#24326]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
Trying to upgrade from an older version of NextCloud (I think 18 but I'm not 100% sure) to 20.0.2
This is a long running server updated from time to time to newer versions.

### Expected behaviour
To finish the installation

### Actual behaviour
An exception occurred

### Server configuration

**Operating system:**
Debian testing

**Web server:**
apache 

**Database:**
SQLite

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
Updating to 20.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
update from an older version

**Where did you install Nextcloud from:**
Self-update

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.12.0
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.1.0
  - dav: 1.15.0
  - deck: 1.0.5
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.8.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.9.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.9.0
  - tasks: 0.13.3
  - text: 3.1.0
  - theming: 1.10.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - viewer: 1.4.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - calendar
  - contacts
  - dashboard
  - encryption
  - files_external
  - mail
  - qownnotesapi
  - ransomware_detection
  - ransomware_protection
  - sharerenamer
  - user_ldap
  - user_status
  - weather_status
teras@yot:/var/www
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nx.yot.is"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "19.0.3.1",
        "overwrite.cli.url": "https:\/\/nx.yot.is",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "sharerenamer"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "accessibility": {
            "installed_version": "1.6.0",
            "types": "",
            "enabled": "yes"
        },
        "activity": {
            "installed_version": "2.12.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "backgroundjob": {
            "lastjob": "23"
        },
        "bruteforcesettings": {
            "installed_version": "2.0.1",
            "enabled": "yes",
            "types": ""
        },
        "calendar": {
            "installed_version": "2.0.4",
            "enabled": "no",
            "types": ""
        },
        "cloud_federation_api": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "comments": {
            "installed_version": "1.9.0",
            "types": "logging",
            "enabled": "yes"
        },
        "contacts": {
            "installed_version": "3.3.0",
            "enabled": "no",
            "types": ""
        },
        "contactsinteraction": {
            "installed_version": "1.1.0",
            "types": "dav",
            "enabled": "yes"
        },
        "core": {
            "installedat": "1564225694.1431",
            "lastupdatedat": "1606208063",
            "vendor": "nextcloud",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "public_files": "files_sharing\/public.php",
            "installed.bundles": "[\"CoreBundle\"]",
            "scss.variables": "b78167848c59d9db74b0b69f563cb4b4",
            "lastcron": "1606208086",
            "lastupdateResult": "{\"version\":\"19.0.5.2\",\"versionstring\":\"Nextcloud 19.0.5\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/releases\\\/nextcloud-19.0.5.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/19\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"changes\":\"https:\\\/\\\/updates.nextcloud.com\\\/changelog_server\\\/?version=19.0.5\",\"autoupdater\":\"1\",\"eol\":\"0\"}",
            "updater.secret.created": "1606208109",
            "theming.variables": "170d7aa707d79502bbaa98b50f7d1843",
            "enterpriseLogoChecked": "yes",
            "oc.integritycheck.checker": "{\"qownnotesapi\":{\"INVALID_HASH\":{\"README.md\":{\"expected\":\"c2aa234b791495bbcf7e3be06915f35ffabcc50c0d8872aed35fb4674a7e229c665426c7c5abca2e08489114968edee54b31987cc9af2a7c4ebfa4fbf318c07d\",\"current\":\"9cab5d84b33f95b51458eac8ea8382c5c1178cf7a1f69d07f31627073c8c4619568eca927822a281dc24ab9371e5094d48b56ff43897a7a34385de1888c1d8fd\"},\"screenshot.png\":{\"expected\":\"45d7ed1c40c52c709271e89c0360229469f4371eeac1ee72fbae52796d4b7cc20093589f369498d3aff699875cac160a073230ac4d8cbc345f770617535f89ce\",\"current\":\"88ee4e1d292c6ae1753178d2e19366f2883e29458594fd26493383147b0049ec6554d3ff2bb410c39f8be9e47ba4a8bde5fec28915955da60d67efd2074fa216\"}},\"EXTRA_FILE\":{\".git\\\/objects\\\/pack\\\/pack-c11f61914f037ba493b844aea2f2fb5f02d416d4.pack\":{\"expected\":\"\",\"current\":\"5ffaa684a17c6c5a472c7365d7c7ea5f767fedf0f96df0e26ae532d596b9d871a143ee4f1e5800af1f75aa05839213eca207278dba81973c755747b6a57578ed\"},\".git\\\/objects\\\/pack\\\/pack-c11f61914f037ba493b844aea2f2fb5f02d416d4.idx\":{\"expected\":\"\",\"current\":\"53edb10b83675240a5d33dc81b2a3d635c1a1b596b051bc736d3e98734376f52ae63c3b9a7505101065391aa682c8deaf5310716b80f75c0c13f23c69207fcbe\"},\".git\\\/logs\\\/HEAD\":{\"expected\":\"\",\"current\":\"9630e940385fc3293993a689f2e370d3497e97f20fb8acffc6d3998727edcd0489dc758c7455fadb3b29054cd0e2fc77b27a3af0a39613e7f247ae264baacd1b\"},\".git\\\/info\\\/exclude\":{\"expected\":\"\",\"current\":\"9828c6ecdf91bf117416e17f4ee9caee2e1e37b6fb00b9ff04035ace17a3089b9d0a25c6baa1046c0e1c62d3da88838e8fca74ea82973d6b975905fde58f3072\"},\".git\\\/description\":{\"expected\":\"\",\"current\":\"f7e152f75b124c3e1c5d12f00427729d9eec4e2c1bf70d7606440a6600d003367eb178331e75ab976a61496e79c2c822020849d28ffd170946397b934611b471\"},\".git\\\/HEAD\":{\"expected\":\"\",\"current\":\"0ae4adc954e969e3961dd8ae0b159c0249d192ae6e21f0de3c9db808d23d4592a39e3066744fdcd977140ac0ade0344d0973d574e2f0d88d6e626f9aeef6f9d5\"},\".git\\\/index\":{\"expected\":\"\",\"current\":\"200d3e636caf563e57197554e01134b4427188674369fa3851d64c9a695bf80db1c4cf295c205ef4d6b2fe740a07181b7412261bcb6077f5b80d3df320e4a723\"},\".git\\\/refs\\\/heads\\\/develop\":{\"expected\":\"\",\"current\":\"fee61ee6e5b88095934c7c424172e685f6b178f881835ba77e20cde0023a174928b820b62ed1890a404c3b217da1e783948bfa7212bd15a6a9b362e2b8ffaff7\"},\".git\\\/refs\\\/remotes\\\/origin\\\/HEAD\":{\"expected\":\"\",\"current\":\"478213bbd19d42b6cb00b888c4c64ba85586cd820d7f0148b6039f6a184da9e157af397ebc5af4b62141e3f9468b3b680cbadcdb5e3a5a8af3c8b05f26070d16\"},\".git\\\/packed-refs\":{\"expected\":\"\",\"current\":\"86f17be1b87e57b3a2580df679a3271257d62f9eafede0f759e006297eaaa9b3ef150e80b398d1ca76d8738c79f5ed6c2ee94d7259d92acb8c8fd9bc6698ef0d\"},\".git\\\/config\":{\"expected\":\"\",\"current\":\"a1b68ae52672d8e66ac2abb3b72e9f0a47009c5af60a76c8d2df8291c2db183902df3cdc97e62b8ca5d9e767ca51ea36d0b0c18ee56f76c4bfe90c6e6612f053\"},\".git\\\/hooks\\\/pre-rebase.sample\":{\"expected\":\"\",\"current\":\"00d21d5d72386c3d9b5a1c36ba85201f730556a8295d4353af54af7892ab81010d42aff209ec1fda61c54e4dda3737cea5fda64f09d40ce5004ae28239565025\"},\".git\\\/hooks\\\/update.sample\":{\"expected\":\"\",\"current\":\"759abd33e5d1dda9b3e3d3116c47b23f616320d70cd66d567b1c4eeefeb6d78571d83b67d825d9e23aac35f0a2e0745cfab1381ecf486e30076b08797699f2c4\"},\".git\\\/hooks\\\/commit-msg.sample\":{\"expected\":\"\",\"current\":\"d6bb7fa747f4625adf1877f546565cbe812ca7dd4168f7e9068e6732555d8737eba549546cf5946649e3f38de82d173aaf9c160a4c9f9445655258b4c5f955eb\"},\".git\\\/hooks\\\/pre-push.sample\":{\"expected\":\"\",\"current\":\"37cd20a090494acb16c2255fe93dadeb409f2553afddc409dad5b5e99c9f5612a28eba397c0f3ae771e17edbe0a6c2a3af311154285e6d9c43e4cc4f06ba5b8d\"},\".git\\\/hooks\\\/prepare-commit-msg.sample\":{\"expected\":\"\",\"current\":\"50ec8a0dd98427e80a82a8d8ce44462a845876e1594c9d0e89483ce9a8aaad616edea0e5c45c1bb69d8fe7f520c6f2260d6fa350d77b400899c3ae375e965bfb\"},\".git\\\/hooks\\\/fsmonitor-watchman.sample\":{\"expected\":\"\",\"current\":\"4f611b6fc08db7552a0eaca432c41d1114cd4daa066d9fc722f34f6de05ec3eed615286e8cfc5a27df0cbfb90887473beb0f859ba3edbcd1e829bb3b5050d2a9\"},\".git\\\/hooks\\\/post-update.sample\":{\"expected\":\"\",\"current\":\"473ad124642571656276bf83b9ff63ab1804d3c23a5bdae52391c6f70a894849ac60c10c9d31deff3938922ce83b68b1e60c11592bbf7ea503f4acd39968cefa\"},\".git\\\/hooks\\\/applypatch-msg.sample\":{\"expected\":\"\",\"current\":\"536cce804d84e25813993efdd240537b52d00ce9cdcecf1982f85096d56a521290104c825c00b370b2752201952a9616a3f4e28c5d27a5b4e4842101a2ff9bee\"},\".git\\\/hooks\\\/pre-receive.sample\":{\"expected\":\"\",\"current\":\"ee08c11fab7e896b2e09c241954ba7640338b12c75cd8040daf053c31b2f22236d7a0deac736f89d305236312fdb4f560a38d4d8debdcc9dcdd23b2d975907d5\"},\".git\\\/hooks\\\/pre-applypatch.sample\":{\"expected\":\"\",\"current\":\"cb78aa7e9b9c146e5db65d86dd83f04e2b6942a06fab50c704a0fd900683f3b6ad1164e74afe2f267f6da91cdff0b9ab07713e12cefc6f8d741b5df194f4fda6\"},\".git\\\/hooks\\\/pre-commit.sample\":{\"expected\":\"\",\"current\":\"337579c03ec152cc04240141f16a7bc471d7ea1cdc214f6e553367d03a337621e3f0ed2dc0eaa800e4a080e37b0ea3967d5daee3744b7519b5c789262beb1d39\"}}}}"
        },
        "dav": {
            "installed_version": "1.15.0",
            "types": "filesystem",
            "enabled": "yes",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "buildCalendarSearchIndex": "yes",
            "buildCalendarReminderIndex": "yes",
            "chunks_migrated": "1"
        },
        "deck": {
            "installed_version": "1.0.5",
            "enabled": "yes",
            "types": "dav"
        },
        "federatedfilesharing": {
            "installed_version": "1.10.1",
            "types": "",
            "enabled": "yes"
        },
        "federation": {
            "installed_version": "1.10.1",
            "types": "authentication",
            "enabled": "yes"
        },
        "files": {
            "installed_version": "1.15.0",
            "types": "filesystem",
            "enabled": "yes",
            "cronjob_scan_files": "500"
        },
        "files_mindmap": {
            "installed_version": "0.0.22",
            "enabled": "no",
            "types": ""
        },
        "files_pdfviewer": {
            "installed_version": "2.0.1",
            "types": "",
            "enabled": "yes"
        },
        "files_rightclick": {
            "installed_version": "0.17.0",
            "types": "",
            "enabled": "yes"
        },
        "files_sharing": {
            "installed_version": "1.11.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_texteditor": {
            "installed_version": "2.8.0",
            "types": "",
            "enabled": "no"
        },
        "files_trashbin": {
            "installed_version": "1.9.0",
            "types": "filesystem,dav",
            "enabled": "yes"
        },
        "files_versions": {
            "installed_version": "1.12.0",
            "types": "filesystem,dav",
            "enabled": "yes"
        },
        "files_videoplayer": {
            "installed_version": "1.9.0",
            "types": "",
            "enabled": "yes"
        },
        "firstrunwizard": {
            "installed_version": "2.8.0",
            "types": "logging",
            "enabled": "yes"
        },
        "gallery": {
            "installed_version": "18.3.0",
            "types": "",
            "enabled": "no"
        },
        "logreader": {
            "installed_version": "2.5.0",
            "types": "",
            "enabled": "yes"
        },
        "lookup_server_connector": {
            "installed_version": "1.8.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "mail": {
            "installed_version": "1.4.1",
            "enabled": "no",
            "types": ""
        },
        "nextcloud_announcements": {
            "installed_version": "1.8.0",
            "types": "logging",
            "enabled": "yes",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200"
        },
        "notes": {
            "installed_version": "3.6.4",
            "enabled": "yes",
            "types": ""
        },
        "notifications": {
            "installed_version": "2.7.0",
            "types": "logging",
            "enabled": "yes"
        },
        "oauth2": {
            "installed_version": "1.8.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "onlyoffice": {
            "installed_version": "6.0.0",
            "enabled": "no",
            "types": "filesystem"
        },
        "ownpad": {
            "installed_version": "0.6.15",
            "enabled": "no",
            "types": "",
            "ownpad_etherpad_enable": "yes",
            "ownpad_ethercalc_enable": "yes",
            "ownpad_etherpad_host": "https:\/\/pad.feneas.org\/",
            "ownpad_ethercalc_host": "https:\/\/ethercalc.net\/",
            "ownpad_etherpad_useapi": "no"
        },
        "password_policy": {
            "installed_version": "1.10.1",
            "types": "authentication",
            "enabled": "yes"
        },
        "photos": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes"
        },
        "privacy": {
            "installed_version": "1.4.0",
            "types": "",
            "enabled": "yes"
        },
        "provisioning_api": {
            "installed_version": "1.10.0",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "qownnotesapi": {
            "installed_version": "20.1.0",
            "enabled": "no",
            "types": ""
        },
        "ransomware_detection": {
            "installed_version": "0.8.0",
            "enabled": "no",
            "types": "logging",
            "debug": "0",
            "expire_days": "15",
            "minimum_sequence_length": "10"
        },
        "ransomware_protection": {
            "installed_version": "1.7.0",
            "enabled": "no",
            "types": "logging"
        },
        "recommendations": {
            "installed_version": "0.8.0",
            "types": "",
            "enabled": "yes"
        },
        "richdocuments": {
            "installed_version": "3.7.4",
            "enabled": "no",
            "types": "filesystem,dav,prevent_group_restriction",
            "wopi_url": "https:\/\/nx.yot.is\/apps\/richdocumentscode\/proxy.php?req=",
            "disable_certificate_verification": "yes"
        },
        "richdocumentscode": {
            "installed_version": "4.2.800",
            "enabled": "no",
            "types": ""
        },
        "serverinfo": {
            "installed_version": "1.10.0",
            "types": "",
            "enabled": "yes"
        },
        "settings": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes"
        },
        "sharebymail": {
            "installed_version": "1.9.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "sharerenamer": {
            "installed_version": "2.7.3",
            "enabled": "no",
            "types": ""
        },
        "support": {
            "installed_version": "1.3.0",
            "types": "session",
            "enabled": "yes",
            "SwitchUpdaterServerHasRun": "yes"
        },
        "survey_client": {
            "installed_version": "1.8.0",
            "types": "",
            "enabled": "yes",
            "last_sent": "1600603225",
            "last_report": "{\"id\":\"oc3s3wacd9n6\",\"items\":[[\"server\",\"version\",\"18.0.7.1\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"none\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"ajax\"],[\"php\",\"version\",\"7.3.19\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",3600],[\"php\",\"upload_max_filesize\",2097152],[\"database\",\"type\",\"sqlite3\"],[\"database\",\"version\",\"3.27.2\"],[\"database\",\"size\",3149824],[\"apps\",\"files_texteditor\",\"disabled\"],[\"apps\",\"gallery\",\"disabled\"],[\"apps\",\"files_mindmap\",\"disabled\"],[\"apps\",\"sharerenamer\",\"disabled\"],[\"apps\",\"mail\",\"disabled\"],[\"apps\",\"lookup_server_connector\",\"1.6.0\"],[\"apps\",\"comments\",\"1.8.0\"],[\"apps\",\"survey_client\",\"1.6.0\"],[\"apps\",\"oauth2\",\"1.6.0\"],[\"apps\",\"files_videoplayer\",\"1.7.0\"],[\"apps\",\"workflowengine\",\"2.0.0\"],[\"apps\",\"provisioning_api\",\"1.8.0\"],[\"apps\",\"files\",\"1.13.1\"],[\"apps\",\"notifications\",\"2.6.0\"],[\"apps\",\"cloud_federation_api\",\"1.1.0\"],[\"apps\",\"viewer\",\"1.2.0\"],[\"apps\",\"federation\",\"1.8.0\"],[\"apps\",\"privacy\",\"1.2.0\"],[\"apps\",\"dav\",\"1.14.0\"],[\"apps\",\"serverinfo\",\"1.8.0\"],[\"apps\",\"files_pdfviewer\",\"1.7.0\"],[\"apps\",\"sharebymail\",\"1.8.0\"],[\"apps\",\"firstrunwizard\",\"2.7.0\"],[\"apps\",\"theming\",\"1.9.0\"],[\"apps\",\"federatedfilesharing\",\"1.8.0\"],[\"apps\",\"systemtags\",\"1.8.0\"],[\"apps\",\"recommendations\",\"0.6.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.7.0\"],[\"apps\",\"updatenotification\",\"1.8.0\"],[\"apps\",\"nextcloud_announcements\",\"1.7.0\"],[\"apps\",\"files_versions\",\"1.11.0\"],[\"apps\",\"activity\",\"2.11.0\"],[\"apps\",\"support\",\"1.1.1\"],[\"apps\",\"accessibility\",\"1.4.0\"],[\"apps\",\"files_sharing\",\"1.10.1\"],[\"apps\",\"logreader\",\"2.3.0\"],[\"apps\",\"files_rightclick\",\"0.15.2\"],[\"apps\",\"password_policy\",\"1.8.0\"],[\"apps\",\"files_trashbin\",\"1.8.0\"],[\"apps\",\"bruteforcesettings\",\"1.6.0\"],[\"apps\",\"ransomware_protection\",\"1.6.1\"],[\"apps\",\"ransomware_detection\",\"0.7.1\"],[\"apps\",\"deck\",\"1.0.5\"],[\"apps\",\"notes\",\"3.6.0\"],[\"apps\",\"tasks\",\"0.13.2\"],[\"apps\",\"calendar\",\"2.0.3\"],[\"apps\",\"contacts\",\"3.3.0\"],[\"apps\",\"text\",\"2.0.0\"],[\"apps\",\"onlyoffice\",\"4.3.0\"],[\"apps\",\"settings\",\"1.0.0\"],[\"apps\",\"photos\",\"1.0.0\"],[\"apps\",\"qownnotesapi\",\"20.1.0\"],[\"stats\",\"num_files\",2595],[\"stats\",\"num_users\",2],[\"stats\",\"num_storages\",3],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",2],[\"stats\",\"num_storages_other\",0],[\"stats\",\"num_comments\",0],[\"stats\",\"num_comment_markers\",0],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",4],[\"files_sharing\",\"num_shares_user\",0],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",4],[\"files_sharing\",\"num_shares_link_no_password\",4],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_3_1\",\"3\"],[\"files_sharing\",\"permissions_3_15\",\"1\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}"
        },
        "systemtags": {
            "installed_version": "1.9.0",
            "types": "logging",
            "enabled": "yes"
        },
        "tasks": {
            "installed_version": "0.13.3",
            "enabled": "yes",
            "types": ""
        },
        "text": {
            "installed_version": "3.1.0",
            "types": "dav",
            "enabled": "yes"
        },
        "theming": {
            "installed_version": "1.10.0",
            "types": "logging",
            "enabled": "yes",
            "name": "CrossMobile",
            "cachebuster": "11",
            "url": "***REMOVED SENSITIVE VALUE***",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "color": "#002E2F",
            "logoMime": "image\/png"
        },
        "twofactor_backupcodes": {
            "installed_version": "1.9.0",
            "types": "",
            "enabled": "yes"
        },
        "updatenotification": {
            "installed_version": "1.10.0",
            "types": "",
            "enabled": "yes",
            "update_check_errors": "0",
            "core": "19.0.4.2",
            "calendar": "2.0.3",
            "contacts": "3.4.1",
            "notes": "3.6.0",
            "ransomware_protection": "1.5.2",
            "tasks": "0.13.5",
            "bruteforcesettings": "1.6.0",
            "deck": "1.1.2",
            "onlyoffice": "4.3.0"
        },
        "viewer": {
            "installed_version": "1.4.0",
            "types": "",
            "enabled": "yes"
        },
        "workflowengine": {
            "installed_version": "2.1.0",
            "types": "filesystem",
            "enabled": "yes"
        }
    }
}
```
</details>

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Firefox

**Operating system:**
Arch Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Tue Nov 24 08:54:00.995784 2020] [access_compat:error] [pid 35422] [client 154.57.12.162:49420] AH01797: client denied by server configuration: /var/www/nx/config
[Tue Nov 24 08:54:27.648620 2020] [access_compat:error] [pid 35415] [client 154.57.12.162:49574] AH01797: client denied by server configuration: /var/www/nx/data/.ocdata
[Tue Nov 24 08:54:45.599807 2020] [access_compat:error] [pid 35351] [client 154.57.12.162:49604] AH01797: client denied by server configuration: /var/www/nx/data/.ocdata
[Tue Nov 24 08:56:27.102924 2020] [php7:error] [pid 35426] [client 154.57.12.162:49562] PHP Fatal error:  require_once(): Failed opening required '/appinfo/v2/remote.php' (include_path='/var/www/nx/3rdparty/pear/archive_tar:/var/www/nx/3rdparty/pear/console_getopt:/var/www/nx/3rdparty/pear/pear-core-minimal/src:/var/www/nx/3rdparty/pear/pear_exception:/var/www/nx/apps') in /var/www/nx/remote.php on line 167
[Tue Nov 24 08:56:27.300752 2020] [php7:error] [pid 35422] [client 154.57.12.162:49646] PHP Fatal error:  require_once(): Failed opening required '/appinfo/v2/remote.php' (include_path='/var/www/nx/3rdparty/pear/archive_tar:/var/www/nx/3rdparty/pear/console_getopt:/var/www/nx/3rdparty/pear/pear-core-minimal/src:/var/www/nx/3rdparty/pear/pear_exception:/var/www/nx/apps') in /var/www/nx/remote.php on line 167
[Tue Nov 24 08:56:27.518582 2020] [php7:error] [pid 35428] [client 154.57.12.162:49566] PHP Fatal error:  require_once(): Failed opening required '/appinfo/v2/remote.php' (include_path='/var/www/nx/3rdparty/pear/archive_tar:/var/www/nx/3rdparty/pear/console_getopt:/var/www/nx/3rdparty/pear/pear-core-minimal/src:/var/www/nx/3rdparty/pear/pear_exception:/var/www/nx/apps') in /var/www/nx/remote.php on line 167
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"UqtaflSCpnasRl0oRc6m","level":3,"time":"2020-11-24T08:57:45+00:00","remoteAddr":"154.57.12.162","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=.......","message":"\\OC\\Updater::failure: Doctrine\\DBAL\\Exception\\DriverException: An exception occurred while executing 'ALTER TABLE oc_activity_mq ADD COLUMN amq_subjectparams CLOB NOT NULL':\n\nSQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"19.0.3.1"}
{"reqId":"UqtaflSCpnasRl0oRc6m","level":3,"time":"2020-11-24T08:57:45+00:00","remoteAddr":"154.57.12.162","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=........","message":"\\OC\\Updater::updateEnd: Update failed","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"19.0.3.1"}
{"reqId":"UqtaflSCpnasRl0oRc6m","level":1,"time":"2020-11-24T08:57:45+00:00","remoteAddr":"154.57.12.162","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=.......","message":"\\OC\\Updater::maintenanceActive: Maintenance mode is kept active","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"19.0.3.1"}
{"reqId":"UqtaflSCpnasRl0oRc6m","level":1,"time":"2020-11-24T08:57:45+00:00","remoteAddr":"154.57.12.162","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=........","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"19.0.3.1"}

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

The javascript console log:

Security Error: Content at https://nx.yot.is/ may not load or link to moz-extension://89859b76-8484-46df-a455-5d7bf8b2d451/js/content/inject.js.
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). onloadwff.js:71:799505
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). content.js:40:10
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). content-fontface.js:50:25
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). utils.js:35:9
No OC found index.js:46:12
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
session heartbeat polling started session-heartbeat.js:97:9
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 102 globals.js:60:15
```
</details>

<details>
<summary>This is what I see on screen:
</summary>

```
Update to 20.0.2

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_activity_mq ADD COLUMN amq_subjectparams CLOB NOT NULL': SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL
Detailed logs

Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: Not a mysql database -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Repair step: Migrate old user config

[1 / 0]: Migrate old user config

[2 / 0]: Migrate old user config

[2 / 2]: Migrate old user config

Updated "accessibility" to 1.6.0

Updated "contactsinteraction" to 1.1.0

Updated "federatedfilesharing" to 1.10.1

Updated "files_pdfviewer" to 2.0.1

Updated "files_rightclick" to 0.17.0

Updated "files_videoplayer" to 1.9.0

Updated "logreader" to 2.5.0

Updated "photos" to 1.2.0

Updated "privacy" to 1.4.0

Updated "provisioning_api" to 1.10.0

Updated "recommendations" to 0.8.0

Updated "serverinfo" to 1.10.0

Updated "settings" to 1.2.0

Repair step: Switches from default updater server to the customer one if a valid subscription is available

Repair info: Repair step already executed

Updated "support" to 1.3.0

Repair step: Send an admin notification if monthly report is disabled

Updated "survey_client" to 1.8.0

Updated "text" to 3.1.0

Repair step: Add background job to check for backup codes

Updated "twofactor_backupcodes" to 1.9.0

Updated "updatenotification" to 1.10.0

Updated "viewer" to 1.4.0

Updated "federation" to 1.10.1

Updated "lookup_server_connector" to 1.8.0

Repair step: Update OAuth token expiration times

Updated "oauth2" to 1.8.0

Updated "password_policy" to 1.10.1

Updated "files" to 1.15.0

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_activity_mq ADD COLUMN amq_subjectparams CLOB NOT NULL': SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL

The update was unsuccessful. Please report this issue to the Nextcloud community.

```
</details>

**Comment by tgly307** [comment]
same to me

**Comment by pascalBokBok** [comment]
Same here during upgrade from 19.x to 20.02.

**Comment by oleander798** [comment]
Almost same during upgrade from 19.x to 20.02:
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken CHANGE `password_invalid` password_invalid TINYINT(1) DEFAULT '0'': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by pascalBokBok** [comment]
Workaround for the oc_activity_mq alter table failing that allowed me to finish the upgrade:
Went into the database (old owncloud upgraded to nextcloud):  psql -h localhost --user=owncloud owncloud
Saw that there was only 1 seemingly insignificant row in the table: select * from oc_activity_mq;
So I wiped the contents of the table: delete from oc_activity_mq;
I only did this because I considered the content of the activity table insignificant. I think it was a log entry about that a user had been removed from a group.
Above procedure allowed me to proceed run and finish the upgrade.

**Comment by snagglewest** [comment]
Same issue
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken CHANGE `password_invalid` password_invalid TINYINT(1) DEFAULT '0'': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by teras** [comment]
@pascalBokBok  I am using the SQLite backend. I tried to edit the table oc_activity_mq (in file data/owncloud.db)  but...

```
sqlite> select * from oc_activity_mq;
sqlite> 
```

nothing is there.

**Comment by teras** [comment]
So maybe here a solution?

Since I was there, I thought, let's change the table. So I copied and pasted the command:
```
sqlite> ALTER TABLE oc_activity_mq ADD COLUMN amq_subjectparams CLOB NOT NULL;
Error: Cannot add a NOT NULL column with default value NULL

```

So indeed there's an issue there.

Here's my definition of the table:
```
sqlite> .schema oc_activity_mq
CREATE TABLE oc_activity_mq (mail_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, amq_timestamp INTEGER DEFAULT 0 NOT NULL, amq_latest_send INTEGER DEFAULT 0 NOT NULL, amq_type VARCHAR(255) NOT NULL COLLATE BINARY, amq_affecteduser VARCHAR(64) NOT NULL COLLATE BINARY, amq_subject VARCHAR(255) NOT NULL COLLATE BINARY, object_type VARCHAR(255) DEFAULT NULL COLLATE BINARY, object_id BIGINT DEFAULT 0 NOT NULL, amq_appid VARCHAR(32) NOT NULL COLLATE BINARY, amq_subjectparams2 CLOB NOT NULL COLLATE BINARY);
CREATE INDEX amp_timestamp_time ON oc_activity_mq (amq_timestamp);
CREATE INDEX amp_latest_send_time ON oc_activity_mq (amq_latest_send);
CREATE INDEX amp_user ON oc_activity_mq (amq_affecteduser);
```

So I decided to be brave. I found [this solution](https://stackoverflow.com/questions/3170634/how-to-solve-cannot-add-a-not-null-column-with-default-value-null-in-sqlite3) which is what we wer suffering exactly. 
So the solution was obvious: it's a bug of sqlite and we need to address it and do it manually.

I used the following commands (note!!!! they are dangerous!!) : 
```
drop table oc_activity_mq;

CREATE TABLE oc_activity_mq (mail_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, amq_timestamp INTEGER DEFAULT 0 NOT NULL, amq_latest_send INTEGER DEFAULT 0 NOT NULL, amq_type VARCHAR(255) NOT NULL COLLATE BINARY, amq_affecteduser VARCHAR(64) NOT NULL COLLATE BINARY, amq_subject VARCHAR(255) NOT NULL COLLATE BINARY, object_type VARCHAR(255) DEFAULT NULL COLLATE BINARY, object_id BIGINT DEFAULT 0 NOT NULL, amq_appid VARCHAR(32) NOT NULL COLLATE BINARY, amq_subjectparams2 CLOB NOT NULL COLLATE BINARY, amq_subjectparams CLOB NOT NULL);

CREATE INDEX amp_timestamp_time ON oc_activity_mq (amq_timestamp);

CREATE INDEX amp_latest_send_time ON oc_activity_mq (amq_latest_send);

CREATE INDEX amp_user ON oc_activity_mq (amq_affecteduser);
```

and it WORKED!

**Comment by eugene-reim** [comment]
Almost same for me 
20.0.0 => 20.0.2

An exception occurred while executing 'ALTER TABLE oc_activity_mq ADD amq_subjectparams2 TEXT NOT NULL': SQLSTATE[23502]: Not null violation: 7 ERROR: column "amq_subjectparams2" contains null values

**Comment by Hades32** [comment]
That's very probably not a SQLite bug, as I have the same issue, upgrading from 20.0.0 to 20.0.2 via the Helm Chart and a PostgreSQL backend

**Comment by df6269** [comment]
Same issue
20.0.0 => 20.0.2

**Comment by halapp** [comment]
same issue with same version

**Comment by jiamliang** [comment]
> So maybe here a solution?
> 
> Since I was there, I thought, let's change the table. So I copied and pasted the command:
> 
> ```
> sqlite> ALTER TABLE oc_activity_mq ADD COLUMN amq_subjectparams CLOB NOT NULL;
> Error: Cannot add a NOT NULL column with default value NULL
> ```
> 
> So indeed there's an issue there.
> 
> Here's my definition of the table:
> 
> ```
> sqlite> .schema oc_activity_mq
> CREATE TABLE oc_activity_mq (mail_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, amq_timestamp INTEGER DEFAULT 0 NOT NULL, amq_latest_send INTEGER DEFAULT 0 NOT NULL, amq_type VARCHAR(255) NOT NULL COLLATE BINARY, amq_affecteduser VARCHAR(64) NOT NULL COLLATE BINARY, amq_subject VARCHAR(255) NOT NULL COLLATE BINARY, object_type VARCHAR(255) DEFAULT NULL COLLATE BINARY, object_id BIGINT DEFAULT 0 NOT NULL, amq_appid VARCHAR(32) NOT NULL COLLATE BINARY, amq_subjectparams2 CLOB NOT NULL COLLATE BINARY);
> CREATE INDEX amp_timestamp_time ON oc_activity_mq (amq_timestamp);
> CREATE INDEX amp_latest_send_time ON oc_activity_mq (amq_latest_send);
> CREATE INDEX amp_user ON oc_activity_mq (amq_affecteduser);
> ```
> 
> So I decided to be brave. I found [this solution](https://stackoverflow.com/questions/3170634/how-to-solve-cannot-add-a-not-null-column-with-default-value-null-in-sqlite3) which is what we wer suffering exactly.
> So the solution was obvious: it's a bug of sqlite and we need to address it and do it manually.
> 
> I used the following commands (note!!!! they are dangerous!!) :
> 
> ```
> drop table oc_activity_mq;
> 
> CREATE TABLE oc_activity_mq (mail_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, amq_timestamp INTEGER DEFAULT 0 NOT NULL, amq_latest_send INTEGER DEFAULT 0 NOT NULL, amq_type VARCHAR(255) NOT NULL COLLATE BINARY, amq_affecteduser VARCHAR(64) NOT NULL COLLATE BINARY, amq_subject VARCHAR(255) NOT NULL COLLATE BINARY, object_type VARCHAR(255) DEFAULT NULL COLLATE BINARY, object_id BIGINT DEFAULT 0 NOT NULL, amq_appid VARCHAR(32) NOT NULL COLLATE BINARY, amq_subjectparams2 CLOB NOT NULL COLLATE BINARY, amq_subjectparams CLOB NOT NULL);
> 
> CREATE INDEX amp_timestamp_time ON oc_activity_mq (amq_timestamp);
> 
> CREATE INDEX amp_latest_send_time ON oc_activity_mq (amq_latest_send);
> 
> CREATE INDEX amp_user ON oc_activity_mq (amq_affecteduser);
> ```
> 
> and it WORKED!

it works for me.  
after doing above, turn off maintenance mode :
in docker container with www-data user login: 
php occ maintenance:mode --off 
or :
docker exec -it -u www-data nextcloud php occ maintenance:mode --off

**Comment by jiamliang** [comment]
> So maybe here a solution?
> 
> Since I was there, I thought, let's change the table. So I copied and pasted the command:
> 
> ```
> sqlite> ALTER TABLE oc_activity_mq ADD COLUMN amq_subjectparams CLOB NOT NULL;
> Error: Cannot add a NOT NULL column with default value NULL
> ```
> 
> So indeed there's an issue there.
> 
> Here's my definition of the table:
> 
> ```
> sqlite> .schema oc_activity_mq
> CREATE TABLE oc_activity_mq (mail_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, amq_timestamp INTEGER DEFAULT 0 NOT NULL, amq_latest_send INTEGER DEFAULT 0 NOT NULL, amq_type VARCHAR(255) NOT NULL COLLATE BINARY, amq_affecteduser VARCHAR(64) NOT NULL COLLATE BINARY, amq_subject VARCHAR(255) NOT NULL COLLATE BINARY, object_type VARCHAR(255) DEFAULT NULL COLLATE BINARY, object_id BIGINT DEFAULT 0 NOT NULL, amq_appid VARCHAR(32) NOT NULL COLLATE BINARY, amq_subjectparams2 CLOB NOT NULL COLLATE BINARY);
> CREATE INDEX amp_timestamp_time ON oc_activity_mq (amq_timestamp);
> CREATE INDEX amp_latest_send_time ON oc_activity_mq (amq_latest_send);
> CREATE INDEX amp_user ON oc_activity_mq (amq_affecteduser);
> ```
> 
> So I decided to be brave. I found [this solution](https://stackoverflow.com/questions/3170634/how-to-solve-cannot-add-a-not-null-column-with-default-value-null-in-sqlite3) which is what we wer suffering exactly.
> So the solution was obvious: it's a bug of sqlite and we need to address it and do it manually.
> 
> I used the following commands (note!!!! they are dangerous!!) :
> 
> ```
> drop table oc_activity_mq;
> 
> CREATE TABLE oc_activity_mq (mail_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, amq_timestamp INTEGER DEFAULT 0 NOT NULL, amq_latest_send INTEGER DEFAULT 0 NOT NULL, amq_type VARCHAR(255) NOT NULL COLLATE BINARY, amq_affecteduser VARCHAR(64) NOT NULL COLLATE BINARY, amq_subject VARCHAR(255) NOT NULL COLLATE BINARY, object_type VARCHAR(255) DEFAULT NULL COLLATE BINARY, object_id BIGINT DEFAULT 0 NOT NULL, amq_appid VARCHAR(32) NOT NULL COLLATE BINARY, amq_subjectparams2 CLOB NOT NULL COLLATE BINARY, amq_subjectparams CLOB NOT NULL);
> 
> CREATE INDEX amp_timestamp_time ON oc_activity_mq (amq_timestamp);
> 
> CREATE INDEX amp_latest_send_time ON oc_activity_mq (amq_latest_send);
> 
> CREATE INDEX amp_user ON oc_activity_mq (amq_affecteduser);
> ```
> 
> and it WORKED!

it works for me, thanks a lot!

**Comment by halapp** [comment]
OK, but how do I access the sqlite within a docker

**Comment by Senci** [comment]
> OK, but how do I access the sqlite within a docker container

You can try to get a shell in the container?
`docker exec -it my_db_container /bin/bash`
---
@halapp

**Comment by jiamliang** [comment]
> OK, but how do I access the sqlite within a docker container
you need to install  sqlite3, login container as root user as @Senci mention，and then install :

apt-get update
apt-get install sqlite3

**Comment by halapp** [comment]
> apt-get update

was the key. Thank you but  unfortunately it didn't work for me with the recreation.

**Comment by halapp** [comment]
Finally it worked for me, too.
I edited the owncloud.db directly on the mount and not from within the container.

Thanks a lot.

**Comment by jowlo** [comment]
I ran into the same problem using a `docker-compose` setup.

If you do not want to fiddle with the database directly, i managed to fix the migration after seeing https://github.com/nextcloud/server/issues/24536. There seem to be two errors in the migrations scripts `apps/activity/lib/Migration/Version2011Date20201006132546.php` and `apps/activity/lib/Migration/Version2011Date20201006132544.php`.

As @nickvergessen mentioned in #24536 just change the two lines https://github.com/nextcloud/activity/blob/master/lib/Migration/Version2011Date20201006132546.php#L56 and https://github.com/nextcloud/activity/blob/master/lib/Migration/Version2011Date20201006132544.php#L64 to `false` and rerun the upgrade (e.g. `docker-compose exec --user www-data app php occ upgrade `).

I had to manually disable maintenance mode afterwards as it was still active from the initial (failed) upgrade.

**Comment by ljgww** [comment]
Anyone with docker + postgres?

status.php claims

{"installed":true,"maintenance":false,"needsDbUpgrade":true,"version":"20.0.2.2","versionstring":"20.0.2","edition":"","productname":"Nextcloud","extendedSupport":false}

**Comment by ljgww** [comment]
fixed according to https://help.nextcloud.com/t/update-to-20-0-2-failed-oc-activity-mq-not-empty-solved/98886/3
- deleted rows in the database
- restart container
- update passed the issue and went on until next error (mail in v.20)

**Comment by antonionardella** [comment]
Same here in a docker-swarm configuration with postgresql.
Stop the **nextcloud** and **redis** container/services beforehand

Enter the container  
`docker exec -it <dbcontainer> /bin/bash`
Run **psql** with nextcloud database user  
` psql -U <username> -W`
Verify the content of the **oc_activity_mq** table
`SELECT * FROM oc_activity_mq;`
Delete content from the **oc_activity_mq** table 
`DELETE FROM oc_activity_mq;`

Quit **psql**
`quit`

Restart **nextcloud** and **redis** container/services

**Comment by pk198105** [comment]
> 
> 
> So maybe here a solution?
> 
> Since I was there, I thought, let's change the table. So I copied and pasted the command:
> 
> ```
> sqlite> ALTER TABLE oc_activity_mq ADD COLUMN amq_subjectparams CLOB NOT NULL;
> Error: Cannot add a NOT NULL column with default value NULL
> ```
> 
> So indeed there's an issue there.
> 
> Here's my definition of the table:
> 
> ```
> sqlite> .schema oc_activity_mq
> CREATE TABLE oc_activity_mq (mail_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, amq_timestamp INTEGER DEFAULT 0 NOT NULL, amq_latest_send INTEGER DEFAULT 0 NOT NULL, amq_type VARCHAR(255) NOT NULL COLLATE BINARY, amq_affecteduser VARCHAR(64) NOT NULL COLLATE BINARY, amq_subject VARCHAR(255) NOT NULL COLLATE BINARY, object_type VARCHAR(255) DEFAULT NULL COLLATE BINARY, object_id BIGINT DEFAULT 0 NOT NULL, amq_appid VARCHAR(32) NOT NULL COLLATE BINARY, amq_subjectparams2 CLOB NOT NULL COLLATE BINARY);
> CREATE INDEX amp_timestamp_time ON oc_activity_mq (amq_timestamp);
> CREATE INDEX amp_latest_send_time ON oc_activity_mq (amq_latest_send);
> CREATE INDEX amp_user ON oc_activity_mq (amq_affecteduser);
> ```
> 
> So I decided to be brave. I found [this solution](https://stackoverflow.com/questions/3170634/how-to-solve-cannot-add-a-not-null-column-with-default-value-null-in-sqlite3) which is what we wer suffering exactly.
> So the solution was obvious: it's a bug of sqlite and we need to address it and do it manually.
> 
> I used the following commands (note!!!! they are dangerous!!) :
> 
> ```
> drop table oc_activity_mq;
> 
> CREATE TABLE oc_activity_mq (mail_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, amq_timestamp INTEGER DEFAULT 0 NOT NULL, amq_latest_send INTEGER DEFAULT 0 NOT NULL, amq_type VARCHAR(255) NOT NULL COLLATE BINARY, amq_affecteduser VARCHAR(64) NOT NULL COLLATE BINARY, amq_subject VARCHAR(255) NOT NULL COLLATE BINARY, object_type VARCHAR(255) DEFAULT NULL COLLATE BINARY, object_id BIGINT DEFAULT 0 NOT NULL, amq_appid VARCHAR(32) NOT NULL COLLATE BINARY, amq_subjectparams2 CLOB NOT NULL COLLATE BINARY, amq_subjectparams CLOB NOT NULL);
> 
> CREATE INDEX amp_timestamp_time ON oc_activity_mq (amq_timestamp);
> 
> CREATE INDEX amp_latest_send_time ON oc_activity_mq (amq_latest_send);
> 
> CREATE INDEX amp_user ON oc_activity_mq (amq_affecteduser);
> ```
> 
> and it WORKED!

So I followed your solution to the letter without errors but it does not solve the issue for me which is exactly the same as yours. What is even more frustrating is that when I do occ status it tells me it upgraded but I still cant acces my Nextcloud, keeps telling me to update

**Comment by jowlo** [comment]
> What is even more frustrating is that when I do occ status it tells me it upgraded but I still cant acces my Nextcloud, keeps telling me to update

You might have to set maintenance mode off manually: `occ maintenance:mode --off`

**Comment by pk198105** [comment]
> 
> 
> > What is even more frustrating is that when I do occ status it tells me it upgraded but I still cant acces my Nextcloud, keeps telling me to update
> 
> You might have to set maintenance mode off manually: `occ maintenance:mode --off`

I did, when its off it goes back to Start Update, its a vicious circle

**Comment by nickvergessen** [comment]
Should be fixed with 20.0.4

**Comment by rohit-patel** [comment]
I am upgrading from 19.0.6 -> 20.0.4 and this has not been fixed. Exact same error.

**Comment by anthraxn8b** [comment]
Same problem for me. It seems as if this is just the next table with an equal problem...
Tried to upgrade from 19.0.6 to 20.0.3...

    # docker exec --user www-data myapp php occ upgrade
    Nextcloud or one of the apps require upgrade - only a limited number of commands are available
    You may use your browser or the occ upgrade command to do the upgrade
    Setting log level to debug
    Updating database schema
    Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE authtoken CHANGE `password_invalid` password_invalid TINYINT(1) DEFAULT '0'':
    
    SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
    Update failed
    Maintenance mode is kept active
    Resetting log level
