### ISSUE TITLE
[21beta7] - Could not validate CRL signature

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#25350]
When trying to install the app, the following message appears: `Could not validate CRL signature`.

![obraz](https://user-images.githubusercontent.com/47037905/105995488-5662ff00-60a9-11eb-8bef-01dc21f10031.png)

```
Error	settings	Exception: Could not validate CRL signature

    /home/xxx/public_html/xxx/apps/settings/lib/Controller/AppSettingsController.php - line 445:

    OC\Installer->downloadApp("spreed")

    /home/xxx/public_html/xxx/lib/private/AppFramework/Http/Dispatcher.php - line 218:

    OCA\Settings\Controller\AppSettingsController->enableApps([ "spreed"], [])

    /home/xxx/public_html/xxx/lib/private/AppFramework/Http/Dispatcher.php - line 127:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "enableApps")

    /home/xxx/public_html/xxx/lib/private/AppFramework/App.php - line 157:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "enableApps")

    /home/xxx/public_html/xxx/lib/private/Route/Router.php - line 302:

    OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", OC\AppFramew ... {}, { _route: "s ... "})

    /home/xxx/public_html/xxx/lib/base.php - line 1002:

    OC\Route\Router->match("/settings/apps/enable")

    /home/xxx/public_html/xxx/index.php - line 37:

    OC::handleRequest()
```
App:
Nextcloud 21.0.0 beta7
PHP 7.3.25

**Comment by nickvergessen** [comment]
@rullzer what was the issue here again? Shouldn't it be fixed with beta7?

**Comment by schnello** [comment]
I upgrade Nextcloud 21.0.0 beta6 to beta7 and issue is not fixed

**Comment by kesselb** [comment]
I closed a bunch of those reports as duplicate of https://github.com/nextcloud/server/issues/25243.

**Comment by rullzer** [comment]
beta8 fixes it (so tomorrow)

**Comment by Valdnet** [comment]
Beta 8 fixes the bug.
Thanks. I can now close Issue.
