### ISSUE TITLE
All office files corrupted

### ISSUE THREAD

**Issue by Inkletblot** [nextcloud/server#26303]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Just a note, this is kind of important to me, I have backups of the vm but it's pretty much 4 years of university work. I haven't checked the backups yet. I do 2 a week but only save 2 due to space constraints. And the most recent one was 12AM today so my oldest backup is only from the 24th and I don't have a lot of hope right now.

Also, it is only office documents, so far it seems that nothing else is wrong, pdf, images (many types), zips all work fine still.

### Steps to reproduce
1. Create Microsoft Office Document.
2. Upload to nextcloud though desktop client.
3. Download from web interface, or other machine.

### Expected behaviour
Word document (or other office document) opens normally.

### Actual behaviour
All office documents are corrupted, salvaging text or repairing in word does nothing.
Changing extension from .docx (or other) to .zip does not work either, archive manager complains that archive is corrupted.

### Server configuration

**Operating system:**
Ubuntu 20.04.02 LTS

**Web server:**
Apache2

**Database:**
MySQL

**PHP version:**
PHP 7.4.3

**Nextcloud version:** (see Nextcloud admin page)
20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install.

**Where did you install Nextcloud from:**
from source, I still have the tar in the home folder of the VM (from memory, it was around 6 months ago)

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.2
  - bookmarks: 4.0.5
  - breezedark: 20.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.1
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - forms: 2.0.4
  - integration_gitlab: 0.0.8
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.9
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - mail
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "1": "nextcloud.inkletblot.com",
            "2": "cloud.inkletblot.com",
            "4": "192.168.2.104"
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.1.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.13.2",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "199"
        },
        "bookmarks": {
            "enabled": "yes",
            "installed_version": "4.0.5",
            "types": ""
        },
        "breezedark": {
            "enabled": "yes",
            "installed_version": "20.0.1",
            "theme_enabled": "1",
            "theme_login_page": "1",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "2.1.2",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "3.4.1",
            "types": "filesystem"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "dav"
        },
        "core": {
            "installedat": "1605519981.5796",
            "lastcron": "1616723948",
            "lastupdateResult": "{\"version\":\"20.0.8.1\",\"versionstring\":\"Nextcloud 20.0.8\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/releases\\\/nextcloud-20.0.8.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/20\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"changes\":\"https:\\\/\\\/updates.nextcloud.com\\\/changelog_server\\\/?version=20.0.8\",\"autoupdater\":\"1\",\"eol\":\"0\"}",
            "lastupdatedat": "1616723488",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "theming.variables": "b92d206521717ac032f8aa58d3c7ff2f",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.0.0",
            "types": ""
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.16.0",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.17.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.9.0",
            "types": "logging"
        },
        "forms": {
            "enabled": "yes",
            "installed_version": "2.0.4",
            "types": ""
        },
        "integration_gitlab": {
            "enabled": "yes",
            "installed_version": "0.0.8",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "no",
            "installed_version": "1.7.0",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.8.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": ""
        },
        "richdocuments": {
            "enabled": "yes",
            "installed_version": "3.7.9",
            "types": "filesystem,dav,prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "filesystem"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "logging"
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.1.0",
            "types": "dav"
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "updatenotification": {
            "contacts": "3.4.2",
            "core": "20.0.2.2",
            "enabled": "yes",
            "installed_version": "1.10.0",
            "richdocuments": "3.7.10",
            "types": "",
            "update_check_errors": "0"
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": "filesystem"
        }
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Firefox 87.0 (64-bit)

**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

error.log
```
[Fri Mar 26 00:01:02.776500 2021] [mpm_prefork:notice] [pid 865] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Fri Mar 26 00:01:02.776545 2021] [core:notice] [pid 865] AH00094: Command line: '/usr/sbin/apache2'
[Fri Mar 26 00:49:12.967034 2021] [access_compat:error] [pid 176549] [client 192.168.2.101:35160] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Fri Mar 26 01:42:41.459442 2021] [mpm_prefork:notice] [pid 865] AH00169: caught SIGTERM, shutting down
[Fri Mar 26 01:44:04.478992 2021] [mpm_prefork:notice] [pid 913] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Fri Mar 26 01:44:04.479469 2021] [core:notice] [pid 913] AH00094: Command line: '/usr/sbin/apache2'
[Fri Mar 26 01:44:15.244276 2021] [access_compat:error] [pid 1112] [client 192.168.2.101:55334] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Fri Mar 26 01:44:19.039099 2021] [access_compat:error] [pid 1129] [client 192.168.2.101:55380] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Fri Mar 26 01:51:32.281191 2021] [access_compat:error] [pid 1135] [client 192.168.2.101:58234] AH01797: client denied by server configuration: /var/www/nextcloud/data/.ocdata
```
access.log
```
https://www.mediafire.com/file/x8r0xn8tdwvpfjm/access.log/file
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
https://www.mediafire.com/file/2a3xr2wrx9paf7z/nextcloud.log/file
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Not sure how this will help but here it is.

```
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 globals.js:60:15
[Nano] Nano Defender Activated :: cloud.inkletblot.com core.js:43:24
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). common.js:2:319
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 11 core.js:214:33
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). utils.js:35:9
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). gps.js:199:11
No OC found index.js:46:12
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
Notifications permissions granted App.vue:296
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
OCA.Files.Sidebar initialized Sidebar.js:37:10
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 3 globals.js:60:15
Uncaught TypeError: OCA.Files.DetailTabView is undefined
    <anonymous> https://cloud.inkletblot.com/index.php/js/activity/activity-sidebar.js?v=6ad94606-0:603
    <anonymous> https://cloud.inkletblot.com/index.php/js/activity/activity-sidebar.js?v=6ad94606-0:803
activity-sidebar.js:603:24
Uncaught TypeError: n.Files.DetailTabView is undefined
    <anonymous> commentstabview.js:21
    <anonymous> commentstabview.js:756
    Webpack 3
commentstabview.js:21:23
Uncaught TypeError: OCA.Files.DetailTabView is undefined
    <anonymous> versionstabview.js:18
    Webpack 3
versionstabview.js:18:7
OCA.Sharing.ShareSearch initialized ShareSearch.js:33:10
OCA.Sharing.ExternalLinkActions initialized ExternalLinkActions.js:33:10
OCA.Viewer initialized Viewer.js:46:10
No OCA.Files app found, viewer is now in standalone mode Viewer.vue:295
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
```
</details>

**Comment by Inkletblot** [comment]
### UPDATE!

The files on the NC server are not corrupted, something in the client/web portal is corrupting them when they are downloaded.
I recently bought a new laptop and had to download everything for the first time. The files were likely broken then, although I do not know. 

I have downloaded one of the files directly from the NC server and it opened up just fine, downloading the same file through the client renders a corrupted file.

Not sure what to make of this but it's nice to know that I haven't permanently lost any of my docs.

**Comment by Michael2222** [comment]
Hello, I have the same problem, but I have stored my documents via external storage support (sftp) on my DiskStation.

1. I create a Office document via WebDAV in a nextcloud folder. This folder is stored via sftp on my DiskSataion.
2. I opend again, and the Office document is corrupt.
3. If I open the Office document directly on my DiskStation, the file is fine

A transfer error must therefore occur on the way between my DiskStation and the client. 
If I stored the Office document direct on the nextcloud server (so no of my DiskStation) all is fine.
If I download the file from the browser, it is also corrupt. So WebDAV between my Client and nextcloud can't be the problem.

I think it is a problem from the "external storage support" app.
I have compare the original file (on DiskStation) and the file was I get via sftp, the file size is smaller by a few bytes. 

The same problem is also by libreoffice documents.

Reagards
 
Nextcloud 20.0.8

**Comment by Michael2222** [comment]
Hello,

I can allways reproduce the error.
If you can give me instructions on how to search incorrectly, I can check it out step by step. 

Regards
  Michael

**Comment by szaimen** [comment]
I think this was an issue with NC21.0.1 and should be fixed in the meantime https://github.com/nextcloud/server/issues/26457

**Comment by Michael2222** [comment]
Hello,

I have update my nextcloud today to 21.0.3 and the bug is NOT fixed!
I can at any time reproduce the error.

Please reopen the ticket.
If you have questions, please send me instructions, so we can isolate the error.

Thanks!

**Comment by szaimen** [comment]
Are you using external storage?

**Comment by Michael2222** [comment]
> 
> 
> Are you using external storage?

Yes, I use the app "External storage support" via SFTP.
I can at any time reproduce the error.
If you can tell me which analysis steps I can take to solve the error. 

Thank you very much!

**Comment by szaimen** [comment]
Duplicate of https://github.com/nextcloud/server/issues/21429
