### ISSUE TITLE
More space for navigation text

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#2693]
There is really no need to limit the label length to 8 characters:
> ![bildschirmfoto vom 2016-12-15 14-35-40](https://cloud.githubusercontent.com/assets/213943/21226089/463170d4-c2d4-11e6-8d35-065d88b41ba7.png)

We have so much space available...

Also the padding left is broken and the text also doesn't look centered:
> ![bildschirmfoto vom 2016-12-15 14-36-17](https://cloud.githubusercontent.com/assets/213943/21226082/411966e2-c2d4-11e6-9c31-42558bf2bb5c.png)

@nextcloud/designers

**Comment by jancborchardt** [comment]
Of course the limit is necessary, otherwise the names would overflow. Just look at this:
![capture du 2016-12-15 15-45-39](https://cloud.githubusercontent.com/assets/925062/21228334/b08b3f24-c2dd-11e6-9f18-473b9f21da3d.png)

The padding issue on the left is correct.

But regarding the actual problem of the long name of »Announcement center«:
I think I mentioned before and I still think that the announcement center should be a part of »Activity«. This adding of apps upon apps doesn’t make sense. Announcements are in the timeline, and they show in the Activity app. The rest to integrate is just putting the input field for admins on the very top of the Activity app. And having a filter on the left for »Announcements« with the announcement icon.
What do you think @nickvergessen?

**Comment by nickvergessen** [comment]
The name is already "Announcements"

**Comment by jancborchardt** [comment]
> And no, the app does way too much, to "simply" melt it into activities.
> This is not what this is about. Please stay on track.

Yes it also is about that. Please explain why it does way too much? While code-wise it can stay a different app, interface-wise it can be combined just fine, and should do so. It’s all chronological activity info. Let’s keep things simple here as we do in Nextcloud.

**Comment by jancborchardt** [comment]
> The name is already "Announcements" (if there would at least be hover for ellipsed titles you would see that)

Yeah, a tooltip for ellipsized titles would be cool. But we need to do that in JS so that not all titles blindly get a hover tooltip. Because most are short enough.

> Make it possible that an app can have more then 8 fucking characters as a link

As shown in the screenshot above, how should we do that? Look at your Android phone or an iOS device … there has to be a cutoff at some point. Swearing doesn’t help fix it.


> I would also use "News" as a link title, but a well-known "RSS Feed Reader" abuses this name already.

Why abuse? It’s a user-facing app and people read news with it. What does the announcements app have to do with »News«? ;) Sure we can talk about different words like »Notice« or »Post« or whatnot but this tackles the wrong problem. See my previous comment about integration.

**Comment by nickvergessen** [comment]
> What does the announcements app have to do with »News«?

It's news about your instance

I will NEVER integrate this into activities, please stay on track, "Annoucements" is really not a very long word, we have 1600 pixels left on that page,....

**Comment by schiessle** [comment]
I have to agree with @nickvergessen. Also keep translations in mind, some languages use to have longer words some shorter, some needs 2-3 words for a proper name and some have a catchy short word to name a app. Most of the time you have more than enough space, so why not just let the drop-down grow/shrink with the content and give every app enough space to display the full name? I think from a UX it is much nicer to see the full name than just a few letters followed by '...'

**Comment by jancborchardt** [comment]
So we are thinking about using a direct-menu like approach for Nextcloud 12 because also apps are too hidden and not discoverable. Talked with @eppfel @juliushaertl :)

That would also partly take care of this issue.

**Comment by schiessle** [comment]
What do you mean by "direct-menu"? Do you already have a mock-up, screenshot, etc? Does this mean to have again a always visible menu like many years ago?

**Comment by nickvergessen** [comment]
https://apps.nextcloud.com/apps/direct_menu

**Comment by jancborchardt** [comment]
@schiessle basically similar to this: https://apps.nextcloud.com/apps/direct_menu by @juliushaertl. See discussion at https://help.nextcloud.com/t/is-this-the-most-awesome-or-what/6163/3?u=jan
And yes, always visible but limited to the first ~5 apps (and then a 3-dot-menu for the rest) to not clutter too much.

**Comment by schiessle** [comment]
@jancborchardt @nickvergessen thanks for the pointer. To be honest, I'm not a big fan of the "direct-menu" but let's see how things evolve.

**Comment by jancborchardt** [comment]
@schiessle it of course needs to be polished, but the problem we need to really solve is people not knowing that Nextcloud has other apps except files. We hear that more and more. :)

**Comment by MorrisJobke** [comment]
Fixed by new menu - see #3959 for the remaining issue

**Comment by nickvergessen** [comment]
This is still a problem in the overview menu.

But jan wanted to change it to a lined layout (like settings menu) instead of the current box-layout.

@jancborchardt is there already a dedicated issue for that?

**Comment by MorrisJobke** [comment]
Nothing for 12 I would say.

**Comment by eppfel** [comment]
So, we have either work out a dynamic solution, which could lead to app names, which are just too long.

Or we agree on a character limit and fix the menu.

In particular changing "announcement center" to "announcements", would solve the issue for now, right?
<img width="275" alt="bildschirmfoto 2017-05-15 um 11 46 56" src="https://cloud.githubusercontent.com/assets/1899308/26052050/85d7ceac-3964-11e7-8ac2-88762d23c6d3.png">

**Comment by jancborchardt** [comment]
> But jan wanted to change it to a lined layout (like settings menu) instead of the current box-layout.

This was actually done through @juliushaertl's responsive menu at https://github.com/nextcloud/server/pull/4439

The names now have more space, and I would say that’s also enough, no? @nickvergessen what do you think?

EDIT: Yep, as @eppfel said the name should be concise. »Announcements« is good. :)

**Comment by nickvergessen** [comment]
> In particular changing "announcement center" to "announcements"

Hu? the navigation string is already announcements since ever ;)

Anyway, yes this one is solved
