### ISSUE TITLE
Shared folders/files icons not showing up instantly, need to reload the page

### ISSUE THREAD

**Issue by Beltran1337** [nextcloud/server#26969]
**Nextcloud version:** 21.0.1 Latest Stable
**Operating system and version:** Oracle Linux 7.9
**Apache or nginx version:**  Apache 2.4.6
**PHP version:** 7.4

**The issue you are facing:** 
Every time I share a folder or a file (everything else works perfectly), the icon of the folder and the icons showing that the file/folder are not showing up when I finish sharing it.
If I reload the page, they show up normally.
Is this a background job that cron runs too?
My cron is running every 5 minutes, configured according to the NC's best practices manual.

**Before you say that refreshing the page isn't a big trouble:** 
I have a nextcloud server, which will be in production soon integrated with my AD, containing more than 1300 users.
I have knowledge that refreshing the page is a simple task and it is not a big trouble the need of having to do so.
But the problem here, is for the lay users that will not understand if the files/folders were actually shared or not.

**Is this the first time you've seen this error?:** N

Steps to replicate it:

1. Go to files;
2. Try sharing a folder/file;
3. If the icons doesn't appear, try refreshing the page.

Any suggestions will be very appreciated. 

Thank you guys.

**Comment by Beltran1337** [comment]
I tried to open this case inside help.nextcloud.com but did not received any help, so I'm trying github now...

Thank you guys!

Here's the link for the community forum: https://help.nextcloud.com/t/shared-folders-files-icons-not-showing-up-instantly-need-to-reload-the-page/113802

**Comment by Discostu36** [comment]
Same problem with NC 20.0.9.1 as managed Nextcloud (nginx) at hosting.de

**Comment by szaimen** [comment]
Can you please send screenshots to clarify what you are describing in this issue? Thank you!

**Comment by Discostu36** [comment]
1. Go to a folder with a file in it ![grafik](https://user-images.githubusercontent.com/30999326/128927749-906cc2eb-6c9f-4cad-adad-82f4398d53fe.png)

2. Click on the file and create a share link 
![grafik](https://user-images.githubusercontent.com/30999326/128927924-2b5eaa6b-258a-4367-a2de-90b152ef8898.png)

3. Nothing has changed in the file list 
![grafik](https://user-images.githubusercontent.com/30999326/128928027-48cbc22f-c022-4eb2-b3e6-f00d67896ff2.png)

4. Reload the page. Now the share status is shown 
![grafik](https://user-images.githubusercontent.com/30999326/128928191-34721c28-d4d6-4a90-9180-ad7a4d31ebff.png)

The status should update immediately, not only after reload.

**Comment by szaimen** [comment]
I am not sure if this ever worked so I interpret this as a feature request.

cc @nextcloud/server for input on this.

**Comment by Beltran1337** [comment]
Thank you very much @szaimen 

At the time I created this ticket, I didn't realized that it was actually a feature request.

Thank you again, all the best!

**Comment by PVince81** [comment]
this used to work, it probably broke when the sidebar panels got ported to Vue

the challenge is to have the Vue components trigger events to tell the filelist to refresh the share icons
there used to be an event called "sharedChanged" in apps/files_sharing/src/share.js but I couldn't find quickly when it got removed

**Comment by johnnyq** [comment]
Calendar Nextcloud addon is using Vue now and calendar updates its icon in realtime when you click share.
Maybe this can be replicated for Files as well.
This should be bumped up on priority
Anyhow I'm really hoping for a fix for the new Nextcloud 25 but we'll wait and see

**Comment by johnnyq** [comment]
I'm really hoping this finally gets fixed for Nextcloud 26 but we'll see

**Comment by skjnldsv** [comment]
@johnnyq until the files app is done being rewritten, no it will not be fixed (not with 26 at least)

**Comment by szaimen** [comment]
I think this was fixed with https://github.com/nextcloud/server/pull/38259?

**Comment by johnnyq** [comment]
@szaimen This is still not fixed i tried the latest 27.0 release

Steps to reproduce

1. Share a folder
2. Notice the folder doesn't update right away with a share icon
3. Refresh page manually now the folder has a share icon next to it
4. now un-share the folder notice the share icon does not go away
5. refresh page share icon goes away

**Comment by szaimen** [comment]
Yeah the backport to stable27 is not merged yet: https://github.com/nextcloud/server/pull/38420

**Comment by johnnyq** [comment]
@szaimen oh that is super fantastic!! Thanks for pointing that out, i'm looking forward to the next update for sure.

**Comment by szaimen** [comment]
Great! Thanks for verifying! :)
