### ISSUE TITLE
UI problem in a shared folder containing .md file

### ISSUE THREAD

**Issue by Apflkuacha** [nextcloud/server#28357]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open this link:  [https://cloud3.linuxfabrik.io/s/aDNZ2FHW9YiZmFk](https://cloud3.linuxfabrik.io/s/aDNZ2FHW9YiZmFk)
2. clicking on the "+ Symbol" (marked green in the screenshot)
![grafik](https://user-images.githubusercontent.com/31316050/128698372-b7436f99-d6a9-4bf5-9af8-05dc602342a6.png)

### Expected behaviour
The popup of the "+ Symbol" should be above the readme.md text.

### Actual behaviour
When being on a shared folder on my NextCloud hoster (running Version ) and clicking on the "+ Symbol" (marked green in the screenshot) the Text for the button is not completly visible (marked red) because the information of the readme.md is shown above the popup. 

### Server configuration

**Nextcloud version:** 21.0.3.1

### Client configuration
**Browser:** tested on Firefox and Edge

**Operating system:** tested on Manjaro Linux, Andorid and Windows 10

**Comment by szaimen** [comment]
Thanks for your report. This should be fixed with 21.0.4

**Comment by Apflkuacha** [comment]
@szaimen The server now updated to Version 21.0.4.1 but the bug still exists

**Comment by szaimen** [comment]
Yes, you are right. The backport is still pending
https://github.com/nextcloud/text/pull/1770
