### ISSUE TITLE
Sharing admin settings are broken - $elements.select2 is not a function

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#31589]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Uncaught TypeError: $elements.select2 is not a function
    success settings.js:53
    jQuery 4
[settings.js:53:17](https://nextcloud24.local/apps/settings/js/settings.js)
    success settings.js:53
    jQuery 4

### Steps to reproduce

1. Go to index.php/settings/admin/sharing
2. Try to select a group for "Exclude groups from creating link shares: "
3. Try to select a group for "Exclude groups from sharing"

### Expected behavior

Works

### Installation method

Other

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Master
```

### List of activated Apps

```shell
default
```

**Comment by szaimen** [comment]
@artonge shouldn't that be fixed with https://github.com/nextcloud/server/pull/31572?

**Comment by nickvergessen** [comment]
Ref https://github.com/nextcloud/server/issues/31570

But still not working on master.

**Comment by nickvergessen** [comment]
Seems to work now after pressing ctrl+f5 even harder and more often
