### ISSUE TITLE
[Bug]: Federated sharing cannot open a shared file

### ISSUE THREAD

**Issue by Raudius** [nextcloud/server#31896]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Integration tests failing on `richdocuments` for federated sharing. Failing specifically on steps related to opening files shared accross instances.

Failing CI on `richdocuments/master`:
https://github.com/nextcloud/richdocuments/runs/5853738007

`git bisect` suggests originating commit is `44a8ebdc1fa796d4f7dc453c58561b64902ca12f` from PR:
https://github.com/nextcloud/server/pull/31773 

### Steps to reproduce

Still working on reproducing it on the web environment.

1.
2.
3.

### Expected behavior

Opening of files shared across instances should work

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_sharing: 1.16.0
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - lookup_server_connector: 1.12.0
  - oauth2: 1.12.0
  - provisioning_api: 1.14.0
  - richdocuments: 6.0.0-dev.1
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - systemtags: 1.14.0
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - testing
  - user_ldap
```

**Comment by PVince81** [comment]
@icewind1991 please have a look, it's related to the recent perf improvements.

I wonder if it's similar to https://github.com/nextcloud/server/issues/31858

**Comment by PVince81** [comment]
@Raudius we've merged a fix on master https://github.com/nextcloud/server/pull/31901

can you rerun the integration tests of richdocuments to confirm whether this also fixes that issue ?
if yes, you can close this ticket :smile:

**Comment by Raudius** [comment]
@icewind1991 

Federattion tests are still not fixed on `richdocuments` :(

**Comment by PVince81** [comment]
@Raudius can you post instructions how to run that specific test locally ?

**Comment by Raudius** [comment]
Pre-requisiites:
 * Non-docker Nextcloud instance
 * Global composer installation
 * CODE package installed and running: https://www.collaboraoffice.com/code/linux-packages/

Then:
```
cd /var/www/html/apps/richdocuments/tests
sudo -u \#33 -- ./run-integration.sh ./features/federation.feature
```

**Comment by icewind1991** [comment]
> Pre-requisiites:

- user `admin` setup with password `password`

**Comment by icewind1991** [comment]
should be fixed with https://github.com/nextcloud/server/pull/31934
