### ISSUE TITLE
[Bug]: setting maintenance mode should work even if config_is_readonly is set

### ISSUE THREAD

**Issue by darix** [nextcloud/server#32291]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

up until v23 you could run `occ upgrade` without first having to set the read only flag in the config.php to false manually.
`occ config:system:set config_is_read_only --type boolean --value false` does not work either to achieve this.

### Steps to reproduce

1. set the read only flag in config.php
2. run `occ upgrade`

### Expected behavior

upgrade should actually run.

### Installation method

Manual installation

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

PostgreSQL

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
-
```

**Comment by darix** [comment]
1. this is still a regression.
2. yes manually it is easy. automated e.g. as part of an RPM post scriptlet starts to get annoying already.

**Comment by szaimen** [comment]
I rather don't think that this will be changed again since it fixed this bug: https://github.com/nextcloud/server/issues/29901

Cc @mejo-

**Comment by darix** [comment]
well then maybe the whole maintenance flag should maybe moved out of the config file?

**Comment by szaimen** [comment]
I don't think this will happen either but lets see what @mejo- says

**Comment by danieljkemp** [comment]
The config file should not contain anything that can change. Both the version and maintenance flag can change during runtime (updates, other maintenance tasks). 

Once the application is configured, the config file should be able to be managed via a proper configuration management (or git) solution. The config file should not need to be a volume.

**Comment by baldurmen** [comment]
I updated from 24.0.6 to 25.0.0 today using `occ` and I did not experience this issue, even though my config has `config_is_read_only' => false,`. I think this bug can be closed, as it seems to have been resolved?

**Comment by nierdz** [comment]
It's the other way around @baldurmen , this is when `config_is_read_only` is set to `true` this bug appears so this bug is still present even with `25.0.1`.

**Comment by baldurmen** [comment]
@nierdz well, the behavior reported my @micah here is fixed at least, which means you can set the value to `false`, upgrade, and then set it back to `true`.

IMO it's acceptable that the updater refuses to update if the config is marked as read-only...

**Comment by danieljkemp** [comment]
Why is the config file used to store dynamic application state to behind with?

**Comment by darix** [comment]
Well given that this bug was not about micah's issue but that something else. I am not sure why this was closed.

Please reopen it.

**Comment by nierdz** [comment]
@baldurmen Thanks for this information, I didn't test that behavior. What I tested is to perform `occ upgrade` when `config_is_read_only` is set to `true` which was previously possible.

 I agree with @danieljkemp on that, it shouldn't be an issue if `config.php` was not used to store dynamic application state.

**Comment by gonzalo** [comment]
Same problem here with Nextcloud 25.0.4.

- config_is_read_only  set to true in config.php because of security issues
- Config.php is writable
- I want to set Nextcloud into maintenance mode to perform backups, obviously with scripts. Or perform an upgrade
- I agree that first I should remove the config_is_read_only restriction but if I try to do it with occ...

```
# occ config:system:set --type boolean --value true config_is_read_only

In Config.php line 310:
                                                                   
  Config is set to be read-only via option "config_is_read_only".  
                                                                   

config:system:set [--output [OUTPUT]] [--type TYPE] [--value VALUE] [--update-only] [--] <name>...
```
 So, the workaround

```
sed -i -e '/config_is_read_only/d' /your_path/config/config.php 
...
[do your stuff]
occ config:system:set --type boolean --value true config_is_read_only
```
I would like to be able to disable that config_is_read_only flag from occ command line but I understand that is exactly what that flag is trying to avoid.
