### ISSUE TITLE
[Bug]: PHP Fatal error: Nesting level too deep - recursive dependency?

### ISSUE THREAD

**Issue by waja** [nextcloud/server#32432]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When creating a user which is part of any group, there is an error thrown in the UI: "An error occurred during the request. Unable to proceed.". `nextcloud.log` has `PHP Fatal error: Nesting level too deep - recursive dependency? in /var/www/html/lib/private/Log/ExceptionSerializer.php on line 212`.
Creating a user without being part of a group works as expected.

If you try this again, this fails cause the user is already present. Reloading the page you see the user and it's part of the group, but any other user information is missing.

See this on a new instance of latest 22.x, 23.x and 24.0. With 21.x and below we do not face this issue.

### Steps to reproduce

1. Login to Nextcloud instance with privileged account
2. Navigate to /settings/users
3. Click on "New User"
4. Fill in the users information including e-mail, password, group (this is important to trigger the bug) and display name
5. Click "Add new user"
6. Error appears on the upper right corner: "An error occurred during the request. Unable to proceed."
7. Refresh webpage
8. After that, the user is present in the users list and the admin account can edit the user's information as expected and the welcome e-mail will be sent

### Expected behavior

Created user with details when user is part of a group when creating.

### Installation method

Other

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "apps_paths": [
            {
                "path": "\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/nextcloud\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.test.org"
        ],
        "dbtype": "mysql",
        "version": "24.0.0.12",
        "overwrite.cli.url": "http:\/\/nextcloud.test.org",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "redis": {
            "port": 6379,
            "host": "***REMOVED SENSITIVE VALUE***"
        },
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "default_phone_region": "DE",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bruteforcesettings: 2.4.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
T  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - firstrunwizard: 2.12.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"VhqXg7aIKAOoQCHZZLyW","level":3,"time":"2022-05-16T11:52:16+00:00","remoteAddr":"172.19.0.2","user":"admin","app":"PHP","method":"POST","url":"/ocs/v2.php/cloud/users","message":"Nesting level too deep - recursive dependency? at /nextcloud/lib/private/Log/ExceptionSerializer.php#212","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36","version":"24.0.0.12","id":"62823b928edc0"}
```

### Additional info

This seems also be an [issue](https://github.com/nextcloud/helm/issues/229) with the official helm chart. The suggested dirty fix in https://github.com/pulsejet/nextcloud-oidc-login/issues/133#issuecomment-1102459032 seems also work for us.

It might also be related to https://github.com/nextcloud/server/issues/23429#issuecomment-708901668

**Comment by CarlSchwan** [comment]
This is potentially fixed with 891c10d09da @waja could you try to patch your server with this patch and confirm?

**Comment by waja** [comment]
Looks like the version from 24.0.2 differs in the following way:
```
--- ExceptionSerializer.php.24.0.2	2022-06-20 17:01:33.000000000 +0200
+++ ExceptionSerializer.php	2022-06-21 17:06:01.668852037 +0200
@@ -42,8 +42,6 @@
 use OCP\HintException;
 
 class ExceptionSerializer {
-	public const SENSITIVE_VALUE_PLACEHOLDER = '*** sensitive parameters replaced ***';
-
 	public const methodsWithSensitiveParameters = [
 		// Session/User
 		'completeLogin',
@@ -182,7 +180,7 @@
 		if (isset($traceLine['args'])) {
 			$sensitiveValues = array_merge($sensitiveValues, $traceLine['args']);
 		}
-		$traceLine['args'] = [self::SENSITIVE_VALUE_PLACEHOLDER];
+		$traceLine['args'] = ['*** sensitive parameters replaced ***'];
 		return $traceLine;
 	}
 
@@ -213,7 +211,7 @@
 		$workArgs = [];
 		foreach ($args as $arg) {
 			if (in_array($arg, $values, true)) {
-				$arg = self::SENSITIVE_VALUE_PLACEHOLDER;
+				$arg = '*** sensitive parameter replaced ***';
 			} elseif (is_array($arg)) {
 				$arg = $this->removeValuesFromArgs($arg, $values);
 			}
```

**Comment by waja** [comment]
This issue seems still present when creating a user present in a group and with mail and display name:
```
{"reqId":"spSXyDTGLqAu7cnpKZk6","level":3,"time":"2022-06-21T15:21:06+00:00","remoteAddr":"172.19.0.2","user":"admin","app":"PHP","method":"POST","url":"/ocs/v2.php/cloud/users","message":"Nesting level too deep - recursive dependency? at /nextcloud/lib/private/Log/ExceptionSerializer.php#213","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36","version":"24.0.2.1"}
```

**Comment by dsec-be** [comment]
As additional information, it was working in 22.2.5, not anymore in 22.2.7 and above.
If not possible to revert to code from previous version, is there any upgrade path that would solve that issue?

**Comment by elkangaroo** [comment]
> This is potentially fixed with [891c10d](https://github.com/nextcloud/server/commit/891c10d09da333e6af172bacd0c28540fd7a7032) @waja could you try to patch your server with this patch and confirm?

I just tried this patch on our installation, but unfortunately this did not fix the issue. Still got the "Nesting level too deep" fatal error when creating a new user with group membership, just on line 213 instead of 212 now.

**Comment by dsec-be** [comment]
With 2k issues in the pipe, what's the chance to get this one addressed soon? I can understand that it's not the highest priority as it's not blocking or security related. But it's seriously impacting the use of the whole system. 
Is there really people creating users without any group? Also users set as admin for a group doesn't have the choice, new users that they create, always come with that group assigned.

**Comment by ChristophWurst** [comment]
My attempt at fixing this: https://github.com/nextcloud/server/pull/33501

You can download it as patch from https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/33501.patch. Patching instructions can be found here: https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html. Let me know if this improves anything.

**Comment by Volker-K** [comment]
After migrating from 23 to 24.0.3 I encountered a similar error while logging in (same error with local NC IDs and LDAP IDs) but with another line number:

Aug 10 06:57:55 lxcloudp01 Nextcloud[18323]: {"reqId":"S3Q0cyy8kiY2fwkMF2CM","level":3,"time":"2022-08-10T06:57:55+02:00","remoteAddr":"10.100.41.137","user":"-ser-","app":"PHP","method":"POST","url":"**/index.php/login**","message":**"Nesting level too deep - recursive dependency? at /srv/www/htdocs/owncloud/lib/private/Log/ExceptionSerializer.php#215"**,"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0","version":"24.0.3.2","data":{"app":"PHP"}}[Wed Aug 10 06:53:02.096193 2022] [php7:error] [pid 18300] [client 10.100.41.137:65027] PHP Fatal error:  Nesting level too deep - recursive dependency? in /srv/www/htdocs/owncloud/lib/private/Log/ExceptionSerializer.php on line 215

I think this is the same error, isn't it? Would try to migrate to a stable version where it is fixed. 

And one question: The program affected is ExceptionSerializer. I don't understand it's job, so I wonder if this Nesting level too deep the only error or does it occur while catching another error of another module?

**Comment by dsec-be** [comment]
> My attempt at fixing this: #33501
> 
> You can download it as patch from https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/33501.patch. Patching instructions can be found here: https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html. Let me know if this improves anything.

Hi I tried to patch but looks like the code already changed a lot in ExceptionSerializer.php (we're still running on 22.2.7, and I was waiting for a fix before my next update).

`patch -p 1 < /home/test/nextcloud/33501.patch
patching file lib/private/Log/ExceptionSerializer.php
Hunk #1 FAILED at 40.
Hunk #2 FAILED at 210.
2 out of 2 hunks FAILED -- saving rejects to file lib/private/Log/ExceptionSerializer.php.rej`

Could you confirm that changes would be compatible with our installed version if:
- add Hunk1 to the use
- replace whole content of function removeValuesFromArgs($args, $values) with only the + of Hunk2
` 	private function removeValuesFromArgs($args, $values) {
		return array_map(function($arg) use ($values) {
			// Sensitive?
			try {
				if (in_array($arg, $values, true)) {
					return self::SENSITIVE_VALUE_PLACEHOLDER;
				}
			} catch (Throwable $e) {
				// In very rare cases PHP can't run in_array on the args because
				// of a recursive structure. In that case we fall back to
				// assuming the argument could be sensitive
				return self::SENSITIVE_VALUE_PLACEHOLDER;
			}

			// Array?
			if (is_array($arg)) {
				return $this->removeValuesFromArgs($arg, $values);
			}

			return $arg;
		}, $args);
 	}
`

Thanks !

**Comment by ChristophWurst** [comment]
> ### Steps to reproduce
> 
>     1. Login to Nextcloud instance with privileged account
> 
>     2. Navigate to /settings/users
> 
>     3. Click on "New User"
> 
>     4. Fill in the users information including e-mail, password, group (this is important to trigger the bug) and display name
> 
>     5. Click "Add new user"
> 
>     6. Error appears on the upper right corner: "An error occurred during the request. Unable to proceed."
> 
>     7. Refresh webpage

I'm unable to reproduce with latest master branch.

**Comment by ChristophWurst** [comment]
I can reproduce with the Docker image. I'll see if that is debuggable.

**Comment by ChristophWurst** [comment]
1) ``\OCA\Provisioning_API\Controller\UsersController::addUser`` runs until ``$this->groupManager->get($group)->addUser($newUser);``.
2) ``\OC\Group\Group::addUser`` runs until ``$this->emitter->emit('\OC\Group', 'postAddUser', [$this, $user]);``
3) From there it gets messy as there are many hooks and listeners for the event.

I did find out that disabling the app `circles` eliminates the bug. Could someone try and see if that helps your instance as well?

**Comment by waja** [comment]
> Could someone try and see if that helps your instance as well?

Jepp ... disabling `circles` eliminates the `PHP Fatal error: Nesting level too deep - recursive dependency?` problem on our instances.

**Comment by ChristophWurst** [comment]
@ArtificialOwl could you have a look at https://github.com/nextcloud/server/issues/32432#issuecomment-1222143890? Maybe we can break the recursive structure. Otherwise I suggest dropping the `$wrapper` object from being logged.

**Comment by dsec-be** [comment]
Excellent !! Thank you for the debugging 👍 
Disabling "Circles" app indeed solves the issue here as well.

**Comment by thgoebel** [comment]
I hit this with the Docker image as well when upgrading to Nextcloud 25.0.0. `occ app:disable circles` fixed it as well for me.

**Comment by dreary-ennui** [comment]
>  I hit this with the Docker image as well when upgrading to Nextcloud 25.0.0. `occ app:disable circles` fixed it as well for me.

Same behavior here when upgraded to 25 from docker img ver 24.

**Comment by ArtificialOwl** [comment]
this was supposed to be fixed, do you have more logs available ?

**Comment by dreary-ennui** [comment]
Sure thing. Here's from my Nextcloud.log, you can see the update process finish and then just 12 seconds later a client checks in and gets the issue:

`{"reqId":"M5DMmmt53bmHVotmnrSt","level":1,"time":"2022-10-20T10:27:12+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"OC\\Repair\\Events\\RepairStepEvent: Repair step: Add token cleanup job","userAgent":"--","version":"24.0.6.1","data":{"app":"updater"}}
{"reqId":"M5DMmmt53bmHVotmnrSt","level":1,"time":"2022-10-20T10:27:12+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"OC\\Repair\\Events\\RepairStepEvent: Repair step: Clean up abandoned apps","userAgent":"--","version":"24.0.6.1","data":{"app":"updater"}}
{"reqId":"M5DMmmt53bmHVotmnrSt","level":1,"time":"2022-10-20T10:27:12+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"--","version":"24.0.6.1","data":{"app":"updater"}}
{"reqId":"M5DMmmt53bmHVotmnrSt","level":1,"time":"2022-10-20T10:27:15+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"--","version":"24.0.6.1","data":{"app":"updater"}}
{"reqId":"M5DMmmt53bmHVotmnrSt","level":1,"time":"2022-10-20T10:27:15+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"--","version":"25.0.0.18","data":{"app":"updater"}}
{"reqId":"M5DMmmt53bmHVotmnrSt","level":1,"time":"2022-10-20T10:27:15+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"--","version":"25.0.0.18","data":{"app":"updater"}}
{"reqId":"M5DMmmt53bmHVotmnrSt","level":1,"time":"2022-10-20T10:27:15+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"--","version":"25.0.0.18","data":{"app":"updater"}}
{"reqId":"U0VNPCruyE5MkNqPYtGG","level":3,"time":"2022-10-20T10:27:37+00:00","remoteAddr":"myIPAddr","user":"myUser","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/myUser/","message":"Nesting level too deep - recursive dependency? at /var/www/html/lib/private/Log/ExceptionSerializer.php#215","userAgent":"Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.0.18","data":{"app":"PHP"}}
{"reqId":"ZXF1H1AVri1VN4Aldgm6","level":3,"time":"2022-10-20T10:27:37+00:00","remoteAddr":"myIPAddr","user":"myUser","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/myUser/","message":"Nesting level too deep - recursive dependency? at /var/www/html/lib/private/Log/ExceptionSerializer.php#215","userAgent":"Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.0.18","data":{"app":"PHP"}}
{"reqId":"JK36xRDfqZYCUDRbnfNr","level":3,"time":"2022-10-20T10:29:41+00:00","remoteAddr":"myIPAddr","user":"myUser","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/myUser/","message":"Nesting level too deep - recursive dependency? at /var/www/html/lib/private/Log/ExceptionSerializer.php#215","userAgent":"Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.0.18","data":{"app":"PHP"}}
{"reqId":"XqfoG2Pu0YwvJivHiSyr","level":3,"time":"2022-10-20T10:32:47+00:00","remoteAddr":"myIPAddr","user":"myUser","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/myUser/","message":"Nesting level too deep - recursive dependency? at /var/www/html/lib/private/Log/ExceptionSerializer.php#215","userAgent":"Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.0.18","data":{"app":"PHP"}}
{"reqId":"4BsP1LSGPpLtRM3GyI34","level":3,"time":"2022-10-20T10:36:55+00:00","remoteAddr":"myIPAddr","user":"myUser","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/myUser/","message":"Nesting level too deep - recursive dependency? at /var/www/html/lib/private/Log/ExceptionSerializer.php#215","userAgent":"Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.0.18","data":{"app":"PHP"}}
{"reqId":"QIH8aM8OkRAdtKUVXTiH","level":3,"time":"2022-10-20T10:42:06+00:00","remoteAddr":"myIPAddr","user":"myUser","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/myUser/","message":"Nesting level too deep - recursive dependency? at /var/www/html/lib/private/Log/ExceptionSerializer.php#215","userAgent":"Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.0.18","data":{"app":"PHP"}}
{"reqId":"tebE6JDGHQ0PaGLE8LCL","level":3,"time":"2022-10-20T10:48:17+00:00","remoteAddr":"myIPAddr","user":"myUser","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/myUser/","message":"Nesting level too deep - recursive dependency? at /var/www/html/lib/private/Log/ExceptionSerializer.php#215","userAgent":"Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.0.18","data":{"app":"PHP"}}
{"reqId":"CcjDTTHfdsZrRugBZBHV","level":3,"time":"2022-10-20T10:55:31+00:00","remoteAddr":"myIPAddr","user":"myUser","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/myUser/","message":"Nesting level too deep - recursive dependency? at /var/www/html/lib/private/Log/ExceptionSerializer.php#215","userAgent":"Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.0.18","data":{"app":"PHP"}}
{"reqId":"Whf4lELHVcSxXxTXX5T0","level":3,"time":"2022-10-20T11:03:47+00:00","remoteAddr":"myIPAddr","user":"myUser","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/myUser/","message":"Nesting level too deep - recursive dependency? at /var/www/html/lib/private/Log/ExceptionSerializer.php#215","userAgent":"Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.0.18","data":{"app":"PHP"}}
{"reqId":"AClBtqYrpXjcD2jHsApi","level":3,"time":"2022-10-20T11:13:06+00:00","remoteAddr":"myIPAddr","user":"myUser","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/myUser/","message":"Nesting level too deep - recursive dependency? at /var/www/html/lib/private/Log/ExceptionSerializer.php#215","userAgent":"Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.0.18","data":{"app":"PHP"}}`

Same time frame, this time from NGINX's perspective:

`myIpAddr - myUser [20/Oct/2022:06:27:37 -0400] "PROPFIND /remote.php/dav/files/myUser/ HTTP/2.0" 500 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
myIpAddr - myUser [20/Oct/2022:06:27:37 -0400] "PROPFIND /remote.php/dav/files/myUser/ HTTP/2.0" 500 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
myIpAddr - myUser [20/Oct/2022:06:29:41 -0400] "PROPFIND /remote.php/dav/files/myUser/ HTTP/2.0" 500 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
myIpAddr - myUser [20/Oct/2022:06:32:47 -0400] "PROPFIND /remote.php/dav/files/myUser/ HTTP/2.0" 500 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
myIpAddr - myUser [20/Oct/2022:06:36:55 -0400] "PROPFIND /remote.php/dav/files/myUser/ HTTP/2.0" 500 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
myIpAddr - myUser [20/Oct/2022:06:42:06 -0400] "PROPFIND /remote.php/dav/files/myUser/ HTTP/2.0" 500 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
myIpAddr - myUser [20/Oct/2022:06:48:17 -0400] "PROPFIND /remote.php/dav/files/myUser/ HTTP/2.0" 500 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
myIpAddr - myUser [20/Oct/2022:06:55:31 -0400] "PROPFIND /remote.php/dav/files/myUser/ HTTP/2.0" 500 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.6.1git (build 11939) (Nextcloud, osx-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)"`

My currently installed version of Circles is 25.0.0. From what I can tell, these issues occurred during every PROPFIND request after the upgrade process from my Mac and iOS clients until I disabled the Circles app. That was a few hours ago when I found this thread; no errors since.

**Comment by ArtificialOwl** [comment]
Do you still have error if running (first):
- `./occ config:app:set circles route_to_circle --value ''`

then try to enable the Circles app again ?
- `./occ app:enable circles`

**Comment by ArtificialOwl** [comment]
> @ArtificialOwl could you have a look at [#32432 (comment)](https://github.com/nextcloud/server/issues/32432#issuecomment-1222143890)? Maybe we can break the recursive structure. Otherwise I suggest dropping the `$wrapper` object from being logged.

I think this will be the next step

**Comment by dreary-ennui** [comment]
> Do you still have error if running (first):
> 
> * `./occ config:app:set circles route_to_circle --value ''`
> 
> then try to enable the Circles app again ?
> 
> * `./occ app:enable circles`

Nope! After setting route_to_circle to '' and then re-enabling Circles I am unable to recreate the issue and the clients can check in successfully.

**Comment by Verequies** [comment]
My team and I are also experiencing this issue with NC 25.0.0, running `php occ app:disable circles` fixes it.

**Comment by GreenTentacle** [comment]
Same issue as @Verequies -- same solution seems to work.  (Thanks!)

**Comment by michaelkrieger** [comment]
> Do you still have error if running (first):
> 
> * `./occ config:app:set circles route_to_circle --value ''`
> 
> then try to enable the Circles app again ?
> 
> * `./occ app:enable circles`

I ran into this when upgrading to 25 from 24 (Docker image).  **Setting the route_to_circle and then re-enabling this does NOT fix the problem**.  Logging in results in a 500 error (via web interface) and the PROPFIND 500 error on the NextCloud Windows instance.  Disabling circles and leaving it disabled is the only thing that worked.

To reiterate, circles needs to be disabled, not just the route_to_circle set and then circle re-enabled.

**Comment by r-tierney** [comment]
Same happened to me when upgrading from 24 to 25.0 just now.
using docker / postgres

I was unable to login to my admin account ( just a blank white screen after clicking login )

here is the access log with the error:
```
[Sun Oct 30 14:35:30.324279 2022] [php:error] [pid 35] [client 192.168.1.14:42380] PHP Fatal error:  Nesting level too deep - recursive dependency? in /var/www/html/lib/private/Log/ExceptionSerializer.php on line 215
```

Disabling the circle app allowed me to login
```
docker exec --user www-data nextcloud php occ app:disable circles
```
And i no longer see this error in the logs.

**Comment by Volker-K** [comment]
> Same happened to me when upgrading from 24.0.1.1 to 25.0 just now. using docker / postgres
> I was unable to login to my admin account ( just a blank white screen after clicking login )

Same here migrating from 23 to 24.0.3 as I wrote on Aug, 11.


> [Sun Oct 30 14:35:30.324279 2022] [php:error] [pid 35] [client 192.168.1.14:42380] PHP Fatal error:  Nesting level too deep - recursive dependency? in /var/www/html/lib/private/Log/ExceptionSerializer.php on line 215

Same message, same linenumber.

> docker exec --user www-data nextcloud php occ app:disable circles

We need Circles in our installation. Seems there's a problem within Circles, did you manage to fix it? Otherwise we won't be able to migrate to any version above 24.0.1

**Comment by tebruno99** [comment]
This happened to me today with a docker pull & upgrade to 25.0.0.18. Disabling circles also fixed the issue, thanks for posting a fix!

**Comment by jmhbnz** [comment]
Was also impacted by this after an upgrade to 25.  The circles disable resolved it for me as well, thanks! 🙏🏻

**Comment by Volker-K** [comment]
We definitely need Circles. Are we stuck on NC 23 now? 
What is Circles app doing wrong? Can't it be fixed?

**Comment by sselka** [comment]
We also need `circles` working and I can confirm, that disabling circles after upgrading to NC25 helps as a workaround for those not in need for `circles`.

**Comment by Verequies** [comment]
Updated to NC 25.0.1 and re-enabled circles, team is able to login successfully now. Hopefully the issue does not re-appear.

**Comment by Volker-K** [comment]
> Updated to NC 25.0.1 and re-enabled circles, team is able to login successfully now. Hopefully the issue does not re-appear.
That sounds good. However, I was not able to reproduce the error after making a 1:1 copy of the live instance from the backups I made before the failed update. 
Is there any indication of specific errors in Circles, User IDs or other things in the instance that are causing the error? Number of users? Incorrect settings of individual users? LDAP/AD users in a certain status (it takes a while after being added to the corresponding LDAP group until the user is filled with all data).
Here I only read that switching off the Circles prevents the error, and for some route_to_circles " has prevented the error even with activated Circles. For some, however, it did not. 
So the migration to 25.0.1 is also a blind flight. The problem might be solved, maybe not.

**Comment by slate17** [comment]
Had the same Issue with the Docker Image of Version 25.0.1.
Disabled Circles as a temporary fix.

**Comment by Tapchicoma** [comment]
just bumped into it after updating Nextcloud docker installation from `24.0.6.1` to `24.0.7.1`. Disabling circles helped.

**Comment by af7567** [comment]
I also started gettng this error after upgrading to 24.0.7 (from 24.0.6). I have disabled circles now to see if that fixes it.

**Comment by subtruth** [comment]
Same as @af7567 in a non-Docker, shared hosting installation. Killing circles fixed it.

Strange thing though: the admin account had its username changed to "admin" (it was never named so).

**Comment by Schimy** [comment]
same issue after upgrade NC 22.0.10 to 22.0.11 on rpi with dietpi. after `sudo -u www-data php /var/www/nextcloud/occ app:disable circles` NC works ... but the kollektive-app needs the circles-app ... :-(

**Comment by R0Wi** [comment]
I can reproduce this error on my NC25 instance. I think I first observed the issue after installing [twofactor_nextcloud_notification](https://github.com/nextcloud/twofactor_nextcloud_notification) and trying to login but I'm not completely sure. I cannot reproduce it on my dev machine but I was able to create some stacktrace on my prod instance by adding a [`debug_print_backtrace`](https://www.php.net/manual/en/function.debug-print-backtrace.php) at the beginning of https://github.com/nextcloud/server/blob/47327e66302cf96156b7803925aa4d832083024b/lib/private/Log/ExceptionSerializer.php#L212

Here is the output without parameters (`DEBUG_BACKTRACE_IGNORE_ARGS`):

```
#0  OC\Log\ExceptionSerializer->removeValuesFromArgs() called at [/var/www/nextcloud/lib/private/Log/ExceptionSerializer.php:206]
#1  OC\Log\ExceptionSerializer->OC\Log\{closure}()
#2  array_map() called at [/var/www/nextcloud/lib/private/Log/ExceptionSerializer.php:204]
#3  OC\Log\ExceptionSerializer->filterTrace() called at [/var/www/nextcloud/lib/private/Log/ExceptionSerializer.php:240]
#4  OC\Log\ExceptionSerializer->encodeTrace() called at [/var/www/nextcloud/lib/private/Log/ExceptionSerializer.php:291]
#5  OC\Log\ExceptionSerializer->serializeException() called at [/var/www/nextcloud/lib/private/Log.php:325]
#6  OC\Log->logException() called at [/var/www/nextcloud/lib/private/Log/PsrLoggerAdapter.php:208]
#7  OC\Log\PsrLoggerAdapter->info() called at [/var/www/nextcloud/lib/private/Route/Router.php:363]
#8  OC\Route\Router->generate() called at [/var/www/nextcloud/lib/private/Route/CachingRouter.php:58]
#9  OC\Route\CachingRouter->generate() called at [/var/www/nextcloud/lib/private/URLGenerator.php:103]
#10 OC\URLGenerator->linkToRoute() called at [/var/www/nextcloud/apps/circles/lib/Model/ModelManager.php:561]
#11 OCA\Circles\Model\ModelManager->generateLinkToCircle() called at [/var/www/nextcloud/apps/circles/lib/Model/Circle.php:733]
#12 OCA\Circles\Model\Circle->getUrl() called at [/var/www/nextcloud/apps/circles/lib/Model/Circle.php:855]
#13 OCA\Circles\Model\Circle->jsonSerialize()
#14 json_encode() called at [/var/www/nextcloud/apps/circles/lib/Service/CircleService.php:550]
#15 OCA\Circles\Service\CircleService->getCircles() called at [/var/www/nextcloud/apps/circles/lib/CirclesManager.php:332]
#16 OCA\Circles\CirclesManager->getCircles() called at [/var/www/nextcloud/apps/deck/lib/Service/CirclesService.php:115]
#17 OCA\Deck\Service\CirclesService->getUserCircles() called at [/var/www/nextcloud/apps/deck/lib/Db/BoardMapper.php:137]
#18 OCA\Deck\Db\BoardMapper->findBoardIds() called at [/var/www/nextcloud/apps/deck/lib/Sharing/DeckShareProvider.php:717]
#19 OCA\Deck\Sharing\DeckShareProvider->getSharedWith() called at [/var/www/nextcloud/lib/private/Share20/Manager.php:1406]
#20 OC\Share20\Manager->getSharedWith() called at [/var/www/nextcloud/apps/files_sharing/lib/MountProvider.php:99]
#21 OCA\Files_Sharing\MountProvider->getMountsForUser() called at [/var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php:134]
#22 OC\Files\Config\MountProviderCollection->addMountForUser() called at [/var/www/nextcloud/lib/private/Files/SetupManager.php:225]
#23 OC\Files\SetupManager->OC\Files\{closure}() called at [/var/www/nextcloud/lib/private/Files/SetupManager.php:317]
#24 OC\Files\SetupManager->setupForUserWith() called at [/var/www/nextcloud/lib/private/Files/SetupManager.php:226]
#25 OC\Files\SetupManager->setupForUser() called at [/var/www/nextcloud/lib/private/Files/Filesystem.php:379]
#26 OC\Files\Filesystem::initMountPoints() called at [/var/www/nextcloud/lib/private/Cache/File.php:57]
#27 OC\Cache\File->getStorage() called at [/var/www/nextcloud/lib/private/Cache/File.php:178]
#28 OC\Cache\File->gc() called at [/var/www/nextcloud/lib/base.php:851]
#29 OC::{closure}()
#30 call_user_func_array() called at [/var/www/nextcloud/lib/private/Hooks/EmitterTrait.php:106]
#31 OC\Hooks\BasicEmitter->emit() called at [/var/www/nextcloud/lib/private/Hooks/PublicEmitter.php:40]
#32 OC\Hooks\PublicEmitter->emit() called at [/var/www/nextcloud/lib/private/User/Session.php:400]
#33 OC\User\Session->completeLogin() called at [/var/www/nextcloud/lib/private/Authentication/Login/CompleteLoginCommand.php:44]
#34 OC\Authentication\Login\CompleteLoginCommand->process() called at [/var/www/nextcloud/lib/private/Authentication/Login/ALoginCommand.php:40]
#35 OC\Authentication\Login\ALoginCommand->processNextOrFinishSuccessfully() called at [/var/www/nextcloud/lib/private/Authentication/Login/LoggedInCheckCommand.php:60]
#36 OC\Authentication\Login\LoggedInCheckCommand->process() called at [/var/www/nextcloud/lib/private/Authentication/Login/ALoginCommand.php:40]
#37 OC\Authentication\Login\ALoginCommand->processNextOrFinishSuccessfully() called at [/var/www/nextcloud/lib/private/Authentication/Login/EmailLoginCommand.php:58]
#38 OC\Authentication\Login\EmailLoginCommand->process() called at [/var/www/nextcloud/lib/private/Authentication/Login/ALoginCommand.php:40]
#39 OC\Authentication\Login\ALoginCommand->processNextOrFinishSuccessfully() called at [/var/www/nextcloud/lib/private/Authentication/Login/UidLoginCommand.php:54]
#40 OC\Authentication\Login\UidLoginCommand->process() called at [/var/www/nextcloud/lib/private/Authentication/Login/ALoginCommand.php:40]
#41 OC\Authentication\Login\ALoginCommand->processNextOrFinishSuccessfully() called at [/var/www/nextcloud/lib/private/Authentication/Login/UserDisabledCheckCommand.php:58]
#42 OC\Authentication\Login\UserDisabledCheckCommand->process() called at [/var/www/nextcloud/lib/private/Authentication/Login/ALoginCommand.php:40]
#43 OC\Authentication\Login\ALoginCommand->processNextOrFinishSuccessfully() called at [/var/www/nextcloud/lib/private/Authentication/Login/PreLoginHookCommand.php:53]
#44 OC\Authentication\Login\PreLoginHookCommand->process() called at [/var/www/nextcloud/lib/private/Authentication/Login/Chain.php:108]
#45 OC\Authentication\Login\Chain->process() called at [/var/www/nextcloud/core/Controller/LoginController.php:318]
#46 OC\Core\Controller\LoginController->tryLogin() called at [/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php:225]
#47 OC\AppFramework\Http\Dispatcher->executeController() called at [/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php:133]
#48 OC\AppFramework\Http\Dispatcher->dispatch() called at [/var/www/nextcloud/lib/private/AppFramework/App.php:172]
#49 OC\AppFramework\App::main() called at [/var/www/nextcloud/lib/private/Route/Router.php:298]
#50 OC\Route\Router->match() called at [/var/www/nextcloud/lib/base.php:1047]
#51 OC::handleRequest() called at [/var/www/nextcloud/index.php:36]
```

Since there is recursion involved, it was a bit cumbersome to get the parameters logged but here is a snippet of the first stacktrace entry \#0:

```
#0 OC\Log\ExceptionSerializer->removeValuesFromArgs(
	Array ([0] => contacts.contacts.directcircle, [1] => Array ([singleId] => <ID>),[2] => 1),
	Array ([0] => OC\User\User Object ([*accountManager] => ,
[OC\User\Useruid] => robin,
[OC\User\UserdisplayName] => robin,
[OC\User\Userbackend] => OC\User\Database Object ([OC\User\Databasecache] => OCP\Cache\CappedMemoryCache Object ([OCP\Cache\CappedMemoryCachecapacity] => 512,
[OCP\Cache\CappedMemoryCachecache] => Array ([robin] => Array ([uid] => robin,
[displayname] => robin,
[password] => <REPLACED>))),
[OC\User\DatabaseeventDispatcher] => OC\EventDispatcher\EventDispatcher Object ([OC\EventDispatcher\EventDispatcherdispatcher] => Symfony\Component\EventDispatcher\EventDispatcher Object ([Symfony\Component\EventDispatcher\EventDispatcherlisteners] => Array ([OC\Authentication\Events\LoginFailed] => Array ([0] => Array ([0] => OC\EventDispatcher\ServiceEventListener Object ([OC\EventDispatcher\ServiceEventListenercontainer] => OC\Server Object ([OC\ServerwebRoot] => ,
[*appContainers] => Array ([files] => OC\AppFramework\DependencyInjection\DIContainer Object ([OC\AppFramework\DependencyInjection\DIContainermiddleWares] => Array (),
[OC\AppFramework\DependencyInjection\DIContainerserver] => OC\Server Object ( *RECURSION*,
[OC\AppFramework\Utility\SimpleContainercontainer] => Pimple\Container Object ([Pimple\Containervalues] => Array ([AppName] => files,
[urlParams] => Array (),
[Request] => Closure Object (),
[appName] => Closure Object (),
[webRoot] => Closure Object (),
[userId] => Closure Object (),
[OCP\AppFramework\Http\IOutput] => Closure Object (),
[OCP\Files\Folder] => Closure Object (),
[OCP\Files\IAppData] => Closure Object (),
[OCP\IL10N] => OC\L10N\LazyL10N Object ([OC\L10N\LazyL10Nl] => ,
[OC\L10N\LazyL10Nfactory] => Closure Object ()),
[Psr\Log\LoggerInterface] => Closure Object (),
[OCP\ILogger] => Closure Object (),
[OCP\IServerContainer] => Closure Object (),
[ServerContainer] => Closure Object (),
[OCP\WorkflowEngine\IManager] => Closure Object (),
[Psr\Container\ContainerInterface] => Closure Object (),
[OCP\AppFramework\IAppContainer] => Closure Object (),
[UserId] => Closure Object (),
[WebRoot] => Closure Object (),
[OC_Defaults] => Closure Object (),
[Protocol] => Closure Object (),
[Dispatcher] => Closure Object (),
[corsMethods] => PUT,
 POST,
 GET,
 DELETE,
 PATCH,
[corsAllowedHeaders] => Authorization,
 Content-Type,
 Accept,
[corsMaxAge] => 1728000,
[MiddlewareDispatcher] => Closure Object (),
[OC\AppFramework\Middleware\MiddlewareDispatcher] => Closure Object (),
[OCP\AppFramework\Services\IAppConfig] => Closure Object (),
[OCP\AppFramework\Services\IInitialState] => Closure Object (),
[OCA\Files\AppInfo\Application] => OCA\Files\AppInfo\Application Object ([OCP\AppFramework\Appcontainer] => OC\AppFramework\DependencyInjection\DIContainer Object ( *RECURSION*),
[APIController] => Closure Object (),
[OCA\Files\Service\TagService] => Closure Object ()),
[Pimple\Containerfactories] => SplObjectStorage Object (),
[Pimple\Containerprotected] => SplObjectStorage Object (),
[Pimple\Containerfrozen] => Array ([OCP\IL10N] => 1),
[Pimple\Containerraw] => Array ([OCP\IL10N] => Closure Object ()),
[Pimple\Containerkeys] => Array ([AppName] => 1,
[urlParams] => 1,
[Request] => 1,
[appName] => 1,
[webRoot] => 1,
[userId] => 1,
[OCP\AppFramework\Http\IOutput] => 1,
[OCP\Files\Folder] => 1,
[OCP\Files\IAppData] => 1,
[OCP\IL10N] => 1,
[Psr\Log\LoggerInterface] => 1,
[OCP\ILogger] => 1,
[OCP\IServerContainer] => 1,
[ServerContainer] => 1,
[OCP\WorkflowEngine\IManager] => 1,
[Psr\Container\ContainerInterface] => 1,
[OCP\AppFramework\IAppContainer] => 1,
[UserId] => 1,
[WebRoot] => 1,
[OC_Defaults] => 1,
[Protocol] => 1,
[Dispatcher] => 1,
[corsMethods] => 1,
[corsAllowedHeaders] => 1,
[corsMaxAge] => 1,
[MiddlewareDispatcher] => 1,
[OC\AppFramework\Middleware\MiddlewareDispatcher] => 1,
[OCP\AppFramework\Services\IAppConfig] => 1,
[OCP\AppFramework\Services\IInitialState] => 1,
[OCA\Files\AppInfo\Application] => 1,
[APIController] => 1,
[OCA\Files\Service\TagService] => 1))),
[activity] => OC\AppFramework\DependencyInjection\DIContainer Object ([OC\AppFramework\DependencyInjection\DIContainermiddleWares] => Array (),
[OC\AppFramework\DependencyInjection\DIContainerserver] => OC\Server Object ( *RECURSION*,
[OC\AppFramework\Utility\SimpleContainercontainer] => Pimple\Container Object ([Pimple\Containervalues] => Array ([AppName] => activity,
[urlParams] => Array (),
[Request] => Closure Object (),
[appName] => Closure Object (),
[webRoot] => Closure Object (),
[userId] => Closure Object (),
[OCP\AppFramework\Http\IOutput] => Closure Object (),
[OCP\Files\Folder] => Closure Object (),
[OCP\Files\IAppData] => Closure Object (),
[OCP\IL10N] => Closure Object (),
[Psr\Log\LoggerInterface] => Closure Object (),
[OCP\ILogger] => Closure Object (),
[OCP\IServerContainer] => Closure Object (),
[ServerContainer] => Closure Object (),
[OCP\WorkflowEngine\IManager] => Closure Object (),
[Psr\Container\ContainerInterface] => Closure Object (),
[OCP\AppFramework\IAppContainer] => Closure Object (),
[UserId] => Closure Object (),
[WebRoot] => Closure Object (),
[OC_Defaults] => Closure Object (),
[Protocol] => Closure Object (),
[Dispatcher] => Closure Object (),
[corsMethods] => PUT,
 POST,
 GET,
 DELETE,
 PATCH,
[corsAllowedHeaders] => Authorization,
 Content-Type,
 Accept,
[corsMaxAge] => 1728000,
[MiddlewareDispatcher] => Closure Object (),
[OC\AppFramework\Middleware\MiddlewareDispatcher] => Closure Object (),
[OCP\AppFramework\Services\IAppConfig] => Closure Object (),
[OCP\AppFramework\Services\IInitialState] => Closure Object (),
[OCA\Activity\AppInfo\Application] => OCA\Activity\AppInfo\Application Object ([OCP\AppFramework\Appcontainer] => OC\AppFramework\DependencyInjection\DIContainer Object ( *RECURSION*),
[ActivityDBConnection] => Closure Object (),
[ActivityConnectionAdapter] => Closure Object (),
[OCA\Activity\Data] => Closure Object (),
[OCA\Activity\MailQueueHandler] => Closure Object (),
[OC\Files\View] => Closure Object (),
[OCA\Activity\Listener\SetUserDefaults] => Closure Object ()),
[Pimple\Containerfactories] => SplObjectStorage Object (),
[Pimple\Containerprotected] => SplObjectStorage Object (),
[Pimple\Containerfrozen] => Array (),
[Pimple\Containerraw] => Array (),
[Pimple\Containerkeys] => Array ([AppName] => 1,
[urlParams] => 1,
[Request] => 1,
[appName] => 1,
[webRoot] => 1,
[userId] => 1,
[OCP\AppFramework\Http\IOutput] => 1,
[OCP\Files\Folder] => 1,
[OCP\Files\IAppData] => 1,
[OCP\IL10N] => 1,
[Psr\Log\LoggerInterface] => 1,
[OCP\ILogger] => 1,
[OCP\IServerContainer] => 1,
[ServerContainer] => 1,
[OCP\WorkflowEngine\IManager] => 1,
[Psr\Container\ContainerInterface] => 1,
[OCP\AppFramework\IAppContainer] => 1,
[UserId] => 1,
[WebRoot] => 1,
[OC_Defaults] => 1,
[Protocol] => 1,
[Dispatcher] => 1,
[corsMethods] => 1,
[corsAllowedHeaders] => 1,
[corsMaxAge] => 1,
[MiddlewareDispatcher] => 1,
[OC\AppFramework\Middleware\MiddlewareDispatcher] => 1,
[OCP\AppFramework\Services\IAppConfig] => 1,
[OCP\AppFramework\Services\IInitialState] => 1,
[OCA\Activity\AppInfo\Application] => 1,
[ActivityDBConnection] => 1,
[ActivityConnectionAdapter] => 1,
[OCA\Activity\Data] => 1,
[OCA\Activity\MailQueueHandler] => 1,
[OC\Files\View] => 1,
[OCA\Activity\Listener\SetUserDefaults] => 1))),
[adminaudit] => OC\AppFramework\DependencyInjection\DIContainer Object ([OC\AppFramework\DependencyInjection\DIContainermiddleWares] => Array (),
[OC\AppFramework\DependencyInjection\DIContainerserver] => OC\Server Object ( *RECURSION*,
[OC\AppFramework\Utility\SimpleContainercontainer] => Pimple\Container Object ([Pimple\Containervalues] => Array ([AppName] => admin_audit,
[urlParams] => Array (),
[Request] => Closure Object (),
[appName] => Closure Object (),
[webRoot] => Closure Object (),
[userId] => Closure Object (),
[OCP\AppFramework\Http\IOutput] => Closure Object (),
[OCP\Files\Folder] => Closure Object (),
[OCP\Files\IAppData] => Closure Object (),
[OCP\IL10N] => Closure Object (),
[Psr\Log\LoggerInterface] => Closure Object (),
[OCP\ILogger] => Closure Object (),
[OCP\IServerContainer] => OC\Server Object ( *RECURSION*,
[ServerContainer] => Closure Object (),
[OCP\WorkflowEngine\IManager] => Closure Object (),
[Psr\Container\ContainerInterface] => Closure Object (),
[OCP\AppFramework\IAppContainer] => Closure Object (),
[UserId] => Closure Object (),
[WebRoot] => Closure Object (),
[OC_Defaults] => Closure Object (),
[Protocol] => Closure Object (),
[Dispatcher] => Closure Object (),
[corsMethods] => PUT,
 POST,
 GET,
 DELETE,
 PATCH,
[corsAllowedHeaders] => Authorization,
 Content-Type,
 Accept,
[corsMaxAge] => 1728000,
[MiddlewareDispatcher] => Closure Object (),
[OC\AppFramework\Middleware\MiddlewareDispatcher] => Closure Object (),
[OCP\AppFramework\Services\IAppConfig] => Closure Object (),
[OCP\AppFramework\Services\IInitialState] => Closure Object (),
[OCA\AdminAudit\AppInfo\Application] => OCA\AdminAudit\AppInfo\Application Object ([*logger] => ,
[OCP\AppFramework\Appcontainer] => OC\AppFramework\DependencyInjection\DIContainer Object ( *RECURSION*), <MORE_VALUES...>)))))))))))))))))))))
```

IMO the circle app is clearly involved here, since we can see that in the stacktrace and in the first parameter (`$args`) of the call ` OC\Log\ExceptionSerializer->removeValuesFromArgs`. The main problem though seems to be the second parameter (`$values`) which is of type `OC\User\User` and contains references to  `OC\AppFramework\DependencyInjection\DIContainer`, where the \*RECURSION\* seems to come from.

Please let me know if there is anything else to help getting this fixed.

Btw. @ChristophWurst can confirm that https://github.com/nextcloud/server/pull/33501 does not fix the problem since the error cannot be caught that way.

**Comment by nilshellerhoff** [comment]
Just wanted to comment since I am encountering this issue as well.
- Nextcloud 24.0.7 (updated from 24.0.6 yesterday, maybe that's relevant)
- user could not login, would get a blank page

Either removing the user from all groups or disabling the circles app remedies the issue.

**Comment by nmapx** [comment]
Had the same issue, disabling circles app solved the issue
```bash
./occ app:disable circles
```

**Comment by Pudding26** [comment]
What nextcloud version is currently stable with circles, as we can not really work without.

**Comment by meckiemac** [comment]
run into the same issue without changing the system. A prior updated to 25 run fine and I could work for a while. Disabling circles helped as temporary solution.

**Comment by Pudding26** [comment]
> run into the same issue without changing the system. A prior updated to 25 run fine and I could work for a while. Disabling circles helped as temporary solution.

kk, that really is weird then. I was just wondering if there is a way to continue using circles in the meantime. By my understanding the problem is apperieng at least since may 22 and since it is such a "core" feature of nc I would have expected way more users with issues unless there are versions that are not affected by this bug or a lasting fix for the issue. But i guess i have to continue digging (:

**Comment by nilshellerhoff** [comment]
@Pudding26 check this reply by @ArtificialOwl 

https://github.com/nextcloud/circles/issues/1197#issuecomment-1328869536

> You should be able to bypass the issue by running this command:

> ```./occ config:app:set circles route_to_circles --value ''```

**Comment by Schimy** [comment]
> @Pudding26 check this reply by @ArtificialOwl
> 
> [nextcloud/circles#1197 (comment)](https://github.com/nextcloud/circles/issues/1197#issuecomment-1328869536)
> 
> > You should be able to bypass the issue by running this command:
> 
> > `./occ config:app:set circles route_to_circles --value ''`

doesn't work for my ... :-(
got the same issue

**Comment by Pudding26** [comment]
> @Pudding26 check this reply by @ArtificialOwl
> 
> [nextcloud/circles#1197 (comment)](https://github.com/nextcloud/circles/issues/1197#issuecomment-1328869536)
> 
> > You should be able to bypass the issue by running this command:
> 
> > `./occ config:app:set circles route_to_circles --value ''`

Did not do it for me either.

**Comment by R0Wi** [comment]
For everyone who cannot disable the `circles` app, here might be a **temporary** workaround:
try first to apply the patch from https://github.com/nextcloud/server/commit/e2d4d198ffc3867ea7d7fa6b9068d34f8b53dfa7.patch (trying to only accept sensitive data logging in the case where log message comes from `circles` app).

If that does not work, try https://github.com/nextcloud/server/commit/250553e535b20804d3591b0906e133ad37fbf3e3.patch (generally letting sensitive data be logged)

```bash
# Please adjust path as needed
wget https://github.com/nextcloud/server/commit/e2d4d198ffc3867ea7d7fa6b9068d34f8b53dfa7.patch -O- | patch -p1 --directory=/var/www/nextcloud
```

⚠️ Since the patche disable the removal of sensitive data from log messages, this will lead to sensitive data like passwords being logged to `nextcloud.log`. Please ensure that you're the only one who can access the logfile and that you regularly clear it! This is only a temporary workaround and not meant to be the fix of this issue!⚠️ 

Feedback appreciated

**Comment by Pudding26** [comment]
@R0Wi 

First thank you very much foryour patch!

I do have some issues deploying it though. I have NC installed via Docker and tried the following:

`sudo docker exec -ti --user www-data nextcloud-app-1 curl https://github.com/nextcloud/server/commit/e2d4d198ffc3867ea7d7fa6b9068d34f8b53dfa7.patch | git apply`

=> error: patch failed: lib/private/Log/ExceptionSerializer.php:210
error: lib/private/Log/ExceptionSerializer.php: patch does not apply

And also on the host server wihin the nextcloud folder:

`root@h2992584:/var/lib/docker/volumes/nextcloud_nextcloud/_data# curl https://github.com/nextcloud/server/commit/250553e535b20804d3591b0906e133ad37fbf3e3.patch | git apply`

What is it I am missing?

**Comment by R0Wi** [comment]
Not sure if `git apply` works without an initialized git repository. Since the official Docker image does not contain a git repo, I used the `patch` command. The following worked for me with the official NC 25 Docker image:

```bash
docker exec -it --user www-data nextcloud-app curl -q https://github.com/nextcloud/server/commit/e2d4d198ffc3867ea7d7fa6b9068d34f8b53dfa7.patch | patch -p1
```

**Comment by Pudding26** [comment]
Sorry to ask once more, running your command leads me to:

**Comment by R0Wi** [comment]
Okay that's weird. For me this is working as expected. To not overload this conversation with specific messages, could you please send my a PM? Would be glad to help you 👍

**Comment by ArtificialOwl** [comment]
I am sorry, I got the settings wrong, please try this:

>      ./occ config:app:set circles route_to_circle --value ''

**Comment by R0Wi** [comment]
@ArtificialOwl this does not work for me. I think it's because the value is checked for empty here: [route_to_circle ](https://github.com/nextcloud/circles/blob/3beecabfee1cfa6a532bea0e011a88e203f9d7d7/lib/Service/ConfigService.php#L243).

## Worarounds that work for me

1. Disable the `circles` app OR
2. Run `php occ config:app:set circles route_to_circle --value 'files.view.index'` (to be run as `www-data`) OR
3. Install and enable [`contacts`](https://apps.nextcloud.com/apps/contacts) app

## Sideeffects for the workarounds

1. Circles won't be there (obviously)
2. Generated circle links point to the Nextcloud index page (instead of jumping to the contacts page)
3. none

## Some technical background

The trace, like I observed it, is the following:

1. ` OCA\Circles\Model\Circle->jsonSerialize()` is called, which invokes `OCA\Circles\Model\Circle->getUrl()`
2. [`OC\Route\Router->generate()`](https://github.com/nextcloud/server/blob/2adb1f85e655604aee9b88c2b147859418adc984/lib/private/Route/Router.php#L337) is called with the [`circles` app config value of `route_to_circle`](https://github.com/nextcloud/circles/blob/3beecabfee1cfa6a532bea0e011a88e203f9d7d7/lib/Service/ConfigService.php#L243). If that value is empty, the default constant [`contacts.contacts.directcircle`](https://github.com/nextcloud/circles/blob/3beecabfee1cfa6a532bea0e011a88e203f9d7d7/lib/Service/ConfigService.php#L179) is used for the `$name` parameter of `OC\Route\Router->generate()`
3. If the `contacts` app is not installed on the system, the route `contacts.contacts.directcircle` cannot be resolved, which throws a `RouteNotFoundException`. `Router` will try to log this exception [here](https://github.com/nextcloud/server/blob/2adb1f85e655604aee9b88c2b147859418adc984/lib/private/Route/Router.php#L363)
4. Logging of the exception invokes the `OC\Log\ExceptionSerializer`, which tries to remove sensitive values from the log message before logging
5. The native recursion exception occures [here](https://github.com/nextcloud/server/blob/2adb1f85e655604aee9b88c2b147859418adc984/lib/private/Log/ExceptionSerializer.php#L215) because `$values` contains one or more objects (like `OC\User\User`) which contain recursive references and cannot be used for the `in_array`-check (btw.: I tried to rewrite it to `foreach` but that also failed)

## What needs to be fixed/implemented (IMO)

**In the `circles` app:** only link to the `contacts` app if the `contacts` app is installed on the system. Otherwise use some system independent default route for https://github.com/nextcloud/circles/blob/3beecabfee1cfa6a532bea0e011a88e203f9d7d7/lib/Service/ConfigService.php#L179

**In NC core:** check if there is a way to circumvent that (recursive) objects are passed inside the array of `$values` in [`removeValuesFromArgs`](https://github.com/nextcloud/server/blob/2adb1f85e655604aee9b88c2b147859418adc984/lib/private/Log/ExceptionSerializer.php#L212). (The only way I managed this currently is to filter objects in general and only allow simple types like strings etc. but that might not be desireable)

**Comment by Volker-K** [comment]
> ## Worarounds that work for me
> [...]
> 3. Install and enable [`contacts`](https://apps.nextcloud.com/apps/contacts) app

In our case, "Contacs" is enabled since it's the UI for managing Circles since NC 21 (or 22?)

_Otherwise_, there are some outdated Apps (witeboard e.g.) placed in config.php within the array app_install_override and are not installed after the update. Since I restored the old config.php when rolling back the failed upgrade, I can't see if it was like this. 

It _might_ have possibly happened with contacts in case there was just some foobar version problem on 2022-08-09 when I tried to upgrade. So far it would be obvious why I couldn't reproduce the error. 

I just disabled Contacts in our stageing environment and got the error. I think it's getting clearer what happend and how to prevent it.

**Comment by ArtificialOwl** [comment]
> @ArtificialOwl this does not work for me. I think it's because the value is checked for empty here: [route_to_circle ](https://github.com/nextcloud/circles/blob/3beecabfee1cfa6a532bea0e011a88e203f9d7d7/lib/Service/ConfigService.php#L243).

Yes, you are right; but _how was it working before ?..._

Next release should avoid calling this method when generating an exception, but I will see to add a check on the availability of the app before generating the url from the route.

Thanks for your deep report

**Comment by R0Wi** [comment]
> Yes, you are right; but how was it working before ?...

Well, that's a question I cannot answer directly. The only thing that I can tell is, that for example on my DEV machine I cannot reproduce the error even when trying to replicate my PROD setup. Could imagine that it somehow depends on how exactly the arguments/objects inside of `$values` are structured, when giving them to the `in_array`-check. That would be something for NC core but like I said it's quite hard to reproduce.

Generally speaking: when fixing the log problem inside the `circles`-app, it would work for this particular problem discussed here. But nevertheless in general it could somehow happen, that the [removeValuesFromArgs](https://github.com/nextcloud/server/blob/2adb1f85e655604aee9b88c2b147859418adc984/lib/private/Log/ExceptionSerializer.php#L212) function is fed with "recursive objects", which IMO should be avoided because it can paralyze the whole NC system.

**Comment by Volker-K** [comment]
> > Yes, you are right; but how was it working before ?...
> Well, that's a question I cannot answer directly. The only thing that I can tell is, that for example on my DEV machine I cannot reproduce the error even when trying to replicate my PROD setup. 

Same here, but I also didn't check for activated/updated/deactivated Apps after the error occurred since I had to bring the live system online again. If I had any hint which App might be the source of the error I would have checked it on CLI.

**Comment by magikmw** [comment]
Updating from 24.0.2 to 24.0.7 *likely* caused this on our instance. We use LDAP as a user backend, along with a group added to all users by default. Disabling circles did help as a workaround.

Maybe helpful also, it didn't affect *my* account, one of the first on the instance, but it did accounts that never logged in before or perhaps newer than some date. I haven't established what's the oldest account affected, and it's likely impossible now.

**Comment by JannF** [comment]
> Had this error _when logging in_ (instead of being logged in, getting a 500 and blank page) with a 25.0.1 instance, no special configuration, and disabling the Circles app made it work again. Did not debug it further than that.

+1 on Nextcloud 25.0.2

**Comment by PatientLightning** [comment]
Also had this issue when logging in, getting a 500 and blank page, on a NC23 docker instance after an upgrade from a NC22, then again on a NC24.0.8 after trying to just upgrade my way past it. Then again on NC25.0.2 which I tried just for fun.

I found this thread and disabled circles and I could log in again for each NC24 and NC25.

Hopefully someone will understand what causes this and can help get it sorted. For now I'll just keep circles disabled I guess.

My log showed 
`,"remoteAddr":"######","user":"######","app":"PHP","method":"POST","url":"/login","message":"Nesting level too deep - recursive dependency? at /var/www/html/lib/private/Log/ExceptionSerializer.php#215"`
and is how I found this thread and the solution to try to disable circles

**Comment by PhrozenByte** [comment]
> It might also be related to [#23429 (comment)](https://github.com/nextcloud/server/issues/23429#issuecomment-708901668)

Just for the record, this is not just related to #23429, this issue is a duplicate of #23429. It's the same issue with just a different error message.

The cause of this is a bug in [`ExceptionSerializer::removeValuesFromArgs()`](https://github.com/nextcloud/server/blob/2adb1f85e655604aee9b88c2b147859418adc984/lib/private/Log/ExceptionSerializer.php#L212) not handling variable references properly. If you want to recursively iterate arbitrary input, you must account for references (i.e. arrays referencing itself, e.g. `$a = ["foo"]; $a[] = &$a;`). This causes an infinite loop until either the memory limit or XDebug's recursion limit is reached.

Simplest solution is to limit recursion depth. Since we're talking about an exception serializer whose job is to process exceptions for human display, we don't need arbitrary deep stack traces anyway... The funny thing is: `ExceptionSerializer` already limits recursion. But for some reason someone chose [to filter](https://github.com/nextcloud/server/blob/2adb1f85e655604aee9b88c2b147859418adc984/lib/private/Log/ExceptionSerializer.php#L226) sensitive information separately [prior to](https://github.com/nextcloud/server/blob/2adb1f85e655604aee9b88c2b147859418adc984/lib/private/Log/ExceptionSerializer.php#L226) the recursion depth checks in [`ExceptionSerializer::encodeArg()`](https://github.com/nextcloud/server/blob/2adb1f85e655604aee9b88c2b147859418adc984/lib/private/Log/ExceptionSerializer.php#L235). Doesn't make much sense and causes these issues.

Calling `ExceptionSerializer::removeValuesFromArgs()` should be moved to `ExceptionSerializer::encodeArg()`. Then the issue will disappear.

I was just thinking about an quick fix, but honestly, `ExceptionSerializer` is a mess. It iterates the stack trace and all arguments multiple times and following what the code does is very hard. The methods seem to be in random order. Why? This class should be rewritten from scratch. Unfortunately I don't have enough time for this...

Just for the record: PHP now comes with native support to redact sensitive information from stack traces in a cradle to grave approach. See https://php.watch/versions/8.2/backtrace-parameter-redaction. Even though this is also possible without native support (requires to wrap any sensitive information into objects, but also requires to change how this sensitive information is used elsewhere), it makes things way easier. When Nextcloud drops support for PHP 8.1 and earlier, we should think about using PHP's new native feature insead.

**Comment by samtuke** [comment]
FYI I just upgraded to NC 25.0.2 and experienced this error. The workaround of disabling the circles app via CLI solved the issue.

**Comment by solracsf** [comment]
Feel free to try https://github.com/nextcloud/server/pull/35970

**Comment by R0Wi** [comment]
Applied the patch from the first commit of the mentioned PR

```
wget -q -O- https://github.com/nextcloud/server/commit/330523b7995db8702c7fb980c393d171d947ff94.patch | patch -p1
```

**For me the error has gone** after patching, thank you @juliushaertl ! 

Note: I also noticed that the error just occures sometimes on my system (so I cannot reproduce the error constantly). So a few other testers would definately make sense :+1:

**Comment by juliushaertl** [comment]
> Note: I also noticed that the error just occures sometimes on my system (so I cannot reproduce the error constantly). So a few other testers would definately make sense.

I noticed this being caused by a info log message (that was not logged in my logs) but caused the error and then the failure. For my case was caused by https://github.com/nextcloud/circles/pull/1233 which also only happened from time to time due to caching being in place for the router.

**Comment by R0Wi** [comment]
Thanks for the hint! Would really be great to have a sample Exception/message which causes the problem. A testcase could then proove that this won't happen again. Already tried to construct such a thing but with no luck so far 😢

**Comment by lukas-staab** [comment]
I had the same issue, but only the calendar and file dav sync did not work anymore. Webinterface worked fine for me. Disabling Circles worked.

**Comment by dahafner** [comment]
Had the same issue when upgrading from 24 to 25. Disabling the app Circles fixed the problem for the moment.

**Comment by juliushaertl** [comment]
Closing as https://github.com/nextcloud/server/pull/35970 was merged and the fix itself back ported for the next 24/25 maintenance release.

**Comment by R0Wi** [comment]
So the fix is to come with `25.0.4` and `24.0.10` 🚀

**Comment by vgoineau** [comment]
Hi, 

Got the same error when user logged in. The issue was two-factor authentification. When I user is created without TOTP enable and then you add group user to force TOTP this error happen : PHP Fatal error: Nesting level too deep - recursive dependency? Looks like when we force user or group after user creation it create this error. 

My fix : 

1) remove group or user from Two Authentification enforced
2) log with your user credential back to nextcloud
3) enable TOTP in user settings
4) go back to admin setting page and enforce your 2auth back. 

Hope this help !

**Comment by TheIceMagmaCube** [comment]
I just had the same error.
I couldn't log-in. Manually deleting Circle App files in the container volume did the trick.

**Comment by handkerchief333** [comment]
I can confirm everything from @TheIceMagmaCube. Same is true for me.

**Comment by rawtaz** [comment]
> Manually deleting Circle App files in the container volume did the trick.

Couldn't you just *disable* the Circles app?

**Comment by handkerchief333** [comment]
> > Manually deleting Circle App files in the container volume did the trick.
> 
> Couldn't you just _disable_ the Circles app?

Oh, I misread the comment. In my case, disabling the Circles app actually did the trick.

**Comment by R0Wi** [comment]
If possible, please update to the latest Nextcloud version `25.0.4`. This should also fix the problem. If not, please report again 👍
