### ISSUE TITLE
Method OC_L10N_String and vsprintf(): Too few arguments

### ISSUE THREAD

**Issue by EazyDefcon** [nextcloud/server#3309]
### Steps to reproduce
Browsing from apps menu to admin in webbrowser
### Expected behaviour
No Error messages.
### Actual behaviour
Get PHP error messages:
Method OC_L10N_String::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#85
and
vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/legacy/l10n/string.php#72

### Server configuration
**Operating system**: Ubuntu Server 16.04

**Web server**: Apache/2.4.18

**Database**: mysqlnd 5.0.12-dev

**PHP version**: 7.0.13

**Nextcloud version**: 11.0.1

**Where did you install Nextcloud from**: From Nextcloud site

**Signing status:**
<details>
<summary>Signing status</summary>

```
I get routed to files. Normal behavior?
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - direct_menu: 0.10.0 
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1 
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2 
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0 
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - files_videoplayer
  - firstrunwizard
  - nextcloud_announcements
  - ownpad
  - richdocuments
  - survey_client
  - systemtags
  - templateeditor
  - updatenotification
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ochqqzuu1rav",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my.secret.com",
            "MY_LOCAL_IP",
            "MY_SECRET_IP"
        ],
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0,
            "dbindex": 0
        },
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/brons.dynu.com\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Stockholm",
        "installed": true
    }
}

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** No
**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** Webdav

### Client configuration
**Browser:** Firefox 50.0.2

**Operating system:** Debian 8.1

#### Web server error log
<details>
<summary>Web server error log</summary>
```

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
PHP Error Messages:
Method OC_L10N_String::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#85
vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/legacy/l10n/string.php#72

**Comment by nickvergessen** [comment]
Which language do you use?

**Comment by EazyDefcon** [comment]
I use Swedish

**Comment by EazyDefcon** [comment]
After you asked about what language I use, I tested some more with changing to English and Swedish back and forth . 

It seems the error messages comes when I change to Swedish > go to apps >  go directly to admin from the to right menu. If I change to English and try the same (go to apps > right top menu > admin) the error stops.

**Comment by nickvergessen** [comment]
Can't reproduce so it seems this is already fixed in the latest swedish strings.

So I will close this, please test this once the next RC is out.

**Comment by tflidd** [comment]
I still have this problem on NC 11.0.2 and Passman 2.1.1:
https://github.com/nextcloud/passman/issues/209
https://github.com/nextcloud/passman/issues/238

**Comment by dartcafe** [comment]
I get this error when entering Passman. 
![grafik](https://user-images.githubusercontent.com/26707476/29090396-ba6d6506-7c7f-11e7-887f-936afbda6b5b.png)
After that I hav the same entries in the log:

Error | PHP | Method  OC_L10N_String::__toString() must return a string value at  /www/htdocs/nextcloud/lib/private/L10N/L10N.php#85

Error | PHP | vsprintf():  Too few arguments at  /www/htdocs/nextcloud/lib/private/legacy/l10n/string.php#72
-- | -- | --

**Comment by crashwriter** [comment]
same here like @dartcafe 

Error | PHP | Method OC_L10N_String::__toString() must return a string value at
/.../lib/private/L10N/L10N.php#85 |
-- | -- | -- | --
Error | PHP | vsprintf(): Too few arguments at
/.../lib/private/legacy/l10n/string.php#72 |

Nexcloud: 12.0.2
Passman: 2.1.4
