### ISSUE TITLE
Request shared secred for federated sharing failed

### ISSUE THREAD

**Issue by mightyBroccoli** [nextcloud/server#3380]
### Steps to reproduce
1. share some file to different nextcloud server
2. watch log file

### Actual behaviour
GuzzleHttp\Exception\ClientException: Client error response [url] https://differentserver.com/ocs/v2.php/apps/federation/api/v1/request-shared-secret?format=json [status code] 400 [reason phrase] Bad request
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/guzzle/src/Subscriber/HttpError.php - line 32: GuzzleHttp\Exception\RequestException create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/guzzle/src/Event/Emitter.php - line 108: GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 91: GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/var/www/magicbroccoli.de/nextcloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 150: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
/var/www/magicbroccoli.de/nextcloud/lib/private/Http/Client/Client.php - line 203: GuzzleHttp\Client->post('https //nextclo...', Array)
/var/www/magicbroccoli.de/nextcloud/apps/federation/lib/BackgroundJob/RequestSharedSecret.php - line 154: OC\Http\Client\Client->post('https //nextclo...', Array)
/var/www/magicbroccoli.de/nextcloud/lib/private/BackgroundJob/Job.php - line 53: OCA\Federation\BackgroundJob\RequestSharedSecret->run(Array)
/var/www/magicbroccoli.de/nextcloud/apps/federation/lib/BackgroundJob/RequestSharedSecret.php - line 135: OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
/var/www/magicbroccoli.de/nextcloud/apps/federation/lib/BackgroundJob/RequestSharedSecret.php - line 120: OCA\Federation\BackgroundJob\RequestSharedSecret->parentExecute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
/var/www/magicbroccoli.de/nextcloud/cron.php - line 128: OCA\Federation\BackgroundJob\RequestSharedSecret->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
{main}

### Server configuration
**Operating system**: Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64

**Web server:** Apache (apache2handler)

**Database:** mysql 5.5.54

**PHP version:** 7.0.15-1~dotdeb+8.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, igbinary, msgpack, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mcrypt, memcached, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 11.0.1 (stable) - 11.0.1.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated all the way from owncloud 9

**Where did you install Nextcloud from:** 
the official website 

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.4.1
 - admin_audit: 1.1.0
 - announcementcenter: 3.0.0
 - apporder: 0.3.3
 - audioplayer: 1.4.1
 - calendar: 1.5.0
 - comments: 1.1.0
 - contacts: 1.5.2
 - dav: 1.1.1
 - direct_menu: 0.10.0
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_automatedtagging: 1.1.1
 - files_downloadactivity: 1.0.0
 - files_external: 1.1.2
 - files_pdfviewer: 1.0.1
 - files_retention: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - news: 10.1.0
 - nextcloud_announcements: 1.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - previewgenerator: 1.0.1
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - systemtags: 1.1.3
 - templateeditor: 0.2
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - twofactor_totp: 1.0.0
 - updatenotification: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - encryption
 - external
 - files_accesscontrol
 - survey_client
 - user_external
 - user_ldap
 - user_saml
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "ocdwzxwi729i",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.magicbroccoli.de"
    ],
    "datadirectory": "\/var\/www\/magicbroccoli.de\/data",
    "version": "11.0.1.2",
    "installed": true,
    "cipher": "AES-256-CFB",
    "dbtype": "mysql",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "default_language": "de",
    "defaultapp": "files",
    "enable_avatars": true,
    "allow_user_to_change_display_name": true,
    "remember_login_cookie_lifetime": 864000,
    "session_lifetime": 86400,
    "auth.bruteforce.protection.enabled": true,
    "updatechecker": true,
    "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
    "updater.release.channel": "stable",
    "upgrade.disable-web": false,
    "has_internet_connection": true,
    "check_for_working_htaccess": true,
    "check_for_working_webdav": true,
    "check_for_working_wellknown_setup": true,
    "appstoreenabled": true,
    "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v0",
    "appstore.experimental.enabled": true,
    "appcodechecker": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "\/var\/run\/redis\/redis.sock",
        "port": 0,
        "timeout": 0
    },
    "overwrite.cli.url": "https:\/\/cloud.magicbroccoli.de",
    "htaccess.RewriteBase": "\/",
    "trashbin_retention_obligation": "auto, 60",
    "versions_retention_obligation": "auto",
    "activity_expire_days": 80,
    "filesystem_check_changes": 0,
    "theme": "",
    "maintenance": false,
    "singleuser": false,
    "data-fingerprint": "16b42c01070fc24c2086fb974eda1d16",
    "mail_smtpmode": "smtp",
    "mail_from_address": "nextcloud",
    "mail_domain": "magicbroccoli.de",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "mail.server-speed.net",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "logdateformat": "d.m.Y - H:i:s",
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 52428800,
    "loglevel": 2,
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "enable_previews": true,
    "preview_max_x": 1024,
    "preview_max_y": 1024,
    "preview_max_filesize_image": 25,
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to pdf --outdir "
}
```
</details>

**Are you using external storage, if yes which one:** Array
(
    [1] => \OC\Files\Storage\DAV
    [2] => \OCA\Files_External\Lib\Storage\OwnCloud
    [3] => \OCA\Files_External\Lib\Storage\Dropbox
    [4] => \OCA\Files_External\Lib\Storage\Google

)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
GuzzleHttp\Exception\ClientException: Client error response [url] https://nextcloud-whv.gew-wilhelmshaven.de/ocs/v2.php/apps/federation/api/v1/request-shared-secret?format=json [status code] 400 [reason phrase] Bad request
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/guzzle/src/Subscriber/HttpError.php - line 32: GuzzleHttp\Exception\RequestException create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/guzzle/src/Event/Emitter.php - line 108: GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 91: GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/var/www/magicbroccoli.de/nextcloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/var/www/magicbroccoli.de/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 150: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
/var/www/magicbroccoli.de/nextcloud/lib/private/Http/Client/Client.php - line 203: GuzzleHttp\Client->post('https //nextclo...', Array)
/var/www/magicbroccoli.de/nextcloud/apps/federation/lib/BackgroundJob/RequestSharedSecret.php - line 154: OC\Http\Client\Client->post('https //nextclo...', Array)
/var/www/magicbroccoli.de/nextcloud/lib/private/BackgroundJob/Job.php - line 53: OCA\Federation\BackgroundJob\RequestSharedSecret->run(Array)
/var/www/magicbroccoli.de/nextcloud/apps/federation/lib/BackgroundJob/RequestSharedSecret.php - line 135: OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
/var/www/magicbroccoli.de/nextcloud/apps/federation/lib/BackgroundJob/RequestSharedSecret.php - line 120: OCA\Federation\BackgroundJob\RequestSharedSecret->parentExecute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
/var/www/magicbroccoli.de/nextcloud/cron.php - line 128: OCA\Federation\BackgroundJob\RequestSharedSecret->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
{main}
	```
</details>

**Comment by MorrisJobke** [comment]
cc @schiessle

**Comment by mightyBroccoli** [comment]
Are there any ideas about this? My error logging is pretty much filled up with this error.

**Comment by bcutter** [comment]
Copy that. Every 15 minutes, filling like hell...

**Comment by mightyBroccoli** [comment]
I am quite happy I am not the only one with this problem. I hope this gets fixed in NC12 or even with one of the RCs befor that.

**Comment by bcutter** [comment]
It´s not only in NC, OC as well...

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing

**Comment by rullzer** [comment]
mmmm I might have an idea why.... let me assign this so I don't forget.

**Comment by schiessle** [comment]
I fixed a "bad request" here, https://github.com/nextcloud/server/pull/4029 Will be released with 11.0.3 soon. Note, that this will not fix the issue automatically but will require that remove pending federated shares and create them again.

**Comment by schiessle** [comment]
@rullzer when you dig into it, the fix is this commit: https://github.com/nextcloud/server/pull/4029/commits/e2656c6521b4498f9a27e4c243451458ec709bfc

We returned for every execption a "bad request" while in case the server just refuses to ask for the shared secret and let the other server ask for it (because `$remoteToken > $localToken`) but to make this work we shouldn't return a bad request but another status code.

**Comment by rullzer** [comment]
Mmmm no my idea was that it might be the CSRF protection kicking in. But of course those are public endpoints. Setting up trusted servers works here it seems...

**Comment by bcutter** [comment]
Can I/we as affected users help you more by providing specific information? We´re highly interested (and motivated :-) ) in fixing this.

**Comment by rullzer** [comment]
Ok I think I managed to trigger it. Don't know the exact steps but I think I found the reason why... PR will be incomming shortly.

**Comment by rullzer** [comment]
So yes it seems to be triggered by a badly converted exception. So the patch from @schiessle should fix it. So hopefully all is right in the world again soon

**Comment by LukasReschke** [comment]
Sadly it seems not to. This still happens on c.nc.c which is on 11.0.3 RC2 😢

**Comment by rullzer** [comment]
Please checkout #4418

So the issue is fixed with the patch from @schiessle. But if you are quering an old server it will still throw the wrong error code causing the log flood.

**Comment by bcutter** [comment]
Thank you @rullzer. I tested the fix.

**Before:**

_server1 (NextCloud up to date):_
`GuzzleHttp\Exception\ClientException: Client error response [url] https://nextcloud.tld//ocs/v2.php/apps/federation/api/v1/request-shared-secret?format=json [status code] 400 [reason phrase] Bad request`

_server2 (OwnCloud - running v8.2.7.1 **rolling-eyes**):_
`Server error response [url] https://owncloud.tld/ocs/v2.php/apps/federation/api/v1/request-shared-secret?format=json [status code] 500 [reason phrase] Internal Server Error`

**After:**

_server1 (NextCloud up to date): no more log entries since 8 cron runs/2 hours._
I see "GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 3000 milliseconds with 0 bytes received" sometimes but I´m not sure to which FedCloud it belongs to.

_server2 (OwnCloud - running v8.2.7.1 **rolling-eyes**):_
`Server error response [url] https://owncloud.tld/ocs/v2.php/apps/federation/api/v1/request-shared-secret?format=json [status code] 500 [reason phrase] Internal Server Error`

==> So NCs seems fine, (old) OCs without any change. I noticed the server error catch part few lines below both php files but... I don´t think it´s a good idea to degrade them to "info only", right... <==


Side note: I´m on OC v9.1.4. That´s it, my outing :-) But the federation app codes are almost the same. So do you know what to do/whome to point to this issue to make sure those guys will implement that fix too?

Many thanks for the (reeeeeeeeeally fast) support by the way. I´m not used to having fixed problems that super fast. Good work.

**Comment by rullzer** [comment]
The issue here is that if cloud1 send a request to cloud2 and an exception occurs on 2 then logging the full trace on 1 makes no sense. Since there is no real info. 

I'll think about how to add more detailed logging to 2.
