### ISSUE TITLE
some elements in the sharing dropdown are not visible and no way to scroll down in certain screen resolutions

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#33839]
See 
![image](https://user-images.githubusercontent.com/42591237/188104888-fe1cde25-e850-46f7-a0ef-949844d00957.png)

**Comment by szaimen** [comment]
I think this should be fixed with the next vue 7.0 release as well...

**Comment by szaimen** [comment]
No, isn't yet

**Comment by thomasgg23** [comment]
Version: Nextcloud Hub 3 Version 25.0.0
Browser: 106.0.1370.47 (Offizielles Build) (64-Bit) - cache and cookies cleared

Bug still exists.
Sharing of folder can't be removed on smaller screen sizes, because the button is not displayed and menu can't be scrolled down.

![image](https://user-images.githubusercontent.com/2633051/196776551-fed6b7e4-0f68-4385-b2e6-de59448c552c.png)

**Comment by szaimen** [comment]
cc @jancborchardt @nimishavijay @nextcloud/server-frontend

**Comment by PVince81** [comment]
still happening on master, we're still on vue 7.0.0-beta.4 though

I need to zoom to 50% to see the "Note to recipient" and "+ Add another link" at the bottom of the dropdown.

**Comment by szaimen** [comment]
@nextcloud/frontenders any ideas how to solve this? I guess the popper element would need som scrolling so that it doesnt get out of view?

**Comment by szaimen** [comment]
found a solution

**Comment by PVince81** [comment]
https://github.com/nextcloud/nextcloud-vue/pull/3445 is merged

requires a nextcloud-vue release + lib update here

**Comment by szaimen** [comment]
Needs:
- [x] backport to vue 7
- [x] new release of vue 7
- [ ] merge of new vue 7 in master
- [ ] backport of new vue 7 to stable25

**Comment by szaimen** [comment]
Reopening for the last missing step
