### ISSUE TITLE
[Bug]: After a folder was removed, it appears again soon.

### ISSUE THREAD

**Issue by luckydogxf** [nextcloud/server#34046]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud 24.0

After a folder was removed, it appears again soon.

### Steps to reproduce

1. User A creates a new folder 'test' , which hosts on external storage.
2.  Users B has full access to test,  he deletes test on purpose.
3.  Soon after deletion, test appears again.

### Expected behavior

Removed folder shall disappear forever.

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "proxy": "172.16.232.21:8088",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.pacific-textiles.com",
            "172.16.215.175",
            "https:\/\/nextcloud.pacific-textiles.com",
            "https:\/\/nextcloud.pacific-textiles.com:8443",
            "next.pacific-textiles.com"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR",
            "X-Forwarded-For"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.0.12",
        "overwrite.cli.url": "https:\/\/nextcloud.pacific-textiles.com",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "allow_local_remote_servers": "true",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "sharing.enable_share_accept": true,
        "sharing.force_share_accept": true,
        "maintenance": false,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [
            "warehouse",
            "SAP-CONSULTANT",
            "monitor",
            "SAP-KU"
        ],
        "onlyoffice": {
            "verify_peer_off": true
        },
        "loglevel": 0,
        "theme": "",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - bruteforcesettings: 2.4.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.1.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - encryption: 2.12.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - fulltextsearch_elasticsearch: 24.0.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - richdocuments: 6.0.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_totp: 6.3.0
  - updatenotification: 1.14.0
  - user_ldap: 1.14.1
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - mail: 1.13.8
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"lE3EISo2Xi3VXoQp9OZa","level":3,"time":"2022-09-13T08:40:19+00:00","remoteAddr":"172.30.20.44","user":"root","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/root/","message":"disk_free_space(): No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#395","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","version":"24.0.0.12","exception":{"Exception":"Error","Message":"disk_free_space(): No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#395","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"disk_free_space(): No such file or directory","/var/www/html/lib/private/Files/Storage/Local.php",395]},{"file":"/var/www/html/lib/private/Files/Storage/Local.php","line":395,"function":"disk_free_space","args":["/var/www/html/data/31000042/files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)/files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Local","type":"->","args":["files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)/files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)/files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)/files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Jail.php","line":344,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)/files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Jail","type":"->","args":["files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)"]},{"file":"/var/www/html/lib/private/legacy/OC_Helper.php","line":548,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)"]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php","line":341,"function":"getStorageInfo","class":"OC_Helper","type":"::","args":["/root/files/PY - UAT Scenarios (Test Cases and Scripts)",{"__class__":"OC\\Files\\Node\\Folder"},false]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":765,"function":"getQuotaInfo","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":[]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/PropFind.php","line":95,"function":"Sabre\\DAV\\{closure}","class":"Sabre\\DAV\\CorePlugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":769,"function":"handle","class":"Sabre\\DAV\\PropFind","type":"->","args":["{DAV:}quota-available-bytes",{"__class__":"Closure"}]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"propFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1052,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["propFind",[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":984,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1662,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["files/root",["{DAV:}getlastmodified","{DAV:}getetag","{DAV:}getcontenttype","{DAV:}resourcetype","{http://owncloud.org/ns}fileid","And 15 more entries, set log level to debug to see all entries"],1]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1647,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\Xml\\Writer","elementMap":[],"contextUri":"/remote.php/dav/","namespaceMap":{"DAV:":"d","http://sabredav.org/ns":"s","http://owncloud.org/ns":"oc","http://nextcloud.org/ns":"nc"},"classMap":[]},{"__class__":"Generator"},false]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PROPFIND",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":352,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":166,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"lE3EISo2Xi3VXoQp9OZa","level":3,"time":"2022-09-13T08:40:19+00:00","remoteAddr":"172.30.20.44","user":"root","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/root/","message":"disk_free_space(): No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#395","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","version":"24.0.0.12","exception":{"Exception":"Error","Message":"disk_free_space(): No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#395","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"disk_free_space(): No such file or directory","/var/www/html/lib/private/Files/Storage/Local.php",395]},{"file":"/var/www/html/lib/private/Files/Storage/Local.php","line":395,"function":"disk_free_space","args":["/var/www/html/data/31000042/files/S4HANA_Upgrade/files"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Local","type":"->","args":["files/S4HANA_Upgrade/files/S4HANA_Upgrade"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/S4HANA_Upgrade/files/S4HANA_Upgrade"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/S4HANA_Upgrade/files/S4HANA_Upgrade"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Jail.php","line":344,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/S4HANA_Upgrade/files/S4HANA_Upgrade"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Jail","type":"->","args":["files/S4HANA_Upgrade"]},{"file":"/var/www/html/lib/private/legacy/OC_Helper.php","line":548,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/S4HANA_Upgrade"]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php","line":341,"function":"getStorageInfo","class":"OC_Helper","type":"::","args":["/root/files/S4HANA_Upgrade",{"__class__":"OC\\Files\\Node\\Folder"},false]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":765,"function":"getQuotaInfo","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":[]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/PropFind.php","line":95,"function":"Sabre\\DAV\\{closure}","class":"Sabre\\DAV\\CorePlugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":769,"function":"handle","class":"Sabre\\DAV\\PropFind","type":"->","args":["{DAV:}quota-available-bytes",{"__class__":"Closure"}]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"propFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1052,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["propFind",[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":984,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1662,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["files/root",["{DAV:}getlastmodified","{DAV:}getetag","{DAV:}getcontenttype","{DAV:}resourcetype","{http://owncloud.org/ns}fileid","And 15 more entries, set log level to debug to see all entries"],1]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1647,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\Xml\\Writer","elementMap":[],"contextUri":"/remote.php/dav/","namespaceMap":{"DAV:":"d","http://sabredav.org/ns":"s","http://owncloud.org/ns":"oc","http://nextcloud.org/ns":"nc"},"classMap":[]},{"__class__":"Generator"},false]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PROPFIND",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":352,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":166,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
```

### Additional info

Nope

**Comment by szaimen** [comment]
Can you update to NC24.0.5 and try again?

**Comment by luckydogxf** [comment]
okay, I learn NC 25.0 will be released in the next month.   So I'm waiting for it and going to upgrade to 25.0 then.
I'll check whether it happens again or not.

**Comment by luckydogxf** [comment]
okay, I learn NC 25.0 will be released in the next month. So I'm waiting for it and going to upgrade to 25.0 then.
I'll check whether it happens again or not.

**Comment by luckydogxf** [comment]
This is fairly hard to find out the root cause,  Logging is inrelevant.
```
{"reqId":"uwYMUyZtCUq5oWs7LvZi","level":3,"time":"2022-09-13T09:17:58+00:00","remoteAddr":"172.30.20.44","user":"root","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/root/","message":"disk_free_space(): No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#395","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","version":"24.0.0.12","exception":{"Exception":"Error","Message":"disk_free_space(): No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#395","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"disk_free_space(): No such file or directory","/var/www/html/lib/private/Files/Storage/Local.php",395]},{"file":"/var/www/html/lib/private/Files/Storage/Local.php","line":395,"function":"disk_free_space","args":["/var/www/html/data/31000042/files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)/files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Local","type":"->","args":["files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)/files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)/files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)/files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Jail.php","line":344,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)/files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Jail","type":"->","args":["files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)"]},{"file":"/var/www/html/lib/private/legacy/OC_Helper.php","line":548,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/S4HANA_Upgrade/1 Project Management/Testing Management/S20 Testing\uff08\u7b2c\u4e00\u8f2a\u6e2c\u8a66\uff09/PY - UAT Scenarios (Test Cases and Scripts)"]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php","line":341,"function":"getStorageInfo","class":"OC_Helper","type":"::","args":["/root/files/PY - UAT Scenarios (Test Cases and Scripts)",{"__class__":"OC\\Files\\Node\\Folder"},false]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":765,"function":"getQuotaInfo","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":[]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/PropFind.php","line":95,"function":"Sabre\\DAV\\{closure}","class":"Sabre\\DAV\\CorePlugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":769,"function":"handle","class":"Sabre\\DAV\\PropFind","type":"->","args":["{DAV:}quota-available-bytes",{"__class__":"Closure"}]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"propFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1052,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["propFind",[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":984,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1662,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["files/root",["{DAV:}getlastmodified","{DAV:}getetag","{DAV:}getcontenttype","{DAV:}resourcetype","{http://owncloud.org/ns}fileid","And 15 more entries, set log level to debug to see all entries"],1]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1647,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\Xml\\Writer","elementMap":[],"contextUri":"/remote.php/dav/","namespaceMap":{"DAV:":"d","http://sabredav.org/ns":"s","http://owncloud.org/ns":"oc","http://nextcloud.org/ns":"nc"},"classMap":[]},{"__class__":"Generator"},false]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PROPFIND",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":352,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":166,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"uwYMUyZtCUq5oWs7LvZi","level":3,"time":"2022-09-13T09:17:58+00:00","remoteAddr":"172.30.20.44","user":"root","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/root/","message":"disk_free_space(): No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#395","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","version":"24.0.0.12","exception":{"Exception":"Error","Message":"disk_free_space(): No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#395","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"disk_free_space(): No such file or directory","/var/www/html/lib/private/Files/Storage/Local.php",395]},{"file":"/var/www/html/lib/private/Files/Storage/Local.php","line":395,"function":"disk_free_space","args":["/var/www/html/data/31000042/files/S4HANA_Upgrade/files"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Local","type":"->","args":["files/S4HANA_Upgrade/files/S4HANA_Upgrade"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/S4HANA_Upgrade/files/S4HANA_Upgrade"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/S4HANA_Upgrade/files/S4HANA_Upgrade"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Jail.php","line":344,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/S4HANA_Upgrade/files/S4HANA_Upgrade"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":334,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Jail","type":"->","args":["files/S4HANA_Upgrade"]},{"file":"/var/www/html/lib/private/legacy/OC_Helper.php","line":548,"function":"free_space","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/S4HANA_Upgrade"]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php","line":341,"function":"getStorageInfo","class":"OC_Helper","type":"::","args":["/root/files/S4HANA_Upgrade",{"__class__":"OC\\Files\\Node\\Folder"},false]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":765,"function":"getQuotaInfo","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":[]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/PropFind.php","line":95,"function":"Sabre\\DAV\\{closure}","class":"Sabre\\DAV\\CorePlugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":769,"function":"handle","class":"Sabre\\DAV\\PropFind","type":"->","args":["{DAV:}quota-available-bytes",{"__class__":"Closure"}]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"propFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1052,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["propFind",[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":984,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1662,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["files/root",["{DAV:}getlastmodified","{DAV:}getetag","{DAV:}getcontenttype","{DAV:}resourcetype","{http://owncloud.org/ns}fileid","And 15 more entries, set log level to debug to see all entries"],1]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1647,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\Xml\\Writer","elementMap":[],"contextUri":"/remote.php/dav/","namespaceMap":{"DAV:":"d","http://sabredav.org/ns":"s","http://owncloud.org/ns":"oc","http://nextcloud.org/ns":"nc"},"classMap":[]},{"__class__":"Generator"},false]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PROPFIND",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":352,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":166,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
```

**Comment by CarlSchwan** [comment]
Please update to the latest 24 release, this should fix the issue

**Comment by luckydogxf** [comment]
Hello, guys, I worked over time yesterday to updrade Nextcloud to `24.05`.
However the issues are still there.

**Comment by luckydogxf** [comment]
The word around is weird.
Upload a new file within 'test', then delete this file.
Test is going to be deleted as well.
