### ISSUE TITLE
[Bug]: Missing shared files/directory in shared folder

### ISSUE THREAD

**Issue by baboupc** [nextcloud/server#34976]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

We have updated our Nexcloud serveur to version 24.0.7 from 24.0.5.
This update seems to broke share folder with the web client.
We cannot see any shared file/folder in shared folder.
We have custom shared_folder from many years in config.php : /Partagés (French name)

See attachements for context 

Tests with have made : 

- Shared files/folders are present in the view "Shared with you". Click on it redirect to root folder.
- Using link /index.php/apps/files?dir=/Partag%C3%A9s/CFVE redirect to root folder too 
- Ios & Android App can brown shared folder and works as expected 
- NC Desktop client also shown shared folder with shared file/directory
- Database contains coherent data 
- Redis was purged,
- All www apache service was rebooted 

<img width="1280" alt="NC_webview_shared_folder_content_empty" src="https://user-images.githubusercontent.com/8754369/200024617-47489ff0-a68f-44d0-8251-04c541bd913c.png">
<img width="1378" alt="NC_webview_shared_with_you" src="https://user-images.githubusercontent.com/8754369/200024594-5858ae6d-c1e9-4070-a46e-bf946e446c2f.png">
<img width="595" alt="NC_Desktop_client_shared_folder" src="https://user-images.githubusercontent.com/8754369/200024607-e1f81521-965b-412e-b976-50a1797cdaf3.png">
![IOS_shared_folder](https://user-images.githubusercontent.com/8754369/200024610-a8072633-2d1b-4742-8553-d04f65aeeaa1.png)

### Steps to reproduce

1. Update to Nexcloud server to version 24.0.7 from 24.0.5.
2. See shared folder in web view, no shared files or folders 
3. Shared folders and files are listed in "Shared with you" 

### Expected behavior

See and access shared files or folders from web view

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Partag\u00e9s",
        "integrity.check.disabled": false,
        "dbtype": "mysql",
        "version": "24.0.7.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "fr",
        "default_phone_region": "FR",
        "force_language": "fr",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "forcessl": true,
        "logtimezone": "Europe\/Paris",
        "log_type": "file",
        "logfile": "\/var\/www\/nc_data\/nextcloud.log",
        "loglevel": 0,
        "logdateformat": "F d, Y H:i:s",
        "log_rotate_size": 104857600,
        "log_authfailip": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Partag\u00e9s",
        "integrity.check.disabled": false,
        "dbtype": "mysql",
        "version": "24.0.7.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "fr",
        "default_phone_region": "FR",
        "force_language": "fr",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "forcessl": true,
        "logtimezone": "Europe\/Paris",
        "log_type": "file",
        "logfile": "\/var\/www\/nc_data\/nextcloud.log",
        "loglevel": 0,
        "logdateformat": "F d, Y H:i:s",
        "log_rotate_size": 104857600,
        "log_authfailip": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "activity_expire_days": 14,
        "appstore.experimental.enabled": true,
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "updater.release.channel": "stable",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": ***REMOVED SENSITIVE VALUE***,
            "dbindex": 0,
            "timeout": 1.5
        },
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp",
        "sharing.minSearchStringLength": 1
    }
}",
        "theme": "",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "activity_expire_days": 14,
        "appstore.experimental.enabled": true,
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "updater.release.channel": "stable",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": ***REMOVED SENSITIVE VALUE***,
            "dbindex": 0,
            "timeout": 1.5
        },
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp",
        "sharing.minSearchStringLength": 1
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - announcementcenter: 6.3.1
  - bbb: 2.3.1
  - bruteforcesettings: 2.4.0
  - cloud_federation_api: 1.7.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - forms: 2.5.1
  - groupfolders: 12.0.2
  - impersonate: 1.11.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notes: 4.5.1
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - ransomware_protection: 1.14.0
  - recommendations: 1.3.0
  - richdocuments: 6.3.1
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.6
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_ldap: 1.14.1
  - user_saml: 5.0.3
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - welcome: 1.0.2
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - circles: 0.19.11
  - comments: 1.5.0
  - deck: 1.7.2
  - drawio: 1.0.3
  - encryption
  - federation: 1.5.0
  - files_accesscontrol: 1.14.1
  - files_fulltextsearch: 24.0.1
  - files_markdown: 2.3.6
  - files_mindmap: 0.0.26
  - files_trackdownloads: 1.11.0
  - fulltextsearch: 24.0.0
  - fulltextsearch_elasticsearch: 24.0.1
  - sharelisting: 1.1.1
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by mart-ffbsee** [comment]
I have the same issue, also after updating to 24.0.7 from an older 24.0.x version.
I also see the shared files under shareoverview but I cannot access them there.

**Comment by fenvarien** [comment]
After the update to 24.0.7 I can’t see the files and folders in my “shared folder” anymore. They are still visible and accessible in the Android app and my desktop app in Windows. So the files and the database seems to be intact.

**Comment by tron65** [comment]
we have the same problem on our test instance, where we updated from 24.0.6 to 24.0.7, "Shared" folder is empty, when i go to "Shared with you" and click on something, i land in root.

**Comment by thoschi** [comment]
Same with us. All shares gone suddenly. 

The folder defined by shared_folder is empty - but in the left pane under "Shared With You" they are still visible. But when any share is clicked, the user gets redirected to the root folder.

What helped was to delete the shared_folder - prefix from each share inside the database column containing the file names. Now the shares are back (phew) but of course they are all inside every users root folder.

Moving any share back to the folder set by "shared_folder" inside config makes this share inaccessible. Moving it to another folder works.

**Comment by boulabytes** [comment]
Same problem here since upgrade to 24.0.7.
Is anyone from nextcloud team aware of this problem ?

**Comment by ZID-TU-Graz** [comment]
same here (upgrade to NC 24.0.7)

**Comment by mosesdd** [comment]
similar issue: we only use groupfolders and files view is just blank after update to 24.0.7

**Comment by 4tler** [comment]
same problem here. Update via Nextcloud AIO to 24.0.7 and some users no longer have access to DECK attachments and also files shared in TALK. They are also no longer displayed. Other users have no problems and can access all. 

I can exclude admin and standard users. Even the NC Admin can no longer use any shares.

**Comment by szaimen** [comment]
cc @PVince81 @icewind1991

**Comment by szaimen** [comment]
`share_folder`
Do all of you have this value configured in your config.php?

**Comment by 4tler** [comment]
me yes with 'share_folder' => '/Shared',

**Comment by thoschi** [comment]
> `share_folder` Do all of you have this value configured in your config.php?

Yes we do

**Comment by fenvarien** [comment]
> `share_folder` Do all of you have this value configured in your config.php?

Yes, 'share_folder' => '/Geteilt',

**Comment by skainz** [comment]
Hello, also issue with my installation: Same problem here since upgrading to 24.0.7.
Regards,

**Comment by foer** [comment]
I also have the same issue since upgrading to 24.0.7. 
The 'share_folder' value is set on my installation:
'share_folder' => 'TAUSCHORDNER',

**Comment by PVince81** [comment]
the storage / mounts code got reworked in NC 24, however if no one had this issue in NC 24.0.1 then it's a recent addition

it should be possible to git bisect to find the breaking commit

**Comment by szaimen** [comment]
Hi everyone, if you know how to apply a patch, can you try out if https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/35155.patch makes it work again? 
Please don't forget to create a backup before applying the patch!

**Comment by szaimen** [comment]
> Hi everyone, if you know how to apply a patch, can you try out if https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/35155.patch makes it work again?
> Please don't forget to create a backup before applying the patch!

**Comment by PVince81** [comment]
My first attempt at reproducing this failed, steps:
1. Setup Nextcloud 24.0.7 from scratch
2. `occ config:system:set share_folder --value "received_shares"`
3. as admin, create a folder "test"
4. share "test" with another user "alice"
5. login as "alice"
6. see that "/received_shares/test" exists and is accessible

Also, I noticed that we didn't have integration tests with "share_folder" so I added one here: https://github.com/nextcloud/server/pull/35173
The automated test also passes as it runs similar steps like the above.

Alright, so a new setup from scratch works fine.
Next up: test with an upgrade scenario.

I suspect that maybe something is wrong with oc_mounts.

In the meantime, those affected by the bug, can you run: `select * from oc_mounts where user_id='alice';` where "alice" is the user who doesn't see the received share

**Comment by PVince81** [comment]
## Test with update

1. Setup Nextcloud 24.0.5
2. `occ config:system:set share_folder --value "received_shares"`
3. login as admin
4. create a folder "test"
5. share "test" with another user "alice"
6. login as "alice" (important to get their mount points setup)
7. see that "/received_shares/test" exists and is accessible
8. logout
9. upgrade to Nextcloud 24.0.7
10. login as "alice" again
11. see that "/received_shares/test" exists and is accessible

- 24.0.5 => 24.0.7: works fine
- 24.0.9 => 24.0.7: works fine
- 23.0.11 => 24.0.7: works fine
- 23.0.11 => 24.0.0 (oc_mounts.mount_provider_class is NULL) => 24.0.5 (stays NULL) => 24.0.7 (populated now): works fine

**Comment by baboupc** [comment]
Hi,

In our case we cannot test anymore because we revert to NC 24.0.5. 
As @mart-ffbsee, maybe this issue affect only ldap users ?

**Comment by fenvarien** [comment]
> if only LDAP, there's a known issue in 24.0.7, you can try applying #35131

We have the issue and don't use LDAP. Not all users are affected, some can still see the contents of their shared folder.
The upgrade from 24.0.6 to 24.0.7 introduced the problem in our case.

**Comment by fenvarien** [comment]
> can you create a new test user and share something with them, and check if they see the parent folder ? this might give more clues if it's a potential "update issue with existing users" or a general issue @fenvarien

A new created user is able to see the shared folder and it's contents (older shares and a new test folder).

**Comment by RehavistaGmbH** [comment]
We had the same problem.
Following your request to execute `select * from oc_mounts where user_id='affecteduser';` i noticed that a few entries did have the mount_provider_class as `NULL`
In an act of desperation we simply inserted `OCA\Files_Sharing\MountProvider` as value since we don't have any other kind of mounts in our cloud anyways.
And indeed this resolved the issue for the affected user.

**Comment by szaimen** [comment]
So it seems to be indeed the same issue like https://github.com/nextcloud/server/issues/34752

**Comment by fenvarien** [comment]
> @fenvarien and for one of the affected user, run `select * from oc_mounts where user_id='affecteduser';` and `select * from oc_share where share_with="affecteduser"`

The second command gave me this output:

ERROR: column "id_of_affecteduser" does not exist
LINE 1: select * from oc_share where share_with="id_of_affecteduser";

**Comment by ThomasBahn** [comment]
replace double quotes by single quotes

**Comment by 4tler** [comment]
@szaimen is it possible to integrate this patch into the next version of NC AIO?

And to all: Thanks for this fast fix!

**Comment by PVince81** [comment]
I'm closing this here (duplicate) in favor of https://github.com/nextcloud/server/issues/34752 which is assigned for resolution.

feel free to continue contributing hints there, I've linked back here

**Comment by fenvarien** [comment]
> I'm closing this here (duplicate) in favor of #34752 which is assigned for resolution.
> 
> feel free to continue contributing hints there, I've linked back here

Will this fix be included with 24.0.8? #34752 is only assigned to NC 25.0.2.

**Comment by szaimen** [comment]
Yes, it will get backported to 24.0.8 as soon as the fix is merged

**Comment by m8ichael** [comment]
I've applied the patch to 24.0.7, but existing shares still don't show up in the defined folder. Can someone double check this?

**Comment by boulabytes** [comment]
Hello,
I managed to fix this problem for affected users by using this request : 
`UPDATE `oc_mounts` SET `mount_provider_class` = 'OCA\\Files_Sharing\\MountProvider' WHERE `mount_provider_class` is NULL AND `mount_point` LIKE '%Shared%';`
Maybe some new affected users might appear but for now it does the job...

**Comment by fenvarien** [comment]
[This patch](https://github.com/nextcloud/server/issues/34752#issuecomment-1317337605) is working successfully with 24.0.7.

**Comment by tron65** [comment]
as far as i can say, the sql-statement fixed the problem on our instance (it's the test-instance, we haven't rolled 24.0.7 out on our main one yet)
