### ISSUE TITLE
[Bug]: Logo not showing in header after the update (FIX)

### ISSUE THREAD

**Issue by mattiosystems** [nextcloud/server#35871]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After one update the logo in header just disappeared and I've been trying all solutions of other people but none of them worked. No future updates fixed it so I found a solution myself.

### How to fix the bug

1. Go to /var/www/nextcloud/.
2. Write command "sudo -u www-data php occ config:system:get instanceid". You'll get your instance ID. Remember how it looks, you don't need to remember the whole thing.
3. Go to your nextcloud data directory (it might be "/var/www/nextcloud/data/" or something like "/mnt/ncdata/").
4. You should find a folder "appdata_yourinstanceid". Open it.
5. Go to theming/global/images. There should be files like "background", "logo" and something else (but no file "logoheader").
6. Copy file "logo" to "logoheader" with the command "sudo cp logo logoheader".
7. After these steps, you should see the logo in header. 

### Expected behavior

After these steps, the logo should appear.

### Installation method

Community Manual installation with Archive

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
Hi, which NC version?

**Comment by mattiosystems** [comment]
> 

NC 25.0.2.3

**Comment by mattiosystems** [comment]
> Hi, which NC version?
NC 25.0.2.3

**Comment by daveo132** [comment]
Confirming this issue with 25.0.2 (just upgraded) resetting to default does not fix.
Have not tired the manual method as yet.

**Comment by MeCias** [comment]
Should that issue be fixed in NC 25.0.3? I have now the normal logo instead of the header logo in the header.

**Comment by ernolf** [comment]
After updating from 25.02.3 to 25.0.3.2 the logo (login screen) and the logo-header (upper left corner in the web frontend) have disappeared. Only alternative text (`name`-value from settings) is displayed. The logo remained in the Android app.
I tried:

- The workaround from @mattiosystems 

no files where missing or corrupted

- Reset to default

nothing changed, no default logo was displayed

- Upload header logo again

no logo was displayed. The only thing what changed was (sql-query):

    SELECT * FROM `oc_appconfig` WHERE `appid` LIKE 'theming';

showed me a new `cachebuster` value and a new directory with that number was created in the appdata directory. But the behavior in the web frontend hasn't changed: no logo in the login screen, no header logo in the upper left corner, only alternative text.

Here my current theming config:

    - name: nextcloud on mycloud.tld
    - url: https://mycloud.tld
    - imprintUrl:
    - privacyUrl:
    - slogan: The flexible open source file synchronization and sharing solution.
    - color: #60b0f4
    - disable-user-theming: yes
    - background: image/jpeg
    - logo: image/png
    - favicon: image/vnd.microsoft.icon
    - logoheader: image/png

What can i do, to get it work again?

**Comment by ernolf** [comment]
I have also tried uploading the logos as SVG files but still no luck.
Has anyone else experienced this issue or have any suggestions on what could be causing it?
I would greatly appreciate any help or guidance on resolving this. Thank you.

**Comment by szaimen** [comment]
should be fixed with 25.0.4

**Comment by Jerome-Herbinet** [comment]
I've also noticed when upgrading my private instance from 24.0.9 to 25.0.3 that the custom instance background image (visible on the login screen) disappears after the upgrade. @szaimen are you aware of this problem (maybe similar to this issue) ?

**Comment by szaimen** [comment]
Yesx the migration didnt work until 25.0.4. So you need to add your assets back manually or restore a backup and only upgrade to 25 after 25.0.4 is out.

**Comment by ernolf** [comment]
OK, I fixed it for me, I patched my installation with this [revert](https://github.com/nextcloud/server/commit/9af7ee8d11b43a7a3d14f7aa8390aff0a4174f55) and now my logo is back.

**Comment by brunob** [comment]
> I have also tried uploading the logos as SVG files but still no luck.

Same here on 25.0.4, we have switched back to old png logos.

**Comment by szaimen** [comment]
Just upgraded my instance from 24 zo 25.0.4 and it kept the theming asstets
