### ISSUE TITLE
[Bug]: Theming Custom Header Icon not displaying

### ISSUE THREAD

**Issue by ON3-CL1CK** [nextcloud/server#36319]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When uploading a Header logo it uses the default or auto-generated one from Logo instead of the image provided.

Uploading a Favicon, Logo and Background works as expected.

The file headerlogo in the data-"id" folder is changed to the uploaded image however it is not displayed in the header when visiting the Website.

Uploading a Logo but not a header logo replaces the default header logo with an auto-generated one from the logo as expected.

### Steps to reproduce

1. Log into an Administrator Account
2. Go to Administration settings
3. Under Administration select Theming
4. Select any image and upload it as Header logo under Advanced Options

### Expected behavior

Uploading a custom header logo replaces the current header logo independent of whether a custom logo or the default logo is used.

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 104857600,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "quota_include_external_storage": false,
        "share_folder": "\/Shares",
        "skeletondirectory": "",
        "theme": "",
        "default_phone_region": "DE",
        "trashbin_retention_obligation": "auto, 7",
        "updater.release.channel": "stable",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "unsplash",
            "checksum",
            "files_retention"
        ],
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [
            "admin"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - calendar: 4.2.1
  - checksum: 1.2.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - collectives: 2.2.1
  - comments: 1.15.0
  - contacts: 5.0.2
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_retention: 1.14.1
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - metadata: 0.17.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - ransomware_protection: 1.14.0
  - related_resources: 1.0.3
  - richdocuments: 7.1.0
  - richdocumentscode: 22.5.802
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.3
  - support: 1.8.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - theming_customcss: 1.12.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - unsplash: 2.1.1
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings
  - dashboard: 7.1.0
  - encryption
  - federation: 1.10.1
  - files_external
  - firstrunwizard: 2.9.0
  - nextcloud_announcements: 1.9.0
  - recommendations: 1.0.0
  - survey_client: 1.8.0
  - suspicious_login
  - user_ldap
  - user_status: 1.0.0
  - weather_status: 1.0.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
No logs relevant to the bug.
```

### Additional info

Tried 2 different Browsers: firefox and opera
Bug reproduced on two different Nextcloud Installations on version 25.0.3
Both instances were recently upgraded to 25.0.3 from 24.0.9
One instance has  unsplash installed, the other one does not. It is independent of unsplash.
No custom css is currently in use.

**Comment by rinal13** [comment]
Same behaviour on my instance after update from 25.0.2 to 25.0.3

**Comment by ernolf** [comment]
I have same problems after update from 25.0.2.3 to 25.0.3.2
Is this a duplicate of #35871? (I reported there)

Can I assume [this](https://github.com/nextcloud/server/commit/e5977a19ab94342fed5c543c84255af9cf3f8ec8) to be the solution to this problem or is that another issue?

**Comment by szaimen** [comment]
Should be fixed with 25.0.4

**Comment by ON3-CL1CK** [comment]
> I have same problems after update from 25.0.2.3 to 25.0.3.2 Is this a duplicate of #35871? (I reported there)
> 
> Can I assume [this](https://github.com/nextcloud/server/commit/e5977a19ab94342fed5c543c84255af9cf3f8ec8) to be the solution to this problem or is that another issue?

It does not seem to be related to the issue you mentioned. The file "logoheader" is present. The file is changed to the correct image if you update it via the Upload function on the Theme page. However even though the correct file is present on the Filesystem it is not displayed on the webpage. Rather the file "logo" is displayed. It even points to the logo file in the HTML Element

<img class="logo logo-icon" alt="Nextcloud logo" src="/apps/theming/image/logo?useSvg=1&amp;v=16">

The element above should point to /apps/theming/image/headerlogo
This behavior cloud be correct if no headerlogo was uploaded because then logo should be used as headerlogo according to [Custom header logo and favicon as alternative to auto-generation based on logo](https://docs.nextcloud.com/server/24/admin_manual/configuration_server/theming.html) . It seems like the HTML is not updated correctly if a headerlogo is uploaded.


Worth mentioning is that I also had the Problem that you reported. The admin theming was not migrated but I fixed that by simple customizing it again from scrap.

**Comment by MrSteelMiner** [comment]
> The element above should point to headerlogo (/apps/theming/image/logoheader?v=16) instead.
> The behavior in the code above might be correct if no headerlogo was uploaded because then logo should be used as headerlogo according to [Custom header logo and favicon as alternative to auto-generation based on logo](https://docs.nextcloud.com/server/24/admin_manual/configuration_server/theming.html) . It seems like the HTML is not updated correctly if a headerlogo is uploaded.

Same issue here. "logo" is displayed even if headerlogo exists. Resetting do default and reuploading it still doesn't change anything
![image](https://user-images.githubusercontent.com/47743654/216568651-d6c3b686-6483-414a-a755-0bc2ccc9f765.png)

**Comment by ernolf** [comment]
OK, I fixed it for me, I patched my installation with this [revert](https://github.com/nextcloud/server/commit/9af7ee8d11b43a7a3d14f7aa8390aff0a4174f55) and now my logo is back.

**Comment by JohanBoshoffWebAware** [comment]
When is 25.04 releasing.  My theming totally does not work.  I would like to re-instate the theming ASAP.

**Comment by ON3-CL1CK** [comment]
I can confirm that Release 25.04 fixes the bug and theming is working as expected. Therefore I am closing the issue.

@JohanBoshoffWebAware I cannot reproduce your problem as my theming works correctly for me. You might try opening your own issue.
