### ISSUE TITLE
[Bug]: Creating a file does not generate a notification even if push notifications are enabled for "A file or folder has been changed"

### ISSUE THREAD

**Issue by bertvandepoel** [nextcloud/server#37707]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Currently, the notification settings "A file or folder has been changed" and "A file or folder has been shared" have the option to push notifications to the client. However, neither of these options seems to generate a desktop notification when a new file is added or when a file is removed. Especially the lack of notifications when a file is added is very confusing, since this would be one of the main reasons to enable this notification settings. Technically you could claim that "changed" here literally means "editing a file". However, adding/deleting files inside a folder boils down to changing a folder, and regular users I would argue consider adding files as a "change" to that file. Especially since there's no separate option to push notifications about file creation, the expected behavior would be that "changes" include file creation and deletion.

Even though we've indicated just one OS below, we've tested this on Ubuntu 22.04, macOS 10.15.7 and Debian Sid.

### Steps to reproduce

1. Enable push notifications for "A file or folder has been changed"
2. Create a file on the web client or have someone else create or add a file inside shared folder
3. No notification will be shown even though this newly created/added file will be synced
4. If the file is edited, then a notification will be shown

### Expected behavior

A notification should be shown when new files are created/added, and ideally also when they are deleted, or separate options should be added to receive such push notifications.

### Which files are affected by this bug

NA

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 22.04

### Package

Distro package manager

### Nextcloud Server version

25.0.4

### Nextcloud Desktop Client version

3.4.2-1 (Ubuntu), 3.7.3 (Debian), 3.6.6 (macOS)

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Should be working today.
There was a more recent regression, but that was just fixed pending release.
See #49133

**Comment by tigernero79** [comment]
I UPDATED TO 31.0.3 BUT THE BUG STILL PERSISTS... BUT HOW IS THIS POSSIBLE?

REOPEN THE REPORT... BUT IS IT POSSIBLE THAT WE CAN'T GET TO THE END OF IT?

**Comment by tigernero79** [comment]
I confirm by deleting file and folder sharing with internal accounts and recreating them the notifications started working again
thanks
