### ISSUE TITLE
The name of shared folder will be renamed to " (2)" without the real name, if it contains non-ASCII characters

### ISSUE THREAD

**Issue by mchtech** [nextcloud/server#3807]
I shared a folder to another group, and logined by the account that belongs to the group. The folder name contains(consists of) non-ASCII characters, because I use Asia language. After I refreshed the page some times, the folder name had been renamed to " (2)" instead of the real folder name. Sometime, the name is not changed inmediately (I must refresh the page many times).
**If the name consists of ASCII characters, the problem will not happen forever.**
I found that a new row was inserted in "oc_share" table. The "share_type" was 2 , "share_with" was account name, "file_target" was " (2)" and "parent" inherited the row id of source group share. After I deleted this row and refresh the page, the folder name was restored. But it will also change back to " (2)" after I refresh the page some times.
I think the problem is caused by function "verifyMountPoint" in apps/files_sharing/lib/SharedMount.php.
I added extra outputs to trace some variables in this function.

$mountPoint = basename($share->getTarget());
$parent = dirname($share->getTarget());

The return value of "$share->getTarget()" is normal, but $mountPoint and $parent are empty (length are zero) SOMETIME. So "$this->updateFileTarget($newMountPoint, $share);" inserted a new row.
I have to change this line to
if($mountPoint != ""){
                                $this->updateFileTarget($newMountPoint, $share);
}
to avoid the problem temporarily.

Another issue is the folder name may change to "files", if it contains non-ASCII characters. What is different with the previous issue   is   it is not read from database.

### Server configuration
**Operating system**:CentOS 7.3

**Web server:** httpd 2.4.6

**Database:**MySQL 5.6.35

**PHP version:**PHP 7.0.16 and 7.1

**Nextcloud version:** 11.0.2

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - audioplayer: 1.4.1
  - bookmarks: 0.9.1
  - calendar: 1.5.1
  - comments: 1.1.0
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_reader: 0.8.4
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextant: 1.0.6
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.25
  - serverinfo: 1.1.1
  - spreed: 1.2.0
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - sharebymail
  - survey_client
  - systemtags
  - templateeditor
  - user_external
  - user_saml

**Comment by nickvergessen** [comment]
Can you please provide the asian name? Thanks

**Comment by mchtech** [comment]
e.g. 测试

**Comment by nickvergessen** [comment]
Works pretty fine here, please make sure you have your server set up correctly.
Especially the php extensions intl and mbstring are required.

If that doesn't help and you are using MySQL, please try https://docs.nextcloud.com/server/11/admin_manual/maintenance/mysql_4byte_support.html

**Comment by Xuanwo** [comment]
I used to have this problem in owncloud, after a fresh install in nextcloud, this problem dismissed.

**Comment by mchtech** [comment]
@nickvergessen 
Thank you for your help,  but the problem still exists. I have captured a video and some images and uploaded to my github.
[https://github.com/mchtech/nextcloud_problems_temp](url)

**Comment by mchtech** [comment]
@Xuanwo 
I have completely reinstalled nextcloud many times. However, this problem still exists.
The strange thing is that “basename” sometimes returns empty, but not every time. It's normal to execute "basename(...)" alone, but it sometimes becomes abnormal in nextcloud.
I don't know it's a bug of php [https://bugs.php.net/bug.php?id=62119](url) or nextcloud.
I can only add "setlocale(...)" before calling "basename(...)" to solve a part of the problem temporarily.

**Comment by Xuanwo** [comment]
@mchtech Looks like problem solved by my pr https://github.com/nextcloud/server/pull/3838 ,  maybe you can use my patch and script in [issue](https://github.com/nextcloud/server/issues/3837) to fix this problem.

**Comment by mchtech** [comment]
@Xuanwo 
Thank you for your help! 
But another problem still exists. The shared folder name somtimes is renamed "files" instead of " (2), (3) ...".
Finally, I replace all "basename" to "\OC_Util::basename" (except the code in "util.php") and solve this problem .

The script is:
`grep -rn ' basename('|grep -Eo "^.*\.php"|grep -v "util\.php"| xargs sed -i 's/ basename(/ \\OC_Util::basename(`

**Comment by MorrisJobke** [comment]
Could you please try to update to 11.0.3 or higher. We improved there the detection of the share duplicates.

See https://github.com/nextcloud/server/issues/2061#issuecomment-298211876

**Comment by HelloLemon1992** [comment]
I think the question is cause by server environment, php locale...

**Comment by HelloLemon1992** [comment]
The question maybe caused by icewind wrapper. and then change the locale with the function setlocale(). and then , when basename(), it will be taken something wrong.

php.net:
basename() is locale aware, so for it to see the correct basename with multibyte character paths, the matching locale must be set using the setlocale() function.
