### ISSUE TITLE
Can't share folders by email, files work fine

### ISSUE THREAD

**Issue by krisj** [nextcloud/server#4219]
### Steps to reproduce
1. create a folder
2. try sharing it via email (share by mail app enabled)
3. observe error message

### Expected behaviour

being able to share a folder

### Actual behaviour
I get an UX error saying "Error"
In the chrome dev tools I see a 403 returned on the json request going to "https://cloud.mydomain.net/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json" with POST data: "shareType=4&shareWith=myemail%40gmail.com&permissions=31&path=%2FNotes"

### Server configuration

**Operating system**:
CentOS 7.3

**Web server:**
Nginx

**Database:**
mysql  5.5.52

**PHP version:**
 7.0.16

**Nextcloud version:** (see Nextcloud admin page)
11.0.2 daily

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from Owncloud 9...

**Where did you install Nextcloud from:**
github

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
cc @schiessle

**Comment by schiessle** [comment]
I can't reproduce it. Do you have any additional errors in your apache error log or the nextcloud.log? Would be also interesting to know if there is anything in the response body of the request.

**Comment by krisj** [comment]
@schiessle I will give you as much as I can, including response etc. you can even have access to the system if you like.

**Comment by faichelbaum** [comment]
on my side, I'm not using Apache: I'm using a n-tier setup with nginx (with SSL) + php-fpm and files stored on an NFS
I don't have additional error messages besides the CSRF error if I click on the URL provided in the JS console

**Comment by krisj** [comment]
@faichelbaum you would have to look at the response body in the network activity...

@schiessle My response body is in fact a full 403 page instead of json which I believe would be normal expected response?

**Comment by faichelbaum** [comment]
`<!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" >
	<head data-requesttoken="cn/wUdS7rjKGPkXafEGpfHpCgtDl6k9myx/I3AUYaGo=:HUeIFL7pyhnvD2q1HyjaHQAS052uhyc3u3mA90dvLAY=">
		<meta charset="utf-8">
		<title>
		Actility Shared Storage		</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="referrer" content="never">
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
		<meta name="apple-itunes-app" content="app-id=1125420102">
		<meta name="theme-color" content="#0082c9">
		<link rel="icon" href="/core/img/favicon.ico">
		<link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#1d2d44">
					<link rel="stylesheet" href="/core/vendor/select2/select2.css?v=0f8de67e1de5dd680a6a14c0a7f252cc">
					<link rel="stylesheet" href="/core/css/styles.css?v=0f8de67e1de5dd680a6a14c0a7f252cc">
					<link rel="stylesheet" href="/core/css/header.css?v=0f8de67e1de5dd680a6a14c0a7f252cc">
					<link rel="stylesheet" href="/core/css/icons.css?v=0f8de67e1de5dd680a6a14c0a7f252cc">
					<link rel="stylesheet" href="/core/css/fonts.css?v=0f8de67e1de5dd680a6a14c0a7f252cc">
					<link rel="stylesheet" href="/core/css/apps.css?v=0f8de67e1de5dd680a6a14c0a7f252cc">
					<link rel="stylesheet" href="/core/css/global.css?v=0f8de67e1de5dd680a6a14c0a7f252cc">
					<link rel="stylesheet" href="/core/css/fixes.css?v=0f8de67e1de5dd680a6a14c0a7f252cc">
					<link rel="stylesheet" href="/core/css/multiselect.css?v=0f8de67e1de5dd680a6a14c0a7f252cc">
					<link rel="stylesheet" href="/core/css/mobile.css?v=0f8de67e1de5dd680a6a14c0a7f252cc">
					<link rel="stylesheet" href="/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=0f8de67e1de5dd680a6a14c0a7f252cc">
					<link rel="stylesheet" href="/core/css/jquery-ui-fixes.css?v=0f8de67e1de5dd680a6a14c0a7f252cc">
					<link rel="stylesheet" href="/core/css/tooltip.css?v=0f8de67e1de5dd680a6a14c0a7f252cc">
					<link rel="stylesheet" href="/core/css/inputs.css?v=0f8de67e1de5dd680a6a14c0a7f252cc">
					<link rel="stylesheet" href="/core/css/jquery.ocdialog.css?v=0f8de67e1de5dd680a6a14c0a7f252cc">
									<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" type="text/javascript">
				var oc_debug=false;
var oc_isadmin=true;
var oc_dataURL="data";
var oc_webroot="";
var oc_appswebroots={"activity":"/apps/activity","admin_audit":"/apps/admin_audit","comments":"/apps/comments","dav":"/apps/dav","federatedfilesharing":"/apps/federatedfilesharing","files":"/apps/files","files_external":"/apps/files_external","files_pdfviewer":"/apps/files_pdfviewer","files_sharing":"/apps/files_sharing","files_texteditor":"/apps/files_texteditor","files_trashbin":"/apps/files_trashbin","files_versions":"/apps/files_versions","firstrunwizard":"/apps/firstrunwizard","gallery":"/apps/gallery","logreader":"/apps/logreader","lookup_server_connector":"/apps/lookup_server_connector","nextcloud_announcements":"/apps/nextcloud_announcements","notifications":"/apps/notifications","password_policy":"/apps/password_policy","provisioning_api":"/apps/provisioning_api","serverinfo":"/apps/serverinfo","sharebymail":"/apps/sharebymail","survey_client":"/apps/survey_client","systemtags":"/apps/systemtags","templateeditor":"/apps/templateeditor","theming":"/apps/theming","twofactor_backupcodes":"/apps/twofactor_backupcodes","updatenotification":"/apps/updatenotification","workflowengine":"/apps/workflowengine"};
var datepickerFormatDate="M\/d\/yy";
var nc_lastLogin=0;
var dayNames=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
var dayNamesShort=["Sun.","Mon.","Tue.","Wed.","Thu.","Fri.","Sat."];
var dayNamesMin=["Su","Mo","Tu","We","Th","Fr","Sa"];
var monthNames=["January","February","March","April","May","June","July","August","September","October","November","December"];
var monthNamesShort=["Jan.","Feb.","Mar.","Apr.","May.","Jun.","Jul.","Aug.","Sep.","Oct.","Nov.","Dec."];
var firstDay=0;
var oc_config={"session_lifetime":1440,"session_keepalive":true,"version":"11.0.2.7","versionstring":"11.0.2","enable_avatars":true,"lost_password_link":null,"modRewriteWorking":true};
var oc_appconfig={"core":{"defaultExpireDateEnabled":true,"defaultExpireDate":7,"defaultExpireDateEnforced":false,"enforcePasswordForPublicLink":true,"sharingDisabledForUser":false,"resharingAllowed":true,"remoteShareAllowed":true,"federatedCloudShareDoc":"https:\/\/docs.nextcloud.com\/server\/11\/go.php?to=user-sharing-federated","allowGroupSharing":true}};
var oc_defaults={"entity":"Actility Shared Storage","name":"Actility Shared Storage","title":"Actility Shared Storage","baseUrl":"https:\/\/www.actility.com","syncClientUrl":"https:\/\/nextcloud.com\/install\/#install-clients","docBaseUrl":"https:\/\/docs.nextcloud.com","docPlaceholderUrl":"https:\/\/docs.nextcloud.com\/server\/11\/go.php?to=PLACEHOLDER","slogan":"Make smarter connections","logoClaim":"","shortFooter":"<a href=\"https:\/\/www.actility.com\" target=\"_blank\" rel=\"noreferrer\">Actility Shared Storage<\/a> \u2013 Make smarter connections","longFooter":"<a href=\"https:\/\/www.actility.com\" target=\"_blank\" rel=\"noreferrer\">Actility Shared Storage<\/a> \u2013 Make smarter connections","folder":""};
var oc_userconfig={"avatar":{"version":0}};
			</script>
							<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/vendor/jquery/dist/jquery.min.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/vendor/jquery-migrate/jquery-migrate.min.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/vendor/underscore/underscore.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/vendor/moment/min/moment-with-locales.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/vendor/handlebars/handlebars.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/vendor/blueimp-md5/js/md5.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/vendor/bootstrap/js/tooltip.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/vendor/backbone/backbone.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/vendor/es6-promise/dist/es6-promise.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/vendor/davclient.js/lib/client.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/vendor/clipboard/dist/clipboard.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/vendor/autosize/dist/autosize.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/jquery.ocdialog.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/oc-dialogs.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/js.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/l10n.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/octemplate.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/eventsource.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/public/appconfig.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/config.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/search/js/search.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/oc-requesttoken.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/apps.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/mimetype.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/mimetypelist.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/vendor/snapjs/dist/latest/snap.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/vendor/backbone/backbone.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/oc-backbone.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/placeholder.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/jquery.avatar.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/backgroundjobs.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/vendor/select2/select2.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/select2-toggleselect.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/jquery-ui-fixes.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/files/fileinfo.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					<script nonce="Y24vd1VkUzdyaktHUGtYYWZFR3BmSHBDZ3REbDZrOW15eC9JM0FVWWFHbz06SFVlSUZMN3B5aG52RDJxMUh5amFIUUFTMDUydWh5YzN1M21BOTBkdkxBWT0=" src="/core/js/files/client.js?v=0f8de67e1de5dd680a6a14c0a7f252cc"></script>
					</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			This application requires JavaScript for correct operation. Please <a href="http://enable-javascript.com/" target="_blank" rel="noreferrer">enable JavaScript</a> and reload the page.		</div>
	</div>
</noscript>
		<div class="wrapper">
			<div class="v-align">
									<header role="banner">
						<div id="header">
							<div class="logo">
								<h1 class="hidden-visually">
									Actility Shared Storage								</h1>
							</div>
							<div id="logo-claim" style="display:none;"></div>
						</div>
					</header>
								<ul>
	<li class='error'>
		Access forbidden<br>
		<p class='hint'></p>
	</li>
</ul>
				<div class="push"></div>
			</div>
		</div>
		<footer role="contentinfo">
			<p class="info">
				<a href="https://www.actility.com" target="_blank" rel="noreferrer">Actility Shared Storage</a> – Make smarter connections			</p>
		</footer>
	<script>(function(e,c,a,g,f){function d(){var b=c.createElement("script");b.async=!0;b.src="//radar.cedexis.com/1/21830/radar.js";c.body.appendChild(b)}(function(){for(var b=[/\bMSIE (5|6)/i],a=b.length;a--;)if(b[a].test(navigator.userAgent))return!1;return!0})()&&("complete"!==c.readyState?(a=e[a])?a(f,d,!1):(a=e[g])&&a("on"+f,d):d())})(window,document,"addEventListener","attachEvent","load");</script></body>
</html>
`

**Comment by faichelbaum** [comment]
Hi guys, any update ?

**Comment by schiessle** [comment]
I still have no idea how to reproduce it... @rullzer do you have more luck?

**Comment by rullzer** [comment]
I'm betting the error message is NGINX's fault.

Please make sure that 

```
error_page 403 /core/templates/403.php;
error_page 404 /core/templates/404.php;
```

is removed from your nginx config.

**Comment by faichelbaum** [comment]
That worked !

thanks @rullzer

**Comment by krisj** [comment]
@rullzer thanks, thats it, that worked! I wonder why were they recommended in the Doc in the first place. Does it break or remove some other functionality if removed? Certainly fixes this issue though.

**Comment by rullzer** [comment]
Aaah it is still in the old docs I think. Let me fix that right away.

It is to show fancy error pages. But it should only do that when the server can't find the file. If a status code is set by php it should not meddle with it. My nginx foo is not good enough to handle that.

**Comment by rullzer** [comment]
Doc pr in https://github.com/nextcloud/documentation/pull/409

**Comment by rullzer** [comment]
Anyway since it is fixed now lets close this.

**Comment by Micha-Btz** [comment]
I have the same problem with an apache. I chose the mail nc finds the user from my carddav entrys and then it goes wrong.
error from firefox web console, nothing in nextcloud.log

> https://owncloud.xxxxx/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json
> POST Data:
> shareType=4
> shareWith=xxxxxx@online.de
> permissions=15
> path=/share
> Request header
> POST /ocs/v2.php/apps/files_sharing/api/v1/shares?format=json HTTP/1.1
> Host: owncloud.xxxxx
> User-Agent: Mozilla Firefox 53.03
> Accept: application/json, text/javascript, */*; q=0.01
> Accept-Language: en-US,en;q=0.5
> Accept-Encoding: gzip, deflate, br
> Content-Type: application/x-www-form-urlencoded; charset=UTF-8
> requesttoken: BnA9vPxcU9H9B/xLchvKC1j/lmvU2s5keiwj9cV12kw=:Yjlbzo8yGueab8gBKHqkXiKOwzuBr/tVFlZlnrJHvH0=
> OCS-APIREQUEST: true
> X-Requested-With: XMLHttpRequest
> Content-Length: 70
> Cookie: nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; oca2cf00c606=fbb476sqd1201lbve3i60ur864; oc_sessionPassphrase=r1cfyGXtgVf7ycLmtHFk64%2FLKQ95GFMguy%2F9SBUQcVeEWmEHDsuUGAx1FB8Csd96e%2FGn2GQIYPXRHNSyuWK%2BWTSToAiYhAIiYP1o%2B4v1898YFhrow%2BAGeSFGL30Dh6oo
> DNT: 1
> Connection: keep-alive
> Response header
> HTTP/1.1 403 Forbidden
> Date: Tue, 23 May 2017 05:30:20 GMT
> Server: Apache/2.4.10 (Debian)
> X-Powered-By: PHP/7.0.16
> Expires: Thu, 19 Nov 1981 08:52:00 GMT
> Pragma: no-cache
> X-Xss-Protection: 1; mode=block
> X-Content-Type-Options: nosniff
> X-Frame-Options: Sameorigin
> X-Robots-Tag: none
> X-Download-Options: noopen
> X-Permitted-Cross-Domain-Policies: none
> Cache-Control: no-cache, must-revalidate
> Content-Security-Policy: default-src 'none'
> Content-Length: 102
> Keep-Alive: timeout=1, max=1000
> Connection: Keep-Alive
> Content-Type: application/json; charset=utf-8
> 
then the webinterface is showing Public upload not allowed.

**Comment by Micha-Btz** [comment]
@rullzer Can you please reopen this since it is not fixed for all.
