### ISSUE TITLE
[Bug]: scan.nextcloud.com reports "Not on patch level" after update to 28.0.0.11

### ISSUE THREAD

**Issue by mjmccarn** [nextcloud/server#42332]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

scan.nextcloud.com reports "Not on Latest Patch Level" after upgrde to NC 28.0.0.11

### Steps to reproduce

1. Start with Nextcloud 27.1.4
2. Upgrade using `sudo -u www-data php /var/www/nextcloud/updater/updater.phar`
3. Cleanup post-upgrade issues
  `sudo -u www-data php /var/www/nextcloud/occ db:add-missing-indices`
  `sudo -u www-data php /var/www/nextcloud/occ maintenance:mimetype:update-js
  `sudo apt-get install php8.2-bz2
  `sudo -u www-data php /var/www/nextcloud/occ app:update --all`
  `sudo systemctl restart apache2 redis php8.2-fpm`
4. trigger re-scan at https://scan.nextcloud.com/

Rating: A
Running: Nextcloud 28.0.0.11
-  NOT on Latest Patch Level
- Major Version still supported

### Expected behavior

Rating: A+
Running: Nextcloud 28.0.0.11
-  Latest Patch Level
- Major Version still supported

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "scanresult": "\/results\/fa3a7d24-4303-4cda-8b05-52bd288c9382",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.200.167",
            "cloud.mmsionline.us"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "default_language": "en_US",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "auto_logout": false,
        "token_auth_enforced": false,
        "auth.bruteforce.protection.enabled": true,
        "auth.webauthn.enabled": true,
        "hide_login_form": false,
        "skeletondirectory": "",
        "tempdirectory": "\/var\/www\/nc-temp",
        "overwrite.cli.url": "https:\/\/cloud.mmsionline.us\/",
        "overwritehost": "cloud.mmsionline.us",
        "htaccess.RewriteBase": "\/",
        "updatedirectory": "\/var\/www\/updater",
        "dbtype": "pgsql",
        "version": "28.0.0.11",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 1.5
        },
        "loglevel": 2,
        "log_rotate_size": 104857600,
        "logfile": "\/var\/www\/nc-log\/nextcloud.log",
        "log.condition": {
            "apps": [
                "user_external"
            ]
        },
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            },
            {
                "path": "\/var\/www\/nextcloud\/local",
                "url": "\/local",
                "writable": true
            }
        ],
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Krita"
        ],
        "asset-pipline.enabled": true,
        "user_backends": [
            {
                "class": "\\OCA\\UserExternal\\IMAP",
                "arguments": [
                    "outlook.office365.com",
                    993,
                    "ssl",
                    "aicr.org",
                    false,
                    true,
                    true
                ]
            },
            {
                "class": "\\OCA\\UserExternal\\IMAP",
                "arguments": [
                    "outlook.office365.com",
                    993,
                    "ssl",
                    "wcrf.org",
                    false,
                    true,
                    true,
                    "@"
                ]
            },
            {
                "class": "\\OCA\\UserExternal\\IMAP",
                "arguments": [
                    "outlook.office365.com",
                    993,
                    "ssl",
                    "wkof.org",
                    false,
                    true,
                    true
                ]
            },
            {
                "class": "\\OCA\\UserExternal\\IMAP",
                "arguments": [
                    "office.mmsionline.us",
                    993,
                    "ssl",
                    "mmsionline.us",
                    true,
                    true,
                    true,
                    ""
                ]
            }
        ],
        "maintenance": false,
        "theme": "",
        "updater.release.channel": "stable",
        "appcodechecker": false,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin",
            "wcrf.org"
        ],
        "twofactor_enforced_excluded_groups": [],
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "passman",
            "imap_auth_aicr",
            "issuetemplate",
            "sociallogin",
            "dicomviewer",
            "impersonate",
            "files_mindmap"
        ],
        "onlyoffice": {
            "verify_peer_off": true,
            "timeout": 5,
            "editors_check_interval": 90
        },
        "allow_local_remote_servers": true,
        "default_phone_region": "US",
        "mail_sendmailmode": "smtp"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - analytics: 4.12.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - dicomviewer: 1.2.5
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_external: 1.20.0
  - files_mindmap: 0.0.30
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - impersonate: 1.15.0
  - integration_github: 2.0.6
  - integration_gitlab: 1.0.18
  - integration_openai: 1.1.5
  - integration_openproject: 2.5.1
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - mail: 3.5.0
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.1
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - onlyoffice: 9.0.0
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - sociallogin: 5.6.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_email: 2.7.4
  - twofactor_totp: 10.0.0-beta.2
  - twofactor_webauthn: 1.3.2
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - bruteforcesettings: 2.8.0 (installed 1.5.0)
  - drawio: 2.1.4 (installed 2.1.4)
  - encryption: 2.16.0 (installed 2.15.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - imap_auth_aicr: 0.1.3 (installed 0.1.3)
  - maps: 1.3.1 (installed 1.3.1)
  - music: 1.9.1 (installed 1.9.1)
  - registration: 2.2.0 (installed 2.2.0)
  - sharepoint: 1.15.0 (installed 1.15.0)
  - sociallogin-aicr: 3.4.1 (installed 3.4.1)
  - spreed: 18.0.1 (installed 18.0.1)
  - suspicious_login: 6.0.0 (installed 5.0.0)
  - twofactor_nextcloud_notification: 3.8.0 (installed 3.8.0)
  - user_external: 3.2.0 (installed 3.2.0)
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

```shell
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 550ab566d30693bfa24ec4b15d9df87731ae8a3be8f79dabf94757e5b8b20eec6e4b678f17af1718297f2872f6b04519eeb024d1dff11947f29da431c7f11201
                            [current] => 24e6faa4a1361e51ff70027024f41c4b37fdb5f6f347ceb095450ddbde2d0a6b6dd1403be92a912d2889064a9736a9bed89d7dc62470035fc1299d4b977c5f46
                        )

                )

        )

)
```

### Nextcloud Logs

```shell
I'll add these if you really think it will help.

Mostly, my logs show `User backend \OCA\UserExternal\IMAP not found. `
```

**Comment by Bad-and-Mad** [comment]
Same here after update to version 28.0.0.11 last week.

**Comment by joshtrichards** [comment]
Cc: @blizzz

**Comment by blizzz** [comment]
> Cc: @blizzz

Waiting internally, sorry, but should be sorted out soon.

**Comment by Altahrim** [comment]
Hello,

I fixed it this morning :) Should be working now.

**Comment by TaneshimaPopura** [comment]
I think this is not solved.

after I update to 28.0.1

there is more files message

```
Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 550ab566d30693bfa24ec4b15d9df87731ae8a3be8f79dabf94757e5b8b20eec6e4b678f17af1718297f2872f6b04519eeb024d1dff11947f29da431c7f11201
                            [current] => 301654cbbe168b8723530db88fd2e40ad688f4e6b0bdaeade5b4fe34bd94d9d3cfe760821e97dc792e585d4b6ccff838597bfd46466bb07d30ff84df4cb79518
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [core/img/filetypes/drawio.svg] => Array
                        (
                            [expected] => 
                            [current] => 92e0974cf869bf8ab969c3442dc2b80d55fde36441d22924db74916a06b407520aa2a9dc39336f9157195ebede697ffac0e639360879255ab91932d406e1897d
                        )

                    [core/img/filetypes/dwb.svg] => Array
                        (
                            [expected] => 
                            [current] => 43731dd5f17a048112ea5109b40b02ec019b3ee2324385a0f448e3bd2264cb13dc160ab018d893f92f8e2f168fd09009b51578c8c6b97a02a1617c67ac087701
                        )

                )

        )

)
```

**Comment by TaneshimaPopura** [comment]
OK,
there's no error after I remove drawio app.

**Comment by jjasoncool** [comment]
@Altahrim Can you give some advice when this issue happened?
I have same issue after update to 28.0.1

**Comment by joshtrichards** [comment]
@TaneshimaPopura Your situation has nothing to do with this issue. I suggest posting to the Nextcloud Help Forum for assistance - https://help.nextcloud.com
