### ISSUE TITLE
Internal Server Error aftter sharing via iCal

### ISSUE THREAD

**Issue by alve89** [nextcloud/server#4241]
I tried to share a calendar via iCal link. After opening this link I got the following error message: 
![06-04-2017 10-12-41](https://cloud.githubusercontent.com/assets/11487054/24744279/c693c1e8-1ab1-11e7-80c7-f44dc7cfd1b7.png)

Logging shows this fatal error:
```
Sabre\VObject\InvalidDataException: Unsupported VALUE parameter for DTEND property. You supplied ""

    /cloud/LIVE/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 453: Sabre\VObject\Document->createProperty('DTEND', NULL, Array)
    /cloud/LIVE/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 234: Sabre\VObject\Parser\MimeDir->readProperty('DTEND;TZID=Euro...')
    /cloud/LIVE/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 217: Sabre\VObject\Parser\MimeDir->parseLine('DTEND;TZID=Euro...')
    /cloud/LIVE/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 181: Sabre\VObject\Parser\MimeDir->parseLine('BEGIN VEVENT')
    /cloud/LIVE/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 89: Sabre\VObject\Parser\MimeDir->parseDocument()
    /cloud/LIVE/3rdparty/sabre/vobject/lib/Reader.php - line 46: Sabre\VObject\Parser\MimeDir->parse('BEGIN VCALENDAR...', 0)
    /cloud/LIVE/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php - line 307: Sabre\VObject\Reader read('BEGIN VCALENDAR...')
    /cloud/LIVE/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php - line 225: Sabre\CalDAV\ICSExportPlugin->mergeObjects(Array, Array)
    /cloud/LIVE/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php - line 151: Sabre\CalDAV\ICSExportPlugin->generateResponse('public-calendar...', NULL, NULL, false, false, 'text/calendar', Array, Object(Sabre\HTTP\Response))
    [internal function] Sabre\CalDAV\ICSExportPlugin->httpGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /cloud/LIVE/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /cloud/LIVE/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method GET', Array)
    /cloud/LIVE/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /cloud/LIVE/apps/dav/lib/Server.php - line 227: Sabre\DAV\Server->exec()
    /cloud/LIVE/apps/dav/appinfo/v2/remote.php - line 30: OCA\DAV\Server->exec()
    /cloud/LIVE/remote.php - line 165: require_once('/www/htdocs/w01...')
    {main}
```

What's the problem?

**Comment by MorrisJobke** [comment]
Should be fixed by #4066 - we will release the fix with 11.0.3 next week.

**Comment by MorrisJobke** [comment]
cc @nickvergessen @rullzer

**Comment by alve89** [comment]
Well this problem is still unsolved.
Nextcloud 11.0.3
Calendar app 1.5.3

Or at least it is still not working (I tried to import the calendar in Outlook):
`{"reqId":"WSKlZ1UNgrgAABt9haAAAAAM","remoteAddr":"195.65.152.65","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/w013e4e2\/mydomain.tld\/cloud\/LIVE\/lib\/private\/TempManager.php#189","level":3,"time":"2017-05-22T08:46:31+00:00","method":"GET","url":"\/cron.php","user":"--","version":"11.0.3.2"}
{"reqId":"WSKlgVUNgrgAABWLcFAAAAAJ","remoteAddr":"195.65.152.65","app":"webdav","message":"Exception: {\"Message\":\"Unsupported VALUE parameter for DTEND property. You supplied \\\"\\\"\",\"Exception\":\"Sabre\VObject\InvalidDataException\",\"Code\":0,\"Trace\":\"#0 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(453): Sabre\VObject\Document->createProperty('DTEND', NULL, Array)\\n#1 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(234): Sabre\VObject\Parser\MimeDir->readProperty('DTEND;TZID=Euro...')\\n#2 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(217): Sabre\VObject\Parser\MimeDir->parseLine('DTEND;TZID=Euro...')\\n#3 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(181): Sabre\VObject\Parser\MimeDir->parseLine('BEGIN:VEVENT')\\n#4 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(89): Sabre\VObject\Parser\MimeDir->parseDocument()\\n#5 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/vobject/lib/Reader.php(46): Sabre\VObject\Parser\MimeDir->parse('BEGIN:VCALENDAR...', 0)\\n#6 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php(307): Sabre\VObject\Reader::read('BEGIN:VCALENDAR...')\\n#7 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php(225): Sabre\CalDAV\ICSExportPlugin->mergeObjects(Array, Array)\\n#8 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php(151): Sabre\CalDAV\ICSExportPlugin->generateResponse('public-calendar...', NULL, NULL, false, false, 'text/calendar', Array, Object(Sabre\HTTP\Response))\\n#9 [internal function]: Sabre\CalDAV\ICSExportPlugin->httpGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\\n#10 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#11 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter->emit('method:GET', Array)\\n#12 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\\n#13 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/apps/dav/lib/Server.php(231): Sabre\DAV\Server->exec()\\n#14 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/apps/dav/appinfo/v2/remote.php(30): OCA\DAV\Server->exec()\\n#15 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/remote.php(165): require_once('/www/htdocs/w01...')\\n#16 {main}\",\"File\":\"/www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/vobject/lib/Document.php\",\"Line\":220,\"User\":false}","level":4,"time":"2017-05-22T08:46:58+00:00","method":"GET","url":"\/remote.php\/dav\/public-calendars\/ALB6B0WK3XIQM57L?export","user":"--","version":"11.0.3.2"}`


And I tried to download it with its link:

`{"reqId":"WSKmhVUNgrgAAFQER84AAAAW","remoteAddr":"195.65.152.65","app":"webdav","message":"Exception: {\"Message\":\"Unsupported VALUE parameter for DTEND property. You supplied \\\"\\\"\",\"Exception\":\"Sabre\VObject\InvalidDataException\",\"Code\":0,\"Trace\":\"#0 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(453): Sabre\VObject\Document->createProperty('DTEND', NULL, Array)\\n#1 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(234): Sabre\VObject\Parser\MimeDir->readProperty('DTEND;TZID=Euro...')\\n#2 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(217): Sabre\VObject\Parser\MimeDir->parseLine('DTEND;TZID=Euro...')\\n#3 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(181): Sabre\VObject\Parser\MimeDir->parseLine('BEGIN:VEVENT')\\n#4 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(89): Sabre\VObject\Parser\MimeDir->parseDocument()\\n#5 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/vobject/lib/Reader.php(46): Sabre\VObject\Parser\MimeDir->parse('BEGIN:VCALENDAR...', 0)\\n#6 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php(307): Sabre\VObject\Reader::read('BEGIN:VCALENDAR...')\\n#7 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php(225): Sabre\CalDAV\ICSExportPlugin->mergeObjects(Array, Array)\\n#8 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php(151): Sabre\CalDAV\ICSExportPlugin->generateResponse('public-calendar...', NULL, NULL, false, false, 'text/calendar', Array, Object(Sabre\HTTP\Response))\\n#9 [internal function]: Sabre\CalDAV\ICSExportPlugin->httpGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\\n#10 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#11 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter->emit('method:GET', Array)\\n#12 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\\n#13 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/apps/dav/lib/Server.php(231): Sabre\DAV\Server->exec()\\n#14 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/apps/dav/appinfo/v2/remote.php(30): OCA\DAV\Server->exec()\\n#15 /www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/remote.php(165): require_once('/www/htdocs/w01...')\\n#16 {main}\",\"File\":\"/www/htdocs/w013e4e2/mydomain.tld/cloud/LIVE/3rdparty/sabre/vobject/lib/Document.php\",\"Line\":220,\"User\":\"stefan\"}","level":4,"time":"2017-05-22T08:51:19+00:00","method":"GET","url":"\/remote.php\/dav\/public-calendars\/ALB6B0WK3XIQM57L?export","user":"stefan","version":"11.0.3.2"}`

**Comment by MorrisJobke** [comment]
This is a new problem. Looks like your temp directory is not writable.

**Comment by alve89** [comment]
Oh, I wanted to delete this line, sorry. The other log entries aren't about the tmp directory.

**Comment by alve89** [comment]
This issue is solved with Nextcloud 12.0.0. Just one more question about sharing: I just imported my calendars in Outlook. Obviously I can't write to them. Is it possible to change that so I can create / edit events from within Outlook?

**Comment by MorrisJobke** [comment]
> Obviously I can't write to them. Is it possible to change that so I can create / edit events from within Outlook?

Please open a new ticket for that. (or first search if there is one available.
