### ISSUE TITLE
[Bug]: after rename, folder stays in edit mode and is not clickable anymore

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#42813]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Rename operation succeeded, but the display stays as follow:
![image](https://github.com/nextcloud/server/assets/87175513/f3384261-ef05-4d1b-8976-531440258c97)

### Steps to reproduce

1. In a folder with many subfolders or files (the list must exceed the display area)
2. Create a new folder
3. It will be placed among folders starting by N
4. Rename that folder so it is starting with a A for example
5. Folder will instantly move among folders starting by A, and will disappear from your screen, and a notification pops at the top right corner sayong the rename operation succeeded
6. Scroll to the renamed folder.
7. It looks like the rename operation is still pending.

This does not happen if the folder you rename stays inside the displayed list of folders.

### Expected behavior

The renamed folder should be in a default state, and clickable.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by maximelehericy** [comment]
https://github.com/nextcloud/server/issues/43052

**Comment by Mer0me** [comment]
The problem occurs when renaming files as well  :

1. Go to a folder with more files than the screen can display at once.
2. Create a file named "a.txt"
3. Rename this file "z.txt", it goes at the end of the list, but stays in edit name mode, it's stuck, you can't do anything but reload the page

Note that if you rename z.txt in a.txt, it works ! The file goes at the top of the list and it is ready to use.
If you rename and the file stays in the screen, it also works.

So the problem occurs when you rename a file (or a folder) and it's sent **lower** and out of the screen.

**Comment by Mer0me** [comment]
Renaming files and folders is becoming tricky : sometimes, the filename field content is not highlighted after selecting rename action. So you click on the field to place the cursor on the name you want to edit but... It opens the file !

Tested on two different instances of Nextcloud 29.0.3


https://github.com/user-attachments/assets/64ca6635-3106-4594-a7bb-cee80c3bd839

**Comment by Mer0me** [comment]
With NC 29.0.4, renaming will not open the file when you click on the name, but, the name is not updated unless you reload the page. And now, it's when your new filename send the file away at the top of the list that freeze the name in edit mode !

**Comment by susnux** [comment]
This is a combination of 3 different bugs, happy to announce that at least for master branch all of them are now fixed, backports should be included in next maintenance release.

**Comment by Mer0me** [comment]
Just tried 29.0.5 and the bug is only partially fixed :
- When renaming, the old name is selected but immediately deselected, you have to click on the name to edit it
- If you rename a file and the new name sends the file at the bottom of the list, not visible on screen, then the folder stays in edit mode and you need to reload the page.

Is it supposed to be completely fixed in 29.0.5 ?
