### ISSUE TITLE
[Bug]: In 28.0.0-2 context menu "Leave this share" is replaced with "Delete"

### ISSUE THREAD

**Issue by antoninchadima** [nextcloud/server#43314]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading to the Nextcloud 28 the context menu "Leave this share" is replaced with "Delete".
If you do this action on a directory or file inside the share and you have rights to delete items - it deletes the item.
If you do this action on the actual share and you have rights to delete items - it leaves the share without deleting anything.
If you **don't have rights to delete items** inside the share - the menu item "Delete" is **not displayed** and you cannot leave the share.

I have hoped that the 28.0.2 update will solve this issue 
Fix(files): fix unshare action and merge duplicate shares (server#42703)
But it didn't fix it.

I have gone through all the bugreports related to this issue, but my issue seems to be a little specific (with the rights etc.).
I am using Nextcloud on 4 production servers and all of them have the same behavior.
Before the upgrade I was running on all 4 servers with the **"Right click" app**.

My servers are docker, all in one, VM appliance and manual installation.
 

### Steps to reproduce

1. use Nextcloud 27 -> Leave this share
2. (have "Right click" app installed)
3. update to Nextcloud 28 -> Delete (only if you have delete items rights)

### Expected behavior

Context menu on top level shared folders and files "Leave this share" even if you don't have rights to delete items.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "data.localdomain",
            "data.ucl.cas.cz"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "overwrite.cli.url": "https:\/\/data.ucl.cas.cz",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "theme": "",
        "default_phone_region": "CZ",
        "loglevel": 2,
        "maintenance": false,
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": true,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "data.ucl.cas.cz",
        "lost_password_link": "disabled",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "",
        "data-fingerprint": "8787a8ca1800ba217a58f741d56de641",
        "updater.release.channel": "stable",
        "auth.webauthn.enabled": false,
        "defaultapp": "",
        "app_install_overwrite": [
            "files_rightclick"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - cloud_federation_api: 1.11.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - impersonate: 1.15.0
  - lookup_server_connector: 1.16.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - onlyoffice: 9.0.0
  - photos: 2.4.0
  - provisioning_api: 1.18.0
  - settings: 1.10.1
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - unroundedcorners: 1.1.2
  - user_ldap: 1.19.0
  - user_usage_report: 1.12.0
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0 (installed 1.17.0)
  - bruteforcesettings: 2.8.0 (installed 2.7.0)
  - circles: 28.0.0-dev (installed 27.0.1)
  - comments: 1.18.0 (installed 1.17.0)
  - contactsinteraction: 1.9.0 (installed 1.8.0)
  - dashboard: 7.8.0 (installed 7.1.0)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 0.0.4)
  - files_external: 1.20.0 (installed 1.18.0)
  - files_reminders: 1.1.0 (installed 1.0.0)
  - firstrunwizard: 2.17.0 (installed 1.1)
  - logreader: 2.13.0 (installed 2.12.0)
  - nextcloud_announcements: 1.17.0 (installed 1.16.0)
  - password_policy: 1.18.0 (installed 1.17.0)
  - privacy: 1.12.0 (installed 1.5.0)
  - recommendations: 2.0.0 (installed 1.4.0)
  - related_resources: 1.3.0 (installed 1.2.0)
  - serverinfo: 1.18.0 (installed 1.17.0)
  - sharebymail: 1.18.0 (installed 1.17.0)
  - support: 1.11.0 (installed 1.4.0)
  - survey_client: 1.16.0 (installed 1.9.0)
  - suspicious_login: 6.0.0 (installed 5.0.0)
  - systemtags: 1.18.0 (installed 1.17.0)
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0 (installed 1.17.0)
  - user_status: 1.8.1 (installed 1.7.0)
  - weather_status: 1.8.0 (installed 1.1.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by susnux** [comment]
@skjnldsv was fixed or 28.0.2, no?

**Comment by antoninchadima** [comment]
@skjnldsv , yes i went through all the links - bug reports,
but it wasn't fixed in 28.0.2

If you **don't have rights to delete** items inside the share - the menu item "Delete" is not displayed and you **cannot leave the share**.

This is the problem.

**Comment by skjnldsv** [comment]
> it wasn't fixed in 28.0.2

You can see the issue is stiill opened and the link I gave shows `Nextcloud 29` :)
It will be backported to 28.0.3 though!

**Comment by antoninchadima** [comment]
thanks @skjnldsv 

looking forward to 28.0.3
(minimally i know what to say to the users...)
