### ISSUE TITLE
[Bug]: Translate text at Files -> "Add" ("New") button

### ISSUE THREAD

**Issue by drlight17** [nextcloud/server#44723]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When open /apps/files button "+ Add" changes to "+ New" during page loading. In ru translation it changes from "+ Добавить" to "+ New" instead of "Добавить" remain.

While loading:
![image](https://github.com/nextcloud/server/assets/37434652/51897091-696f-43e1-aed4-b6995e11d3fe)

After fully loaded:
![image](https://github.com/nextcloud/server/assets/37434652/0b44c9e5-0b8a-47e0-8c11-bad7cab9e456)

### Steps to reproduce

1. Just open apps/files/
2. Wait the page to be fully loaded

### Expected behavior

"+ Add"  button should remain the same instead of change to something. Or it must change to the proper value. But, for example, in ru locale it changes from "+ Добавить" to "+ New".

### Installation method

Official All-in-One appliance

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "one-click-instance": true,
        "one-click-instance.user-limit": 100,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "appsallowlist": false,
        "check_data_directory_permissions": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwritehost": "cloud.kgilc.ru",
        "overwriteprotocol": "https",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.kgilc.ru"
        ],
        "default_language": "ru",
        "force_language": "ru",
        "default_locale": "ru_RU",
        "force_locale": "ru_RU",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "dbtype": "pgsql",
        "version": "28.0.3.2",
        "overwrite.cli.url": "https:\/\/cloud.kgilc.ru\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": "2",
        "log_type": "file",
        "logfile": "\/var\/www\/html\/data\/nextcloud.log",
        "log_rotate_size": "10485760",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "enabledPreviewProviders": {
            "1": "OC\\Preview\\Image",
            "2": "OC\\Preview\\MarkDown",
            "3": "OC\\Preview\\MP3",
            "4": "OC\\Preview\\TXT",
            "5": "OC\\Preview\\OpenDocument",
            "6": "OC\\Preview\\Movie",
            "7": "OC\\Preview\\Krita",
            "8": "OC\\Preview\\Imaginary",
            "9": "OC\\Preview\\PNG",
            "10": "OC\\Preview\\JPEG",
            "11": "OC\\Preview\\GIF",
            "12": "OC\\Preview\\HEIC",
            "13": "OC\\Preview\\BMP",
            "14": "OC\\Preview\\XBitmap",
            "15": "OC\\Preview\\MarkDown",
            "16": "OC\\Preview\\MSOffice2003",
            "17": "OC\\Preview\\MSOffice2007",
            "18": "OC\\Preview\\MSOfficeDoc",
            "19": "OC\\Preview\\PDF",
            "20": "OC\\Preview\\Photoshop",
            "21": "OC\\Preview\\StarOffice",
            "22": "OC\\Preview\\SVG",
            "23": "OC\\Preview\\TIFF",
            "24": "OC\\Preview\\Font",
            "0": "OC\\Preview\\Imaginary"
        },
        "enable_previews": true,
        "upgrade.disable-web": true,
        "mail_smtpmode": "smtp",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "activity_expire_days": "30",
        "simpleSignUpLink.shown": false,
        "share_folder": "\/Shared",
        "one-click-instance.link": "https:\/\/nextcloud.com\/all-in-one\/",
        "upgrade.cli-upgrade-link": "https:\/\/github.com\/nextcloud\/all-in-one\/discussions\/2726",
        "updatedirectory": "\/nc-updater",
        "maintenance_window_start": 100,
        "allow_local_remote_servers": true,
        "davstorage.request_timeout": 3600,
        "htaccess.RewriteBase": "\/",
        "dbpersistent": false,
        "files_external_allow_create_new_local": false,
        "session_lifetime": 259200,
        "remember_login_cookie_lifetime": 259200,
        "session_keepalive": true,
        "filesystem_check_changes": 0,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "preview_imaginary_url": "***REMOVED SENSITIVE VALUE***",
        "preview_imaginary_key": "21436ba292f0b7784b151a74ae45e569265e68734783bb1f",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "enforce_theme": "",
        "integrity.check.disabled": true,
        "allow_user_to_change_display_name": false,
        "oidc_login_client_id": "cloud-kgilc-client",
        "oidc_login_client_secret": "nYAhlaIZjKdgDnbxzsvrUiD3WcBN85uN",
        "oidc_login_provider_url": "https:\/\/kc.arcticdigital.ru\/realms\/ad_loc_ldap",
        "oidc_login_button_text": "\u0412\u043e\u0439\u0442\u0438 \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438",
        "oidc_login_end_session_redirect": true,
        "oidc_login_logout_url": "https:\/\/cloud.kgilc.ru\/apps\/oidc_login\/oidc",
        "oidc_login_auto_redirect": false,
        "oidc_login_redir_fallback": true,
        "oidc_login_attributes": {
            "id": "preferred_username",
            "ldap_uid": "preferred_username"
        },
        "oidc_login_proxy_ldap": true,
        "oidc_login_disable_registration": true,
        "debug": true,
        "auth.webauthn.enabled": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - cloud_federation_api: 1.11.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - lookup_server_connector: 1.16.0
  - oauth2: 1.16.3
  - provisioning_api: 1.18.0
  - settings: 1.10.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - activity: 2.20.0 (installed 2.20.0)
  - admin_audit: 1.18.0 (installed 1.18.0)
  - breezedark: 27.0.0 (installed 27.0.0)
  - bruteforcesettings: 2.8.0 (installed 2.8.0)
  - calendar: 4.6.7 (installed 4.6.7)
  - cfg_share_links: 5.0.0 (installed 5.0.0)
  - circles: 28.0.0-dev (installed 28.0.0-dev)
  - comments: 1.18.0 (installed 1.18.0)
  - contacts: 5.5.3 (installed 5.5.3)
  - contactsinteraction: 1.9.0 (installed 1.9.0)
  - dashboard: 7.8.0 (installed 7.8.0)
  - deck: 1.12.2 (installed 1.12.2)
  - drawio: 3.0.2 (installed 3.0.2)
  - encryption: 2.16.0
  - external: 5.3.1 (installed 5.3.1)
  - extract: 1.3.6 (installed 1.3.6)
  - federation: 1.18.0 (installed 1.18.0)
  - files_external: 1.20.0 (installed 1.20.0)
  - files_fulltextsearch: 28.0.0 (installed 28.0.0)
  - files_linkeditor: 1.1.19 (installed 1.1.19)
  - files_pdfviewer: 2.9.0 (installed 2.9.0)
  - files_reminders: 1.1.0 (installed 1.1.0)
  - files_sharing: 1.20.0 (installed 1.20.0)
  - files_trashbin: 1.18.0 (installed 1.18.0)
  - files_versions: 1.21.0 (installed 1.21.0)
  - firstrunwizard: 2.17.0 (installed 2.17.0)
  - fulltextsearch: 28.0.1 (installed 28.0.1)
  - fulltextsearch_elasticsearch: 28.0.1 (installed 28.0.1)
  - group_default_quota: 0.1.8 (installed 0.1.8)
  - groupfolders: 16.0.6 (installed 16.0.6)
  - guests: 3.0.1 (installed 3.0.1)
  - impersonate: 1.15.0 (installed 1.15.0)
  - jsloader: 1.5.0 (installed 1.5.0)
  - keeweb: 0.6.17 (installed 0.6.17)
  - ldap_contacts_backend: 1.8.0 (installed 1.8.0)
  - ldap_write_support: 1.10.0 (installed 1.10.0)
  - logreader: 2.13.0 (installed 2.13.0)
  - nextcloud-aio: 0.5.0 (installed 0.5.0)
  - nextcloud_announcements: 1.17.0 (installed 1.17.0)
  - notes: 4.9.4 (installed 4.9.4)
  - notifications: 2.16.0 (installed 2.16.0)
  - notify_push: 0.6.10 (installed 0.6.10)
  - oidc_login: 3.0.2 (installed 3.0.2)
  - onlyoffice: 9.0.0 (installed 9.0.0)
  - password_policy: 1.18.0 (installed 1.18.0)
  - photos: 2.4.0 (installed 2.4.0)
  - privacy: 1.12.0 (installed 1.12.0)
  - quota_warning: 1.19.0 (installed 1.19.0)
  - recommendations: 2.0.0 (installed 2.0.0)
  - related_resources: 1.3.0 (installed 1.3.0)
  - serverinfo: 1.18.0 (installed 1.18.0)
  - sharebymail: 1.18.0 (installed 1.18.0)
  - side_menu: 3.11.8 (installed 3.11.8)
  - spreed: 18.0.6 (installed 18.0.6)
  - support: 1.11.0 (installed 1.11.0)
  - survey_client: 1.16.0 (installed 1.16.0)
  - suspicious_login: 6.0.0 (installed 6.0.0)
  - systemtags: 1.18.0 (installed 1.18.0)
  - tasks: 0.15.0 (installed 0.15.0)
  - text: 3.9.1 (installed 3.9.1)
  - theming_customcss: 1.15.0 (installed 1.15.0)
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0 (installed 1.19.0)
  - user_status: 1.8.1 (installed 1.8.1)
  - weather_status: 1.8.0 (installed 1.8.0)
```

**Comment by susnux** [comment]
This is already fixed in 28.0.4

ref: https://github.com/nextcloud/server/pull/43858

**Comment by SadmL** [comment]
Nextcloud 29.0.3
Still presists
Recent files: 
![изображение](https://github.com/nextcloud/server/assets/30765190/146e052b-e81a-45a4-815f-e28501409387)
But in all files
![изображение](https://github.com/nextcloud/server/assets/30765190/6aa23360-99e8-4606-96d7-f8555cccd7d1)

Cache is cleared, tested on Chromium and Librewolf.

**Comment by pkejval** [comment]
Still happening to me with Czech language. When page is loading, translation is shown well but after page is fully loaded it switches to English.

Nextcloud AIO - latest version - Nextcloud Hub 8 (29.0.3)

![obrazek](https://github.com/user-attachments/assets/eb88e13c-e532-46a6-a616-1d7ebcafee6e)

**Comment by susnux** [comment]
Problem seem to be old localizations that hide the new ones (there is `cs` and `cs_CZ`)

**Comment by SadmL** [comment]
@susnux 
I guess we need to wait 29.0.4? Or we can patch it manually?

**Comment by susnux** [comment]
Too late for 29.0.4 RC1 is already released, will be included in 29.0.5.
I do not think patching is (with reasonable effort) possible.

**Comment by SadmL** [comment]
@susnux 
No changes after upgrade to 29.0.5.
Non translated `+ New` button still presence.
Tested again on FF (Librewolf) and Chromium.

**Comment by SadmL** [comment]
Updated to 29.0.6. Can confirm that button is translated now.

**Comment by uuwang** [comment]
Hi guys, I upgrade to 30.0.1 from 29.0.7 and 29.0.8, but this bug is still exists, what can i do to fix it myself.

**Comment by susnux** [comment]
@uuwang which language?

**Comment by uuwang** [comment]
> [@uuwang](https://github.com/uuwang) which language?

zh_CN

**Comment by uuwang** [comment]
@susnux Taking zh_CN as an example, through debugging, I found the cause of the problem. First, the translation of "New" takes effect because of apps/files/i10n/zh_CN.js, but after loading dist/files-main.js, the translation of "New" fails because the translation in dist/files-main.js is missing. I fix it just by fill it in. At the same time, “ Upload from device”,"Upload folders","Create new"are also missing. What I don't understand is why dist/files-main.js has a higher priority than apps/files/i10n/zh_CN.js。

**Comment by susnux** [comment]
Was simply not translated. Translation was added in nextcloud-upload 1.6.1
So resolved with https://github.com/nextcloud/server/pull/48802
