### ISSUE TITLE
[Bug]: Auto logout with and without inactivity - 28.0.5 & 29.0.0

### ISSUE THREAD

**Issue by daebak74** [nextcloud/server#45132]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

With the latest update from 28.0.4 -> 28.0.5, I encountered the following problem: auto logout after about 30 minutes of inactivity, sometimes even without this pause of non-use. I still have a version in 28.0.4 and I checked the config.php file and it’s identical. On version 28.0.5, I also tried to add the following parameters in config.php but the result does not change:

‘session_lifetime’ => 86400, ‘session_keepalive’ => true, ‘auto_logout’ => false,

### Steps to reproduce

1. Login
2. Auto logout
3.

### Expected behavior

Login
Not auto Logout

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by SystemKeeper** [comment]
Please try to apply https://github.com/nextcloud/server/pull/45093. it is for 29, but the changes can be done for 28 as well until the backport is done.

**Comment by bcutter** [comment]
Looks like this is the same issue here, isn't it?

https://help.nextcloud.com/t/nextcloud-randomly-logs-out-in-browsers/165107/20

**Comment by heisenbol** [comment]
#45093 fixed this for me for 28.0.5

**Comment by Karamelmar** [comment]
for us https://github.com/nextcloud/server/pull/45093 did fix the auto logout error but Nextcloud Office / Collabora Code could not access the files any more, so we had to choose whats more important, NC Office or a reliable Talk App.
A general question:
Does the Maintenance and Release Schedule, in this case for 28.0.6 (2024-05-23) and 29.0.1 (2024-05-23), also apply to critical  issues like that or are hotfixes rolled out via the Updater earlier?

**Comment by daebak74** [comment]
Hi @SystemKeeper  unfortunately the logout also occurs during operations such as inserting an appointment in the calendar with the need to repeat the operation. Does version 28.0.6 include the fix for this problem? Thank you!

**Comment by susnux** [comment]
Fixed with 28.0.6

**Comment by roelofz** [comment]
It looks this still isn´t fixed completely:
I reported this in the AIO part, was advised to ask it here:


### Steps to reproduce
1. Configure config.php as follows:
  'remember_login_cookie_lifetime' => '43200',
  'session_lifetime' => '43200',
  'session_keepalive' => 'true',
  'auto_logout' => true,
Tested with multiple browsers (Edge and Firefox, no tracking protection for the nextcloud interface.
With the default settings, the session does not close

### Expected behavior
The session should be closed after 12 hours

### Actual behavior
The session is closed after less then half an hour
In some case it was possible after more then 12 hours to go back to the last page (Snappymail) without reauthenticating

### Host OS 
Ubuntu 22.04.4
#### Docker run command or docker-compose file that you used
    nextcloud-aio-mastercontainer:
      image: nextcloud/all-in-one:latest
      init: true
      container_name: nextcloud-aio-mastercontainer
      restart: unless-stopped
      volumes:
        - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
        - /var/run/docker.sock:/var/run/docker.sock:ro
      ports:
        - 8091:8080

      environment:
        - APACHE_PORT=11000
        - APACHE_IP_BINDING=0.0.0.0
        - NEXTCLOUD_DATADIR=/mnt/nextcloud
        - NEXTCLOUD_MOUNT=/mnt/nc-filedata
        - NEXTCLOUD_MEMORY_LIMIT=1024M
        - AIO_COMMUNITY_CONTAINERS=local-ai
      networks:
        nextcloud:
        frontend:

#### Nextcloud AIO version 
[Nextcloud Hub 8](https://nextcloud.com/) (29.0.4)
I tried asking overhere, but no dice there: https://help.nextcloud.com/t/automatic-disconnection-log-out/82230

Anyone any ideas about this, what can I check, change, do to get this working in a normal manner?

Thanks!
