### ISSUE TITLE
Allow app to specify dependency on other app

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4531]
e.g. sharepoint requires on files_external

**Comment by nickvergessen** [comment]
files_markdown requires files_texteditor

**Comment by nickvergessen** [comment]
workflow engine is required by all the plugins (currently solved by force enabling workflow instead).

So yes, would be really nice to have something like this.

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by bigcat88** [comment]
When will this be done? Needs this ability...

**Comment by DaphneMuller** [comment]
In general it is a product management decision to not support app to app dependencies. There are of course some super specific and controlled cases in which we do have such dependencies like Photos<>Recognize. But I don’t think we should introduce app to app dependencies. Let's talk about it in the meeting later today, of course if there are clear use cases with large impact we can always talk to product management to see if this decision may be reverted.

**Comment by nickvergessen** [comment]
> Let's talk about it in the meeting later today

Which meeting 🤔 
Talk also has some apps that depend on Talk, e.g. the matterbridge integration, etc.

**Comment by DaphneMuller** [comment]
sorry @nickvergessen , I was referring to a meeting with @bigcat88 that was scheduled yesterday.
I discussed this with Frank in the meantime and he has a strong perspective on that it is not good for the ecosystem to proceed with this. I will close this issue for now.

**Comment by nickvergessen** [comment]
I'll reopen it as the request is still valid and useful
