### ISSUE TITLE
[Bug]: The VirtualList of file app drops items on the bottom of the list (while Sidebar content is displayed)

### ISSUE THREAD

**Issue by printminion-co** [nextcloud/server#45668]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The VirtualList of file app does not render the upper part of the file list (when user inspects lower part of the list) while Sidebar content is displayed.
[virtual_list_dropping_file_items-2024-06-04_16.46.09.webm](https://github.com/nextcloud/server/assets/145785698/06831460-dc1c-420b-8699-0ce6a4940e8a)

### Steps to reproduce

1. install https://github.com/nextcloud/server/releases/tag/v29.0.1 
2. install and activate activity app https://github.com/nextcloud/activity/releases/tag/v29.0.2rc2
3. upload folder with images (in order to make the file list scrollable)
4. scroll down to the end of the list
5. click in last x files rows (modified field) in oder to 
6. Observe the upper half of file file items disappears.
7. Scroll a bit. Observe upper half of the file items appears. 

Screencast: [virtual_list_dropping_file_items-2024-06-04_16.46.09.webm](https://github.com/nextcloud/server/assets/145785698/06831460-dc1c-420b-8699-0ce6a4940e8a)

### Expected behavior

The clicking on file items in order to bring Sidebar information on the end of the list does not drop file items in the list.   

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "defaultapp": "files",
        "appstoreenabled": false,
        "updatechecker": false,
        "debug": true,
        "default_language": "de",
        "default_phone_region": "DE",
        "knowledgebaseenabled": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": true
            },
            {
                "path": "\/var\/www\/html\/apps-custom",
                "url": "\/apps-custom",
                "writable": true
            },
            {
                "path": "\/var\/www\/html\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "theme": "foo-theme",
        "overwriteprotocol": "http",
        "trusted_domains": [
            "localhost",
            "localdev",
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "29.0.1.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "updater.release.channel": "git",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - cloud_federation_api: 1.12.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_reminders: 1.2.0
  - files_trashbin: 1.19.0
  - lookup_server_connector: 1.17.0
  - oauth2: 1.17.0
  - provisioning_api: 1.19.0
  - settings: 1.12.0
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0
  - comments: 1.19.0 (installed 1.19.0)
  - contactsinteraction: 1.10.0 (installed 1.10.0)
  - dashboard: 7.9.0 (installed 7.9.0)
  - encryption: 2.17.0
  - files_external: 1.21.0
  - files_sharing: 1.21.0 (installed 1.21.0)
  - files_versions: 1.22.0 (installed 1.22.0)
  - googleanalytics: 0.0.2
  - metadata: 0.20.0
  - sharebymail: 1.19.0 (installed 1.19.0)
  - systemtags: 1.19.0 (installed 1.19.0)
  - testing: 1.19.0
  - updatenotification: 1.19.1 (installed 1.19.1)
  - user_ldap: 1.20.0
  - user_status: 1.9.0 (installed 1.9.0)
  - weather_status: 1.9.0 (installed 1.9.0)
```

**Comment by susnux** [comment]
Fixed with 29.0.3 in https://github.com/nextcloud/server/pull/45611

**Comment by rezaser74** [comment]
This issue remained while trying to move to active files with down arrow key
