### ISSUE TITLE
[Bug]: All file and personal file don't show in Nextcloud 29.0.5

### ISSUE THREAD

**Issue by fdemarchicislveneto** [nextcloud/server#47552]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In section file not show all-file and personal file but if i search it the file is present.

### Steps to reproduce

1. Go to file section and no see file 
2. Go to recent file and it shows

### Expected behavior

I expcted that file is shows

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.cislveneto.it"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.cislveneto.it",
        "dbtype": "mysql",
        "version": "29.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "updater.release.channel": "stable",
        "mail_sendmailmode": "smtp",
        "has_rebuilt_cache": true,
        "app_install_overwrite": [
            "sharerenamer",
            "apporder",
            "files_downloadactivity",
            "admin_notifications",
            "holiday_calendars",
            "files_rightclick",
            "files_texteditor",
            "metadata"
        ],
        "mysql.utf8mb4": true,
        "mail_smtpauthtype": "LOGIN",
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "default_phone_region": "+39",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance_window_start": 1
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - announcementcenter: 6.8.1
  - audioplayer: 3.4.1
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.16
  - calendar_resource_management: 0.8.0
  - carnet: 0.25.6
  - cfg_share_links: 5.1.1
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - deck: 1.13.1
  - event_update_notification: 2.4.0
  - external: 5.4.0
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.1
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_linkeditor: 1.1.20
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.21.0
  - files_texteditor: 2.15.1
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - forms: 4.2.4
  - keeweb: 0.6.19
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - nextcloud_announcements: 1.18.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - polls: 7.2.1
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - quota_warning: 1.20.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.5
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - spreed: 19.0.8
  - support: 1.12.0
  - survey_client: 1.17.0
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0
  - tasks: 0.16.1
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_totp: 11.0.0-dev
  - updatenotification: 1.19.1
  - user_external: 3.4.0
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - accessibility: 1.10.0
  - admin_notifications: 1.0.2 (installed 1.0.2)
  - apporder: 0.15.0 (installed 0.15.0)
  - circles: 29.0.0-dev (installed 0.16.13)
  - encryption: 2.17.0 (installed 2.3.0)
  - files_antivirus: 5.5.7 (installed 5.5.7)
  - files_downloadactivity: 1.17.0 (installed 1.17.0)
  - files_mindmap: 0.0.30 (installed 0.0.30)
  - side_menu: 3.13.1 (installed 3.13.1)
  - user_ldap: 1.20.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"XNnecaJ5aqBTun56wxPb","level":1,"time":"2024-08-27T20:35:03+00:00","remoteAddr":"","user":"--","app":"richdocuments","method":"","url":"--","message":"Fetched remote endpoint from discovery in 0.203 seconds","userAgent":"--","version":"29.0.5.1","data":{"app":"richdocuments"}}
```

### Additional info

 no

**Comment by susnux** [comment]
Is there any error in the browser console?

**Comment by fdemarchicislveneto** [comment]
NS_ERROR_NOT_IMPLEMENTED: Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIAppStartup.secondsSinceLastOSRestart] 
_collectStartupConditionsTelemetry resource:///modules/BrowserGlue.sys.mjs:1851 
BG__onFirstWindowLoaded resource:///modules/BrowserGlue.sys.mjs:1922 
BG_observe resource:///modules/BrowserGlue.sys.mjs:1136 
_delayedStartup chrome://browser/content/browser-init.js:617 
BrowserGlue.sys.mjs:1860:15 
Experiment add-an-image-to-pdf-with-alt-text-rollout has unknown featureId: addAnImageInPDF RemoteSettingsExperimentLoader.sys.mjs:709:21 
<empty string> 2 
Experiment add-an-image-to-pdf-with-alt-text-rollout has unknown featureId: addAnImageInPDF RemoteSettingsExperimentLoader.sys.mjs:709:21 
NotFoundError: No such JSProcessActor 'BrowserToolboxDevToolsProcess' 
AbortError: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved 2 ConduitsParent.sys.mjs:379 
SearchSuggestionController found an unexpected string value: HTTP request timeout SearchSuggestionController.sys.mjs:645:17 

Browser Firefox 129.0.2 



[ https://www.cislveneto.it/ ] 
Francesco De Marchi 
USR CISL Veneto 
cell. 3351364784 
email. [ ***@***.*** | ***@***.*** ] 


Da: "Ferdinand Thiessen" ***@***.***> 
A: "nextcloud/server" ***@***.***> 
Cc: "fdemarchicislveneto" ***@***.***>, "Author" ***@***.***> 
Inviato: Mercoledì, 28 agosto 2024 4:53:32 
Oggetto: Re: [nextcloud/server] [Bug]: All file and personal file don't show in Nextcloud 29.0.5 (Issue #47552) 





Is there any error in the browser console? 

— 
Reply to this email directly, [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnextcloud%2Fserver%2Fissues%2F47552%23issuecomment-2314066483&e=a39aa7eb&h=68463d87&f=y&p=n | view it on GitHub ] , or [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA7WP52E3JTO47IT72RRWWSLZTU3SZAVCNFSM6AAAAABNG5O7HGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMJUGA3DMNBYGM&e=a39aa7eb&h=4c8f7d77&f=y&p=n | unsubscribe ] . 
You are receiving this because you authored the thread. Message ID: ***@***.***> 


-- 
Messaggio analizzato da Libraesva ESG.

**Comment by PeopleInside** [comment]
Hi, I discovered that after upgraded to Nextcloud 29 if files has been uploaded by FTP in the relative user file folder are not visible from the web interface. I don't know if this info helps but reading this issue has remind me this kind of issue. I see also other issues with this new Nextcloud version but i reported in another bug report.

**Comment by susnux** [comment]
@PeopleInside if you upload from outside Nextcloud you need to rescan the directory as otherwise Nextcloud can not detect the changes:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#file-operations

**Comment by susnux** [comment]
@fdemarchicislveneto can you try to [clear the cache](https://support.mozilla.org/en-US/kb/how-clear-firefox-cache)?

**Comment by fdemarchicislveneto** [comment]
Yes! I made it but this not have effect. 

I already make 

occ files:cleanup 

but nothing to do. 
With occ I made a rescan but nothing.... 

occ files:scan <myiduser> 


[ https://www.cislveneto.it/ ] 
Francesco De Marchi 
USR CISL Veneto 
cell. 3351364784 
email. [ ***@***.*** | ***@***.*** ] 


Da: "Ferdinand Thiessen" ***@***.***> 
A: "nextcloud" ***@***.***> 
Cc: "fdemarchicislveneto" ***@***.***>, "Mention" ***@***.***> 
Inviato: Mercoledì, 28 agosto 2024 20:45:58 
Oggetto: Re: [nextcloud/server] [Bug]: All file and personal file don't show in Nextcloud 29.0.5 (Issue #47552) 





[ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Ffdemarchicislveneto&e=a39aa7eb&h=cb2d680e&f=y&p=n | @fdemarchicislveneto ] can you try to [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fsupport.mozilla.org%2Fen-US%2Fkb%2Fhow-clear-firefox-cache&e=a39aa7eb&h=dcdd4211&f=y&p=n | clear the cache ] ? 

— 
Reply to this email directly, [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnextcloud%2Fserver%2Fissues%2F47552%23issuecomment-2316030959&e=a39aa7eb&h=35d9fa31&f=y&p=n | view it on GitHub ] , or [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA7WP52E56SYPMDYXWKNA7V3ZTYLGNAVCNFSM6AAAAABNG5O7HGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMJWGAZTAOJVHE&e=a39aa7eb&h=c023383b&f=y&p=n | unsubscribe ] . 
You are receiving this because you were mentioned. Message ID: ***@***.***> 


-- 
Messaggio analizzato da Libraesva ESG.

**Comment by fdemarchicislveneto** [comment]
No files uploaded in ftp o another method in my case. 


[ https://www.cislveneto.it/ ] 
Francesco De Marchi 
USR CISL Veneto 
cell. 3351364784 
email. [ ***@***.*** | ***@***.*** ] 


Da: "Marco Borla" ***@***.***> 
A: "nextcloud" ***@***.***> 
Cc: "fdemarchicislveneto" ***@***.***>, "Author" ***@***.***> 
Inviato: Mercoledì, 28 agosto 2024 10:59:35 
Oggetto: Re: [nextcloud/server] [Bug]: All file and personal file don't show in Nextcloud 29.0.5 (Issue #47552) 





Hi, I discovered that after upgraded to Nextcloud 29 if files has been uploaded by FTP in the relative user file folder are not visible from the web interface. I don't know if this info helps but reading this issue has remind me this kind of issue. I see also other issues with this new Nextcloud version but i reported in another bug report. 

— 
Reply to this email directly, [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnextcloud%2Fserver%2Fissues%2F47552%23issuecomment-2314744262&e=a39aa7eb&h=3dfb6350&f=y&p=n | view it on GitHub ] , or [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA7WP52DIGBJTAMJ4PCS4YCDZTWGPPAVCNFSM6AAAAABNG5O7HGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMJUG42DIMRWGI&e=a39aa7eb&h=e2fd83dd&f=y&p=n | unsubscribe ] . 
You are receiving this because you authored the thread. Message ID: ***@***.***> 


-- 
Messaggio analizzato da Libraesva ESG.

**Comment by fdemarchicislveneto** [comment]
Appare Only Personal Files and All Files not show the other its ok 


[ https://www.cislveneto.it/ ] 
Francesco De Marchi 
USR CISL Veneto 
cell. 3351364784 
email. [ ***@***.*** | ***@***.*** ] 


Da: "Francesco De Marchi" ***@***.***> 
A: "nextcloud" ***@***.***> 
Inviato: Mercoledì, 28 agosto 2024 22:03:34 
Oggetto: Re: [nextcloud/server] [Bug]: All file and personal file don't show in Nextcloud 29.0.5 (Issue #47552) 


No files uploaded in ftp o another method in my case. 


[ https://www.cislveneto.it/ ] 
Francesco De Marchi 
USR CISL Veneto 
cell. 3351364784 
email. [ ***@***.*** | ***@***.*** ] 


Da: "Marco Borla" ***@***.***> 
A: "nextcloud" ***@***.***> 
Cc: "fdemarchicislveneto" ***@***.***>, "Author" ***@***.***> 
Inviato: Mercoledì, 28 agosto 2024 10:59:35 
Oggetto: Re: [nextcloud/server] [Bug]: All file and personal file don't show in Nextcloud 29.0.5 (Issue #47552) 





Hi, I discovered that after upgraded to Nextcloud 29 if files has been uploaded by FTP in the relative user file folder are not visible from the web interface. I don't know if this info helps but reading this issue has remind me this kind of issue. I see also other issues with this new Nextcloud version but i reported in another bug report. 

— 
Reply to this email directly, [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnextcloud%2Fserver%2Fissues%2F47552%23issuecomment-2314744262&e=a39aa7eb&h=3dfb6350&f=y&p=n | view it on GitHub ] , or [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA7WP52DIGBJTAMJ4PCS4YCDZTWGPPAVCNFSM6AAAAABNG5O7HGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMJUG42DIMRWGI&e=a39aa7eb&h=e2fd83dd&f=y&p=n | unsubscribe ] . 
You are receiving this because you authored the thread. Message ID: ***@***.***> 


-- 
Messaggio analizzato da Libraesva ESG.

**Comment by susnux** [comment]
If you see this in a WebDAV client but not on the webui, then it is a frontend issue and you should see warnings / errors in the browser dev tools, can you check that again?

**Comment by shperrung** [comment]
Thanks for reaction!
!SOLVED!
That one subfolder with missing files of External Storage containing 3 subfolder doesn't show files not only in browser. Android client and DAV client also just show me only sub- subfolders but not files inside.
I detached External Storage with affected subfolder and attached it back to same point as "local storage". Now Nextcloud shows me all subfolders and files inside including affected subfolder. Unfortunately, Memories lost all tags, faces and requires full rescan.

**Comment by susnux** [comment]
Glad to hear the issue is fixed :rocket:

**Comment by fdemarchicislveneto** [comment]
I'm sorry but my bug is not completed and Not Solved! 

In my case all files not show in webui but in Android is all Ok and not is localized on 1 subfolder. 

My personal folder is very Big 160GB and there is many share. 



[ https://www.cislveneto.it/ ] 
Francesco De Marchi 
USR CISL Veneto 
cell. 3351364784 
email. [ ***@***.*** | ***@***.*** ] 


Da: "Ferdinand Thiessen" ***@***.***> 
A: "nextcloud" ***@***.***> 
Cc: "fdemarchicislveneto" ***@***.***>, "Mention" ***@***.***> 
Inviato: Venerdì, 30 agosto 2024 17:35:13 
Oggetto: Re: [nextcloud/server] [Bug]: All file and personal file don't show in Nextcloud 29.0.5 (Issue #47552) 





Closed [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnextcloud%2Fserver%2Fissues%2F47552&e=a39aa7eb&h=cf62e260&f=y&p=n | #47552 ] as completed. 

— 
Reply to this email directly, [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnextcloud%2Fserver%2Fissues%2F47552%23event-14083291679&e=a39aa7eb&h=0f3c0258&f=y&p=n | view it on GitHub ] , or [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA7WP52E5ZQOAIK4Y7QLEN23ZUCGLDAVCNFSM6AAAAABNG5O7HGVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJUGA4DGMRZGE3DOOI&e=a39aa7eb&h=f356255a&f=y&p=n | unsubscribe ] . 
You are receiving this because you were mentioned. Message ID: ***@***.***> 


-- 
Messaggio analizzato da Libraesva ESG.
