### ISSUE TITLE
[Bug]: Drag & Drop upload progress bar does not show for big files

### ISSUE THREAD

**Issue by mgutt** [nextcloud/server#48270]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Drag & Drop showed in the past a progress bar:
https://github.com/nextcloud/server/issues/4164

I think the last time  it worked was in NC28.

### Steps to reproduce

Opened a demo account at https://try.nextcloud.com/ and dropped a file. No progress was visible. The file was uploaded successfully.
I tested with recent Google Chrome. Didn't tested other browsers.

### Expected behavior

Show progress

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
v29.0.7, Chrome.

![image](https://github.com/user-attachments/assets/73cd2032-4946-4845-b395-e28a93b9c443)

**Comment by mgutt** [comment]
> v29.0.7, Chrome.
Did you really use Drag & Drop or did you use the + button? A friend of mine confirmed that if does not work in Chrome with Drag & Drop 😳

**Comment by mTrax-** [comment]
> > v29.0.7, Chrome.
> 
> Did you really use Drag & Drop or did you use the + button? A friend of mine confirmed that if does not work in Chrome with Drag & Drop 😳

I have the same behavior, no progress bar when using file drop while the progress bar is visible when using the "+" button.
Tested with FIrefox, Edge, Chrome, all up to date on Windows 11.

**Comment by solracsf** [comment]
Yes, Drag n Drop an v29.0.7.
Try clear your browser cache?

![explorer_iekajNurO6](https://github.com/user-attachments/assets/493359d8-d64c-4a27-8020-aedb4e14e9df)

**Comment by XueSheng-GIT** [comment]
@solracsf I just tried drag'n'drop in Win11 with Firefox 130 (Nextcloud 29.0.7). For some files the progress bar is shown. For others not at all.
For example, progress bar is not shown for latest nextcloud zip file (using drag'n'drop):
https://download.nextcloud.com/server/releases/latest.zip

Uploading using the `+` works as expected (progress bar is displayed).

Unfortunately, I wasn't able to find a file which works and which I could share (privacy).

**Comment by solracsf** [comment]
Ok this seems to be (maybe) a files size issue because small (<20MiB) works fine, but not bigger files.

**Comment by coinfastman** [comment]
I confirm that after updating to 29.0.7, such a problem appeared. When I upload large files, the progress bar is there until the very end of the file download, but when chunks start to be collected in the background, the progress bar disappears and there is no status about the successfully downloaded file, after some time the file appears in the interface. That is:
1) the progress bar disappears
2) There is no notification about the successfully downloaded file

**Comment by sinohiro** [comment]
This issue was confirmed in Nextcloud 30 as well. 
When files are dragged and uploaded from the web browser, the progress bar works normally for files under 20MB, but it does not display when uploading files larger than that. Since it works correctly in the client app, I believe this problem only occurs in the web browser.

**Comment by VieuFou34** [comment]
Hi,

I have the same issue in the 29.0.7 / firefox-edge. Draggin the file does not make the bar show up. Using the + button works.

Thx

**Comment by NepBlanc** [comment]
I also have the issue in 30.0.0 /firefox-edge uploading large files with drag and drop does not show the ui at all!
have not tried the + button but I assume it is the same

**Comment by solracsf** [comment]
Let me just add that, sometimes, it just stucks at "Estimating Time Left" while uploads happens in the background.

![image](https://github.com/user-attachments/assets/d5ab774c-b9f5-4a63-9691-7e0b062e2658)

**Comment by julien-nc** [comment]
This seems to be related with chunk upload.
This only happens when chunk upload is enabled (default `max_chunk_size` value in Files app config).
After disabling chunk upload (`occ config:app:set files max_chunk_size --value 0`) the progress bar is displayed correctly when dropping big files.

**Comment by solracsf** [comment]
> After disabling chunk upload (`occ config:app:set files max_chunk_size --value 0`) the progress bar is displayed correctly when dropping big files.

Confimed on 29.0.7 👍

**Comment by VieuFou34** [comment]
> > After disabling chunk upload (`occ config:app:set files max_chunk_size --value 0`) the progress bar is displayed correctly when dropping big files.
> 
> Confirmed on 29.0.7 👍

Also confirmed on 29.0.7 here

Isn't it a problem disabling chunks ?

**Comment by skjnldsv** [comment]
Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by XueSheng-GIT** [comment]
@skjnldsv this is a capture while uploading a file with drag'n'drop.
Server: NC 29.0.7
Client: Ubuntu 24.0.4 with Firefox 131.

Is this what you are looking for?

<details><summary>Details of browser console log</summary>
<p>

```
16:39:26.407 [DEBUG] files: Dropped 
Object { app: "files", uid: "admin", level: 0, event: drop, folder: {…}, fileTree: File }
index.mjs:45:16
16:39:26.408 [DEBUG] files: Uploading files to /Upload 
Object { app: "files", uid: "admin", level: 0, root: File, contents: (1) […] }
index.mjs:45:16
16:39:26.408 [DEBUG] files: Uploading file to /Upload/ubuntu-24.04-desktop-amd64.iso 
Object { app: "files", uid: "admin", level: 0, file: File }
index.mjs:45:16
16:39:26.409 [DEBUG] @nextcloud/upload: Uploading ubuntu-24.04-desktop-amd64.iso to https://cloud.domain.de/remote.php/dav/files/admin/Upload/ubuntu-24.04-desktop-amd64.iso 
Object { app: "@nextcloud/upload", uid: "admin", level: 0 }
index.mjs:45:16
16:39:26.409 [DEBUG] @nextcloud/upload: Initializing chunked upload 
Object { app: "@nextcloud/upload", uid: "admin", level: 0, file: File, upload: {…} }
index.mjs:45:16
16:39:29.140 [DEBUG] files: VirtualList: resizeObserver updated 
Object { app: "files", uid: "admin", level: 0 }
index.mjs:45:16
16:39:30.971 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:39:31.046 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:39:36.094 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:39:36.177 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:39:37.501 [DEBUG] text: sending steps  
Object { app: "text", uid: "admin", level: 0, steps: [], awareness: "AWEB5Oiypw8RWXsidXNlciI6eyJuYW1lIjoiYWRtaW4iLCJjbGllbnRJZCI6NDEwOTE1MzM4MCwiY29sb3IiOiIjNDk5YWEyIiwibGFzdFVwZGF0ZSI6MTcyODY1NzMyNn19", version: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:39:37.605 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: [] }
index-DkzhscpN.chunk.mjs:2:859
16:39:41.232 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:39:41.282 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:39:46.322 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:39:46.407 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:39:51.443 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:39:51.568 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:39:52.503 [DEBUG] text: sending steps  
Object { app: "text", uid: "admin", level: 0, steps: [], awareness: "AWEB5Oiypw8SWXsidXNlciI6eyJuYW1lIjoiYWRtaW4iLCJjbGllbnRJZCI6NDEwOTE1MzM4MCwiY29sb3IiOiIjNDk5YWEyIiwibGFzdFVwZGF0ZSI6MTcyODY1NzMyNn19", version: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:39:55.443 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: [] }
index-DkzhscpN.chunk.mjs:2:859
16:39:56.624 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:39:56.674 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:40:01.727 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:40:01.831 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:40:06.876 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:40:06.959 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:40:07.521 [DEBUG] text: sending steps  
Object { app: "text", uid: "admin", level: 0, steps: [], awareness: "AWEB5Oiypw8TWXsidXNlciI6eyJuYW1lIjoiYWRtaW4iLCJjbGllbnRJZCI6NDEwOTE1MzM4MCwiY29sb3IiOiIjNDk5YWEyIiwibGFzdFVwZGF0ZSI6MTcyODY1NzMyNn19", version: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:40:07.599 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: [] }
index-DkzhscpN.chunk.mjs:2:859
16:40:12.007 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:40:12.107 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:40:17.125 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:40:20.195 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:40:22.519 [DEBUG] text: sending steps  
Object { app: "text", uid: "admin", level: 0, steps: [], awareness: "AWEB5Oiypw8UWXsidXNlciI6eyJuYW1lIjoiYWRtaW4iLCJjbGllbnRJZCI6NDEwOTE1MzM4MCwiY29sb3IiOiIjNDk5YWEyIiwibGFzdFVwZGF0ZSI6MTcyODY1NzMyNn19", version: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:40:22.634 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: [] }
index-DkzhscpN.chunk.mjs:2:859
16:40:25.249 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:40:25.368 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:40:30.398 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:40:31.509 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:40:36.574 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:40:36.671 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:40:37.518 [DEBUG] text: sending steps  
Object { app: "text", uid: "admin", level: 0, steps: [], awareness: "AWEB5Oiypw8VWXsidXNlciI6eyJuYW1lIjoiYWRtaW4iLCJjbGllbnRJZCI6NDEwOTE1MzM4MCwiY29sb3IiOiIjNDk5YWEyIiwibGFzdFVwZGF0ZSI6MTcyODY1NzMyNn19", version: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:40:37.594 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: [] }
index-DkzhscpN.chunk.mjs:2:859
16:40:41.729 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:40:41.816 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:40:46.858 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:40:46.944 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:40:51.969 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:40:52.079 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:40:52.520 [DEBUG] text: sending steps  
Object { app: "text", uid: "admin", level: 0, steps: [], awareness: "AWEB5Oiypw8WWXsidXNlciI6eyJuYW1lIjoiYWRtaW4iLCJjbGllbnRJZCI6NDEwOTE1MzM4MCwiY29sb3IiOiIjNDk5YWEyIiwibGFzdFVwZGF0ZSI6MTcyODY1NzMyNn19", version: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:40:52.615 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: [] }
index-DkzhscpN.chunk.mjs:2:859
16:40:57.096 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:40:57.178 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:41:02.223 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:41:02.329 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:41:07.348 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:41:07.522 [DEBUG] text: sending steps  
Object { app: "text", uid: "admin", level: 0, steps: [], awareness: "AWEB5Oiypw8XWXsidXNlciI6eyJuYW1lIjoiYWRtaW4iLCJjbGllbnRJZCI6NDEwOTE1MzM4MCwiY29sb3IiOiIjNDk5YWEyIiwibGFzdFVwZGF0ZSI6MTcyODY1NzMyNn19", version: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:41:34.324 [DEBUG] text: status 
Object { app: "text", uid: "admin", level: 0, status: "disconnected" }
index-DkzhscpN.chunk.mjs:2:859
16:41:34.324 [DEBUG] text: Websocket closed 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:41:34.424 [DEBUG] text: WebSocketPolyfill#constructor 
Object { app: "text", uid: "admin", level: 0, url: "ws://localhost:1234/file:2912129", fileId: 2912129, initialSession: null }
index-DkzhscpN.chunk.mjs:2:859
16:41:34.425 [DEBUG] text: status 
Object { app: "text", uid: "admin", level: 0, status: "connecting" }
index-DkzhscpN.chunk.mjs:2:859
16:41:34.425 [DEBUG] text: status 
Object { app: "text", uid: "admin", level: 0, status: "connected" }
index-DkzhscpN.chunk.mjs:2:859
16:41:38.214 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:41:39.713 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: [] }
index-DkzhscpN.chunk.mjs:2:859
16:41:39.734 [DEBUG] text: sending steps  
Object { app: "text", uid: "admin", level: 0, steps: (1) […], awareness: "AWEB5Oiypw8ZWXsidXNlciI6eyJuYW1lIjoiYWRtaW4iLCJjbGllbnRJZCI6NDEwOTE1MzM4MCwiY29sb3IiOiIjNDk5YWEyIiwibGFzdFVwZGF0ZSI6MTcyODY1NzMyNn19", version: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:41:39.811 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: [] }
index-DkzhscpN.chunk.mjs:2:859
16:41:43.249 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "admin", level: 0 }
index-DkzhscpN.chunk.mjs:2:859
16:41:43.356 [DEBUG] text: synced  
Object { app: "text", uid: "admin", level: 0, version: 0, steps: (1) […] }
index-DkzhscpN.chunk.mjs:2:859
16:41:47.065 [DEBUG] @nextcloud/upload: Successfully uploaded ubuntu-24.04-desktop-amd64.iso 
Object { app: "@nextcloud/upload", uid: "admin", level: 0, file: File, upload: {…} }
index.mjs:45:16
16:41:47.067 [DEBUG] files: Cancelled previous ongoing fetch 
Object { app: "files", uid: "admin", level: 0 }
index.mjs:45:16
16:41:47.081 [DEBUG] files: Files uploaded successfully 
Object { app: "files", uid: "admin", level: 0 }
index.mjs:45:16
16:41:47.089 [DEBUG] files: Scrolling to last upload in current folder 
Object { app: "files", uid: "admin", level: 0, lastUpload: {…} }
index.mjs:45:16
16:41:47.197 [DEBUG] files: Fetched contents 
Object { app: "files", uid: "admin", level: 0, dir: "/Upload", folder: {…}, contents: (4) […] }
index.mjs:45:16
16:41:47.198 [DEBUG] files: Directory contents changed 
Object { app: "files", uid: "admin", level: 0, view: {…}, folder: {…}, contents: (4) […] }
index.mjs:45:16
16:41:47.204 [DEBUG] @nextcloud/upload: Destination set 
Object { app: "@nextcloud/upload", uid: "admin", level: 0, folder: {…} }
index.mjs:45:16
```

</p>
</details>

**Comment by julien-nc** [comment]
Hey, with chunk upload enabled (default value for files `max_chunk_size` app config):
![Image](https://github.com/user-attachments/assets/31e576dd-a29b-4e43-86e2-a57a301ab6e4)

and after setting `max_chunk_size` to 0:
![Image](https://github.com/user-attachments/assets/ef0c9b00-06af-4030-8244-192070d1e791)

The only difference there is:
`[DEBUG] @nextcloud/upload: Initializing chunked upload`
`[DEBUG] @nextcloud/upload: Initializing regular upload`

**Comment by aguilera26** [comment]
> > > After disabling chunk upload (`occ config:app:set files max_chunk_size --value 0`) the progress bar is displayed correctly when dropping big files.
> > 
> > 
> > Confirmed on 29.0.7 👍
> 
> Also confirmed on 29.0.7 here
> 
> Isn't it a problem disabling chunks ?

Confirmed also works on Nextcloud 30.0.1

**Comment by susnux** [comment]
The problem is currently that we have two different upload strategies.
So the simplest way, also for maintenance, is to unify them.
Meaning I am currently working on migrating the drag and drop upload to the same backend as the file upload using the menu.

Preparations are here:
https://github.com/nextcloud-libraries/nextcloud-upload/pull/1463

Afterwards a PR on server will be created.

**Comment by tony-engineering** [comment]
Thanks for handling this. Looking forward to have the fix.

**Comment by allbut0ne** [comment]
I've got this problem too (v. 30.0.2). As this issue exists for more than 2 years I may not hope that there will be a fix soon – right?

**Comment by allbut0ne** [comment]
> > > > After disabling chunk upload (`occ config:app:set files max_chunk_size --value 0`) the progress bar is displayed correctly when dropping big files.
> > > 
> > > 
> > > Confirmed on 29.0.7 👍
> > 
> > 
> > Also confirmed on 29.0.7 here
> > Isn't it a problem disabling chunks ?
> 
> Confirmed also works on Nextcloud 30.0.1

nope, If I do so no files can be uploaded anymore. (nc 30.0.2)

**Comment by susnux** [comment]
> As this issue exists for more than 2 years

What do you mean? The issue was reported 6 weeks ago?

**Comment by allbut0ne** [comment]
Oh yes, sorry. Made a mistake – was totally wrong of course.

**Comment by allbut0ne** [comment]
Why is this closed? I don't understand. What do I have to do to fix the issue?

**Comment by susnux** [comment]
> What do I have to do to fix the issue?

Wait for the next maintenance releases :)

**Comment by skjnldsv** [comment]
Actually no, still broken

**Comment by skjnldsv** [comment]
@susnux on master we still have the following issues:
## 1. uploading big files on drag&drop does not show the upload progress
https://github.com/user-attachments/assets/6da30da5-805f-43af-b2b7-99f8091c48ed

## 2. selecting a conflicting file and clicking cancel does NOT reset the uploader progress bar
https://github.com/user-attachments/assets/5ade3302-c126-4111-beec-d7161f73553b

**Comment by susnux** [comment]
> on master we still have the following issues

I know the server fix PR is not yet merged / in review state 🙈 
(moving drag-and-drop to same library function as input-upload)

**Comment by skjnldsv** [comment]
Fixed by
- https://github.com/nextcloud/server/pull/49764
- https://github.com/nextcloud/server/pull/49769

**Comment by shuum** [comment]
In the latest release from 2024.12.19 the error still persists.

**Comment by skjnldsv** [comment]
@J0riz it wasn't withdrawn, it was just merged after 30.0.4.
It will be part of 30.0.5 :)

**Comment by mwinkens** [comment]
This issue took ages for me to find, just to find out, that I should upgrade from 30.0.4 ...
For completeness, the second upload causes the following nextcloud.log:
```
{"reqId":"KMX3XsRHgsorkLPvPs7b","level":3,"time":"2025-02-02T14:38:23+00:00","remoteAddr":"212.84.249.120","user":"redacted","app":"no app in context","method":"PUT","url":"/remote.php/dav/uploads/edacted/web-file-upload-6df5e7b1a9b2a14f/3","message":"Erwartete Dateigr\u00f6\u00dfe von 10485760 bytes, aber 172032 bytes gelesen (vom Nextcloud-Client) und geschrieben (in den Nextcloud-Speicher). Dies kann entweder ein Netzwerkproblem auf der sendenden Seite oder ein Problem beim Schreiben in den Speicher auf der Serverseite sein.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0","version":"30.0.4.1","exception":{"Exception":"Sabre\\DAV\\Exception\\BadRequest","Message":"Erwartete Dateigr\u00f6\u00dfe von 10485760 bytes, aber 172032 bytes gelesen (vom Nextcloud-Client) und geschrieben (in den Nextcloud-Speicher). Dies kann entweder ein Netzwerkproblem auf der sendenden Seite oder ein Problem beim Schreiben in den Speicher auf der Serverseite sein.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":110,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php","line":34,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1098,"function":"createFile","class":"OCA\\DAV\\Upload\\UploadFolder","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":504,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Server.php","line":43,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":371,"function":"start","class":"OCA\\DAV\\Connector\\Sabre\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":19,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":146,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","Line":259,"message":"Erwartete Dateigr\u00f6\u00dfe von 10485760 bytes, aber 172032 bytes gelesen (vom Nextcloud-Client) und geschrieben (in den Nextcloud-Speicher). Dies kann entweder ein Netzwerkproblem auf der sendenden Seite oder ein Problem beim Schreiben in den Speicher auf der Serverseite sein.","exception":{},"CustomMessage":"Erwartete Dateigr\u00f6\u00dfe von 10485760 bytes, aber 172032 bytes gelesen (vom Nextcloud-Client) und geschrieben (in den Nextcloud-Speicher). Dies kann entweder ein Netzwerkproblem auf der sendenden Seite oder ein Problem beim Schreiben in den Speicher auf der Serverseite sein."}}
```

I don't know why my log is german, I know it may be less helpful
