### ISSUE TITLE
[Bug]: SFTP external storage custom port option not working.

### ISSUE THREAD

**Issue by JMarcosHP** [nextcloud/server#49296]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Cannot mount external storage if the SFTP server is not using the default port. I need to specify the port on the IP input to get this working.

![Image](https://github.com/user-attachments/assets/80a1ad9c-3b64-4827-a5b8-e4f11acefe6b)

### Steps to reproduce

1. Use a custom port for SSH/SFTP
2. Try to mount the external storage and set the custom port on the respective input.

### Expected behavior

The specified port should work on the respective input, not on the IP input.

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
"system": {
        "one-click-instance": true,
        "one-click-instance.user-limit": 100,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "check_data_directory_permissions": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwritehost": "nc.herrerapuentes.work",
        "overwriteprotocol": "https",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nc.herrerapuentes.work"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/mnt\/ncdata\/skeleton",
        "dbtype": "pgsql",
        "version": "29.0.8.1",
        "overwrite.cli.url": "https:\/\/nc.herrerapuentes.work\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "log_type": "file",
        "logfile": "\/var\/www\/html\/data\/nextcloud.log",
        "log_rotate_size": 10485760,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "preview_max_x": 512,
        "preview_max_y": 512,
        "jpeg_quality": 60,
        "enabledPreviewProviders": [
            "OC\\Preview\\Imaginary",
            "OC\\Preview\\Image",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Movie",
            "OC\\Preview\\Krita"
        ],
        "enable_previews": true,
        "upgrade.disable-web": true,
        "mail_smtpmode": "smtp",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "activity_expire_days": 30,
        "simpleSignUpLink.shown": false,
        "share_folder": "\/Shared",
        "one-click-instance.link": "https:\/\/nextcloud.com\/all-in-one\/",
        "upgrade.cli-upgrade-link": "https:\/\/github.com\/nextcloud\/all-in-one\/discussions\/2726",
        "updatedirectory": "\/nc-updater",
        "maintenance_window_start": 100,
        "allow_local_remote_servers": true,
        "davstorage.request_timeout": 86400,
        "htaccess.RewriteBase": "\/",
        "dbpersistent": false,
        "auth.bruteforce.protection.enabled": true,
        "ratelimit.protection.enabled": true,
        "files_external_allow_create_new_local": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "preview_imaginary_key": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "MX",
        "default_locale": "es_MX",
        "default_language": "es_MX",
        "preview_imaginary_url": "***REMOVED SENSITIVE VALUE***",
        "memories.gis_type": 2,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "DOMAIN": "nc.herrerapuentes.work"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - cfg_share_links: 6.1.1
  - checksum: 1.2.5
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contactsinteraction: 1.10.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.1
  - files_downloadactivity: 1.17.0
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - files_zip: 2.1.0
  - firstrunwizard: 2.18.0
  - guests: 3.2.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - metadata: 0.21.0
  - nextcloud-aio: 0.6.0
  - nextcloud_announcements: 1.18.0
  - notifications: 2.17.0
  - notify_push: 0.7.0
  - oauth2: 1.17.1
  - password_policy: 1.19.0
  - photos: 2.5.0
  - previewgenerator: 5.6.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - quota_warning: 1.20.0
  - recommendations: 2.1.0
  - registration: 2.5.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.8
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - skyprint: 0.1.6
  - socialsharing_email: 3.2.0
  - socialsharing_facebook: 3.2.0
  - socialsharing_telegram: 3.2.0
  - socialsharing_twitter: 3.2.0
  - support: 1.12.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_admin: 4.7.1
  - twofactor_backupcodes: 1.18.0
  - twofactor_nextcloud_notification: 3.9.0
  - twofactor_totp: 11.0.0-dev
  - twofactor_webauthn: 1.4.0
  - user_migration: 6.0.0
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - welcome: 1.2.0
  - workflowengine: 2.11.0
Disabled:
  - bruteforcesettings: 2.9.0
  - dashboard: 7.9.0 (installed 7.9.0)
  - encryption: 2.17.0
  - suspicious_login: 7.0.0
  - user_ldap: 1.20.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json
{"reqId":"5XIalExbMfQStXt8K5eM","level":2,"time":"2024-11-14T19:54:51+00:00","remoteAddr":"187.233.94.102","user":"--","app":"no app in context","method":"POST","url":"/login","message":"Login failed: dsds (Remote IP: 187.233.94.102)","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","data":[]}
{"reqId":"ESj90CztBbCYfJWCNnFa","level":3,"time":"2024-11-14T20:04:23+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"GET","url":"/apps/files_external/globalstorages/7?testOnly=true","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":298,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"show","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":[7,"*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"show"]},{"file":"/var/www/>{"reqId":"EwOziztNvXDpTLQGwf9a","level":3,"time":"2024-11-14T20:04:23+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"GET","url":"/apps/files_external/globalstorages/11?testOnly=true","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":298,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"show","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":[11,"*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"show"]},{"file":"/var/ww>{"reqId":"j3pe8vuSpPy2sUT0t3yt","level":3,"time":"2024-11-14T20:04:23+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"GET","url":"/apps/files_external/globalstorages/9?testOnly=true","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":298,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"show","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":[9,"*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"show"]},{"file":"/var/www/>{"reqId":"W7w8nefz75nTA9zJjZPu","level":3,"time":"2024-11-14T20:04:23+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"GET","url":"/apps/files_external/globalstorages/8?testOnly=true","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":298,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"show","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":[8,"*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"show"]},{"file":"/var/www/>{"reqId":"p0heXaBtML2tFDW5Emcl","level":3,"time":"2024-11-14T20:04:27+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"GET","url":"/apps/files_external/globalstorages/7?testOnly=true","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":298,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"show","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":[7,"*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"show"]},{"file":"/var/www/>{"reqId":"sGedlK6UsOt4chV8LXas","level":3,"time":"2024-11-14T20:05:38+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"GET","url":"/apps/files_external/globalstorages/9?testOnly=true","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":298,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"show","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":[9,"*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"show"]},{"file":"/var/www/>{"reqId":"3Cw3SFCdAoPjTuJW1a3E","level":3,"time":"2024-11-14T20:05:38+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"GET","url":"/apps/files_external/globalstorages/7?testOnly=true","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":298,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"show","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":[7,"*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"show"]},{"file":"/var/www/>{"reqId":"DgTPdfh65aMimkvpbO30","level":3,"time":"2024-11-14T20:05:38+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"GET","url":"/apps/files_external/globalstorages/8?testOnly=true","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":298,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"show","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":[8,"*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"show"]},{"file":"/var/www/>{"reqId":"IwnkudVVmVpXWBr3lWWn","level":3,"time":"2024-11-14T20:05:38+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"GET","url":"/apps/files_external/globalstorages/11?testOnly=true","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":298,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"show","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":[11,"*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"show"]},{"file":"/var/ww>{"reqId":"gjbRKrGPFMcT8laBoBVe","level":3,"time":"2024-11-14T20:05:49+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"PUT","url":"/apps/files_external/globalstorages/7","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/GlobalStoragesController.php","line":201,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"update","class":"OCA\\Files_External\\Controller\\GlobalStoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"update"]},{"file":"/var/www/>{"reqId":"YbWwXy3scth4NwBLplte","level":3,"time":"2024-11-14T20:06:12+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"PUT","url":"/apps/files_external/globalstorages/7","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/GlobalStoragesController.php","line":201,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"update","class":"OCA\\Files_External\\Controller\\GlobalStoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"update"]},{"file":"/var/www/>{"reqId":"uYHkTMWBoEGmavQXJPOi","level":3,"time":"2024-11-14T20:07:38+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"GET","url":"/apps/files_external/globalstorages/7?testOnly=true","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":298,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"show","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":[7,"*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"show"]},{"file":"/var/www/>{"reqId":"lS50JW1qKOXZdeSZvjZX","level":3,"time":"2024-11-14T20:08:37+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"PUT","url":"/apps/files_external/globalstorages/7","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/GlobalStoragesController.php","line":201,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"update","class":"OCA\\Files_External\\Controller\\GlobalStoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"update"]},{"file":"/var/www/>{"reqId":"O95dtfDHOhxHuW8RB1O2","level":3,"time":"2024-11-14T20:09:45+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"PUT","url":"/apps/files_external/globalstorages/7","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/GlobalStoragesController.php","line":201,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"update","class":"OCA\\Files_External\\Controller\\GlobalStoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"update"]},{"file":"/var/www/>{"reqId":"ErEA4dIt6wowfUQyiraV","level":3,"time":"2024-11-14T20:09:55+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"PUT","url":"/apps/files_external/globalstorages/7","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/GlobalStoragesController.php","line":201,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"update","class":"OCA\\Files_External\\Controller\\GlobalStoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"update"]},{"file":"/var/www/>{"reqId":"PeKxlhPauyTaG4vu20vC","level":3,"time":"2024-11-14T20:10:15+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"PUT","url":"/apps/files_external/globalstorages/7","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/GlobalStoragesController.php","line":201,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"update","class":"OCA\\Files_External\\Controller\\GlobalStoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"update"]},{"file":"/var/www/>{"reqId":"tANsPEbA58t6d6WRsUxe","level":3,"time":"2024-11-14T20:15:40+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"PUT","url":"/apps/files_external/globalstorages/11","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/GlobalStoragesController.php","line":201,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"update","class":"OCA\\Files_External\\Controller\\GlobalStoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"update"]},{"file":"/var/www>{"reqId":"SNHWCTvzjiv6sOVY57qS","level":3,"time":"2024-11-14T20:15:46+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"PUT","url":"/apps/files_external/globalstorages/11","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/GlobalStoragesController.php","line":201,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"update","class":"OCA\\Files_External\\Controller\\GlobalStoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"update"]},{"file":"/var/www>{"reqId":"j40luXfbkcZSscBB516L","level":3,"time":"2024-11-14T20:15:52+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"PUT","url":"/apps/files_external/globalstorages/11","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/GlobalStoragesController.php","line":201,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"update","class":"OCA\\Files_External\\Controller\\GlobalStoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"update"]},{"file":"/var/www>{"reqId":"hm2rc2sFsN5eRLFwLhoc","level":3,"time":"2024-11-14T20:18:29+00:00","remoteAddr":"2806:103e:15:6bdf:8c0b:a35c:21db:b75d","user":"admin","app":"files_external","method":"PUT","url":"/apps/files_external/globalstorages/8","message":"Login failed","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36","version":"29.0.8.1","exception":{"Exception":"Exception","Message":"Login failed","Code":0,"Trace":[{"file":"/var/www/html/apps/files_external/lib/Lib/Storage/SFTP.php","line":175,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":[]},{"file":"/var/www/html/apps/files_external/lib/MountConfig.php","line":131,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SFTP","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/StoragesController.php","line":245,"function":"getBackendStatus","class":"OCA\\Files_External\\MountConfig","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/files_external/lib/Controller/GlobalStoragesController.php","line":201,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"update","class":"OCA\\Files_External\\Controller\\GlobalStoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Files_External\\Controller\\GlobalStoragesController"],"update"]},{"file":"/var/www/>__
```

### Additional info

Using Nextcloud AIO docker installation, all containers up to date.

**Comment by joshtrichards** [comment]
Oops, my fault!

I see what's up.

(When I did #47526 for FTP I also did #47527 for SFTP, but didn't accommodate for the SFTP constructor handling the port parameter differently. I'll clean this up and also extend the tests.)

**Comment by Tanjohnson99** [comment]
Hi, is this issue solved in any recent release? I'm facing exactly the same problem. Thanks.

**Comment by paolo987** [comment]
> Hi, is this issue solved in any recent release? I'm facing exactly the same problem. Thanks.

Hi Dear,
I still have the problem on the 31.0.5 release
but it is easily solvable: just indicate the connection port number in the hostname field (hostname:port).
Sooner or later they will fix it but it is not a blocking problem.

**Comment by Tanjohnson99** [comment]
> > Hi, is this issue solved in any recent release? I'm facing exactly the same problem. Thanks.
> 
> Hi Dear, I still have the problem on the 31.0.5 release but it is easily solvable: just indicate the connection port number in the hostname field (hostname:port). Sooner or later they will fix it but it is not a blocking problem.

IT WORKS! 
THanks

**Comment by BerziOnline** [comment]
Bug still exists and cost me a lot of hours in debugging... -.-
The bugfixing in using the port attached to the target-host fixes the issue - thanks a lot for the tip!

**Comment by Noyarac** [comment]
Same issue, same working workaround. Thanks!

**Comment by rw-django-fan-2020** [comment]
> Bug still exists and cost me a lot of hours in debugging... -.- The bugfixing in using the port attached to the target-host fixes the issue - thanks a lot for the tip!

Please fix this bug. It really costs a lot of time to find out what is going on.

**Comment by joshtrichards** [comment]
fixed by #57793 + #58350?
