### ISSUE TITLE
3 dots menu in apps header should bring full apps list instead of another entry requiring an extra click to get the list

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#4966]
@nextcloud/designers

**Comment by nickvergessen** [comment]
You mean on hover?

**Comment by oparoz** [comment]
Correct, I don't see the point of showing "more apps". Just show the whole list. The extra click is unnecessary.

**Comment by Espina2** [comment]
@oparoz can you add a print screen so he can see what you are talking about.

**Comment by MorrisJobke** [comment]
Normal menu entry on hover:

<img width="465" alt="bildschirmfoto 2017-05-20 um 16 51 40" src="https://cloud.githubusercontent.com/assets/245432/26279552/a442d032-3d7c-11e7-887f-41ac45a175b9.png">

"More apps" entry on hover:

<img width="503" alt="bildschirmfoto 2017-05-20 um 16 51 45" src="https://cloud.githubusercontent.com/assets/245432/26279554/a448940e-3d7c-11e7-99cf-5643526e3fde.png">

"More apps" entry on click:

<img width="515" alt="bildschirmfoto 2017-05-20 um 16 51 51" src="https://cloud.githubusercontent.com/assets/245432/26279553/a4440fd8-3d7c-11e7-921b-6c89a2a1f0d4.png">

**Comment by oparoz** [comment]
Thanks @MorrisJobke

**Comment by jancborchardt** [comment]
I also thought about that a while ago with showing the menus of the header on hover already. Not only this menu, but also the user menu on the top right. The thing is it was very strange and often opened when you didn't want to open it. Also, you need to open the Contacts menu and Notifications menu on hover too, right?

What do you think @nextcloud/designers?

**Comment by plberd** [comment]
Also, how come a hover or a click is needed even when there's more than enough space left on the screen?

I mean the "..." button appears when there are more than 8 apps to show, even if there are about 1200 empty pixels from there 'till the search button on the other side. Why not just show all apps?

I've seen that if there's not enough space, the "..." button will be moved to the left. Why not keep this feature when there's no space left (on a mobile or otherwise small screen) and just remove the fix boundary that makes it appear on the 8th place.

**Comment by jancborchardt** [comment]
@plberd this has been fixed through https://github.com/nextcloud/server/pull/5135

@oparoz maybe that also fixes most cases where this issue appeared? Because the usable space is always filled with apps.

**Comment by MorrisJobke** [comment]
> @oparoz maybe that also fixes most cases where this issue appeared? Because the usable space is always filled with apps.

I would say so. Let's close this here and test it a bit more.

**Comment by kevin147147** [comment]
I don't think its user friendly to have to click two times on mobile devices (where it's still a problem to me). I'd like to see this issue reopened. The desktop version is good as it is now. (With all the buttons showing and using actual screen space)

**Comment by jancborchardt** [comment]
@kevin147147 after testing and talking to @MorrisJobke, he mentioned that this is acutally a "feature" of Safari on iOS itself. (It’s fine on all other browsers.) There seems to be no way to work around this, as it is a set thing on Safari – but if you find one then please do propose a pull request. :)
