### ISSUE TITLE
occ install doesn't create DB

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#5049]
### Steps to reproduce
1. Install Nextcloud 12 with .occ and set DB name
2. Notice that DB is not created
3. Create a DB manually
4. Run .ooc install again
5. Notice that Nextcloud successfully installs

https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L268 (added the workaround until this is fixed)

### Expected behaviour
DB should be created during install.

### Actual behaviour
DB is not installed.

Error message in red that admin couldn't connect to DB because it doesn't exists

### Server configuration

**Operating system**:
Ubunt Server 16.04
**Web server:**
Apache 2.4
**Database:**
MySQL 5,7
**PHP version:**
7.0

Ref similar issue from before https://github.com/nextcloud/server/issues/2661

**Comment by enoch85** [comment]
https://github.com/nextcloud/server/issues/5034

**Comment by lightonflux** [comment]
We had the same situation with NC11 → #2646

**Comment by tessus** [comment]
@lightonflux how is it possible that something that was fixed in nc11 is not in the code of nc12? maybe bad merges?

**Comment by lightonflux** [comment]
@tessus Was merged properly and the code is still there.

**Comment by enoch85** [comment]
@lightonflux Still doesn't work, so the fact that the code is still there doesn't change anything.

**Comment by enoch85** [comment]
@rullzer Can you please have a look at this?

**Comment by enoch85** [comment]
I'm amazed that this isn't fixed yet.

**Comment by arodriguezf** [comment]
I´m having this problem using the VM downloaded from your web, any fix?

**Comment by enoch85** [comment]
@arodriguezf Nextcloud is already installed in the VM, so I don't understand how you can have this issue?

**Comment by enoch85** [comment]
@MorrisJobke Is this in NC 13 now? Haven't tested as I create a DB per default in the scripts before Nextcloud is installed.

**Comment by MorrisJobke** [comment]
> @MorrisJobke Is this in NC 13 now? Haven't tested as I create a DB per default in the scripts before Nextcloud is installed.

Don't know. Haven't tested again.

**Comment by skjnldsv** [comment]
Still occuring @enoch85 ?

**Comment by enoch85** [comment]
@skjnldsv Have to test it, solved it by creating the DB before so it worked since. But it's a workaround, not a fix to the real issue. 

Will let you know.

**Comment by kesselb** [comment]
Why should nextcloud create the database? Many users are confused because nextcloud creates a database user on setup. I would prefer that nextcloud just uses the provided credentials and print some warning if the db is missing or has the wrong charset. Would like to hear your opinion @enoch85

**Comment by enoch85** [comment]
> Why should nextcloud create the database?

It's convenient. Simple as that. :)

For me though, I don't need it anymore since it's been implemented in the VM to create a DB before `occ:install` is run ever since this issue arise.

I would be OK with closing.

**Comment by skjnldsv** [comment]
@rullzer @MorrisJobke @nickvergessen in or out of our roadmap?

**Comment by MorrisJobke** [comment]
> @rullzer @MorrisJobke @nickvergessen in or out of our roadmap?

"Out" in my opinion.
