### ISSUE TITLE
Problem loading page, reloading in 5 seconds

### ISSUE THREAD

**Issue by gennff** [nextcloud/server#5274]
### Steps to reproduce
1. unfortunaltely, the problem appears intermittently, such that there is no pattern of reproducibility.

### Expected behaviour
a logged in session shall not show up "Problem loading page, reloading in 5 seconds" intermittently and for no reason and kick the user out of the application.

### Actual behaviour
sooner or later, sometimes even when just going beyond the login screen, a page top info box appears, saying "Problem loading page, reloading in 5 seconds" and the session gets closed coming up with the login screen again. this happens now and then, sometimes the session is fine for 30 minutes, no matter how much clicking has been done, sometimes one click is enough or even the background notification call seems to trigger this behaviour.

### Server configuration

**Operating system**:
hosted environment (ManagedHosting Medium, domainfactory, germany)
**Web server:**
apache 2.4
**Database:**
mysql (5.6.19)
**PHP version:**
tried both 5-56stable (5.6.21) and 7-70stable (7.0.6)
**Nextcloud version:** (see Nextcloud admin page)
tried both 12.0.0 and 11.0.3.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh installs both 12.0.0 and 11.0.3.2
**Where did you install Nextcloud from:**
12.0.0 == install script and 11.0.3.2 == zip file

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

"No errors have been found."

**List of activated apps:**
with 12.0.0, aleays latest for a fresh install
Activity  
Comments
Deleted files
File sharing
Gallery
Log Reader
Monitoring
Nextcloud announcements
Notifications
Password policy
PDF viewer
Text editor
Theming
Update notification
Usage survey
Versions
Announcement center
Brute-force settings
Calendar
Group folders
Notes
Tasks

**Nextcloud configuration:**
  'instanceid' => '...',
  'passwordsalt' => '...',
  'secret' => '...',
  'trusted_domains' => 
  array (
    0 => '...',
  ),
  'datadirectory' => '...',
  'overwrite.cli.url' => 'https://...',
  'dbtype' => 'mysql',
  'version' => '12.0.0.29',
  'dbname' => '...',
  'dbhost' => '...',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '...',
  'dbpassword' => '...',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 0,
  'mail_smtpsecure' => 'ssl',
  'mail_from_address' => '...',
  'mail_domain' => '...',
  'mail_smtphost' => '...',
  'mail_smtpport' => '...',
  'mail_smtpname' => '...',
  'mail_smtppassword' => '...',
  'tempdirectory' => '...',
  'session_lifetime' => 3600,
  'session_keepalive' => true,
  'cron_log' => true,
  'default_language' => 'de',
  'overwriteprotocol' => 'https',

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
chrome, opera, iridium, firefox, ...
**Operating system:**
windows, linux

#### Web server error log
the webserver does not log the error

#### Nextcloud log (data/nextcloud.log)
![2017-06-01 11_17_46-admin](https://user-images.githubusercontent.com/11676781/26838751-55227ba2-4ae1-11e7-8104-92574d8bcce9.png)

#### Browser log
![2017-05-30 15_04_58-admin](https://user-images.githubusercontent.com/11676781/26838729-472a3a1c-4ae1-11e7-960e-689d30d0ef93.png)

**Comment by gennff** [comment]
also see #3419

**Comment by blizzz** [comment]
@MorrisJobke any idea? not sure what the original issue (or it's solution) was related to.

**Comment by MorrisJobke** [comment]
> @MorrisJobke any idea? not sure what the original issue (or it's solution) was related to.

It was to only reload if the session is over and not if a network error happened. In this case it is an unauthorised and the reload makes sense, or am I wrong?

> sooner or later, sometimes even when just going beyond the login screen, a page top info box appears, saying "Problem loading page, reloading in 5 seconds" and the session gets closed coming up with the login screen again. this happens now and then, sometimes the session is fine for 30 minutes, no matter how much clicking has been done, sometimes one click is enough or even the background notification call seems to trigger this behaviour.

This indicates, that the session is not valid anymore, so the behaviour is correct.

Do you maybe have setup a quite low timeout for your PHP sessions on your server and they got garbage collected?

**Comment by gennff** [comment]
hi all, thanks for looking into this.
as mentioned above, i installed into a hosted environment and as it turned out eventually, the problem was the accessibilty (?) of the php-runtime tmp-directory (setting the nextcloud tmp-directory in config.php did not help or show any other effect that getting rid of the problem statement in the admin overview). only setting the php-runtime tmp-directory below the webspace-root but above the nextcloud-root did the trick, don't ask me why (got to ask the folks at the hosting company, i will do, after days of trial). however, proceeding like this made the php-sesion-files show up for the first time. accordingly, as i suppose, the issue never appeared again since then.
this is a very nasty issue, maybe close in appearance to a standard inactivity logout, but very different in its intermittend nature (as above, again, logout even happened after a fresh login sometimes). to me, not being a php crack, it seems that nextcloud is not aware of loosing its session files for whatever reason and therefore failes to report this problem comprehensively.
i saw a lot of people reporting this issue throughout the net, never posting a fix, unfortunately, such that nextcloud should, as long as hosted environments belong to the target platforms, check the accessibilty of the given (config.php) or configured (php-runtime) tmp-directory in a much more attentive manner.
regards from dresden

**Comment by nkovacs** [comment]
In our case the problem was caused by the php session storage directory not being readable by users other than root. Debian does this for security reasons (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=267720) and it also disables the garbage collector and relies on a cron job instead, but our php.ini accidentally had gc_probability set to 1, and this caused nextcloud to log the user out if the request happened to trigger the garbage collector. I managed to reproduce this in the nextcloud docker image by setting `session.gc_probability` to 100 and changing `session.save_path` to `/tmp/phpsessions`, then setting the permissions of `tmp/phpsession` to 1733.

**Comment by JimBTek** [comment]
Hey all, I am having the same problem on a HostISO VPS where they installed NextCloud. We are on v 12.0.5 and seeing it.  

A bandaid, is if you select "Stay logged in" on the login page, after the error, instead of logging you out it takes you back to the home page for logged in users.  

![image](https://user-images.githubusercontent.com/1176347/35642852-6fa2fd40-0692-11e8-87be-5a8811c5c00f.png)

Also here is a glimpse of our security settings page:

![image](https://user-images.githubusercontent.com/1176347/35642917-a086b046-0692-11e8-86ad-d6b81185664c.png)

Could the default "Ajax" background job method be causing this or the un-ideal php caching settings?  Thanks

**Comment by tareko** [comment]
This problem has been driving me crazy since upgrading to the latest NC. I've tried the php.ini edit to no effect. Disabling the sharing plugin also didn't help, nor did changing the background of the login screen.

I don't see anything useful in the logs. Anything I can do to debug this?

tarek : )

**Comment by JimBTek** [comment]
did you try changing the garbage collection to cron?  i'm not sure if this
really worked but seemed to be caused by the ajax based garbage collection
interfering with the user session.

Best,

Jim Bartek
BTek Ventures, LLC
317-292-6301
BTekVentures.com

**Comment by tareko** [comment]
Thank you for your suggestions @JimBTek . I was already set to cron. I set it to ajax and webcron, and that didn't help. However, your suggestion led me to the realization that indeed the problem only happens after a cron run!

Any thoughts on how I can further debug?

**Comment by tareko** [comment]
Hello all,

This problem still exists and is still crippling my and my team's usage of nextcloud. Are there any debug options here? Nothing appears to show on the debug logs that's specific to the error.

tarek : )

**Comment by tareko** [comment]
Hello all,

By way of update, I moved my installation over from an older debian server with PHP5 to a new one with PHP 7.0, upgraded to the latest version of all modules and the system. I expected this to fix my problem, but it did not.

I am still entirely unsure how to even *debug* this issue, as nothing useful appears in the logs.

Any thoughts?

tarek : )

**Comment by bseclier** [comment]
Hello,
We are facing the same issue and we don't have any idea on how to solve it. I'm subscribing this page hoping that someone find anything which could help.

**Comment by brandongrant** [comment]
I was able to finally resolve this by changing permissions to the sessions directory. By default, only root had access. This command changes it to all users.
sudo chmod a+rwx /var/lib/php/sessions

**Comment by founderio** [comment]
Wouldn't it be better to adjust ownership so that the user for the
webserver has access to it, instead of giving everyone access?

**Comment by webdev2027** [comment]
I've still the same problem, and we talk about `NextCloud 13.06` and `PHP7.x`.
I've installed NextCloud on a managed server (domainfactory)?!

**Comment by JimBTek** [comment]
Our was just fixed last week.  We used NextCloud to upgrade to the latest 13+ release via the Nextcloud built in upgrade tool.

We are using cron based garbage collection every 15 minutes.  It was DEFINITELY the culprit.  In version 12 it would kick every user out on the dot at 15 minute increments when the cron job ran. 

we also did some of the chmod folder permissions changes and it seems like that combination keeps the sessions from getting garbage collected.

We had some admin page errors listed, and now the only one we have listed is Nextcloud thinks there is no cache, but the server at a higher level uses Redis.  We can now stay logged in for days, and there is still an occasional "Problem loading page, reloading in 5 seconds" but you don't get kicked out anymore. 

Hope this helps.

**Comment by hoggle64** [comment]
I am running version 14.0.3.0 and still have the same issue.

**Comment by bseclier** [comment]
I think I solved this problem here : we used to store PHP sessions in memcached. I changed the storage replacing by the default option (stored in files), it result by a login page 3 or 4 time faster and this problem of loading/reloading page gone.

**Comment by felmab** [comment]
I use Debian. For whatever reason, I had gc_probability = 1 in my php.ini file. Set it to 0 since there is already a crontab to deal with sessions. Now all works as a charm \o/

**Comment by reiner-text** [comment]
> sooner or later, … the session gets closed coming up with the login screen again.
> this happens now and then, sometimes the session is fine for 30 minutes,

For me, the session ran exactly to the next cron run, a maximum of 15 minutes.
Since an upgrade to 15.0.3/15.0.4 I wasn't kicked out again during the cron run.

**Comment by gzeronet** [comment]
https://github.com/nextcloud/server/blob/master/core/js/js.js#L801
if ajax status code in (302, 303, 307, 401): page reload().

**Comment by skjnldsv** [comment]
Looking at everyone's answers, I assume this is a setup issue.
The reload metnionned [here](https://github.com/nextcloud/server/issues/5274#issuecomment-476962643) is on purpose to make sure to reload pages when something goes wrong on nextcloud.

Closing

**Comment by adegans** [comment]
I have this on Nextcloud 17.
Intermittently, no error log to be found. Same as everyone else.

Suggesting it's a permissions error on phpsessions or requiring advanced server tweaks is odd - After all, Nextcloud is mostly a PHP app which means it's a website.
And even if it isn't, the web UI part can easily kickstart whatever runs in the background.

For me it usually happens once or twice a day when I log in the first time that day.
Or when  I didn't open the web UI for a few hours.

If Nextcloud can resolve this after 5 seconds it can also do it after 1 (or immediately).
So instead of bothering users with it, just silently do whatever happens after 5 seconds immediately.

Just silently log a warning or notice in the log (or not, since there is no real issue) and don't bother users with this stuff.
It really can't be more simple... And I don't understand why this has been dragging on for years now 🤪

**Comment by EnigmaticsDE** [comment]
I just came along this problem myself and solved it for my **DomainFactoy** webspace by making a tmp directory in my webspace and adapting the session.save_path in my php.ini like this:

 session.save_path = /kunden/accountNumber_zipCode/tmp

**Comment by EnigmaticsDE** [comment]
I just came along this problem myself and solved it for my DomainFactoy webspace by making a tmp directory in my webspace and adapting the session.save_path in my php.ini like this:

session.save_path = /kunden/accountNumber/tmp
