### ISSUE TITLE
v12.0.0.29 fresh install: cannot connect with caldav/carddav client - OAuth 2.0 not working?

### ISSUE THREAD

**Issue by LeGast00n** [nextcloud/server#5394]
I've done a fresh install on my QNAP. Connection is fine on the DAV port, still, neither Mac OS X's Calendar, nor my Linux calendar client can connect. Calendar says that it cannot recognize user or password while my Linux client says that the server does not support OAuth 2.0

I've tried both with direct login and with an application password.

I've player with the LD_LIBRARY_PATH to avert this to no avail (fixing the pgsql.so issue logged leads me to libk5*-related symbols missing.
Any clue on how I can fix this?

### Server configuration

**Operating system**: Linux

**Web server: apache 2.4.25

**Database: PostgreSQL 9.3.13

**PHP version: 7.1.5

**Nextcloud version: 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install: NO

**Where did you install Nextcloud from: QNAP Club repo https://store.qnapclub.eu/store/fr.xml

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
</details>

**Are you using external storage, if yes which one: N/A

**Are you using encryption: no

**Are you using an external user-backend, if yes which one: no

### Client configuration
**Browser: Safari

**Operating system: macOS Sierra

#### Web server error log
<details>
<summary>Web server error log</summary>

This is the type of log you have on the web server logs:
172.16.x.x - - [13/Jun/2017:08:02:18 +0200] "PROPFIND /remote.php/dav/ HTTP/1.1" 401 557
172.16.x.x - - [13/Jun/2017:08:02:21 +0200] "PROPFIND /.well-known/caldav HTTP/1.1" 405 244
172.16.x.x- - [13/Jun/2017:08:02:21 +0200] "PROPFIND /remote.php/dav/ HTTP/1.1" 401 557
172.16.x.x - - [13/Jun/2017:08:02:22 +0200] "PROPFIND /.well-known/caldav HTTP/1.1" 405 244
172.16.x.x - - [13/Jun/2017:08:02:32 +0200] "PROPFIND /remote.php/dav/ HTTP/1.1" 401 557
172.16.x.x - - [13/Jun/2017:08:02:32 +0200] "PROPFIND /.well-known/caldav HTTP/1.1" 405 244
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
[Tue Jun 13 23:55:34.897759 2017] [auth_digest:notice] [pid 29367:tid 140334756407168] AH01757: generating secret for digest authentication ...
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/Qapache/lib/extensions/no-debug-zts-20160303/pgsql.so' - /opt/Qapache/lib/extensions/no-debug-zts-20160303/pgsql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
PHP Warning:  Xdebug MUST be loaded as a Zend extension in Unknown on line 0
[Tue Jun 13 23:55:34.960533 2017] [mpm_event:notice] [pid 29367:tid 140334756407168] AH00489: Apache/2.4.25 (Unix) OpenSSL/1.0.2k SVN/1.9.5 PHP/7.1.5 configured -- resuming normal operations
[Tue Jun 13 23:55:34.960619 2017] [core:notice] [pid 29367:tid 140334756407168] AH00094: Command line: '/opt/Qapache/bin/httpd -f /share/CE_CACHEDEV1_DATA/.qpkg/NextCloud/httpd.conf'
</details>

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by LukasReschke** [comment]
Fixed by https://github.com/nextcloud/server/pull/5386 and caused by a lying DAV client 😉

**Comment by LeGast00n** [comment]
I'm afraid that does not fix the issue. Shall I rename as "2 different DAV clients unable to connect, whatever the reason" ?

**Comment by LeGast00n** [comment]
Sorry, I understand there is a fix that has been developed as per #5386. I'll look into how to deploy it.

**Comment by MorrisJobke** [comment]
> Sorry, I understand there is a fix that has been developed as per #5386. I'll look into how to deploy it.

or wait for 12.0.1 which is planned for one of the next weeks
