### ISSUE TITLE
User cannot upload files to shared external storage

### ISSUE THREAD

**Issue by Bottswana** [nextcloud/server#5430]
Using External Storage, users the storage is shared to are unable to create or upload files.

### Steps to reproduce
1. Configure external storage, local mode, point to directory owned by webserver user. Enable sharing.
2. Create a directory in external storage, and share it to another user (rw)
3. Attempt to upload file into directory as other user.

### Expected behaviour
Files should be successfully uploaded and visible to the admin user, the user who uploaded them, and in the filesystem on the server.

### Actual behaviour
User receives error 'Error uploading file''  Upload failed. Could not find uploaded file'
Client fails to upload error with HTTP 500 error

### Server configuration

**Operating system**:
Debian Jessie
**Web server:**
Apache 2.4.10-10+deb8u8
**Database:**
mysql  Ver 15.1 Distrib 10.0.30-MariaDB, for debian-linux-gnu (x86_64)
**PHP version:**
7.0 FPM
**Nextcloud version:** (see Nextcloud admin page)
10.0.5 (stable)
**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgraded from ownCloud install
**Where did you install Nextcloud from:**
Updater script
**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.3.2
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_sharing: 1.0.0
  - provisioning_api: 1.0.0
  - theming: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - comments
  - encryption
  - external
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_pdfviewer
  - files_retention
  - files_texteditor
  - files_trashbin
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - gallery
  - notifications
  - password_policy
  - serverinfo
  - survey_client
  - systemtags
  - templateeditor
  - updatenotification
  - user_external
  - user_ldap
  - user_saml
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "ocjfs1rwz4rd",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.2.20"
        ],
        "datadirectory": "\/mnt\/media\/clouddata",
        "overwrite.cli.url": "http:\/\/127.0.0.1\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.5.2",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "asset-pipeline.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "127.0.0.1",
            "port": 6379,
            "timeout": 0
        },
        "has_internet_connection": false,
        "maintenance": false,
        "loglevel": 2,
        "debug": true
    }
}

</details>

**Are you using external storage, if yes which one:** LOCAL

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** NONE

#### Web server error log
<details>
<summary>Web server error log</summary>
Nothing useful in apache error logs, or php fatal error logs.
192.168.2.116 - - [15/Jun/2017:22:34:49 +0100] "PROPFIND /cloud/remote.php/webdav/ HTTP/1.1" 207 4921 "-" "Mozilla/5.0 (Windows) mirall/2.2.0-nightly20160509 (build 6062)"
192.168.2.116 - - [15/Jun/2017:22:34:49 +0100] "PUT /cloud/remote.php/webdav/1921682116%20(2)/New%20Text%20Document.txt HTTP/1.1" 500 1713 "-" "Mozilla/5.0 (Windows) mirall/2.2.0-nightly20160509 (build 6062)"
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"IqlJqPKGVVa4lE2EHqxs","remoteAddr":"192.168.2.116","app":"webdav","message":"\\OC\\Files\\Filesystem::fopen() failed","level":3,"time":"2017-06-15T21:34:49+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/1921682116%20(2)\/New%20Text%20Document.txt","user":"1921682116","version":"9.1.5.2"}
{"reqId":"IqlJqPKGVVa4lE2EHqxs","remoteAddr":"192.168.2.116","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 Could not write file contents\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(137): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #362)\\n#1 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('New Text Docume...', Resource id #362)\\n#2 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('1921682116 (2)\\\/...', Resource id #362, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/cloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/cloud\\\/...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":131,\"User\":\"1921682116\"}","level":4,"time":"2017-06-15T21:34:49+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/1921682116%20(2)\/New%20Text%20Document.txt","user":"1921682116","version":"9.1.5.2"}
{"reqId":"ka3f9eLqeAlJt7Q5t7zM","remoteAddr":"192.168.2.116","app":"webdav","message":"\\OC\\Files\\Filesystem::fopen() failed","level":3,"time":"2017-06-15T21:35:19+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/1921682116%20(2)\/New%20Text%20Document.txt","user":"1921682116","version":"9.1.5.2"}
{"reqId":"ka3f9eLqeAlJt7Q5t7zM","remoteAddr":"192.168.2.116","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 Could not write file contents\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(137): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #362)\\n#1 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('New Text Docume...', Resource id #362)\\n#2 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('1921682116 (2)\\\/...', Resource id #362, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/cloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/cloud\\\/...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":131,\"User\":\"1921682116\"}","level":4,"time":"2017-06-15T21:35:19+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/1921682116%20(2)\/New%20Text%20Document.txt","user":"1921682116","version":"9.1.5.2"}
{"reqId":"EJloA+ac5PUN5ZyjQGUK","remoteAddr":"192.168.2.116","app":"webdav","message":"\\OC\\Files\\Filesystem::fopen() failed","level":3,"time":"2017-06-15T21:35:55+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/1921682116\/New%20Text%20Document.txt","user":"1921682116","version":"9.1.5.2"}
{"reqId":"EJloA+ac5PUN5ZyjQGUK","remoteAddr":"192.168.2.116","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 Could not write file contents\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(137): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #362)\\n#1 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('New Text Docume...', Resource id #362)\\n#2 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('1921682116\\\/New ...', Resource id #362, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/cloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/cloud\\\/...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":131,\"User\":\"1921682116\"}","level":4,"time":"2017-06-15T21:35:55+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/1921682116\/New%20Text%20Document.txt","user":"1921682116","version":"9.1.5.2"}
{"reqId":"0mndZhFJcYucynlJWdtJ","remoteAddr":"192.168.2.116","app":"webdav","message":"\\OC\\Files\\Filesystem::fopen() failed","level":3,"time":"2017-06-15T21:36:25+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/1921682116\/New%20Text%20Document.txt","user":"1921682116","version":"9.1.5.2"}
{"reqId":"0mndZhFJcYucynlJWdtJ","remoteAddr":"192.168.2.116","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 Could not write file contents\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(137): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #362)\\n#1 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('New Text Docume...', Resource id #362)\\n#2 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('1921682116\\\/New ...', Resource id #362, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/cloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/cloud\\\/...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":131,\"User\":\"1921682116\"}","level":4,"time":"2017-06-15T21:36:25+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/1921682116\/New%20Text%20Document.txt","user":"1921682116","version":"9.1.5.2"}
{"reqId":"vXyUXJbwyZhEHqPVw8zk","remoteAddr":"192.168.2.116","app":"webdav","message":"\\OC\\Files\\Filesystem::fopen() failed","level":3,"time":"2017-06-15T21:38:35+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/1921682116\/New%20Text%20Document.txt","user":"1921682116","version":"9.1.5.2"}
{"reqId":"vXyUXJbwyZhEHqPVw8zk","remoteAddr":"192.168.2.116","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 Could not write file contents\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(137): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #362)\\n#1 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('New Text Docume...', Resource id #362)\\n#2 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('1921682116\\\/New ...', Resource id #362, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/var\\\/www\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/cloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/cloud\\\/...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":131,\"User\":\"1921682116\"}","level":4,"time":"2017-06-15T21:38:35+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/1921682116\/New%20Text%20Document.txt","user":"1921682116","version":"9.1.5.2"}

</details>

**Comment by MorrisJobke** [comment]
\\OC\\Files\\Filesystem::fopen() failed

This looks like a permission problem on the web server. Are you 100% sure, that the webserver user can write to this file. Best to be checked by login in into the server via ssh and then sudo to that user. I guess there are some other permission constraints (like SELinux or AppArmor...)

**Comment by evcit** [comment]
I am also having this issue. I installed fresh Nextcloud 11.03 stable via snap, using mysql for database and PHP 7.0 running on Ubunutu Server. 

I have changed the folder **permissions** using the following commands:
chown -R www-data:www-data /MY_DIRECTORY
chmod -R 0750 /MY_DIRECTORY

Below are the errors produced by nextcloud.

**webdav error message**:
Sabre\DAV\Exception: HTTP/1.1 500 Could not write file contents
/snap/nextcloud/2184/htdocs/apps/dav/lib/Connector/Sabre/Directory.php - line 137: OCA\DAV\Connector\Sabre\File->put(Resource id #450)
/snap/nextcloud/2184/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 1072: OCA\DAV\Connector\Sabre\Directory->createFile('my saviour.pdf', Resource id #450)
/snap/nextcloud/2184/htdocs/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile('Software/my sav...', Resource id #450, NULL)
[internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/snap/nextcloud/2184/htdocs/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/snap/nextcloud/2184/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PUT', Array)
/snap/nextcloud/2184/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/snap/nextcloud/2184/htdocs/apps/dav/appinfo/v1/webdav.php - line 60: Sabre\DAV\Server->exec()
/snap/nextcloud/2184/htdocs/remote.php - line 165: require_once('/snap/nextcloud...')
{main}

**webdav error message**:
\OC\Files\Filesystem::fopen() failed

**PHP error message**:
fopen(/MY_DIRECTORY/FILE.file): failed to open stream: Permission denied at /snap/nextcloud/2184/htdocs/lib/private/Files/Storage/Local.php#287

**Steps to reproduce**
Upload file via web interface to external storage folder

**Note**
There are no issues, uploading or downloading files in any non-external storage folder

**Comment by Bottswana** [comment]
Hello,

I fixed this by ensuring that the execute bit was set on directories. In my
case, the external directories were being created without the execute bit
for the web user, which caused this issue.

**Comment by evcit** [comment]
Is that done simply by:
chmod +x /MY_DIRECTORY

If so, unfortunately it does not solve my problem.

**Comment by evcit** [comment]
SOLVED

Moved mounted directory to same directory of all other Nextcloud folders.

**Comment by lamixer** [comment]
I am now having this problem. Admin user can upload to this folder but the user it is shared with cannot. User's upload is a accepted into the temp upload storage folder but when it gets written for real to the external storage it is not allowed.

Nextcloud 14.0.1
Apache / MariaDB / PHP7.2
Manual, Fresh Install on Ubuntu 18.04.1
Encryption YES

Path is: nextcloud/data/adminuser/files_encryption/keys/files/ams-ncl/ext-folder and permissions are drwxr-x--- 3 www-data:www-data all the way down.

series of errors is:
Error, webdav: \OC\Files\Filesystem::fopen() failed
`
{"reqId":"0TjxtU2HkBxJ5rQGDWXg","level":3,"time":"2018-10-02T09:25:00+00:00","remoteAddr":"redacted","user":"testuser","app":"webdav","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/ext2-folder\/Amazonlate.png","message":"\\OC\\Files\\Filesystem::fopen() failed","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"14.0.1.1"}`

Error, no app in context: Sabre\DAV\Exception: Could not write file contents
`same output as below`

Fatal, webdav: Sabre\DAV\Exception: Could not write file contents

/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 156:

    OCA\DAV\Connector\Sabre\File->put(null)

    /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096:

    OCA\DAV\Connector\Sabre\Directory->createFile("Amazonlate.png", null)

    /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 529:

    Sabre\DAV\Server->createFile("ext2-folder ... g", null, null)

    Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

    /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:

    call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])

    /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:

    Sabre\Event\EventEmitter->emit("method:PUT", [ Sabre\HTTP ... }])

    /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:

    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

    /var/www/html/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80:

    Sabre\DAV\Server->exec()

    /var/www/html/nextcloud/remote.php - line 163:

    require_once("/var/www/ht ... p")
