### ISSUE TITLE
Deleting missing files fails removing orphaned DB entries

### ISSUE THREAD

**Issue by carboneater** [nextcloud/server#5449]
### Steps to reproduce
1. Delete a file from storage, without deleting the associated DB entry (AKA fake a dirty delete for some reason...)
2. load the file location in Nextcloud web interface
3. Try to delete the file.
4. Refresh. "Deleted" file still shows.

### Expected behaviour
System tries to delete the file, then deletes the database entry.
On Sabre\DAV\Exception\NotFound the orphaned database entry should be deleted as well

### Actual behaviour
System tries to delete the file, returns Sabre\DAV\Exception\NotFound and aborts

### Server configuration

**Operating system**:
Linux sleipnir 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64 GNU/Linux

**Web server:**
NGINX 1.10.3-1

**Database:**
mariadb 10.1.23-9+deb9u1

**PHP version:**
PHP7.0.19-1 FPM

**Nextcloud version:** (see Nextcloud admin page)
12.0.0 

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from NC 11 to NC12 on release date.

**Where did you install Nextcloud from:**
Updater Module in NC

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "updatechecker": false,
        "instanceid": "oc6n6tqq77xl",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "tsunami.ageg.ca",
            "nextcloud.ageg.ca"
        ],
        "datadirectory": "\/srv\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/tsunami.ageg.ca",
        "dbhost": "localhost",
        "dbname": "nextcloud",
        "dbtype": "mysql",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "version": "12.0.0.29",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "openssl": {
            "config": "\/etc\/ssl\/openssl.cnf"
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "127.0.0.1",
            "port": 6379
        },
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "serveur",
        "mail_domain": "ageg.ca",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "sleipnir.ageg.ca",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "loglevel": 0,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "stable"
    }
}
</details>

**Are you using external storage, if yes which one:** local storage on filesystem (outside nextcloud folder)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-------------------------------+------------------------------------------------------------+
| Configuration                 | s01                                                        |
+-------------------------------+------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                            |
| hasPagedResultSupport         |                                                            |
| homeFolderNamingRule          |                                                            |
| lastJpegPhotoLookup           | 0                                                          |
| ldapAgentName                 | cn=nextcloud,ou=services,dc=ageg,dc=ca                     |
| ldapAgentPassword             | ***                                                        |
| ldapAttributesForGroupSearch  |                                                            |
| ldapAttributesForUserSearch   |                                                            |
| ldapBackupHost                |                                                            |
| ldapBackupPort                |                                                            |
| ldapBase                      | dc=ageg,dc=ca                                              |
| ldapBaseGroups                | dc=ageg,dc=ca                                              |
| ldapBaseUsers                 | dc=ageg,dc=ca                                              |
| ldapCacheTTL                  | 600                                                        |
| ldapConfigurationActive       | 1                                                          |
| ldapDefaultPPolicyDN          |                                                            |
| ldapDynamicGroupMemberURL     |                                                            |
| ldapEmailAttribute            | mail                                                       |
| ldapExperiencedAdmin          | 0                                                          |
| ldapExpertUUIDGroupAttr       |                                                            |
| ldapExpertUUIDUserAttr        |                                                            |
| ldapExpertUsernameAttr        |                                                            |
| ldapGidNumber                 | gidNumber                                                  |
| ldapGroupDisplayName          | cn                                                         |
| ldapGroupFilter               |                                                            |
| ldapGroupFilterGroups         |                                                            |
| ldapGroupFilterMode           | 0                                                          |
| ldapGroupFilterObjectclass    |                                                            |
| ldapGroupMemberAssocAttr      | uniqueMember                                               |
| ldapHost                      | ldapi:///                                                  |
| ldapIgnoreNamingRules         |                                                            |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(cn=%uid)))) |
| ldapLoginFilterAttributes     | cn                                                         |
| ldapLoginFilterEmail          | 0                                                          |
| ldapLoginFilterMode           | 0                                                          |
| ldapLoginFilterUsername       | 1                                                          |
| ldapNestedGroups              | 0                                                          |
| ldapOverrideMainServer        |                                                            |
| ldapPagingSize                | 500                                                        |
| ldapPort                      | 389                                                        |
| ldapQuotaAttribute            |                                                            |
| ldapQuotaDefault              |                                                            |
| ldapTLS                       | 0                                                          |
| ldapUserDisplayName           | displayname                                                |
| ldapUserDisplayName2          |                                                            |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                             |
| ldapUserFilterGroups          |                                                            |
| ldapUserFilterMode            | 0                                                          |
| ldapUserFilterObjectclass     | inetOrgPerson                                              |
| ldapUuidGroupAttribute        | auto                                                       |
| ldapUuidUserAttribute         | auto                                                       |
| turnOffCertCheck              | 0                                                          |
| turnOnPasswordChange          | 0                                                          |
| useMemberOfToDetectMembership | 1                                                          |
+-------------------------------+------------------------------------------------------------+
</details>

### Client configuration
**Browser:**
Chromium 59.0.3071.86 (Developer Build) (64-bit)
Firefox 52.0.2 (64-bit)

**Operating system:**
Debian 4.9.30-2 (2017-06-12) x86_64 GNU/Linux

#### Web server error log
<details>
<summary>Web server error log</summary>
==> nextcloud.access.log <==
10.236.34.39 - - [16/Jun/2017:21:43:30 -0400] "DELETE /remote.php/webdav/Documents%20de%20R%C3%A9f%C3%A9rence/Guide/Guide%20Utilisation%20Informatique/E17-GuideEmail-005-GF.log HTTP/2.0" 404 8486 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36"
(No Internal NGINX or PHP Error Reported)
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
==> /srv/owncloud/data/nextcloud.log <==
{"reqId":"7M9ys6vkDj17ZnJydp1u","level":0,"time":"2017-06-17T01:43:30+00:00","remoteAddr":"10.236.34.39","user":"root","app":"webdav","method":"DELETE","url":"\/remote.php\/webdav\/Documents%20de%20R%C3%A9f%C3%A9rence\/Guide\/Guide%20Utilisation%20Informatique\/E17-GuideEmail-005-GF.log","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name Documents de R\\u00e9f\\u00e9rence\\\/Guide\\\/Guide Utilisation Informatique\\\/E17-GuideEmail-005-GF.log could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(178): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Documents de R\\\\xC3...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(287): Sabre\\\\DAV\\\\Tree->delete('Documents de R\\\\xC3...')\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(71): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":173,\"User\":\"root\"}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/59.0.3071.86 Safari\/537.36","version":"12.0.0.29"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>
core.js?v=766da77867c932e851b286643f995ef2-38:5720 DELETE https://tsunami.ageg.ca/remote.php/webdav/Documents%20de%20R%C3%A9f%C3%A9rence/Guide/Guide%20Utilisation%20Informatique/E17-GuideEmail-005-GF.log 404 ()
request @ core.js?v=766da77867c932e851b286643f995ef2-38:5720
_simpleCall @ client.js?v=766da77867c932e851b286643f995ef2-38:665
remove @ client.js?v=766da77867c932e851b286643f995ef2-38:699
(anonymous) @ merged-index.js?v=766da77867c932e851b286643f995ef2-38:6417
_.each._.forEach @ core.js?v=766da77867c932e851b286643f995ef2-38:166
do_delete @ merged-index.js?v=766da77867c932e851b286643f995ef2-38:6416
_onClickDeleteSelected @ merged-index.js?v=766da77867c932e851b286643f995ef2-38:4743
dispatch @ core.js?v=766da77867c932e851b286643f995ef2-38:3
r.handle @ core.js?v=766da77867c932e851b286643f995ef2-38:3
</details>

**Comment by LukasReschke** [comment]
Please try to run the occ file scan command. That said, directly deleting files on local storage is not really supported.

**Comment by carboneater** [comment]
I ran occ file:scan command, it would not remove orphaned DB entries.

Also, deleting files from filesystem is the shortest way to reproduce said bug. Like I said, it replicates the effects of a bad instruction to the DB.

I have yet to figure out the complete root cause, but I figured that because this bug kept happening on my production server, so it should get reported.

(My researchs so far tend to point that moving a folder breaks the filecache.path & filecache.path_hash in the database, then when browsing the the moved folder, the system redetects the files and adds new entries in the database table with accurate path & path_hash values. (Real cool feature, by the way!)
Thus the files appear as duplicates in the web interface. The average user will try to delete one of the duplicate files. If the user picks the bad file descriptor (which results in a 404), nothing happens. If the user picks the accurate file descriptor, the file is removed from the server, and we have an orphaned DB entry about a missing file.)

That situation above is the exact same as the one we are replicating by manually deleting a file from the server, but with a few more steps. However, I still have to figure out what breaks the filecache.path & filecache.path_hash fields in the DB.

Also, I figured that bug could stand on its own, because the server auto-detects files in the filesystem (or so it looks), so having a "self-cleaning" feature should make sense in itself.

If not, I'll keep on digging the other issue and file a bug when the root cause is found.

**Comment by nickvsh** [comment]
I have fixed the same issue by deleting the files entries from DB and re-scanning the file system with occ files:scan $some_user_here.

First, locate the **fileid**-s of the "bad" files:
_SELECT * FROM nextcloud.oc_filecache where storage = (SELECT numeric_id FROM nextcloud.oc_storages where id like '%**nextcloud-username-here**%');_

Then perform removing the files using fileid-s from step 1, ex.
_delete from nextcloud.oc_filecache where fileid in (1884, 1886, **fileid_from_step_1_here**);_

Rescan filesystem for user
_sudo -u apache php "/var/www/sites/nextcloud/occ" files:scan **nextcloud-username-here**_

**Comment by pascalBokBok** [comment]
I'm having a directory missing, stopping the sync clients. The dir does not exist on server disk - but the nextcloud DB thinks so and files:scan does not fix it.

**Comment by pascalBokBok** [comment]
recreating the dir on server disk has fixed the sync issue.

**Comment by vnz1** [comment]
This happens often when you move and delete your files over davfs2 (NC 14.0.1), so this is a bug somewhere in the core. I have written a [script](https://gist.github.com/vnz1/6ca94c9c13b3d2ae6b55858aafef3891) based on the nickvsh comment as a workaround but this should be fixed in the core of the NC.

**Comment by robertorubioguardia** [comment]
> I have fixed the same issue by deleting the files entries from DB and re-scanning the file system with occ files:scan $some_user_here.
> 
> First, locate the **fileid**-s of the "bad" files:
> _SELECT * FROM nextcloud.oc_filecache where storage = (SELECT numeric_id FROM nextcloud.oc_storages where id like '%**nextcloud-username-here**%');_
> 
> Then perform removing the files using fileid-s from step 1, ex.
> _delete from nextcloud.oc_filecache where fileid in (1884, 1886, **fileid_from_step_1_here**);_
> 
> Rescan filesystem for user
> _sudo -u apache php "/var/www/sites/nextcloud/occ" files:scan **nextcloud-username-here**_

This worked like a charm! Thanks so much mate!

**Comment by nickvsh** [comment]
> > I have fixed the same issue by deleting the files entries from DB and re-scanning the file system with occ files:scan $some_user_here.
> > First, locate the **fileid**-s of the "bad" files:
> > _SELECT * FROM nextcloud.oc_filecache where storage = (SELECT numeric_id FROM nextcloud.oc_storages where id like '%**nextcloud-username-here**%');_
> > Then perform removing the files using fileid-s from step 1, ex.
> > _delete from nextcloud.oc_filecache where fileid in (1884, 1886, **fileid_from_step_1_here**);_
> > Rescan filesystem for user
> > _sudo -u apache php "/var/www/sites/nextcloud/occ" files:scan **nextcloud-username-here**_
> 
> This worked like a charm! Thanks so much mate!

You are welcome)

**Comment by SamSirry** [comment]
Warning: The NC client will delete local files!

I had some misconfiguration on the server that caused the loss of some user files.
Testing the `occ files:scan userx` command fixed the DB entries, but also the next time the user sync'd their local copy of the files got deleted.
The workaround for this was to do the following steps in order:
1. Open each sync'd directory on the client.
2. Close the client NC application.
3. Delete or move away the NextCloud syncing files (two files with names starting with a dot on Windows. One .db file on Linux) from the client directory(s).
4. Do the same on any other syncing client devices.
4. Run `occ files:scan <user>` on the server.
5. Start the NextCloud client. Ignore any errors and wait for it to upload & sync the files to the server.
