### ISSUE TITLE
Enable single sign-on with OAuth 2 / OIDC (for Azure AD, Google Apps, and more)

### ISSUE THREAD

**Issue by ItalyPaleAle** [nextcloud/server#5955]
Please enable Nextcloud to authenticate users via OAuth 2 / OpenID Connect. This will allow signing into NextCloud using credentials from Azure AD or Google Apps, for example (but in theory with any identity provider that supports those protocols).

Organizations are gradually moving away from LDAP and other legacy auth protocol to embrace OAuth 2 and/or OpenID Connect. Many younger companies don't even have Active Directory servers, and only use Azure AD (ie. Office365) or Google Apps.

LDAP is old, heavy, requires external libraries (and PHP extensions), and slow. And, of course, it requires domain controllers, and setting it up is sometimes not trivial.

Using OAuth 2 and/or OpenID Connect would enable easier configuration, a much improved user experience, more stability and true single sign-on.

PS: Box, DropBox and others already support SSO with Azure AD and/or Google Apps!

**Comment by LukasReschke** [comment]
An app implementing OIDC or OAuth2 login would be welcome, however this would not be part of the server core and should be implemented as a dedicated app.

Note that we already support SAML 2.0 which Azure AD as well as Google Apps both support as IdP.

**Comment by EgoAleSum** [comment]
SAML is not less pain than LDAP, sadly (I'd say even more)... the goal of using OIDC/OAuth2 is that they would drastically simplify the architecture and the setup.

**Comment by EgoAleSum** [comment]
@LukasReschke So, I've been trying to setup SAML, and here's the biggest problem I've found so far: quoting from the documentation, "you can use the Nextcloud LDAP user provider to keep the convenience for users. (e.g. when sharing)". Essentially, SAML still requires me to have a domain controller; switching to OIDC and having the proper endpoints would remove that limitation.

**Comment by axel-rutz** [comment]
Is this fixed by that plugin?
https://nextcloud.com/blog/open-id-sso-by-gluu-oxd-is-now-integrated-to-nextcloud/

**Comment by linucksrox** [comment]
Gluu: No, this doesn't quite solve it because that plugin requires the oxd server which is a paid service...
user_saml: this is not OIDC which is what's being requested by this open issue

**Comment by axel-rutz** [comment]
Good to clarify.

As of gluu: the above url says:

> Gluu’s OpenID Connect Single Sign-On (SSO) NextCloud APP will enable you to authenticate users against any standard OpenID Connect Provider (OP). If you don’t already have an OpenID Provider you can use for example Google or deploy the free and open source Gluu Server.

So this sounds like gluu implements OIDC and their nextcloud plugin can also connect to any other OIDC server. Did i get this wrong?

**Comment by axel-rutz** [comment]
RITE, re-reading the pages, gluu oxd in fact is proprietary middleware decorated with marketing gibberish that hides that fact.

**Comment by axel-rutz** [comment]
As OpenID Connect builds on OAuth2, can this be a start?
https://github.com/nextcloud/apps/tree/master/user_oauth

**Comment by anpavlov** [comment]
@axel-rutz This app implements server side part of oauth, so i don't think it could be a start

**Comment by x9t9** [comment]
oAuth2 would in fact be a great addon. As I understand , NC already uses oAuth, but it is not exposed in the UI and is intended only for external storage .. I think it would be a good idea to enhance it to be more open and flexible for users to configure themselves with other services . After all - the whole point ( at least for me ) for using NC is to be free from google / microsoft / dropbox etc ..

**Comment by EgoAleSum** [comment]
@x9t9 this issue is actually for a different thing... being able to use OIDC/OAuth to authenticate into Nextcloud. That is, as an alternative to LDAP...

**Comment by neufeind** [comment]
I expect this request about OAuth2 is about what they have now released for ownCloud? https://owncloud.org/blog/introducing-oauth2-secure-authorization-flow/

**Comment by x9t9** [comment]
@EgoAleSum - I am sorry, but I really do not understand why this issue is different . If nextcloud exposes both parts of the  OAuth2 than any vendor could potentially use it . To Authenticate into nextcloud from other vendors / services , and also vice versa .  Nextcloud can be a server to Authenticate users for other services / plugins / vendors , and exposing the service in a betteer way in the UI will allow other services to Authenticate users for ownCloud ( twitter, facebook, MyOwnServiceSite, google etc .. even other nextcloud servers ..)

**Comment by EgoAleSum** [comment]
@neufeind and @x9t9 again, what you're talking about is different.

What ownCloud introduced is the ability for OC clients to authenticate with the OC server using OAuth. That is: OC acts as the OAuth server.

This issue is about having the NC server use an external OAuth/OpenID Connect directory to authenticate users. So, the clients would not authenticate with NC anymore, but rather with a third-party (Azure AD, Google Apps), and then pass the claim to the NC server.

**Comment by axel-rutz** [comment]
Maybe someone (OP or admin) can update the title to something like
"Let NectCloud authenticate users against external OAuth / OpenID Connect Server"

**Comment by dimm0** [comment]
I'm trying to make this work: https://github.com/maltevogl/useroidc
But so far having issues with autoloading classes... Maybe somebody could take a look?

**Comment by axel-rutz** [comment]
@dimm0: That's really good news!
To your question: I'm not too deep into that, but from a quick look it might be that the [composer.json](https://github.com/maltevogl/useroidc/blob/master/composer.json) lacks the [psr4](https://getcomposer.org/doc/04-schema.md#psr-4) info like so:
```
    "autoload": {
        "psr-4": {
            "OCA\\UserOidc": "lib"
        }
    }
```

For further issues you might want to 
* fork that repo 
* add an issue with more info
* link that issue(s) here 

HTH!

**Comment by zorn-v** [comment]
https://github.com/zorn-v/nextcloud-social-login
https://apps.nextcloud.com/apps/sociallogin

Used hybridauth there https://hybridauth.github.io/providers.html, so can easy add other providers

**Comment by EgoAleSum** [comment]
Thanks for flagging this. I think this is something, but still not offering everything that I had in mind. The end goal would have to be a module that offers the same support that is offered for LDAP, which is a very legacy protocol that many are hoping to get rid of :)

A deep integration with directory services such as Google Apps and Azure AD / Office365 would not only require support for authentication through OAuth, but also the ability to use the remote directory as user database (so users wouldn't have to be re-provisioned inside Nextcloud, and every user in the directory is automatically a user in NC).

**Comment by petrk94** [comment]
Any updates here?

**Comment by wgroenewold** [comment]
I made a small tutorial to do authentication with Azure AD Connect for Nextcloud:

https://gist.github.com/wgroenewold/ace6a64537f0f500676a325632796261

**Comment by ItalyPaleAle** [comment]
That’s very interesting, thanks!

It’s a step in the right direction as it provides SSO. It still doesn’t integrate with the directory and requires LDAP somewhere, however :(

**Comment by akloster** [comment]
The release notes for NextCloud 12 say 
"Nextcloud also offers deep integration with various enterprise authentication methods. These include:

OpenID Connect
OAuth2"

Though, how does this work exactly? I haven't found clear instructions anywhere.

**Comment by petrk94** [comment]
@akloster 
I know what you mean, its not really easy to set it up. 
I could make a connection between OpenID on Wordpress with NextCloud, but the way the user name get displayed in Nextcloud is not really satisfying :/

**Comment by akloster** [comment]
How did you do it and was it OpenID or OpenID connect?

**Comment by petrk94** [comment]
@akloster I have used the OpenID Plugin for wordpress https://de.wordpress.org/plugins/openid/
and the simpleID software https://github.com/simpleid/simpleid
Unfortunately its version 2 which is providing OIDC is in develpment and the developer seems not really to be motivated or open for support to finish it. The documentation of Version 2 is unclear. If you are fine with OpenID v1, than you can selfhost it and get it connected with wordpress and with Nextcloud. But it doesnt really look to be in development anymore. Currently are VERIMI (closed source, propritary) and ID4ME (public open development, support by large corporation, on gitlab) the latest approach for a modern identity service. ID4ME is at least providing the similar structure like OpenID, but is not domain based, its DNS based, which doesnt make it easier.

**Comment by ItalyPaleAle** [comment]
Again, however, please note that this issue is about something a bit different. Not just SSO, but a deeper integration with the SaaS directory.

**Comment by LorbusChris** [comment]
+1
I'd like to use [solid](https://github.com/solid/node-solid-server) as my Identity Provider, which supports [WebID-OIDC Authentication](https://github.com/solid/webid-oidc-spec) which is based on OAuth2/OIDC.

Is this best done as a separate app or added to e.g. user_external?

**Comment by LorbusChris** [comment]
Took a stab at a OIDC auth relay over in https://github.com/nextcloud/user_saml/pull/308, feedback very welcome!

**Comment by mathiasconradt** [comment]
You can already use Nextcloud with **any** OIDC-conformant IdP, including the German IdPs "netID" and "Verimi", by using [Auth0](https://auth0.com) as a broker in between Nextcloud and the original IdP. 
Since Nextcloud supports SAML2 already ootb, you'd setup Nextcloud with SAML2 and Auth0 as IdP (broker), while in Auth0 you configure any OIDC connection (netID, Verimi, etc.).

> Nextcloud <-- (SAML2) --> Auth <-- (OIDC) --> any OIDC-conformant IdP

Useful resources related to this:

* https://medium.com/@mathiasconradt/nextcloud-single-sign-on-with-auth0-a546cdf1fccf
* https://github.com/auth0-blog/auth0-netid-sample
* https://github.com/auth0-blog/auth0-verimi-sample

Nice thing about this approach is that it's entirely based on officially supported (=supported in SLA) Nextcloud components (user_saml), doesn't rely on mod_auth_openidc.

Additionally, you'd get additional optional features such as account linking / merging (username/password and next time via social login can automatically be merged into one user).

(Disclaimer: I worked at Nextcloud before, I now work at Auth0.)

**Comment by ItalyPaleAle** [comment]
Hi @mathiasconradt please see my comment above for more details:

> The end goal would have to be a module that offers the same support that is offered for LDAP, which is a very legacy protocol that many are hoping to get rid of :)
> 
> A deep integration with directory services such as Google Apps and Azure AD / Office365 would not only require support for authentication through OAuth, but also the ability to use the remote directory as user database (so users wouldn't have to be re-provisioned inside Nextcloud, and every user in the directory is automatically a user in NC).

(Big fan of Auth0 too - just check my profile for some stuff I've done with them - but my ask is for a deeper directory integration than just what current SAML implementation offers)

**Comment by mathiasconradt** [comment]
@ItalyPaleAle Got it. Yes, your initial request was a bit broader, so for cases where only simply OIDC is needed, the above might be a way to go adhoc and with supported components.

**Comment by zamgreg** [comment]
It would be very nice to implement oidc client that would work just like user_saml
user_saml is not a solution because I'm using keycloak and throug SAML I can't manage permissions for user accounts there for which sites they can login

social login is not a solution either because it offers login through oidc as one of the options, while I want it to be the only option, with nextcloud login page always redirecting to keycloak realm login; another issue with social login is that users, that existed before connecting oidc can login either through keycloak with their keycloak passwords OR through nextcloud login with their OLD nextcloud passwords

**Comment by LorbusChris** [comment]
linking this here for reference: https://forum.solidproject.org/t/nextlcloud-with-solid-webid-login/1067

**Comment by zorn-v** [comment]
@zamgreg

> social login is not a solution either because it offers login through oidc as one of the options, while I want it to be the only option, with nextcloud login page always redirecting to keycloak realm login

You can enable `'social_login_auto_redirect' => true` setting in `config.php` if only one provider is configured.

**Comment by Anduin2017** [comment]
I got a solution: We are currently using Azure AD to authenticate our stuff. So we config a local Active Directory server and sync all objects from Azure AD. So that we got LDAP service locally. And use LDAP to connect nextcloud to our local AD server. It looks hard to config but it works.

**Comment by ItalyPaleAle** [comment]
It’s not exactly the ideal solution either, however, as you’re still relying on LDAP, and you need to manage domain controllers (with required patching, high availability...).

**Comment by kfox1111** [comment]
And your still handling the users credentials with ldap. :/

**Comment by polarathene** [comment]
@ItalyPaleAle throughout the issue you point out the issue is about external auth provider support *AND* alternatives to LDAP(suggesting Azure AD / Google Apps)... but your title isn't clear on that latter subject imo.

Personally these are two separate issues, so it doesn't help that this issue thread is trying to discuss/request both.

Are there open-source self-hosted alternatives to LDAP that are acceptable to you offering similar experience/parity to what Azure AD or Google Apps is? (I don't have experience with either).

I'm personally interested in OIDC support(or something like Grafana's Auth Proxy which uses a config to match with HTTP auth headers), preferrably with Keycloak(it provides built-in LDAP or you can use external provider). The SAML support as mentioned isn't sufficient as others have shared.

---

I'm not using NextCloud myself yet, I have come across this [NextCloud app for OIDC](https://apps.nextcloud.com/apps/oidc_login):

> *Make possible create users and login via one single OpenID Connect provider. Even though a fork of `nextcloud-social-login`, it fundamentally differs in two ways - aims for simplistic, single provider login (and hence is very minimalastic), and it supports having LDAP as the primary user backend. This way, you can use OpenID Connect to login to Nextcloud while maintaining an LDAP backend with attributes with the LDAP plugin. Supports automatic discovery of endpoints through the OpenID Connect spec, with a single provider configuration attribute.*

Could anyone with NextCloud setup give that a try and provide some feedback if it does the job well?(I'm ok with LDAP for now if I can get single OIDC provider login working as this seems to imply)

**Comment by ItalyPaleAle** [comment]
@polarathene they are two separate issues but tightly connected, as you can't implement connecting to an external directory without implementing OIDC first.

**Comment by polarathene** [comment]
Yeah... so raise the OIDC issue and push for that first. Doesn't need support for an external directory to get that through. Optionally raise a 2nd issue about external directory support and link back to it depending on the OIDC issue.

Instead you are trying to push for both in a single issue, but they're separate features.

The title itself still needs to be more clear about your two intents imo. How about:

**Support for SSO with OAuth/OIDC(Google, Github, Keycloak) and external directories(Azure AD, Google Apps)**

**Comment by pulsejet** [comment]
I have forked @zorn-v's nextcloud-social-login to [nextcloud-oidc-login](https://github.com/pulsejet/nextcloud-oidc-login), which supports only OpenID Connect 1.0 and has some very different design philosophies (only one login provider).

**Comment by zamgreg** [comment]
> It would be very nice to implement oidc client that would work just like user_saml
> user_saml is not a solution because I'm using keycloak and throug SAML I can't manage permissions for user accounts there for which sites they can login
> 
> social login is not a solution either because it offers login through oidc as one of the options, while I want it to be the only option, with nextcloud login page always redirecting to keycloak realm login; another issue with social login is that users, that existed before connecting oidc can login either through keycloak with their keycloak passwords OR through nextcloud login with their OLD nextcloud passwords

Followup. Everything is fine, no issues. First one could be managed on keycloak's side by adding a custom script to a login flow, the second thing could be managed by manually deleting strings with your existing users from nextcloud DB. Those users will be recreated after login and you'll keep everything because uids are the same and all references to users in DB are there. It sounds like a bad advice, though after such recreation (after swithching to user_saml in my case, though this should be applicable to social login as well) I had everything in place, even my unread articles in rss reader.

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/user_oidc
