### ISSUE TITLE
Preview is active on file sidebar even if preview is set false on config.php

### ISSUE THREAD

**Issue by rogerfv1** [nextcloud/server#6764]
### Steps to reproduce
1. Set 'enable_previews' => false on config.php.
2. Create a 'new text file' (ex: preview.txt).
3. Click on 'Details' of that file.

### Expected behaviour
The preview should not be shown on details sidebar.

### Actual behaviour
The preview is showed on details sidebar.

### Server configuration

**Operating system**: Debian 8

**Web server:** Apache 2.4

**Database:** Postgresql 9.4

**PHP version:** php 5.6

**Nextcloud version:** 12.0.3

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

We looked at the source code to see if we found the function that defines the preview load.
So we find a javascript function named loadPreview but it seems that this function is not considering the enable_previews set on config.php.

File: /var/www/nextcloud/apps/files/js/sidebarpreviewmanager.js

"...
_loadPreview: function (model, $thumbnailDiv, $thumbnailContainer) {
    if (model.get('hasPreview') === false && **this.getMimeTypePreviewHandler(model.get('mimetype')) === null**) {_
...
"

In this case when getMimeTypePreviewHandler = 'native code'  the preview is showed even you set  enable_previews to false on config.php.

These are the results we got in our tests.

enable_previews (config.php) | MimeType | hasPreview | getMimeTypePreviewHandler | Preview is showed?(actual behaviour) | Preview is showed? (expected behaviour)
-- | -- | -- | -- | -- | --
true | text/plain | true | native code | yes | yes
true | image/png | true | null | yes | yes
true | text/csv | false | native code | yes | yes
true | application/pdf | false | native code | yes | yes
false | text/plain | false | native code | **yes** | **no**
false | image/png | false | null | false | yes
false | text/csv | false | native code | **yes** | **no**
false | application/pdf | false | native code | **yes** | **no**

**Comment by danxuliu** [comment]
@rogerfv1 Thanks for the detailed information!

This happens in current master too, and it could be solved by providing the `enable_previews` value in [`oc_config` in `JSConfigHelper.php`](https://github.com/nextcloud/server/blob/1bcbeb24bcb82f825d1993217cdb6878375c5077/lib/private/Template/JSConfigHelper.php#L214) and then taking `oc_config.enable_previews` into account in [the condition of `SidebarPreviewManager.loadPreview`](https://github.com/nextcloud/server/blob/a4900bf23fb7b3aca8e773926322742e8ccf0c3a/apps/files/js/sidebarpreviewmanager.js#L44).

For consistency it should be taken into account too in [the public shared file page](https://github.com/nextcloud/server/blob/372e7acfafafaf58b6e4abdaaf13fddf2948090a/apps/files_sharing/js/public.js#L130-L158).

However... should `enable_previews` in the system configuration be used for all that, or should its effects be limited to the generation of previews in the server? In that later case it would be good to add a parameter anyway in the administration settings of the WebUI to control whether previews are shown o not. @MorrisJobke @rullzer @blizzz @nickvergessen

**Comment by blizzz** [comment]
or vice versa, loadPreviews should take enable_previews into account? after all it has an else branch, so it can continue there in case.

**Comment by fgsl** [comment]
I think that change must be implemented according to proposed by @rogerfv1 and @danxuliu.
From the point of view of sysadmin, I think that enable_previews must be used in the system configuration for all.

**Comment by fgsl** [comment]
@rullzer, according @rogerfv1, there are two reasons to disable image previews:

1. There is a note in Nextcloud documentation suggesting to disable preview for enforcing environment:
https://docs.nextcloud.com/server/12/admin_manual/configuration_server/harden_server.html

2. For load/performance test that @rogerfv1 did (two years ago), response time of file access was better with enable_previews disabled. So, we got to serve more users with same configuration. One observation: we don't have these comparison data between times anymore.

**Comment by skjnldsv** [comment]
Fixed with https://github.com/nextcloud/server/pull/15719

**Comment by danxuliu** [comment]
If I am not mistaken the issue is hidden, but not fixed, by #15719; #15719 breaks the `SidebarPreviewManager`, but as soon as that is fixed I think that this issue will appear again.

**Comment by skjnldsv** [comment]
Now because we now rely on what dav is telling us (if a file have a preview or not
https://github.com/nextcloud/server/blob/b81fb182b3d793882a1942c852e8c3d2262b3de9/apps/dav/lib/Connector/Sabre/FilesPlugin.php#L355
https://github.com/nextcloud/server/blob/98f91982be83969c0084ad64c72aeaa72d8c4bcc/lib/private/PreviewManager.php#L218

**Comment by danxuliu** [comment]
But the `SidebarPreviewManager` purpose, if I am not mistaken, is to provide client-only previews besides any server preview that the file might or might not have. Therefore the preview from the `SidebarPreviewManager` should not be based on the information returned by DAV (but it should nevertheless honour the `enable_previews` setting or something additional as discussed in this issue).

**Comment by skjnldsv** [comment]
You can forgtot about the SidebarPreviewManager :)
