### ISSUE TITLE
[13.0.0RC2] Login buttion is off 

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#8043]
![skarmbild fran 2018-01-25 09 07 07](https://user-images.githubusercontent.com/4511254/35377634-4116211e-01b0-11e8-8370-3620a50957c4.png)

What's also not looking good IMHO is the new layout of files where the text is below the icon:
![skarmbild fran 2018-01-25 09 15 44](https://user-images.githubusercontent.com/4511254/35377688-76df8eac-01b0-11e8-8b32-a932c5dbcdc1.png)

Would be better if they where in one row instead.

This is a fresh install with 12.0.5 updated to 13.0.0RC2, using Firefox 57.

## Server configuration detail

**Operating system:** Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64

**Webserver:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** pgsql PostgreSQL 9.6.6 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit

**PHP version:** 7.0.22-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, redis, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mcrypt, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 13.0.0 RC 2 - 13.0.0.11

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Updated from a fresh install of 12.0.5

**Where did you install Nextcloud from:** VM scripts (Nextcloud)

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - cms_pico: 0.9.7
 - comments: 1.3.0
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - passman: 2.1.4
 - password_policy: 1.3.0
 - previewgenerator: 1.0.9
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - user_ldap: 1.3.1
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_external

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "192.168.7.9",
        "nextcloudintern",
        "nextcloudintern"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/nextcloudintern\/",
    "dbtype": "pgsql",
    "version": "13.0.0.11",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "log_rotate_size": "10485760",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "htaccess.RewriteBase": "\/",
    "loglevel": "2",
    "log_type": "file",
    "logfile": "\/var\/ncdata\/nextcloud.log",
    "logtimezone": "Europe\/Stockholm",
    "maintenance": false,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpport": "587",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
+-------------------------------+--------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                            |
+-------------------------------+--------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                          |
| hasPagedResultSupport         |                                                                                            |
| homeFolderNamingRule          |                                                                                            |
| lastJpegPhotoLookup           | 0                                                                                          |
| ldapAgentName                 | CN=Administrator,CN=Users,DC=gruppen,DC=local                                   |
| ldapAgentPassword             | ***                                                                                        |
| ldapAttributesForGroupSearch  |                                                                                            |
| ldapAttributesForUserSearch   |                                                                                            |
| ldapBackupHost                |                                                                                            |
| ldapBackupPort                |                                                                                            |
| ldapBase                      | DC=gruppen,DC=local                                                             |
| ldapBaseGroups                | DC=gruppen,DC=local                                                             |
| ldapBaseUsers                 | DC=gruppen,DC=local                                                             |
| ldapCacheTTL                  | 600                                                                                        |
| ldapConfigurationActive       | 1                                                                                          |
| ldapDefaultPPolicyDN          |                                                                                            |
| ldapDynamicGroupMemberURL     |                                                                                            |
| ldapEmailAttribute            | mail                                                                                       |
| ldapExperiencedAdmin          | 0                                                                                          |
| ldapExpertUUIDGroupAttr       |                                                                                            |
| ldapExpertUUIDUserAttr        |                                                                                            |
| ldapExpertUsernameAttr        | samaccountname                                                                             |
| ldapGidNumber                 | gidNumber                                                                                  |
| ldapGroupDisplayName          | cn                                                                                         |
| ldapGroupFilter               | (&(|(objectclass=group)))                                                                  |
| ldapGroupFilterGroups         |                                                                                            |
| ldapGroupFilterMode           | 0                                                                                          |
| ldapGroupFilterObjectclass    | group                                                                                      |
| ldapGroupMemberAssocAttr      | member                                                                                     |
| ldapHost                      | ldap://192.168.X.XXX                                                                       |
| ldapIgnoreNamingRules         |                                                                                            |
| ldapLoginFilter               | (&(&(|(objectclass=user)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                            |
| ldapLoginFilterEmail          | 1                                                                                          |
| ldapLoginFilterMode           | 0                                                                                          |
| ldapLoginFilterUsername       | 1                                                                                          |
| ldapNestedGroups              | 0                                                                                          |
| ldapOverrideMainServer        |                                                                                            |
| ldapPagingSize                | 500                                                                                        |
| ldapPort                      | 389                                                                                        |
| ldapQuotaAttribute            |                                                                                            |
| ldapQuotaDefault              |                                                                                            |
| ldapTLS                       | 0                                                                                          |
| ldapUserDisplayName           | displayname                                                                                |
| ldapUserDisplayName2          |                                                                                            |
| ldapUserFilter                | (&(|(objectclass=user)))                                                                   |
| ldapUserFilterGroups          |                                                                                            |
| ldapUserFilterMode            | 0                                                                                          |
| ldapUserFilterObjectclass     | user                                                                                       |
| ldapUuidGroupAttribute        | auto                                                                                       |
| ldapUuidUserAttribute         | auto                                                                                       |
| turnOffCertCheck              | 0                                                                                          |
| turnOnPasswordChange          | 0                                                                                          |
| useMemberOfToDetectMembership | 1                                                                                          |
+-------------------------------+--------------------------------------------------------------------------------------------+

```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://192.168.7.9/core/vendor/core.js?v=ced14337-20
Source Map URL: purify.min.js.map
</details>

**Comment by enoch85** [comment]
cc @nextcloud/designers

**Comment by juliushaertl** [comment]
@enoch85 Please fill out the issue template and provide logs for both server/client for that. I cannot reproduce that. Seems some css is not loaded properly.

**Comment by enoch85** [comment]
@juliushaertl Sorry, updated accordingly.

**Comment by enoch85** [comment]
Same thing on another server that I updated a few days ago. Strange thing is that it works on my own server which also is 13.0.0RC2, so hard bug to track down...

**Comment by MorrisJobke** [comment]
@skjnldsv and another one with CSS issues :/

**Comment by enoch85** [comment]
You could move it to 13.0.1, but I can imagine a lot of tickets regarding this if it isn't fixed before.

**Comment by juliushaertl** [comment]
I'm still unable to reproduce, can you check if this might be a browser caching issue and check the browser console for errors/css that might not be loaded?

**Comment by juliushaertl** [comment]
Another option would be to reset the scss cache to see if it works fine after all css is generated again.

Those two steps should accomplish that:
- rm -r data/appdata_*/css/*
- occ files:scan-app-data
- reload the page

**Comment by enoch85** [comment]
> I'm still unable to reproduce, can you check if this might be a browser caching issue and check the browser console for errors/css that might not be loaded?

I tried in incognito, so no cache. 

> Another option would be to reset the scss cache to see if it works fine after all css is generated again.

Didn't work, still same issue - both in Chrome and Firefox.

**Comment by enoch85** [comment]
@juliushaertl Thanks for investigating. Sent you an email.

**Comment by enoch85** [comment]
Issue solved:

```
root@fsgo:/var/ncdata# ll appdata_*/js/files/
total 404
drwxr-xr-x  2 www-data www-data   4096 maj 22  2017 ./
drwxr-xr-x 12 www-data www-data   4096 maj 22  2017 ../
-rw-r--r--  1 www-data www-data 321604 jan 12 19:49 merged-index.js
-rw-r--r--  1 www-data www-data   1957 jan 12 19:49 merged-index.js.deps
-rw-r--r--  1 www-data www-data  76809 jan 12 19:49 merged-index.js.gzip
root@fsgo:/var/ncdata# rm -r appdata_ocdd06e12069/js/
root@fsgo:/var/ncdata# sudo -u www-data php /var/www/nextcloud/occ files:scan-app-data

Scanning AppData for files

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 5161    | 53462 | 00:00:57     |
+---------+-------+--------------+
root@fsgo:/var/ncdata# 
```

**Comment by enoch85** [comment]
Can this make 13.0.0 please?

**Comment by juliushaertl** [comment]
The JSCombiner checks for the mtime of javascript files and generates new ones based on that.  It is quite strange that those files have the timestamp from when the update is happening but still contain the old javascript content. I've no idea why this could happen. @rullzer maybe?

@enoch85 The solution would basically be to force rebuild of combined javascript during the update, which is tracked at #7984

**Comment by skjnldsv** [comment]
@juliushaertl could we clear cache on each update? It would be a great way to ensure fresh content imho :)

**Comment by juliushaertl** [comment]
That would be my plan. I thought we also had an issue about that but I cannot find it atm. :confused:

**Comment by enoch85** [comment]
> Could this make 13.0.0 please?

@MorrisJobke --^

**Comment by MorrisJobke** [comment]
> Could this make 13.0.0 please?

Not likely. The RC4 is out and we don't accept any code anymore. And also there isn't even a solution available. Once this is there we can look into bring it to some release ;)

**Comment by MorrisJobke** [comment]
Fixed by #8197 in 13.0.1

**Comment by Corvan** [comment]
Hey guys, just updated my Nextcloud last week and had exactly this error, even though I am on the stable track and waited for some time until updating. This is a bit unfortunate that it happened anyways, a stable update process looks a bit different to me.

**Comment by enoch85** [comment]
> I am on the stable track and waited for some time until updating.

@Corvan If NC 13 is released then that's the release. Nothing happens because you wait, it's still the same Nextcloud as long as the version is 13. 

With that said, if you are looking to update to a major release (10, 11, 12, 13 and son on) then it's usually best to wait until 13.0.1 is out. Then all the minor issues like these are solved.  

You are very welcome to test releases before they hit stable as well. Before a stable release there are RC releases in which people test as much as possible before the final release of a new version.

**Comment by juliushaertl** [comment]
Should finally be fixed with https://github.com/nextcloud/server/pull/8714 and https://github.com/nextcloud/server/pull/8716
