### ISSUE TITLE
fseek(): stream does not support seeking at *** with S3

### ISSUE THREAD

**Issue by tomtomas99911** [nextcloud/server#8275]
Hi,
i have problem with Nextcloud and S3 based on CEPH. When I am accessing some files (e.g. *jpg) I am getting this error : "fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74"

Is there any way to repair it please? 

### Steps to reproduce
1. Use CEPH S3 storage
2. Set S3 as a primary storage

### Server configuration

**Operating system**:
Debian 9

**Web server:**
Apache 2
**Database:**
Percona DB
**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 13
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

</details>

**Are you using external storage, if yes which one:** S3

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** NO

**Comment by MorrisJobke** [comment]
cc @icewind1991 @rullzer

**Comment by dnwk** [comment]
I am having the same problem when using S3 as primary storage. 
fseek(): stream does not support seeking at /var/www/html/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php#74  is coming up repeatly in my log. However, I haven't encounter failure in opening the file.

**Comment by MorrisJobke** [comment]
Could you check with the upcoming 13.0.3. We updated quite some code in the object storage and filesystem part.

If this is then still not resolved, we could reopen the ticket again and check what's going on here.

**Comment by C439** [comment]
Hi, sorry to re-open this issue. I'm using Nextcloud version13.0.4 and I can see this issue in my log: 
fseek(): stream does not support seeking at /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php#74.
This only happens when I open a video in my external, not encrypted S3 storage.

**Comment by C439** [comment]
@MorrisJobke I'm using [DigitalOcean Spaces](https://www.digitalocean.com/products/spaces/), it's similar to S3. 

Unrelated but another issue I have is that I first used decryption on the storage and then disabled it, this results in error messages like "OC\Encryption\Exceptions\DecryptionFailedException: Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you." and "Couldn't re-calculate unencrypted size for files_versions/<directory>". The files don't exist anymore. Can I fix this somehow?

**Comment by Gmognon** [comment]
@MorrisJobke I Can confirm this behavior when using S3 as Primary Storage and watch a video on web interface.
The video plays ok, but log this. 
fseek(): stream does not support seeking at /var/www/html/nextcloud/3rdparty/icewind/streams/src/Wrapper.php#74

**Comment by tomtomas99911** [comment]
Same problem on NX 14.0.0 - I am facing this issue when I am syncing files via Windows Client.

**Comment by HLFH** [comment]
Same issue on NC 15. I can provide logs if that can help.

**Comment by HLFH** [comment]
@MorrisJobke @icewind1991 Hi. Is this issue fixed by https://github.com/nextcloud/server/pull/13866?

**Comment by koehn** [comment]
I'm using 15.0.4 which includes #13866 and I'm still seeing the issue in the logs:

```
fseek(): stream does not support seeking at /var/www/html/3rdparty/icewind/streams/src/Wrapper.php
```

**Comment by theopen-institute** [comment]
I am also still seeing this issue in 15.0.5 using S3 (digital ocean) as primary backend. Specifically, it prevents all functioning of the collabora plugin on my server.

**Comment by helge000** [comment]
Same here, using Amazon S3

**Comment by torbenschinke** [comment]
I see this also using Minio S3 Server in 15.0.5

**Comment by MorrisJobke** [comment]
cc @rullzer

**Comment by jothoma1** [comment]
Same here, ceph backend with 15.0.7

**Comment by neckos** [comment]
Getting the same error on Wasabi Object Storage as primary storage with 15.0.7

**Comment by Tost69** [comment]
Same issue with 15.0.7 on a Synology NAS when using the Nextcloud app with audio or video files from  external storage (secured webdav on the same machine). To use this are there special requirements for the transmission protocol (e.g. ftp, sftp, unsecured webdav) or is there a php module which needs to be enabled? Thanks and Kind regards, Tom

**Comment by alexgreenshift** [comment]
Same issue with 16.0.1 using S3 storage backed by a Ceph RGW gateway.  It seems to be happening with MOV's and PNG's for me.  

[PHP] Error: fseek(): stream does not support seeking at /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php#82 GET /remote.php/dav/files/.../IMG_7495.MOV

Thanks
Alex

**Comment by zocker-160** [comment]
I have same issue when trying to move / copy / delete text files in my folder, which is a external file share from another NC server.

It looks like a general issue with external_files regardless of share type (NC, ftp, webdav etc)

**Comment by msumm** [comment]
I observe the same log entries every time I access a txt/md-file using the new Text App where the file is located on an external WebDAV storage.
Anyhow, there is no restriction in functionality - I can view and edit the files.

**Comment by KimmoJ** [comment]
16.0.4, my logs are absolutely hammered with this error, I deleted a gigabyte and have another in the most recent log. Wasabi S3, the External Storage plugin. I'm not seeing anything obviously break in NC itself, Collabora works, I can listen to music with the Music app. I do have abnormally high PHP CPU usage, which may well be related.

**Comment by snomisneb** [comment]
I'm having the same issue with NC 16.0.4. I have fixed this 'issue' in the past with an edited version of the AmazonS3.php file but I can't find this file anymore on GitHub!

**Comment by firemdkfighter** [comment]
My installation NC 17.0.1 have the same issue

**Comment by joelkennedy** [comment]
I thought it might be possible to support this by adding 's3' => ['seekable' => true] to https://github.com/nextcloud/server/blob/6a940d5c742490e4e891f675e3f45b5f975cf650/lib/private/Files/ObjectStore/S3ObjectTrait.php#L66 but it doesn't seem to work. 

Not sure if that is on the right lines or not.

https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html

**Comment by tsalwierz** [comment]
Same issue!

**Comment by totalcaos** [comment]
I have the same issue .. running NC 17.0.2 with S3 as primary storage on Ubuntu 18.04

**Comment by krakazyabra** [comment]
Me too. NC 17.0.1 on Debian 10, Minio S3 as primary storage, using `objectstore_multibucket`

**Comment by Dragon988** [comment]
Is there a workaround for this? Also using multibucket.

**Comment by Amalinda** [comment]
same issue on NC 18, Debian Amazon S3.

**Comment by kc0bfv** [comment]
Updating to 19.0.0 RC1 - I no longer see this error message when taking actions that would have previously shown it.

**Comment by MorrisJobke** [comment]
> Updating to 19.0.0 RC1 - I no longer see this error message when taking actions that would have previously shown it.

Let's close this then for now.

**Comment by krakazyabra** [comment]
@MorrisJobke It will be nice, if there will be fix for this bug in production branch (16.0.11)

**Comment by krakazyabra** [comment]
Update: continue to see this error on 18.0.6 with minio S3 as primary storage. Now it appears, when user tries to connect mobile phone. 
@Morikko using release candidate version - is not solving of the problem.

**Comment by cy8aer** [comment]
For me it already fails when opening the file with fopen because of

    certificate verify failed at /var/www/html/lib/private/Files/ObjectStore/S3ObjectTrait.php#73

Though creating the S3 storage and adding deleting objects into the store does not make any problems (own certificte chain, simply stored in `/etc/ssl/certs/ca-certificates.crt`
