### ISSUE TITLE
Decryption failed with s3

### ISSUE THREAD

**Issue by TecJon** [nextcloud/server#8299]
### Steps to reproduce
1. Add s3 external storage
2. Enable default encryption module for external storage
3. Create a folder and upload image files to the external storage using web interface.
4. Open the file / download the file
5. Delete the folder.

### Expected behaviour
The web interface should display the image.  Download should be possible.
The folder should get deleted.

### Actual behaviour
Open: "Error! Could not generate a preview for this file." screen stays black.
Download: File not found browser error
Delete: "Error deleting file test" (test is actually a folder)

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
 nginx/1.10.3
**Database:**
mysql
**PHP version:**
7.0
**Nextcloud version:** 
13.0.0.14
**Updated from an older Nextcloud/ownCloud or fresh install:**
update
**Where did you install Nextcloud from:**
updater
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - caniupdate: 0.1.2
  - comments: 1.3.0
  - contacts: 2.0.1
  - dav: 1.4.6
  - encryption: 2.0.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_automatedtagging: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.2.0
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.9
  - metadata: 0.6.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - previewgenerator: 1.0.9
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_email: 1.0.3
  - spreed: 3.0.1
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - nextant
  - survey_client
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "appstore.experimental.enabled": false,
        "asset-pipeline.enabled": true,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\PDF"
        ]
    }
}

```
</details>

**Are you using external storage, if yes which one:** 
S3
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 58
**Operating system:**
Win 10 
#### Web server error log
<details>
<summary>Web server error log</summary>

```
No errors.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Open file using web interface:
{"reqId":"GT0dm99KGTkForeBI6wm","level":3,"time":"2018-02-10T16:47:24+00:00","remoteAddr":"xx.xxx.xx.xxx","user":"user","app":"gallery","method":"GET","url":"\/apps\/gallery\/preview\/491404?width=2000&height=2000&c=5a7f1ca7d33cf&requesttoken=C3KpKPDpsldwblDmU%2F1ZgYoTDSLMCC5VeETNRTffyNg%3D%3AJEfnecmY3B0gP2WlZaga6eRCOxH0RGMRMjPmCGK%2Bg4I%3D","message":"Exception: Preview generation has failed","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}


Try to delete folder: 
{"reqId":"wO1IIM9dmHqCSyH3COj0","level":4,"time":"2018-02-10T16:48:11+00:00","remoteAddr":"xx.xxx.xx.xxx","user":"user","app":"webdav","method":"DELETE","url":"\/remote.php\/webdav\/AmazonS3\/test","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Encryption library: Decryption (symmetric) of content failed: \",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Crypt.php(471): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decrypt(*** sensitive parameters replaced ***)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Encryption.php(380): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('LmSZEvMHRwf75VA...', '`\\\\x81oj&\\\\xB6O\\\\xB3\\\\x06\\\\xA3{!\\\\x96\\\\n\\\\xB4...', 'AES-256-CTR', 1, 0)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(464): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt(*** sensitive parameters replaced ***)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(295): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/helper.php(297): fread(Resource id #152, 8192)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(747): OC_Helper::streamCopy(Resource id #152, Resource id #153)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(644): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyBetweenStorage(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), 'test\\\/15896368_1...', 'files_trashbin\\\/...', false, true)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(739): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyFromStorage(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), 'test\\\/15896368_1...', 'files_trashbin\\\/...', false, true)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(616): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyBetweenStorage(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), 'test', 'files_trashbin\\\/...', true, true)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(573): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->moveFromStorage(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), 'test', 'files_trashbin\\\/...')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(573): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->moveFromStorage(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), 'test', 'files_trashbin\\\/...')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_accesscontrol\\\/lib\\\/StorageWrapper.php(586): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->moveFromStorage(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), 'test', 'files_trashbin\\\/...')\\n#13 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(254): OCA\\\\FilesAccessControl\\\\StorageWrapper->moveFromStorage(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), 'test', 'files_trashbin\\\/...')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(289): OCA\\\\Files_Trashbin\\\\Trashbin::move2trash('AmazonS3\\\/test', false)\\n#15 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(208): OCA\\\\Files_Trashbin\\\\Storage->doDelete('test', 'rmdir')\\n#16 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(91): OCA\\\\Files_Trashbin\\\\Storage->rmdir('test')\\n#17 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_accesscontrol\\\/lib\\\/StorageWrapper.php(75): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->rmdir('test')\\n#18 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1148): OCA\\\\FilesAccessControl\\\\StorageWrapper->rmdir('test')\\n#19 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(346): OC\\\\Files\\\\View->basicOperation('rmdir', '\\\/AmazonS3\\\/test', Array)\\n#20 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(303): OC\\\\Files\\\\View->rmdir('\\\/AmazonS3\\\/test')\\n#21 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->delete()\\n#22 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(287): Sabre\\\\DAV\\\\Tree->delete('AmazonS3\\\/test')\\n#23 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#24 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#25 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#26 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#27 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#28 \\\/var\\\/www\\\/nextcloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/nextcl...')\\n#29 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Crypt.php\",\"Line\":589,\"Hint\":\"Encryption library: Decryption (symmetric) of content failed: \"}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}

Try to download file:
{"reqId":"HXWHRhMs3BsQ8ySmK26M","level":3,"time":"2018-02-10T17:08:10+00:00","remoteAddr":"xx.xxx.xx.xxx","user":"user","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php:796\nStack trace:\n#0 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(2057): OC\\Files\\Filesystem::normalizePath('\/user\/files\/Am...')\n#1 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(1182): OC\\Files\\View->unlockFile('\/AmazonS3\/test\/...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php#796","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}


```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
No errors.
```
</details>

**Comment by TecJon** [comment]
Subfolder shows same behavior as #7420

**Comment by TecJon** [comment]
@schiessle could you look into this? I believe this could be encryption related.

**Comment by brennovich** [comment]
I'm having the same issue, and it happens when encryption is enable in external storage configuration. I noticed that if a small file is upload everething goes just fine (by small I mean `~128k`), otherwise occurs just as @TecJon described.

Also, only small files are able to be downloaded, the followig errors occurs when trying to download bigger files (more than 1mb):

```
OCP\Encryption\Exceptions\GenericEncryptionException: Missing Signature

    /var/www/nextcloud/apps/encryption/lib/Crypto/Crypt.php - line 529: OCA\Encryption\Crypto\Crypt->hasSignature('KNxCDlE1EkjYu2V...', 'AES-256-CTR')
    /var/www/nextcloud/apps/encryption/lib/Crypto/Crypt.php - line 462: OCA\Encryption\Crypto\Crypt->splitMetaData('KNxCDlE1EkjYu2V...', 'AES-256-CTR')
    /var/www/nextcloud/apps/encryption/lib/Crypto/Encryption.php - line 380: OCA\Encryption\Crypto\Crypt->symmetricDecryptFileContent('KNxCDlE1EkjYu2V...', '1\xF7Z\xD41M\xE2Y\x80\x16\x96\x13\xC9\xE3|...', 'AES-256-CTR', 1, 53)
    /var/www/nextcloud/lib/private/Files/Stream/Encryption.php - line 464: OCA\Encryption\Crypto\Encryption->decrypt(*** sensitive parameters replaced ***)
    /var/www/nextcloud/lib/private/Files/Stream/Encryption.php - line 295: OC\Files\Stream\Encryption->readCache()
    [internal function] OC\Files\Stream\Encryption->stream_read(5864)
    /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php - line 83: fread(Resource id #173, 8192)
    /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php - line 91: Icewind\Streams\Wrapper->stream_read(8192)
    [internal function] Icewind\Streams\CallbackWrapper->stream_read(8192)
    /var/www/nextcloud/3rdparty/sabre/http/lib/Sapi.php - line 80: stream_copy_to_stream(Resource id #176, Resource id #177, '2610344')
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 498: Sabre\HTTP\Sapi sendResponse(Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 164: require_once('/var/www/nextcl...')
```

```
Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /var/www/nextcloud/lib/private/Files/Filesystem.php:796 Stack trace: #0 /var/www/nextcloud/lib/private/Files/View.php(2057): OC\Files\Filesystem::normalizePath('/USERNAME/fil...') #1 /var/www/nextcloud/lib/private/Files/View.php(1182): OC\Files\View->unlockFile('/AmazonS3/FILE...', 1) #2 [internal function]: OC\Files\View->OC\Files\{closure}() #3 /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #5 {main} thrown at /var/www/nextcloud/lib/private/Files/Filesystem.php#796
```

**Comment by im-fabian** [comment]
Same problem here.

PHP 7.2.4
NGINX 1.6.2
Nextcloud 13.0.2

**Comment by lamdacore** [comment]
Definitely something to do with the encryption module. Files already on the s3 bucket can be accessed without problems.

Nextcloud 13.0.2
php 7.2.5
Apache 2.4.33

**Comment by TecJon** [comment]
A small text file (1KB) can indeed be opened on the web interface. But even a small image (16KB) will result in above mentioned errors.

The preview app has issues with images in these folders, too. Name: `slightly_longer_filename.jpg`

```
Preview accessed: "tly_longer_filename.jpg" (width: "32", height: "32" crop: "1", mode: "fill") 
```

The log will always cut off the beginning a file name. Name: `test.jpg`
```
Preview accessed: ".jpg" (width: "32", height: "32" crop: "1", mode: "fill")
```

@icewind1991 any news on this?

**Comment by MartinBober** [comment]
I just wanted to try out Nextcloud and ran into this issue. Kind of a deal-breaker for me. I also deleted everything and re-tried with 12.0.7 with the same result. Uploading of files (photos in my case) works but downloading the file, I only get garbage.

**Comment by cheesefinger** [comment]
Same problem as @brennovich

Interestingly enough if I retry the file several times it eventually works. Intermittent failure makes me think there's issues with s3 implementation rather than the encryption.


```
OCP\Encryption\Exceptions\GenericEncryptionException: Missing Signature

    /var/www/html/nextcloud/apps/encryption/lib/Crypto/Crypt.php - line 529: OCA\Encryption\Crypto\Crypt->hasSignature('kv+SHorhmiIQJPT...', 'AES-256-CTR')
    /var/www/html/nextcloud/apps/encryption/lib/Crypto/Crypt.php - line 462: OCA\Encryption\Crypto\Crypt->splitMetaData('kv+SHorhmiIQJPT...', 'AES-256-CTR')
    /var/www/html/nextcloud/apps/encryption/lib/Crypto/Encryption.php - line 380: OCA\Encryption\Crypto\Crypt->symmetricDecryptFileContent('kv+SHorhmiIQJPT...', '\xD54#\x85\xBC\xE8\xDC\x15N\xC2X\xA6\xF7\x9Ab...', 'AES-256-CTR', 1, 1)
    /var/www/html/nextcloud/lib/private/Files/Stream/Encryption.php - line 464: OCA\Encryption\Crypto\Encryption->decrypt(*** sensitive parameters replaced ***)
    /var/www/html/nextcloud/lib/private/Files/Stream/Encryption.php - line 295: OC\Files\Stream\Encryption->readCache()
    [internal function] OC\Files\Stream\Encryption->stream_read(2120)
    /var/www/html/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php - line 83: fread(Resource id #77, 8192)
    /var/www/html/nextcloud/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php - line 91: Icewind\Streams\Wrapper->stream_read(8192)
    [internal function] Icewind\Streams\CallbackWrapper->stream_read(8192)
    /var/www/html/nextcloud/3rdparty/sabre/http/lib/Sapi.php - line 80: stream_copy_to_stream(Resource id #80, Resource id #82, '844208')
    /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 498: Sabre\HTTP\Sapi sendResponse(Object(Sabre\HTTP\Response))
    /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/html/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()
    /var/www/html/nextcloud/remote.php - line 164: require_once('/var/www/html/n...')
    {main}
```

**Comment by cheesefinger** [comment]
no issues when using server-side encryption with goofys

**Comment by stache3000** [comment]
I have same problem with S3 external storage. Preview is KO, and download say "File not found Firefox can’t find the file at https://fqdn/remote.php/webdav/mybuckets/chat.jpg?downloadStartSecret=krj1575u8uv.

Have you a solution to migrate from "external storage S3" to a "local goofys" to recover all files in my bucket ? (all user key + masterkey + DB are OK, but nextcloud encryption module for external file doesn't works and locks all my files)

**Comment by zgec** [comment]
Same problem here, issue with brand new setup with docker(-compose), tried even using latest image: 13.0.3RC2-apache

External storage + Encryption = same problem as OP

Without encryption no problem.

Local storage + Encryption = no problem

**Comment by ninjao** [comment]
I have this exact issue. Does anyone have some kind of a solution?

Uploads directly to S3 are visible and downloadable perfectly fine. However anything uploaded via web interface from next cloud to S3 gets destroyed.

Preview fails in console with: 
`preview.png:1 GET https://hidden.domain/index.php/core/preview.png?file=%2FJulien+Cloud%2Fsony_logo_PNG2.png&c=5b2980276cdbe&x=56&y=56&forceIcon=0 503 (Service Unavailable)`

After upload there is no error log entry (/home/admin/web/hidden.domain/logs).

Upon download through web interface it produces the following error: 

`[Wed Jun 20 00:14:42.785997 2018] [:error] [pid 18630] [client xxx.xx.xx.xxx:xxxxx] PHP Fatal error:  Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in /home/admin/web/hidden.domain/public_html/lib/private/Files/Filesystem.php:796\nStack trace:\n#0 /home/admin/web/hidden.domain/public_html/lib/private/Files/View.php(2055): OC\\Files\\Filesystem::normalizePath('/admin/files/Ju...')\n#1 /home/admin/web/hidden.domain/public_html/lib/private/Files/View.php(1182): OC\\Files\\View->unlockFile('/Julien Cloud/s...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 /home/admin/web/hidden.domain/public_html/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown in /home/admin/web/hidden.domain/public_html/lib/private/Files/Filesystem.php on line 796`

Man, I havnt been able to get uploads working to external storage for weeks. Im slowly starting to give up :( 

I have tried so many solutions that work sometimes but each one brings me just another problem.

**Comment by dudelson** [comment]
Same issues here: using encrypted s3 external storage, files appear to be completely corrupted, and I cannot preview or open them in any nextcloud client. In my case, I first get this:

```
OCP\Encryption\Exceptions\GenericEncryptionException: Bad Signature

    /snap/nextcloud/7658/htdocs/apps/encryption/lib/Crypto/Crypt.php - line 465: OCA\Encryption\Crypto\Crypt->checkSignature('oNd+ME3y+DFT1d6...', '\x1A?l'@W\x99\x9CBY\xD7w\x046@...', 'da5fc522b67af6d...')
    /snap/nextcloud/7658/htdocs/apps/encryption/lib/Crypto/Encryption.php - line 380: OCA\Encryption\Crypto\Crypt->symmetricDecryptFileContent('oNd+ME3y+DFT1d6...', '\x1A?l'@W\x99\x9CBY\xD7w\x046@...', 'AES-256-CTR', 1, '157end')
    /snap/nextcloud/7658/htdocs/lib/private/Files/Storage/Wrapper/Encryption.php - line 576: OCA\Encryption\Crypto\Encryption->decrypt(*** sensitive parameters replaced ***)
    /snap/nextcloud/7658/htdocs/lib/private/Files/Storage/Wrapper/Encryption.php - line 495: OC\Files\Storage\Wrapper\Encryption->fixUnencryptedSize('files/Photos/Nu...', 1288536, 1296728)
    /snap/nextcloud/7658/htdocs/lib/private/Files/Storage/Wrapper/Encryption.php - line 164: OC\Files\Storage\Wrapper\Encryption->verifyUnencryptedSize('files/Photos/Nu...', 1296728)
    /snap/nextcloud/7658/htdocs/lib/private/Files/Storage/Wrapper/Encryption.php - line 403: OC\Files\Storage\Wrapper\Encryption->filesize('files/Photos/Nu...')
    /snap/nextcloud/7658/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php - line 298: OC\Files\Storage\Wrapper\Encryption->fopen('files/Photos/Nu...', 'r')
    /snap/nextcloud/7658/htdocs/lib/private/Files/View.php - line 1146: OC\Files\Storage\Wrapper\Wrapper->fopen('files/Photos/Nu...', 'r')
    /snap/nextcloud/7658/htdocs/lib/private/Files/View.php - line 987: OC\Files\View->basicOperation('fopen', '/Photos/Nut.jpg', Array, 'r')
    /snap/nextcloud/7658/htdocs/apps/dav/lib/Connector/Sabre/File.php - line 335: OC\Files\View->fopen('Photos/Nut.jpg', 'r')
    /snap/nextcloud/7658/htdocs/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 88: OCA\DAV\Connector\Sabre\File->get()
    [internal function] Sabre\DAV\CorePlugin->httpGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /snap/nextcloud/7658/htdocs/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /snap/nextcloud/7658/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method GET', Array)
    /snap/nextcloud/7658/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /snap/nextcloud/7658/htdocs/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()
    /snap/nextcloud/7658/htdocs/remote.php - line 164: require_once('/snap/nextcloud...')
    {main}
```
followed by this:
```
OCP\Encryption\Exceptions\GenericEncryptionException: Missing Signature

    /snap/nextcloud/7658/htdocs/apps/encryption/lib/Crypto/Crypt.php - line 529: OCA\Encryption\Crypto\Crypt->hasSignature('---------------...', 'AES-256-CTR')
    /snap/nextcloud/7658/htdocs/apps/encryption/lib/Crypto/Crypt.php - line 462: OCA\Encryption\Crypto\Crypt->splitMetaData('---------------...', 'AES-256-CTR')
    /snap/nextcloud/7658/htdocs/apps/encryption/lib/Crypto/Encryption.php - line 380: OCA\Encryption\Crypto\Crypt->symmetricDecryptFileContent('---------------...', '\x1A?l'@W\x99\x9CBY\xD7w\x046@...', 'AES-256-CTR', 1, 0)
    /snap/nextcloud/7658/htdocs/lib/private/Files/Stream/Encryption.php - line 464: OCA\Encryption\Crypto\Encryption->decrypt(*** sensitive parameters replaced ***)
    /snap/nextcloud/7658/htdocs/lib/private/Files/Stream/Encryption.php - line 295: OC\Files\Stream\Encryption->readCache()
    [internal function] OC\Files\Stream\Encryption->stream_read(8192)
    /snap/nextcloud/7658/htdocs/3rdparty/icewind/streams/src/Wrapper.php - line 83: fread(Resource id #103, 8192)
    /snap/nextcloud/7658/htdocs/3rdparty/icewind/streams/src/CallbackWrapper.php - line 91: Icewind\Streams\Wrapper->stream_read(8192)
    [internal function] Icewind\Streams\CallbackWrapper->stream_read(8192)
    /snap/nextcloud/7658/htdocs/3rdparty/sabre/http/lib/Sapi.php - line 80: stream_copy_to_stream(Resource id #106, Resource id #108, '1296728')
    /snap/nextcloud/7658/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 498: Sabre\HTTP\Sapi sendResponse(Object(Sabre\HTTP\Response))
    /snap/nextcloud/7658/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /snap/nextcloud/7658/htdocs/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()
    /snap/nextcloud/7658/htdocs/remote.php - line 164: require_once('/snap/nextcloud...')
    {main}
```

**Comment by schiessle** [comment]
Sounds like the same issue I fixed here: https://github.com/nextcloud/server/pull/10397

Maybe you can test the fix and report back if it works for you

**Comment by TecJon** [comment]
Seems not to work for me: https://github.com/nextcloud/server/issues/10455#issuecomment-410232458

**Comment by TecJon** [comment]
@schiessle this issue still persists with NC 14 beta 3.

#10455 and #10430 are solved though 😃 

`{"reqId":"W23HeDTVNtyqzF-A2zZDcAAAABk","level":4,"time":"2018-08-10T17:12:28+00:00","remoteAddr":"xx.xxx.x.xxx","user":"User","app":"webdav","method":"GET","url":"\/cloud\/remote.php\/webdav\/AmazonS3\/testfolder1\/leo.jpg?downloadStartSecret=a7o5r9n7dpj","message":{"Exception":"OC\\Encryption\\Exceptions\\DecryptionFailedException","Message":"Encryption library: Decryption (symmetric) of content failed: ","Code":0,"Trace":[{"file":"\/www\/htdocs\/w017847f\/example.com\/cloud\/apps\/encryption\/lib\/Crypto\/Crypt.php","line":469,"function":"decrypt","class":"OCA\\Encryption\\Crypto\\Crypt","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/www\/htdocs\/w017847f\/example.com\/cloud\/apps\/encryption\/lib\/Crypto\/Encryption.php","line":379,"function":"symmetricDecryptFileContent","class":"OCA\\Encryption\\Crypto\\Crypt","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***","*** sensitive parameter replaced ***",1,"*** sensitive parameter replaced ***"]},{"file":"\/www\/htdocs\/w017847f\/example.com\/cloud\/lib\/private\/Files\/Stream\/Encryption.php","line":479,"function":"decrypt","class":"OCA\\Encryption\\Crypto\\Encryption","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/www\/htdocs\/w017847f\/example.com\/cloud\/lib\/private\/Files\/Stream\/Encryption.php","line":299,"function":"readCache","class":"OC\\Files\\Stream\\Encryption","type":"->","args":[]},{"function":"stream_read","class":"OC\\Files\\Stream\\Encryption","type":"->","args":[8192]},{"file":"\/www\/htdocs\/w017847f\/example.com\/cloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php","line":91,"function":"fread","args":[null,8192]},{"file":"\/www\/htdocs\/w017847f\/example.com\/cloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php","line":91,"function":"stream_read","class":"Icewind\\Streams\\Wrapper","type":"->","args":[8192]},{"function":"stream_read","class":"Icewind\\Streams\\CallbackWrapper","type":"->","args":[8192]},{"file":"\/www\/htdocs\/w017847f\/example.com\/cloud\/3rdparty\/sabre\/http\/lib\/Sapi.php","line":80,"function":"stream_copy_to_stream","args":[null,null,"162637"]},{"file":"\/www\/htdocs\/w017847f\/example.com\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":498,"function":"sendResponse","class":"Sabre\\HTTP\\Sapi","type":"::","args":[{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/www\/htdocs\/w017847f\/example.com\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/example.com\/cloud\/remote.php\/webdav\/AmazonS3\/testfolder1\/leo.jpg?downloadStartSecret=a7o5r9n7dpj","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/www\/htdocs\/w017847f\/example.com\/cloud\/apps\/dav\/appinfo\/v1\/webdav.php","line":80,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/www\/htdocs\/w017847f\/example.com\/cloud\/remote.php","line":163,"args":["\/www\/htdocs\/w017847f\/example.com\/cloud\/apps\/dav\/appinfo\/v1\/webdav.php"],"function":"require_once"}],"File":"\/www\/htdocs\/w017847f\/example.com\/cloud\/apps\/encryption\/lib\/Crypto\/Crypt.php","Line":586,"Hint":"Encryption library: Decryption (symmetric) of content failed: ","CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.15"}
 `

**Comment by schiessle** [comment]
@TecJon the error message looks different, there is no longer the "bad signature" error. I just tried it but coudn't reproduce it. I used Amazon S3 test account, mounted it as admin for all user to the s3 folder and could upload, download and delete files.

What's your concrete setup? Did you configured the external storage as a system wide mount (for all users or just a specific set of users) or as a user mount in the personal settings? Did you tried it with new files, we probably can't fix the already broken files. What S3 storage do you use? Did you tried it without encryption, does the storage works reliable in this case?

**Comment by TecJon** [comment]
@schiessle I tried it on two independent test installations. One is a one-click install on a shared web space. The other is a installation on a virtual server with the zip from nextcloud.com. For both installations I installed NC 13 and switched to the beta channel. Both installations produce the same error:
```
{"reqId":"LAYjbdNvkZWxDTgY9Y61","level":4,"time":"2018-08-15T19:01:35+00:00","remoteAddr":"xx.xxx.x.xx","user":"User","app":"webdav","method":"GET","url":"\/remote.php\/webdav\/s3-test\/testfolder\/test.zip?downloadStartSecret=urxlbk0g3t","message":{"Exception":"OC\\Encryption\\Exceptions\\DecryptionFailedException","Message":"Encryption library: Decryption (symmetric) of content failed: ","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud_test\/nextcloud\/apps\/encryption\/lib\/Crypto\/Crypt.php","line":469,"function":"decrypt","class":"OCA\\Encryption\\Crypto\\Crypt","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud_test\/nextcloud\/apps\/encryption\/lib\/Crypto\/Encryption.php","line":380,"function":"symmetricDecryptFileContent","class":"OCA\\Encryption\\Crypto\\Crypt","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***","*** sensitive parameter replaced ***",1,"*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/nextcloud_test\/nextcloud\/lib\/private\/Files\/Stream\/Encryption.php","line":422,"function":"decrypt","class":"OCA\\Encryption\\Crypto\\Encryption","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud_test\/nextcloud\/lib\/private\/Files\/Stream\/Encryption.php","line":262,"function":"readCache","class":"OC\\Files\\Stream\\Encryption","type":"->","args":[]},{"function":"stream_read","class":"OC\\Files\\Stream\\Encryption","type":"->","args":[8192]},{"file":"\/var\/www\/nextcloud_test\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php","line":83,"function":"fread","args":[null,8192]},{"file":"\/var\/www\/nextcloud_test\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php","line":91,"function":"stream_read","class":"Icewind\\Streams\\Wrapper","type":"->","args":[8192]},{"function":"stream_read","class":"Icewind\\Streams\\CallbackWrapper","type":"->","args":[8192]},{"file":"\/var\/www\/nextcloud_test\/nextcloud\/3rdparty\/sabre\/http\/lib\/Sapi.php","line":80,"function":"stream_copy_to_stream","args":[null,null,"2091586"]},{"file":"\/var\/www\/nextcloud_test\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":498,"function":"sendResponse","class":"Sabre\\HTTP\\Sapi","type":"::","args":[{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud_test\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/example.com\/remote.php\/webdav\/s3-test\/testfolder\/test.zip?downloadStartSecret=urxlbk0g3t","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud_test\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php","line":80,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud_test\/nextcloud\/remote.php","line":163,"args":["\/var\/www\/nextcloud_test\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud_test\/nextcloud\/apps\/encryption\/lib\/Crypto\/Crypt.php","Line":586,"Hint":"Encryption library: Decryption (symmetric) of content failed: ","CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.14"}
{"reqId":"W3R7FAJsXrNgOTjW@Tg4","level":4,"time":"2018-08-15T19:12:21+00:00","remoteAddr":"xx.xxx.x.xx","user":"User","app":"webdav","method":"GET","url":"\/cloud\/remote.php\/webdav\/AmazonS3\/testfolder\/test.zip?downloadStartSecret=xyyhi8z50o","message":{"Exception":"OC\\Encryption\\Exceptions\\DecryptionFailedException","Message":"Encryption library: Decryption (symmetric) of content failed: ","Code":0,"Trace":[{"file":"\/www\/htdocs\/w017847f\/example.com\/apps\/encryption\/lib\/Crypto\/Crypt.php","line":469,"function":"decrypt","class":"OCA\\Encryption\\Crypto\\Crypt","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/www\/htdocs\/w017847f\/example.com\/apps\/encryption\/lib\/Crypto\/Encryption.php","line":379,"function":"symmetricDecryptFileContent","class":"OCA\\Encryption\\Crypto\\Crypt","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***","*** sensitive parameter replaced ***",1,"*** sensitive parameter replaced ***"]},{"file":"\/www\/htdocs\/w017847f\/example.com\/lib\/private\/Files\/Stream\/Encryption.php","line":479,"function":"decrypt","class":"OCA\\Encryption\\Crypto\\Encryption","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/www\/htdocs\/w017847f\/example.com\/lib\/private\/Files\/Stream\/Encryption.php","line":299,"function":"readCache","class":"OC\\Files\\Stream\\Encryption","type":"->","args":[]},{"function":"stream_read","class":"OC\\Files\\Stream\\Encryption","type":"->","args":[8192]},{"file":"\/www\/htdocs\/w017847f\/example.com\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php","line":91,"function":"fread","args":[null,8192]},{"file":"\/www\/htdocs\/w017847f\/example.com\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php","line":91,"function":"stream_read","class":"Icewind\\Streams\\Wrapper","type":"->","args":[8192]},{"function":"stream_read","class":"Icewind\\Streams\\CallbackWrapper","type":"->","args":[8192]},{"file":"\/www\/htdocs\/w017847f\/example.com\/3rdparty\/sabre\/http\/lib\/Sapi.php","line":80,"function":"stream_copy_to_stream","args":[null,null,"2091586"]},{"file":"\/www\/htdocs\/w017847f\/example.com\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":498,"function":"sendResponse","class":"Sabre\\HTTP\\Sapi","type":"::","args":[{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/www\/htdocs\/w017847f\/example.com\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/example.com\/remote.php\/webdav\/AmazonS3\/testfolder\/test.zip?downloadStartSecret=xyyhi8z50o","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/www\/htdocs\/w017847f\/example.com\/apps\/dav\/appinfo\/v1\/webdav.php","line":80,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/www\/htdocs\/w017847f\/example.com\/remote.php","line":163,"args":["\/www\/htdocs\/w017847f\/example.com\/apps\/dav\/appinfo\/v1\/webdav.php"],"function":"require_once"}],"File":"\/www\/htdocs\/w017847f\/example.com\/apps\/encryption\/lib\/Crypto\/Crypt.php","Line":586,"Hint":"Encryption library: Decryption (symmetric) of content failed: ","CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.15"}
```

Some notes that apply for both test installations:

- configured external storage (s3) system-wide
- for all users, no limitations 
- enabled default encryption without home encryption
- no errors using external s3 storage without encryption
- SSL is enabled. 
- Style path and legacy authentication is disabled
- preview is enabled
- Compatibility with Mac NFD encoding is disabled
- Tiny files of 3 KB are no problem.
- larger files (160 KB) fail

> What S3 storage do you use?

Not sure which information you could need. I configured two s3 buckets, one for each installations. One has default AES-256 encryption enabled, the other one hasn't. One is located in us east, the other in europe central. Let me know if any other info can be of help.

**Comment by MorrisJobke** [comment]
@schiessle @TecJon Could you open a new ticket for this new issue?

**Comment by TecJon** [comment]
re-opened here: #10767
