### ISSUE TITLE
Presentation problem in file actions

### ISSUE THREAD

**Issue by johnny-gonzales** [nextcloud/server#8302]
### Steps to reproduce
1. open file view
2. open PDF document by clicking
3. close PDF document

### Expected behaviour
above the file list there should be a list of actions: "move or copy // download // _filesize_ // erase

### Actual behaviour
instead, this list is moved to the right, out of the visible browser frame, it is only showing half of _download_

### Server configuration

**Operating system**: Debian stretch

**Web server:** apache2 2.4.25

**Database:** 10.1.26

**PHP version:** 7.0.27

**Nextcloud version:** (see Nextcloud admin page) 13.0, but already in 12

**Updated from an older Nextcloud/ownCloud or fresh install:** update since oc 9 maybe

**Where did you install Nextcloud from:** zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>
Enabled:
  - activity: 2.6.1
  - apporder: 0.4.1
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - caniupdate: 0.1.2
  - comments: 1.3.0
  - contacts: 2.0.1
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - rainloop: 5.0.6
  - richdocuments: 1.12.40
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_email: 1.0.3
  - spreed: 3.0.1
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.kalisch.eu"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "nc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtptimeout": 30,
        "mail_smtpport": "587",
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "overwritewebroot": "\/",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *",
        "forceSSLforSubdomains": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "appstore.experimental.enabled": true,
        "loglevel": 3,
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.kalisch.eu"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** firefox 58, but also earlier

**Operating system:** windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

Pictures:
![1](https://user-images.githubusercontent.com/36366569/36073544-e72d876a-0f32-11e8-9017-c2711b0e53dc.JPG)
![2](https://user-images.githubusercontent.com/36366569/36073545-e74ee59a-0f32-11e8-8b52-5d3abc3e0fab.JPG)
![3](https://user-images.githubusercontent.com/36366569/36073546-e76ca3c8-0f32-11e8-8f6b-0df0c08b356b.JPG)

**Comment by MorrisJobke** [comment]
This really reminds me of https://github.com/nextcloud/server/issues/4968#issuecomment-333058757

We fixed this in 12.0.5 and 13.0.0 with https://github.com/nextcloud/files_pdfviewer/pull/49

Could you check again if this looks like what you described?

**Comment by johnny-gonzales** [comment]
Hi Morris, no that is not the same issue, and it is still present in 13.0!

**Comment by MorrisJobke** [comment]
> Hi Morris, no that is not the same issue, and it is still present in 13.0!

Is it better in 13.0.4? We updated the PDF viewer recently as well.

**Comment by johnny-gonzales** [comment]
Hi Morris, it is still the same behavior in 13.04. But anyway I don't think it is a problem of the PDF viewer itself, but a problem of the file broswer. The displaying error just seems to be triggered by the switch of views.

**Comment by ChristophWurst** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. 

As far as I know we also had a bunch of fixes for the file list recently. This might be fixed with 15 or 16.

If this is still happening after an upgrade to the latest version, feel free to reopen.
